### ISSUE TITLE
`servers:cordon` description is not fully shown in `rake --tasks`

### ISSUE THREAD

**Issue by debuglevel** [blindsidenetworks/scalelite#1001]
In `rake -T`, the second line of this description is cut off:

https://github.com/blindsidenetworks/scalelite/blob/1ae48324d9dfe3df5fe2bb55f6e5dbcb53bc608b/lib/tasks/servers.rake#L80-L81

Not sure though whether this is a Rails/Rake/Whatever issue or has to be fixed by project developers.

**Comment by scouillard** [comment]
Hi,
You can set `export RAKE_COLUMNS=200` to increase the column width within your terminal.
Or you can also use `rake -D` instead to see the full task description.
