### ISSUE TITLE
Tag v1.5.1.5 is identical to v1.5.1.4, i.e. doesn't include the listed changes

### ISSUE THREAD

**Issue by Ithanil** [blindsidenetworks/scalelite#1005]
**Describe the bug**

[v1.5.1.5](https://github.com/blindsidenetworks/scalelite/releases/tag/v1.5.1.5) is identical to [v1.5.1.4](https://github.com/blindsidenetworks/scalelite/releases/tag/v1.5.1.4)

The changes listed in the release notes are not included.

**Comment by farhatahmad** [comment]
Ah my mistake :man_facepalming:

**Comment by farhatahmad** [comment]
New images have been released. Thanks for the heads up
