### ISSUE TITLE
Getting wrong URL when joining Meeting over ScaleLite with Greenlight-V3

### ISSUE THREAD

**Issue by Lukas-Rotermund** [blindsidenetworks/scalelite#1031]
**Deployment:**
1. Deployment: I have deployed BBB + Greenlight with the script by BBB --> https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh. 
ScaleLite was deployed with the guide by J. Federico --> https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6
3. Versions:  BBB 2.6, Greenlight-V3
4. Tools used for reproducing the issue:  Joining Meeting with Greenlight

**Describe the problem:**
 The BBB Server with Greenlight and the ScaleLite Server are runnimg.
I added the BBB Server to the pool on the ScaleLite Server and it says enabled and online.

I configured the .env on the BBB Server:
URL=https://loadbalancer.example.com/bigbluebutton/api/
SECRET=[Load-Balancer-Secret]

I can visit the Greenlight landingpage with https://bbb.example.com and can log in, but if I join a meeting, I join under some kind of random hostname (example: https://mxde058024.rna1.blindsidenetworks.com/...) instead of https://bbb.example.com/...
It seems to be some sort of testing URL... but I can't find the config for that.

While in the meeting, the ScaleLite Server can't pull the information of the session. Probably because the URL is diffrent.
If I join the meeting directly, not over the ScaleLite Server, the ScaleLite Server can pull the information.

I can't find, from where the server gets the hostname and need help.
Thanks in advance.

Best regards
L. Rotermund

**Comment by farhatahmad** [comment]
The value in the Greenlight `.env` should be `BIGBLUEBUTTON_ENDPOINT` and `BIGBLUEBUTTON_SECRET`

**Comment by Lukas-Rotermund** [comment]
> The value in the Greenlight `.env` should be `BIGBLUEBUTTON_ENDPOINT` and `BIGBLUEBUTTON_SECRET`

Hello,

thanks for the advise. After changing it I get an error while joining a meeting.
After some research, I found an error with my scalelite loadbalancer.

[error]
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/[domain]/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/[domain]/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

The path /etc/letsencrypt/live is correct and exists (drwxr-xr-x   3 root root 4096 Okt 27 08:07 live). 
I can't find the reason, why the certs can't be opend.

Have any ideo why I get this error?

Best regards
L. Rotermund
