### ISSUE TITLE
import records from old installation

### ISSUE THREAD

**Issue by mikesrus** [blindsidenetworks/scalelite#1032]
I had a very old scalelite instance that was installed by the lazy-deployment method and a separate nfs server that is used as shared storage

Unfortunately, the server with scalelite is no longer available. I made a new instance with latest scalelite using systemd units and connected an nfs server to it.

I can see old records using greenlight v3 because it stores the full url of the record and they are available, although they are not in the scalelite database.

But I can't see the old moodle records created using scalelite, because moodle requests them via the scalelite api and since there are no records in the database, there are no records, although they physically exist.

is it possible to rescan the existing scalelite storage and add records to the database?

**Comment by JeanPluzo** [comment]
Hi,

it's not about rescaning the new SL server. The info about SL recordings is in moodle.
There are 2-3 tables in the moodle DB where this info is stored. I think they're called bigbluebuttonbn or something like that. You should take a look at these tables to figure out the logic of the BBB Plugin in moodle (ok, it's not a plugin anymore as of moodle 4, but it was for a long time).
We had a situation similar to yours. We had to integrate several BBB plugins into a single one (don't ask why, long and complicated story). In the end we had to put the DB records of different tables into a single table. It wasn't fun nor easy, but it's possible.
And please post such a question in the google groups forum. This forum is for issues only. You'll get more help in the other forum.

Regards,
J.

**Comment by mikesrus** [comment]
> Hi,
> 
> it's not about rescaning the new SL server. The info about SL recordings is in moodle. There are 2-3 tables in the moodle DB where this info is stored. I think they're called bigbluebuttonbn or something like that. You should take a look at these tables to figure out the logic of the BBB Plugin in moodle (ok, it's not a plugin anymore as of moodle 4, but it was for a long time). We had a situation similar to yours. We had to integrate several BBB plugins into a single one (don't ask why, long and complicated story). In the end we had to put the DB records of different tables into a single table. It wasn't fun nor easy, but it's possible. And please post such a question in the google groups forum. This forum is for issues only. You'll get more help in the other forum.
> 
> Regards, J.

I would be grateful if you could tell me the right group in google groups that I should write.
is it https://groups.google.com/g/bigbluebutton-dev ?

I looked at the tables in the moodle database and see only the "meeting id" there.
![image](https://github.com/blindsidenetworks/scalelite/assets/15717372/09dbff1a-fbf4-438a-ad8b-10b4b04cfdd1)

when I open a page with recordings in moodle, it makes a request to the scaleline api, I see it in the logs of the nginx docker container. XML returns back with the message "no records"

it request
`https://{scalelite_host}//bigbluebutton/api/getRecordings?meetingID=bb291e8fb3036065289433e03e70e5c7802dde0a-174-24&checksum={scalelite_secret}`
which return
```
<response>
<returncode>SUCCESS</returncode>
<recordings> </recordings>
<messageKey>noRecordings</messageKey>
<message>There are not recordings for the meetings</message>
</response>
```

**Comment by JeanPluzo** [comment]
Hi,

sorry, I won't continue with this post here.
Please use the google group you mentioned.

Regards,
J.

**Comment by mikesrus** [comment]
Problem solved

The records have been moved to an identical location on the new server.
Since there are already events on the new server, I could not simply replace the database, so sql queries were generated based on the database tables of the old server and the data was imported into the new server.

Changed the sequence id for new records so that there are no conflicts with existing ones.
