### ISSUE TITLE
Scalelite / Poller does not delete meeting information in the REDIS database in a special case.

### ISSUE THREAD

**Issue by Tecumtha** [blindsidenetworks/scalelite#1037]
**Describe the bug**
If I start a meeting via a frontend, in this Case Greenlight, the meeting is saved in REDIS with various information.

For Example:

![meeting_start](https://github.com/blindsidenetworks/scalelite/assets/15190085/8a61eb7e-a62a-48f4-99f9-20d1102c2f35)
The meeting ID in this Picture is not the same but does not affect the problem. 

If I now set the BBB-Node to Disable while the meeting is still entered in the REDIS database, the Meeting will be deleted in the REDIS DATABASE:

Clearing Meeting id=4cwffmq4uvdpaaloyv0jyf85tiqx0rtv2ac9j67s

However, if I set the BBB node to delete, the following error message appears when the poller triggers.

Failed to check meeting id=eu3cbejkyphasdasdasdasdnf1gdtmfnwp status: Couldn't find Server with id=bbb001.xxxxx.de

From this point, the Meeting information remains in REDIS and will no longer be deleted.

If I then want to open the Room again, even after "Days", I get the Error Message with Greenlight, for Example:

"Invalid BigBlueButton Endpoint and Secret"

The Scalelite log files contain the following:

> [bf000357-d139-4cfe-8898-4024de688bbd] ApplicationRedisRecord::RecordNotFound (Couldn't find Server with id=bbb001.xxxxx.xx):
> [bf000357-d139-4cfe-8898-4024de688bbd]
> [bf000357-d139-4cfe-8898-4024de688bbd] app/models/server.rb:263:in `block in find'
> [bf000357-d139-4cfe-8898-4024de688bbd] lib/redis_store.rb:38:in `with_connection'
> [bf000357-d139-4cfe-8898-4024de688bbd] app/models/application_redis_record.rb:150:in `with_connection'
> [bf000357-d139-4cfe-8898-4024de688bbd] app/models/server.rb:257:in `find'
> [bf000357-d139-4cfe-8898-4024de688bbd] app/models/meeting.rb:75:in `server'
> [bf000357-d139-4cfe-8898-4024de688bbd] app/controllers/bigbluebutton_api_controller.rb:73:in `is_meeting_running'
> 

**To Reproduce**
1.) Start a Meeting
2.) Check on which node the Meeting is running.
3.) Delete the Node in the LB (bin/rake servers:remove[id]
4.) End the Meeting.
5.) Check REDIS Database, Meeting information will not be deleted

***Deployment:***
1. Deployment: Default systemd deployment and docker-compose
2. Versions: v1.5.1.7

**Comment by farhatahmad** [comment]
https://github.com/blindsidenetworks/scalelite/blob/master/docs/rake-README.md#remove-a-server

You should not remove a server that has active meetings on it
