### ISSUE TITLE
rake poll all error

### ISSUE THREAD

**Issue by freehussain** [blindsidenetworks/scalelite#104]
hello,

i recently used scaleite balancer, it works fine but after i delete server (by mistake) and error comes on run poll

D, [2020-03-26T22:41:54.226368 #35] DEBUG -- : Polling meetings
D, [2020-03-26T22:41:54.226516 #35] DEBUG -- : Polling servers
D, [2020-03-26T22:41:54.274147 #35] DEBUG -- : Polling Server id=d772813e-e03e-4586-83f7-af3442573ef3
W, [2020-03-26T22:41:54.278505 #35]  WARN -- : Failed to check meeting id=3b7a6d1526eb05404bba6337fc8d11b9a63f3517-57-61 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.278934 #35]  WARN -- : Failed to check meeting id=c24a08a93fc5e5c9dcd0a624e9f097300a300755-55-58 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.279309 #35]  WARN -- : Failed to check meeting id=ae2a50108523bbf9924e9c9b1eceda730904980a-89-68 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.279609 #35]  WARN -- : Failed to check meeting id=a4577b915b2cc1e25259972fd16466735595eb91-42-44 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.279977 #35]  WARN -- : Failed to check meeting id=ee4dee1d3a6f55a1eaaa67f5e3ba0cc1122bf82f-94-65 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.280335 #35]  WARN -- : Failed to check meeting id=0d3a7d20d071eddb88ed0195e2b855328ab98549-14-18 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
D, [2020-03-26T22:41:54.280909 #35] DEBUG -- : Polling Meeting id=b293a0d5c3cba069225e87e864b9253973b363e6-86-70 on Server id=fe6affa5-83b9-4dcf-863a-9c870b505652
I, [2020-03-26T22:41:54.333107 #35]  INFO -- : Server id=d772813e-e03e-4586-83f7-ffsdfsdf online load: 0
D, [2020-03-26T22:41:54.333217 #35] DEBUG -- : Polling Server id=fe6affa5-83b9-4dcf-863a-9c870b505652
W, [2020-03-26T22:41:54.345505 #35]  WARN -- : Failed to check meeting id=166df0c484ade5d3ed6f4aac971f1fb38fd817ab-91-57 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.346063 #35]  WARN -- : Failed to check meeting id=460e7d9ed295151a3c6b8d655e4227e44e7adfc6-9-17 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.346551 #35]  WARN -- : Failed to check meeting id=c88c6b0cff932506c92dad97640ca6e0c39ca0f1-58-63 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.347029 #35]  WARN -- : Failed to check meeting id=8c6c92ade250c0089734ee6278abadece52a1e78-41-41 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.347410 #35]  WARN -- : Failed to check meeting id=c27deb3ef797d16ca87192cc233a90e9bbd12828-21-9 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.347757 #35]  WARN -- : Failed to check meeting id=82bab56e81f0533febeb462679a3e76b3bbe1deb-43-47 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.348239 #35]  WARN -- : Failed to check meeting id=d579994c6abf9ea85c26121d71332ef3e03b0cc0-24-7 status: Couldn't find Server with id=c3940afe-b184-47df-8bb4-13a1df3ce446
W, [2020-03-26T22:41:54.348598 #35]  WARN -- : Failed to check meeting id=4e79c41bc6b8423e8d0613c09826a510dfd3f6e6-85-42 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.349038 #35]  WARN -- : Failed to check meeting id=a2f2f50f5df92f1523e74000df81a9b3f5e02dd7-47-51 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
W, [2020-03-26T22:41:54.349475 #35]  WARN -- : Failed to check meeting id=3e6421dfbd243718a223e4874bc9a5ce7f3bd865-20-11 status: Couldn't find Server with id=af0bf45f-8bf9-4b72-bba2-1503ee10f6a2
I, [2020-03-26T22:41:54.396271 #35]  INFO -- : Server id=fe6affa5-83b9-4dcf-863a-344 online load: 1

is there anyway to remove these warnings?

**Comment by farhatahmad** [comment]
Hi @freehussain 

Yes, you'll need to add the server that you removed back, [panic the server](https://github.com/blindsidenetworks/scalelite#panic-a-server) and then re-enable it or remove it again

**Comment by freehussain** [comment]
hello @farhatahmad 

if it tried

./bin/rake servers:panic[af0bf45f-8bf9-4b72-bba2-1503ee10f6a2]
ERROR: No server found with id: af0bf45f-8bf9-4b72-bba2-1503ee10f6a2

it think because it was removed.

any other idea?

**Comment by farhatahmad** [comment]
@freehussain 

> you'll need to add the server that you removed back

**Comment by freehussain** [comment]
i already did it, but it take another id, is there a way to add it with specific id?

**Comment by farhatahmad** [comment]
@freehussain Sorry for the late answer.

In that case you'll have to manually remove them from Redis. Do you know how to SSH into your Redis cache?

**Comment by mkullukcuoglu** [comment]
Hi, same issue exist on my installation. I also have redis cli access. Could you explain how can I remove the server by using redis commands?

Failed to check meeting id=ee9abae1-dfb8-4fce-a5b4-a175d90a646b status: Couldn't find Server with id=5c0d09e2-db36-4bc4-afce-1608c526c27e

~ $ ./bin/rake servers:panic[5c0d09e2-db36-4bc4-afce-1608c526c27e]
ERROR: No server found with id: 5c0d09e2-db36-4bc4-afce-1608c526c27e

**Comment by freehussain** [comment]
i just remove them manually , i don't know if i did FLUSHALL if it's working

**Comment by mkullukcuoglu** [comment]
I will restart the scalelite and redim services tonight. I will check the logs again. Thanks for advice.

**Comment by mkullukcuoglu** [comment]
Restart didn't work.  @farhatahmad , do you know the command which remove the servers or meetings which not exist the environment at the moment.
