### ISSUE TITLE
Garbage-Collect for Redis? / "LOADING Redis is loading the dataset in memory"

### ISSUE THREAD

**Issue by werk21** [blindsidenetworks/scalelite#1041]
After running scalelite a several time the redis needs a couple of minutes to start. When using scalelite you get the message "LOADING Redis is loading the dataset in memory". Is there a possibility to garbarge collect redis database?

Thank you for your work, kelly.

**Comment by ffdixon** [comment]
Hmm ... redis shouldn't be that large. using `redis-cli`, what is the output for `info`?  The information at the bottom should show the number of keys.

```
# Keyspace
db0:keys=33627,expires=1451,avg_ttl=852284048
```

**Comment by werk21** [comment]
Thank you for your quick response! We inspected the redis info and the AOF was too large (18GB). Now we added a cron for BGREWRITEAOF and this fixed the problem.
