### ISSUE TITLE
[v1.5+] protected recording can be accessed by normal BBB playback link

### ISSUE THREAD

**Issue by amg-web** [blindsidenetworks/scalelite#1046]
protected recording , can be accessed by unprotected link.
on screenshot:
bottom browser: vivaldi playback opened by initial protected link, playback started.
middle browser: brave opened same record using same protected link - playback blocked
top layer browser: Firefox playback link opened using normal BBB playback link - playback started, - but expected: playback blocked
**![Screenshot from 2024-02-05 13-16-17](https://github.com/blindsidenetworks/scalelite/assets/22151881/faf03e2e-1190-415f-b33f-5ddeded59561)**

a fresh server created and deployed using systemd with docker tag v1
```
# docker images
REPOSITORY                  TAG                     IMAGE ID       CREATED        SIZE
blindsidenetwks/scalelite   v1-api                  774a941b5ad7   3 months ago   1.31GB
blindsidenetwks/scalelite   v1-recording-importer   3c7cd62a609f   3 months ago   1.31GB
blindsidenetwks/scalelite   v1-poller               8925d9dd4d0c   3 months ago   1.31GB
blindsidenetwks/scalelite   v1-nginx                df6d883d00a8   3 months ago   27MB

```
api response
```
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
<build>v1.5.1.7</build>
</response>
```
Database: select * from recordings;
```
id |                       record_id                        |                meeting_id                | name  | published | participants |   state   |        starttime        |         endtime         | deleted_at | protected | publish_updated 
----+--------------------------------------------------------+------------------------------------------+-------+-----------+--------------+-----------+-------------------------+-------------------------+------------+-----------+-----------------
  1 | 54afe3899a5e7a2ba0e53fa175e7f4ac8ca4fa40-1703594984663 | 5si25gsgswzsxmvr5v80o5fhbgky1jvqgfzkrhxr | Class | t         |            3 | published | 2023-12-26 12:49:44.663 | 2023-12-26 13:58:06.184 |            | t         | f

```

**Comment by relecand** [comment]
See also here: https://github.com/blindsidenetworks/scalelite/issues/983

**Comment by amg-web** [comment]
@relecand 
it https://github.com/blindsidenetworks/scalelite/issues/983#issuecomment-1636724884 does not work for me

**Comment by anandchristudas** [comment]
@amg-web did you solve this?

**Comment by amg-web** [comment]
@anandchristudas 
no

**Comment by anandchristudas** [comment]
@amg-web did you use a lazy development method to install Scalelite?

**Comment by amg-web** [comment]
@anandchristudas 
what is it?
