### ISSUE TITLE
Add server groups so that different tenants can use different groups.

### ISSUE THREAD

**Issue by michaelchen001** [blindsidenetworks/scalelite#1053]
Hi,there
All current tenants will use all servers registered with scalelite. Is it possible to group servers so that different tenants can use all or part of the servers?

Suppose we have tenants A and B, servers S1, S2, S3, S4,
We assign the servers to Group G1(S1+S2) & G2(S1+S3+S4).
For user A, group G1 (servers S1 S2) can be used.
For user B, you can use group G2 (servers S1 S3 S4)

**Comment by Ithanil** [comment]
When https://github.com/blindsidenetworks/scalelite/pull/1049 is merged, it will be possible to "abuse" the feature for the purpose tenant-specific server pools, by tagging the corresponding servers and specifying the meta_server-tag in the OVERRIDE_CREATE_PARAMS of the tenant.

**Comment by Ithanil** [comment]
That said, I'm planning to make a PR with a proper implementation in the future.
