### ISSUE TITLE
running scalelite with a single public ip ?

### ISSUE THREAD

**Issue by denis-b** [blindsidenetworks/scalelite#109]
Hello, 
The scheme on documentation shows a different dns name for each bbb instance. Does it implies to have a public ip for each one ? Or can I use  haproxy and clever UDP port forwarding to use a single public ip for all the setup ?
Thanks.

**Comment by farhatahmad** [comment]
You'll probably need separate public ips for each server, since Scalelite simply redirects the the user to the the individual BigBlueButton server

**Comment by denis-b** [comment]
OK, thanks. So no way with ipv4... 
Does BBB works with ipv6 ?

**Comment by denis-b** [comment]
Or a multi-tenant setup, for example with a BBB server in each school, and a global scalelite load balancer ?

**Comment by farhatahmad** [comment]
BigBlueButton should work with ipv6, but you may need some additional configuration changes. I suggest you post on the forums or the BigBlueButton repo if you run into issues.

> multi-tenant setup

Nope. Scalelite was designed to be single tenant
