### ISSUE TITLE
Integrating with canvas

### ISSUE THREAD

**Issue by roohix** [blindsidenetworks/scalelite#110]
I cant find any mention of Canvas
Can I balance BBB servers and Canvas with this project? how ?

**Comment by farhatahmad** [comment]
Hi @roohix 

You can balance BBB servers for any front-end. You'll need to follow the installation instructions in the README which will point towards the right direction

**Comment by k8smaster** [comment]
@roohix 
Hi Ruhullah Ahmedi,
I want to ask you about deploying bbb to docker.
Could you help me?
I can speak Persian. 
e-mail address: k8smaster20@gmail.com
