### ISSUE TITLE
Scalelite and Phone-Ring-In

### ISSUE THREAD

**Issue by wmchris** [blindsidenetworks/scalelite#111]
This is less a bug/issue than more a general question:

is there any solution for the 'phone number conference join' using scalelite? At the moment the caller needs to know which instance he has to call to join a conference. 

A centralized phone number would be much easier for people w/o internet access, but requires the knowledge which extension to forward based on the load balancer.

**Comment by farhatahmad** [comment]
Not at the moment and probably not anytime soon (if ever). Add a centralized phone number adds its own challenges and changes that we're not planning on doing anytime soon.
