### ISSUE TITLE
rake status ERROR

### ISSUE THREAD

**Issue by rriscado** [blindsidenetworks/scalelite#112]
Command "rake status" return error when exists unrecheable/offline server.

~ $ ./bin/rake status
rake aborted!
Net::OpenTimeout: execution expired
/srv/scalelite/app/controllers/concerns/api_helper.rb:49:in `get_post_req'
/srv/scalelite/lib/tasks/status.rake:11:in `block (2 levels) in <main>'
/srv/scalelite/lib/tasks/status.rake:10:in `each'
/srv/scalelite/lib/tasks/status.rake:10:in `block in <main>'
Tasks: TOP => status
(See full trace by running task with --trace)

**Comment by farhatahmad** [comment]
Hi @rriscado 

Thanks for reporting this. It's a known issue and will be fixed in the next release
