### ISSUE TITLE
scalelite-nginx service: server_names_hash_bucket_size

### ISSUE THREAD

**Issue by sureronald** [blindsidenetworks/scalelite#114]
I get the error below for the scalelite-nginx.service:

```
Apr 01 20:27:39 sc.aabbccddee.ke docker[7820]: 2020/04/01 17:27:39 [emerg] 7#7: could not build server_names_hash, you should increase server_names_hash_bucket_size: 32
Apr 01 20:27:39 sc.aabbccddee.ke docker[7820]: nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 32
```
The actual length of my domain name is sc.aabbccddee.ke (16char). I know I can edit the image (do you recommend?) and fix this in nginx.conf by adjusting the bucket size upwards.

Can you consider raising this value in the container so that it works for slightly longer domain names without having to edit the image manually? For now I have it working using a short domain name but I would like it work with the longer domain name since it is the one reserved for the project.

**Comment by farhatahmad** [comment]
Hi @sureronald 

Coming back to this now, I don't see why this shouldn't be done. Ill tag it as an enhancement

**Comment by sureronald** [comment]
Hi @farhatahmad ,
Well noted. Looking forward.
