### ISSUE TITLE
Scalelite recording importer

### ISSUE THREAD

**Issue by SebastianZiegler** [blindsidenetworks/scalelite#116]
Everything works execpt the recording importer, this is my log. Any Ideas:

 docker logs scalelite-recording-importer

I, [2020-04-02T16:18:55.172589 #7]  INFO -- : Monitoring /mnt/scalelite-recordings/var/bigbluebutton/spool for new recording files
rake aborted!
Errno::ENOENT: No such file or directory @ realpath_rec - /mnt/scalelite-recordings
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/adapter/config.rb:17:in `realpath'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/adapter/config.rb:17:in `realpath'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/adapter/config.rb:17:in `block in initialize'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/adapter/config.rb:16:in `map'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/adapter/config.rb:16:in `initialize'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/backend.rb:25:in `new'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/backend.rb:25:in `initialize'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:47:in `new'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:47:in `initialize'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen.rb:41:in `new'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen.rb:41:in `to'
/srv/scalelite/lib/tasks/recordings.rake:14:in `block (2 levels) in <main>'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => recordings:watch

**Comment by bumblebee87kfu** [comment]
@SebastianZiegler: Did you find the solution to resolve this issue? I have the same with my installation but do not figure out how to solve it.

**Comment by rabser** [comment]
The mountpoint for the shared directory seems not available /mnt/scalelite-recordings: do you can list the files inside ?

**Comment by bumblebee87kfu** [comment]
Yes
`ls -la /mnt/scalelite-recordings/var/bigbluebutton/spool `
shows me files if I run it on the host system.
The scalelite-api and scalelite-nginx container can access the directory too, well it looks like the can. So the problem is only with scalelite-recording-importer.

**Comment by SebastianZiegler** [comment]
I hat a wrong path in the config file
RECORDING_WORK_DIR=/var/bigbluebutton/recording/scalelite
RECORDING_PUBLISH_DIR=/var/bigbluebutton/published
RECORDING_UNPUBLISH_DIR=/var/bigbluebutton/unpublished

here I had used /mnt/scalelite-recording/var/bigbluebutton/...
the config above worked

**Comment by rabser** [comment]
You can check from inside each container through a shell by substituting the container name in the following command

```
docker exec -it <scalelite docker container name> /bin/sh
```

Do you mount the SCALELITE_RECORDING_DIR from outside of the scalelite docker host ? Beware that the dockers should start after this directory is normally available to the system.

**Comment by bumblebee87kfu** [comment]
Yes, I plan to have all the files on a NFS. 
I was able to run the scalelite-recording-importer now by removing the **--env-file** for `docker run` and replaced the SCALELITE_TAG and the SCALELITE_RECORDRING_DIR with the attributes I want them to have (the same values from /etc/default/scalelite). 
Now I can see the content of /mnt/biglbuebutton from host in /var/bigbluebutton in container. 
Does scalelite-recording-importer need other enviroment variables from /etc/default/scalelite?
btw. I have no idea why it works without the **--env-file** in `docker run` command.
