### ISSUE TITLE
Moodle and Greenlight

### ISSUE THREAD

**Issue by SebastianZiegler** [blindsidenetworks/scalelite#119]
Hello,

finally we are finshed setting up scalelite. Is it possible to uses 2 clients (moodle and greenlight) in front of scalellite. I think the only problem would be, that the meetingid could be the same ore are they unique?

Best regards
sebastian

**Comment by farhatahmad** [comment]
You can use as many clients as you like. Each one is designed to be run independently so you shouldn't have any issues

**Comment by SebastianZiegler** [comment]
thx
