### ISSUE TITLE
Redis::CommandError: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by tvitas** [blindsidenetworks/scalelite#120]
Hi,

/etc/default/scalelite:
REDIS_URL=redis://password@host:port

docker exec -it scalelite-api /bin/sh

./bin/rake status
rake aborted!
Redis::CommandError: NOAUTH Authentication required.
~ $

But, if we testing with redis-cli all goes fine:
redis-cli -u redis://password@host:port
host:port>ping
PONG
host:port>

We are using scalelite docker containers.
Where is our mistake?

**Comment by SebastianZiegler** [comment]
du you have an : in front of the PW
REDIS_URL=redis://:password@host:port

**Comment by tvitas** [comment]
> du you have an : in front of the PW
> REDIS_URL=redis://:password@host:port

Dear Sebastian,
YOU ARE LORD!
Lot, lot, huge heap of thanks.
