### ISSUE TITLE
Noob needs a hand

### ISSUE THREAD

**Issue by agustinmono** [blindsidenetworks/scalelite#122]
I think the documentation its too much for someone that comes from just installing bigbluebutton, please, can anyone provide detailed steps to install scalelite, thank you so much .

Also its possible to install it into a VirtualBox server to test?
I have 2 bigbluebutton instalation and I really want to improve the management with scalelite, any help out there?

Thanks a lot

**Comment by rabser** [comment]
I think that the scalelite documentation is more than precise and concise, if you can't follow them, please rethink about the competences needed to run IT services, because at the first problem you will be unable to be effective by yourself in solving it.

**Comment by agustinmono** [comment]
Of course the problem its my knowledge, but maybe out there are peolpel with se same level of knowledge, so I though it would be awesome if as comunity we can set a step by step, for example I have some questions due to my ignorance

Do I need to fork the repository? where? root or /etc/... ?

How can I check if the instalation were ok?

The posterge Database is mandatory to be in another server?same with the redish cache.

> 

1. Multiple BigBlueButton Servers
2. Scalelite LoadBalancer Server
3. NFS Shared Volume
4. PostgreSQL Database
5. Redis Cache

points 2 to 5 can be on the same partition?

about configuration http://prntscr.com/rtitzg is this a mandatory order? 


and finally, can i run it into a virtual box machine? 


Thanks a lot, hope I can learn a lot with this

**Comment by mvasylenko** [comment]
> Do I need to fork the repository? where? root or /etc/... ?

No, it is not necessary, unless you wish to make some custom changes.

> The posterge Database is mandatory to be in another server?same with the redish cache.

No, actually you can install them on the same host, i.e. as docker container.

> and finally, can i run it into a virtual box machine?
Virtual box is usually not used for server virtualisation, but it may work.

**Comment by agustinmono** [comment]
awesome! thanks a lot, is there a first step? i mean, can I start configuring the NFS or i need to start with the docker-README.md and follow that steps

thanks again, sorry if the question is dumb

**Comment by mvasylenko** [comment]
First step is NFS, then database and redis. After that you can start with docker containers.

If you wish to have same look and feel, you may install database and redis also as docker container:
1. Do from docker-Readme.md: install docker, create docker network, create and enable scalilite.target

2. Create folders /opt/postgres and /opt/redis

3. Create file /etc/default/scalelite-db with following content:
 POSTGRES_DB=postgres
 POSTGRES_USER=postgres
 POSTGRES_PASSWORD=yoursecretpassword

4. Create file /etc/systemd/system/scalelite-db.service  with folowing content:
[Unit]
Description=Scalelite DB
After=network-online.target
Wants=network-online.target
Before=scalelite.target
PartOf=scalelite.target
[Service]
ExecStartPre=-/usr/bin/docker kill scalelite-db
ExecStartPre=-/usr/bin/docker rm scalelite-db
ExecStartPre=/usr/bin/docker pull postgres:9.5
ExecStart=/usr/bin/docker run --name scalelite-db --env-file /etc/default/scalelite-db --network scalelite --mount type=bind,source=/opt/postgres,target=/var/lib/postgresql/data postgres:9.5
[Install]
WantedBy=scalelite.target

5. Enable scalelite-db.service
systemctl enable scalelite-db.service

6.  Create file /etc/systemd/system/scalelite-redis.service  with folowing content:
[Unit]
Description=Scalelite REDIS
After=network-online.target
Wants=network-online.target
Before=scalelite.target
PartOf=scalelite.target
[Service]
ExecStartPre=-/usr/bin/docker kill scalelite-redis
ExecStartPre=-/usr/bin/docker rm scalelite-redis
ExecStartPre=/usr/bin/docker pull redis:latest
ExecStart=/usr/bin/docker run --name scalelite-redis --network scalelite --mount type=bind,source=/opt/redis,target=/data redis:latest redis-server --appendonly yes
[Install]
WantedBy=scalelite.target

7. Enable redis service
systemctl enable scalelite-redis.service

8. Restart scalelite.target
systemctl restart scalelite.target

9. Append config file /etc/default/scalelite with:
DATABASE_URL=postgresql://postgres:yoursecretpassword@scalelite-db
REDIS_URL=redis://scalelite-redis

10. Do the rest of docker-Readme.md
Note: add following to [Unit] section in scalelite-api.service:
After=scalelite-db.service
Requires=scalelite-db.service
After=scalelite-redis.service
Requires=scalelite-redis.service

**Comment by agustinmono** [comment]
I will! THANKS A LOT for the detailed explication,  i cant thank you enough.  I will try that this week THANKS again

**Comment by agustinmono** [comment]
is this tutorial ok for NFS ? https://vitux.com/install-nfs-server-and-client-on-ubuntu/ @mvasylenko

**Comment by agustinmono** [comment]
im having an error here with your steps @mvasylenko 
 
https://github.com/blindsidenetworks/scalelite/issues/130

know why?

Thanks a lot
