### ISSUE TITLE
URL configuration

### ISSUE THREAD

**Issue by sharypovandrey** [blindsidenetworks/scalelite#124]
Hello guys,
I'm bit confused.
Regarding this step https://github.com/blindsidenetworks/scalelite#configure-your-front-end-to-use-scalelite, the BBB server URL must be set to `http(s)://<scalelite-hostname>/bigbluebutton/`.
I.e., we have `bbb-1.example.com` and `scalelite.example.com`. Must I execute `bbb-conf --setip scalelite.example.com` on the BBB server to make it work? After this command, I got an error on BBB server. 
Definitely I'm doing something wrong. 
Thank you for any help!

**Comment by farhatahmad** [comment]
No your BigBlueButton servers remain separate from Scalelite. 

What front-end are you using? Set the BIGBLUEBUTTON_ENDPOINT in that front end to `scalelite.example.com`

**Comment by amassaro** [comment]
I am getting a similar problem?

Using greenlight, I have `BIGBLUEBUTTON_ENDPOINT=https://scalelite.example.com/bigbluebutton/`

If I tail `log/production.log` and try and start a meeting I get the following error.
`BigBlueButtonException: Invalid response body. Is the API URL correct? "https://scalelite.example.com/bigbluebutton/api", version 0.8`

When I put `https://scalelite.example.com/bigbluebutton/api` in a browser I am getting the expected response similar if I go directly to the BBB server api endpoint with `GET`

```xml
<response>
  <returncode>SUCCESS</returncode>
  <version>2.0</version>
  <build>v1.0</build>
</response>
```

**Comment by farhatahmad** [comment]
Are you still having this issue?

**Comment by amassaro** [comment]
It seems to be working now. Not sure what I changed tinkering around but now I have another issue  with BBB itself. I will redirect to that project. Thank you for responding.
