### ISSUE TITLE
BBB Room bouncing betweeen two servers

### ISSUE THREAD

**Issue by rabser** [blindsidenetworks/scalelite#125]
Using a Moodle instance connected to my Scalelite with 3 servers, we hit this problem:
- the teacher enter into the room from moodle and scalelite point to bbb1
- some students enter the room and are redirected to bbb1
- the teacher got a problem on their firefox, so exit the room and reenter and scalelite point it to bbb3
- all subsequent students goes to bbb3, but the first one remains obviously on bbb1

so the room is splitted onto two servers: is this a right behaviour or i'm missing anything ?

**Comment by farhatahmad** [comment]
That doesn't sound right. Scalelite should be putting meetings that currently exist on the same server they were on previously. Does this happen consistently?

**Comment by rabser** [comment]
By now i wasn't able to reproduce this behaviour consistently, i'm investigating with the teacher who reported this to better understand the "human-side" of this problem.
Checking on the same moodle server with my credentials, i was pointed to the same meeting, so i need to investigate further, waiting if this happen again or not.

**Comment by paul1278** [comment]
Could it be that there are groups enabled for the BBB-activity on moodle?

**Comment by rabser** [comment]
Thanks for your reply, but no, no groups defined. Since i cannot reproduce the behaviour that happened once, this ticket should be closed.
