### ISSUE TITLE
files in spool aren't processed

### ISSUE THREAD

**Issue by SebastianZiegler** [blindsidenetworks/scalelite#126]
Hello,

we had a long time only one bbb server, last friday we finished setting up scalelite. We transfered local redings via script but this doesn't work for every recording. So some recordings are still missing, so I started the tranfer again. Now I see a list of recordings in the spool folder the missing ones too, but it seems that they aren't procced. 
The Importer tast is up.

Any Ideas.

**Comment by rabser** [comment]
tale a look here: https://github.com/blindsidenetworks/scalelite/issues/96

**Comment by SebastianZiegler** [comment]
solution here: https://github.com/blindsidenetworks/scalelite/issues/96
