### ISSUE TITLE
Impossible to do rake db:setup on startup

### ISSUE THREAD

**Issue by MiStErLu** [blindsidenetworks/scalelite#127]
Hello,

   We try to configure scalelite with an external database with a uri like this : 
    DATABASE_URL: "postgres://mdl-scalelite-pprd:XXXXXXXXXXXX@MYSERVEUR:5432/mdl-scalelite-pprd"

FATAL:  no pg_hba.conf entry for host "XXXXXX", user "mdl-scalelite-pprd", database "postgres", SSL on
FATAL:  no pg_hba.conf entry for host "XXXXXX", user "mdl-scalelite-pprd", database "postgres", SSL off
Couldn't create 'mdl-scalelite-pprd' database. Please check your configuration.                                                                                          
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  no pg_hba.conf entry for host "XXXXX", user "mdl-scalelite-pprd", database "postgres", SSL on
FATAL:  no pg_hba.conf entry for host "XXXXXXX", user "mdl-scalelite-pprd", database "postgres", SSL off
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'    │··············
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'              │··············
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:889:in `new_connection'              │··············
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `checkout_new_connection'     │··············
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:912:in `try_to_checkout_new_connectio│··············
n'                                                                                                                                                                       │··············
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:873:in `acquire_connection'          │

I don't know why he want to use posgres user....

Any idea ?

**Comment by mvasylenko** [comment]
DATABASE_URL should start with postgresql, not postgres
DATABASE_URL=postgresql://username:password@host

**Comment by MiStErLu** [comment]
Hello,
 
    We fix that and we got the same error.
    But we found the bug.

    When a postgresql database is allready up, it's not need to launch rake db:setup
    Because db:setup run db:create that need the postgres user account.

    We fix that buy lauching only db:schema:load and db:seed
    It's should be nice to add it in the documentation.

Best regards,
MiStErLu
Univerty of Strasbourg.
