### ISSUE TITLE
LOADBALANCER_SECRET giving error "You did not pass the checksum security check" in Moodle

### ISSUE THREAD

**Issue by HossamAhmedHamdi** [blindsidenetworks/scalelite#128]
Steps I made:
1- Installed Scalelite, Redis, Docker and BBB on a server named "BBBM" for example.
2- Installed BBB on 3 other servers "BBB1, BBB2 and BBB3" for example.
3- Added the 3 servers to the pool and checked them they are all enabled and online.
4- I logged to Moodle and went to BBB plugin and added the link to the main server bbbm.example.com/bigbluebutton and the load balancer secret in "Shared Secret" field.
5- When I try to open any classroom or create I get this error "bigbluebuttonbn/You did not pass the checksum security check".

What I Checked:
1- BBB is working on main server.
2- Checked Scalelite, Docker and Redis ,,etc.
3- Tested connection with the BBB secret on the main server it's working.

Any help?

**Comment by rabser** [comment]
Does the three secrets into BBB1,BBB2,BBB3 are equal to the BBBM's secret ?
Try to align them and you should be fine.

**Comment by HossamAhmedHamdi** [comment]
> 
> 
> Does the three secrets into BBB1,BBB2,BBB3 are equal to the BBBM's secret ?
> Try to align them and you should be fine.

As i know that Scalelite handles this or do I need to do it manually? if manually how?

**Comment by rabser** [comment]
On each BBB server do
bbb-conf --secret YOUR_SCALELITE_SECRET

**Comment by HossamAhmedHamdi** [comment]
OK I've followed your instructions and made the LOADBALANCER_SECRET the same on all BBB instances "BBBM, BBB1, BBB2 and BBB3" and tried to open 3 different classes from 3 accounts and opened all from different computers but all classes opened on BBBM server and didn't divided on the 4 or 3 servers, please check the following image.
https://pasteboard.co/J2CEXov.jpg

**Comment by rabser** [comment]
??? You installed BBB also on BBBM ? following your description i would say not.
If not: why did you add BBBM to the cluster as a "slave" ? It's the master one.

**Comment by HossamAhmedHamdi** [comment]
> 
> 
> ??? You installed BBB also on BBBM ? following your description i would say not.
> If not: why did you add BBBM to the cluster as a "slave" ? It's the master one.

Yes I installed bigbluebutton on the main server

**Comment by rabser** [comment]
hmmm... you should not, as this probably obfuscate scalelite. The BBBM should have only scalelite which "emulate" the BBB api, so use the same ports and same procotols.
i think that actually you are communicating only with BBB installed onto BBBM, not with scalelite. I believe that maybe you can do this, but it's beyond the suggested architecture.

**Comment by HossamAhmedHamdi** [comment]
> 
> 
> hmmm... you should not, as this probably obfuscate scalelite. The BBBM should have only scalelite which "emulate" the BBB api, so use the same ports and same procotols.
> i think that actually you are communicating only with BBB installed onto BBBM, not with scalelite. I believe that maybe you can do this, but it's beyond the suggested architecture.

before I install bbb on the main server which had scalelite installed I got 404 error when I tried to load bbbm.example.com/bigbluebutton and got error from Moodle

**Comment by rabser** [comment]
I don't know why, this should be investigated,but installing BBB was the wrong way. You have to remove BBB from BBBM server first, then re-analyze if you follow all the instructions for scalelite (double check nginx disabled on host and enabled on docker) and then understand why it does'nt work (if the 404 persist).

**Comment by HossamAhmedHamdi** [comment]
> 
> 
> I don't know why, this should be investigated,but installing BBB was the wrong way. You have to remove BBB from BBBM server first, then re-analyze if you follow all the instructions for scalelite (double check nginx disabled on host and enabled on docker) and then understand why it does'nt work (if the 404 persist).

I've removed bbb from main server and disabled nginx from the server and when I try to start it from the docker with "systemctl status scalelite-nginx.service" I get this error.

[emerg] 6#6: invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/scalelite.conf:4
docker[4841]: nginx: [emerg] invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/scalelite.conf:4

check screen attached
https://pasteboard.co/J2DNzCN.jpg

**Comment by rabser** [comment]
verify that the /etc/default/scalelite has all the required entries and that are all filled in correctly and restart the scalelite nginx service

**Comment by ntatgss** [comment]
> verify that the /etc/default/scalelite has all the required entries and that are all filled in correctly and restart the scalelite nginx service

I did exactly like that but still endpoint, I also tested for greenlight with secret of another bbb server, it works. However, when I change the bbb_url in .env of Greenlight to https://scalelite.myserver.com/bigbluebutton it happens the same way with @HossamAhmedHamdi 

```
CONTAINER ID        IMAGE                                             COMMAND                  CREATED              STATUS                          PORTS               NAMES
d7fd779a3b80        blindsidenetwks/scalelite:v1-poller               "bin/start-poller"       About a minute ago   Up About a minute                                   scalelite-poller
a8ea5afd1e66        blindsidenetwks/scalelite:v1-nginx                "/etc/nginx/start -g…"   About a minute ago   Restarting (1) 31 seconds ago                       scalelite-nginx
f963a29309f8        blindsidenetwks/scalelite:v1-recording-importer   "bin/start-recording…"   About a minute ago   Up About a minute                                   scalelite-recording-importer
5da934fdf0ea        blindsidenetwks/scalelite:v1-api                  "bin/start"              About a minute ago   Up About a minute               3000/tcp            scalelite-api
```

The scalelite-nginx Status is restarting always. Is that a problem?

**Comment by HossamAhmedHamdi** [comment]
> 
> 
> verify that the /etc/default/scalelite has all the required entries and that are all filled in correctly and restart the scalelite nginx service

Thanks I had to add HOST URL as I left it blank as the tutorial says but when I added it it worked.
