### ISSUE TITLE
Cant transfer old records

### ISSUE THREAD

**Issue by agustinmono** [blindsidenetworks/scalelite#129]
When I run the provided script 

https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/scalelite_batch_import.sh

i have this error
http://prntscr.com/rurrkp

`scalelite_batch_import.sh: 15: scalelite_batch_import.sh: [[: not found
sudo: ./post_publish/scalelite_post_publish.rb: command not found`

**Comment by IamLuksha** [comment]
Change 

`( cd "$scripts_dir" && sudo -n -u bigbluebutton ./post_publish/scalelite_post_publish.rb -m "$record_id" )`

to

`( cd "$scripts_dir" && sudo -n -u bigbluebutton ruby ./post_publish/scalelite_post_publish.rb -m "$record_id" )`

**Comment by agustinmono** [comment]
Done!
 now i get
Permission denied, how can I change that? thanks 
http://prntscr.com/rwvrbe

**Comment by agustinmono** [comment]
> Change
> 
> `( cd "$scripts_dir" && sudo -n -u bigbluebutton ./post_publish/scalelite_post_publish.rb -m "$record_id" )`
> 
> to
> 
> `( cd "$scripts_dir" && sudo -n -u bigbluebutton ruby ./post_publish/scalelite_post_publish.rb -m "$record_id" )`

@kepstin  Can you take  a look?  the main script here has that mistake. Thanks
https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/scalelite_batch_import.sh

**Comment by IamLuksha** [comment]
@agustinmono Have you done everything here?
https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md

**Comment by agustinmono** [comment]
Yes @IamLuksha  , I have 2 concerns .

1- I Followed[ this instuctive](https://vitux.com/install-nfs-server-and-client-on-ubuntu/) to create the NFS, configuring the Scalelite Server as NFS Server, and each BBB Server as NFS Clients, its that ok? 


2- here https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/README.md#shared-filesystem-eg-nfs-mount says 

" Ensure that the bigbluebutton user has permission to enter and write to the spool directory."

How can I test that? in case that bigbluebutton doesnt has permission, how can I give permissions to him.

Thanks a lot

**Comment by IamLuksha** [comment]
@agustinmono 
There is an example setup via ssh.
If you need to configure the nfs server not via ssh, here is an example
https://www.tecmint.com/how-to-setup-nfs-server-in-linux/

All permissions are here.
https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md

You can check the permission  by writing a file from the user bigbluebutton

**Comment by agustinmono** [comment]
I did all of that, but when I try to create a file here it says permission denied

`nano /mnt/scalelite-recordings/var/bigbluebutton/spool/test.txt`
http://prntscr.com/rwwq92

Permissions :

http://prntscr.com/rwwqhq

I did all that documentation says.. what im missing ?? i dont understand

**Comment by IamLuksha** [comment]
@agustinmono 

If you do:
`getent group`

You should receive
`scalelite-spool:x:2000:bigbluebutton`

and your permissions are correct
I have the same and everything works

**Comment by agustinmono** [comment]
So why i cant write a file? 

how can i write a file as bigbluebutton ? currently Im as root user, maybe is that?

**Comment by IamLuksha** [comment]
for instance

It was
```
root@bbb-sl-pool1:/# ll /mnt/scalelite-recordings/var/bigbluebutton/spool/    
total 8
drwxrwxr-x 2 bbb-server scalelite-spool 4096 Apr 10 21:10 ./
drwxr-xr-x 6 root       root            4096 Apr  8 22:40 ../
```
I created a file from root user
```
root@bbb-sl-pool1:/# touch /mnt/scalelite-recordings/var/bigbluebutton/spool/111                         
root@bbb-sl-pool1:/# ll /mnt/scalelite-recordings/var/bigbluebutton/spool/      
total 8
drwxrwxr-x 2 bbb-server scalelite-spool 4096 Apr 10 21:11 ./
drwxr-xr-x 6 root       root            4096 Apr  8 22:40 ../
-rw-r--r-- 1 root       root               0 Apr 10 21:11 111
```
I created a file from root BBB
```
root@bbb-sl-pool1:/# sudo -n -u bigbluebutton touch /mnt/scalelite-recordings/var/bigbluebutton/spool/222
root@bbb-sl-pool1:/# ll /mnt/scalelite-recordings/var/bigbluebutton/spool/                               
total 8
drwxrwxr-x 2 bbb-server    scalelite-spool 4096 Apr 10 21:11 ./
drwxr-xr-x 6 root          root            4096 Apr  8 22:40 ../
-rw-r--r-- 1 root          root               0 Apr 10 21:11 111
-rw-r--r-- 1 bigbluebutton bigbluebutton      0 Apr 10 21:11 222
```

**Comment by agustinmono** [comment]
I executed the same commands and I get permission denied, can you share with me your 
 /etc/exports/  file config?

of course withot the IP, just to check if this its OK:

`/mnt/scalelite-recordings MY_IP(rw,sync,no_subtree_check)`

**Comment by IamLuksha** [comment]
No problem

But you see the folders, so this config is right for you

with `no_subtree_check` thinks for a long time and nothing happens

```
/mnt/scalelite-recordings IP_ScaleLite (rw,sync,no_root_squash)
/mnt/scalelite-recordings IP_BBB_server_1 (rw,sync,no_root_squash)
.........
/mnt/scalelite-recordings  IP_BBB_server_2 (rw,sync,no_root_squash)
```

**Comment by agustinmono** [comment]
`exportfs: /etc/exports [6]: Neither 'subtree_check' or 'no_subtree_check' specified for export "IP:/mnt/scalelite-recordings".
  Assuming default behaviour ('no_subtree_check').
  NOTE: this default has changed since nfs-utils version 1.0.x`

**Comment by IamLuksha** [comment]
what have you done
Is there a space between IP and ()? If yes. Take it away

**Comment by agustinmono** [comment]
`/mnt/scalelite-recordings 217.79.240.42(rw,sync,no_root_squash)`

**Comment by agustinmono** [comment]
`touch: setting times of '/mnt/scalelite-recordings/var/bigbluebutton/spool/': Permission denied`

Still getting that, i really dont know whats wrong, just a quick question

Your nfs server... is the BigblueButton or the Scalelite? 

I have the Scalelite ad NFS Server  and each Bigbluebutton is a client

**Comment by IamLuksha** [comment]
I am using a standalone server under NFS on the local network.
SL and BBB are client

But this should not affect

**Comment by agustinmono** [comment]
Any idea? really dont know whats wrong

**Comment by IamLuksha** [comment]
@agustinmono 
I have no ideas either
If I come up with something I will write

**Comment by agustinmono** [comment]
Thanks so much for your time, really appreciate the help

**Comment by agustinmono** [comment]
@IamLuksha  I solved with this

https://github.com/blindsidenetworks/scalelite/issues/90


but now the recordings are not listing in the greenligh, know why?

**Comment by IamLuksha** [comment]
@agustinmono 
I am very glad that you have solved the problem.

I do not use Greenlight. I use Moodle to authorize users. To monitor the rallies on the servers I wrote a simple site

**Comment by agustinmono** [comment]
Thanks! is there a way to track the state of the records? scalelite side

**Comment by IamLuksha** [comment]
@agustinmono 
Yes
You can use the BBB API
https://docs.bigbluebutton.org/dev/api.html#getrecordings

**Comment by rexon07** [comment]
> Change
> 
> `( cd "$scripts_dir" && sudo -n -u bigbluebutton ./post_publish/scalelite_post_publish.rb -m "$record_id" )`
> 
> to
> 
> `( cd "$scripts_dir" && sudo -n -u bigbluebutton ruby ./post_publish/scalelite_post_publish.rb -m "$record_id" )`

@IamLuksha @farhatahmad 

after suggested changes as above iam getting the following error https://prnt.sc/tivr2r
Please help

**Comment by IamLuksha** [comment]
maybe because ?

/mnt/scalelite-recordings/var/bigbluebutton/ failed: no such file or directory (2)

**Comment by rexon07** [comment]
has per the the docs i have created that directory on the scalelite server. Can you please let me know what iam missing here?

**Comment by IamLuksha** [comment]
have you mounted this directory on bbb server?
check if this directory exists on bbb server

**Comment by IamLuksha** [comment]
permission denied...

did you do on the BBB server?

# Create a new group with GID 2000
groupadd -g 2000 scalelite-spool
# Add the bigbluebutton user to the group
usermod -a -G scalelite-spool bigbluebutton

**Comment by rexon07** [comment]
Hi, i have scalelite and shared volume for recording setup on server. may be that might be causing the issue.

i feel it has something to do with  these steps : 
Shared filesystem (e.g. NFS mount)
If the Scalelite recordings spool directory is mounted on the BigBlueButton server as a shared filesystem, then you only need to set spool_dir to the location where the spool directory is mounted. Ensure that the bigbluebutton user has permission to enter and write to the spool directory.

@farhatahmad  can you please elaborate these steps.

**Comment by rexon07** [comment]
Hi @IamLuksha 
Finally i managed to solve it. iam getting the following result. I hope its the desired one.
https://prnt.sc/tj31c2

**Comment by IamLuksha** [comment]
@rexon07 what was wrong?

**Comment by rexon07** [comment]
@IamLuksha  i dont think what i did is right. because the transferred recording is not available under scalelite server. it just got transferred to the /mnt/scalelite-recordings/var/bigbluebutton/spool directory in bbb-server.

**Comment by rexon07** [comment]
@IamLuksha i have not yet created it. I went through it . I guess what i have done is right.

**Comment by rexon07** [comment]
i just  changed the owner to bigbluebutton for this directory /mnt/scalelite-recordings/var/bigbluebutton/spool

**Comment by IamLuksha** [comment]
@rexon07  [read this readme](https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md#recording-importer-scalelite-recording-importer)

**Comment by rexon07** [comment]
@IamLuksha  Hi,
i continued the process of deploying scalelite  docker containers. after fixing most of the issues. i got service running But still there is an error :

scalelite-nginx.service - Scalelite Nginx
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-07-17 15:32:29 CEST; 10s ago
  Process: 27349 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
  Process: 27336 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=0/SUCCESS)
  Process: 27295 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
 Main PID: 27460 (docker)
    Tasks: 13 (limit: 4915)
   CGroup: /system.slice/scalelite-nginx.service
           └─27460 /usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount type=bind,

Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal docker[27349]: v1-nginx: Pulling from blindsidenetwks/scalelite
Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal docker[27349]: Digest: sha256:xxxxxx
Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal docker[27349]: Status: Image is up to date for blindsidenetwks/scalelite:v1-nginx
Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal docker[27349]: docker.io/blindsidenetwks/scalelite:v1-nginx
Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal systemd[1]: Started Scalelite Nginx.
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Startup script was run as init, re-execing using tini.
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Generating templated nginx configuration...
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Using SSL configuration template.
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Starting nginx periodic reload process...
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Starting nginx...

Now the status is active but still an error:
scalelite-nginx (code=exited, status=1/FAILURE)

can you please let me know what am i missing here? Thanks in Advance
