### ISSUE TITLE
scalelite api DEAD

### ISSUE THREAD

**Issue by agustinmono** [blindsidenetworks/scalelite#130]
Hi! 
im stuck at starting the scalelite API 

` scalelite-api.service - Scalelite API
   Loaded: loaded (/etc/systemd/system/scalelite-api.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-04-07 11:54:14 -03; 4s ago
  Process: 11186 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-api (code=exited, status=1/FAILURE)
  Process: 11065 ExecStartPre=/usr/bin/docker rm scalelite-api (code=exited, status=1/FAILURE)
  Process: 11032 ExecStartPre=/usr/bin/docker kill scalelite-api (code=exited, status=1/FAILURE)

Apr 07 11:54:14 theUser systemd[1]: Starting Scalelite API...
Apr 07 11:54:14 theUser  docker[11032]: Error response from daemon: Cannot kill container: scalelite-api: No such container: scalelite-api
Apr 07 11:54:14 theUser docker[11065]: Error: No such container: scalelite-api
Apr 07 11:54:14 theUser docker[11186]: invalid reference format
Apr 07 11:54:14 theUser systemd[1]: scalelite-api.service: Control process exited, code=exited status=1
Apr 07 11:54:14 theUser systemd[1]: Failed to start Scalelite API.
Apr 07 11:54:14 theUser systemd[1]: scalelite-api.service: Unit entered failed state.
Apr 07 11:54:14 theUser systemd[1]: scalelite-api.service: Failed with result 'exit-code'.

● scalelite-nginx.service - Scalelite Nginx
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
   Active: inactive (dead) `

**Comment by farhatahmad** [comment]
Did you set the SCALELITE_TAG in /etc/default/scalelite

**Comment by agustinmono** [comment]
now its on but i have this error:
id: bb6d298c-1516-4c70-85c3-ab33593d2aa2
        url: a1.ofmperu.com/bigbluebutton/api/
        secret: TOP_SECRET
        enabled
        load: unavailable
        offline
~ $ ./bin/rake poll:all
D, [2020-04-07T22:21:41.231839 #63] DEBUG -- : Polling meetings
D, [2020-04-07T22:21:41.231990 #63] DEBUG -- : Polling servers
D, [2020-04-07T22:21:41.250019 #63] DEBUG -- : Polling Server id=bb6d298c-1516-4c70-85c3-ab33593d2aa2
W, [2020-04-07T22:21:41.250265 #63]  WARN -- : Failed to get server id=bb6d298c-1516-4c70-85c3-ab33593d2aa2 status: both URI are relative
I, [2020-04-07T22:21:41.250768 #63]  INFO -- : Server id=bb6d298c-1516-4c70-85c3-ab33593d2aa2 offline load: unavailable




This is the BBB Check of the bigbluebutton server

BigBlueButton Server 2.2.3 (1833)
                    Kernel version: 4.4.0-177-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16431 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://a1.ofmperu.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: a1.ofmperu.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://a1.ofmperu.com
                              red5: a1.ofmperu.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.2.35
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 192.168.2.35:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: a1.ofmperu.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 192.168.2.35

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.2.35
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 192.168.2.35
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870
                        kurentoUrl: wss://a1.ofmperu.com/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
