### ISSUE TITLE
Breakout room seems not working

### ISSUE THREAD

**Issue by siz1103** [blindsidenetworks/scalelite#131]
Hello,

I implemented a BBB cluster, all works fine, but when I'm in a room, if I create a Breakout room, the system redirect the users to the ending page, as something goes wrong.
Are there any parameters to enable or any api value to set to enable this function also using the cluster?

**Comment by farhatahmad** [comment]
Breakout rooms are created directly through the BigBlueButton server and not through Scalelite. You might be better off asking in the BigBlueButton repo or on the forums for this issue
