### ISSUE TITLE
Cant chmod the files

### ISSUE THREAD

**Issue by agustinmono** [blindsidenetworks/scalelite#132]
https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#setting-up-directory-structure-and-permissions

When I do:
`chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/spool`

I get 
`chown: changing ownership of '/mnt/scalelite-recordings/var/bigbluebutton/spool': Operation not permitted`

**Comment by paul1278** [comment]
Hi, I guess you are using a ubuntu-system, try using `sudo` in-front of the command

**Comment by thisismsreddy** [comment]
@agustinmono  it looks like nfs issue, By default the root_squash export option is turned on, therefore NFS does not allow a root user from the client to perform operations as root on the server. in your nfs server /etc/exports 

/yournfs/folder   *(rw,insecure,sync,no_subtree_check,no_root_squash)
