### ISSUE TITLE
Scalelite with Moodle problem

### ISSUE THREAD

**Issue by COArikan** [blindsidenetworks/scalelite#133]
Hi all,
I've installed scalelite and 5 bbb servers, connected on the scalelite.. it seems working fine..
I can see rake servers / rake status all perfect..
But I'd like to use scalelite under moodle but it's not satisfied..

First, is it needed to work bbb on scalelite itself? If I write scalelite bbb api/secret on the moodle it si only work on bbb not on load balancer.. If I stop bbb on scalelite, moodle doesn't connect and says server is not reaching... If I use one of my bbb servers, moodle work only with that one and scalelite shows me on that server have some users/meeting on that one only..
So, I can not find a way to load balancing with moodle...

Is there anyone tell me please:
- scalelite need a bbb on same server itself first?
- in moodle, which api address and secret needed? and how can i obtain it for use with scalelite?

any help will be very appreciated..
Thanks..

**Comment by farhatahmad** [comment]
No you shouldn't install BigBlueButton and Scalelite on the same server. 

In Moodle, set you Endpoint to the hostname of the machine you have Scalelite installed on. Should be in the format of `https://scalelite-hostname/bigbluebutton/api`
Set your secret to the `LOADBALANCER_SECRET` in `/etc/default/scalelite`

**Comment by rabser** [comment]
Just a little thing, the moodle plugin "bigbluebuttonbn" does not require the /api on the end of the url, only https://scalelite-hostname/bigbluebutton/ into the bigbluebuttonbn_server_url setting

**Comment by COArikan** [comment]
I think there is a problem on scalelite side.. Because, I've tried with
Address: https://uzem-bbb.ege.edu.tr/bigbluebutton/
Secret: (from /etc/default/scalelite -- by the way, that one is longer than bbb's secrets is it normal??)
Moodle says: Unable to connect. Please check the url of the BigBlueButton server AND check to see if the BigBlueButton server is running.
And I'm trying to connect that url from browser, there is an error like that:  
To allow requests to **my-address**, add the following to your environment configuration:
config.hosts << "**my-address**"
![bbblb-error](https://user-images.githubusercontent.com/13508662/78747393-fceedf80-7971-11ea-8bea-831c513be8c4.jpg)
Is there anything missing on configuration and where is that config file?
Thanks..

**Comment by COArikan** [comment]
Wow, I think I've fixed with your help :) 
I found configs at: /var/lib/docker/overlay2/4a1ad77ddec0513c37523e71572bf420a6e263456b67d7ec65466c6d2d45a9c2/diff/etc/
But it was not changed.. So, later I try 
docker exec -it scalelite-api /bin/sh
and go to config/environments   and development.rb
there's a UTL_HOST for config.hosts
I found it from /etc/default/scalelite and change it from https:///**my-address**/bigbluebutton to only **my-address**
And Moodle works now :)
Thank you very much..

**Comment by COArikan** [comment]
I have another problem now,  there's a database error...
**~ $ ./bin/rake recordings:update**
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "recordings" does not exist
LINE 8:  WHERE a.attrelid = '"recordings"'::regclass

How can I create tables for scalelite required on postgre? I think these tables are not created itself..
Thanks..

**Comment by farhatahmad** [comment]
@COArikan See https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md#initialize-the-scalelite-api-database

**Comment by kunthar** [comment]
<offtopic-sorry>@COArikan please ping me whenever you need help. i am running a cluster of bbb servers and cluster of moodle with haproxy LBs.
</offtopic-sorry>
