### ISSUE TITLE
Records not visible in Scalelite!

### ISSUE THREAD

**Issue by agustinmono** [blindsidenetworks/scalelite#135]
I had a lot of records, now they are all gone, after changinf the .env route to use scalelite

http://prntscr.com/rv5pm8

**Comment by agustinmono** [comment]
Anyone can help me? 

http://prntscr.com/rwhfjc

I haver ecords but they are not listed on the greenlight!

**Comment by rabser** [comment]
I had the same problem: a reboot to the BBB server (not the greenlight one) solved all magically.

**Comment by agustinmono** [comment]
No luck here, i restarted in many times. I think its a NFS error, can you share with my you config of tour nfc? Wich server acts as client?

**Comment by mbile** [comment]
I am facing the same issue. I have recorded many sessions but None is showing. it says this server has no recordings. How can I solve that?

**Comment by agustinmono** [comment]
it worked now? after that config?
Thanks a lot , I f you made it work I ll will try that configuration

**Comment by mbile** [comment]
Hi @agustinmono 
I have just configured the way you have configured it. I was wrong with Scalelite being the nfs client. It is the nfs server and the BBB servers are the clients. everything is working now for me. Have you managed to solve it? let me know if you need any help with the NFS.

**Comment by agustinmono** [comment]
I tried both ways, nos I have my nfs server as the scalelite server , bue its not working, can you share with me how did you make it work

**Comment by MrCapitalist** [comment]
Hi. I have same problem in show records list. I set up scalelite as NFS server and BBB server as NFS client. But how BBB server know transfer records to scalelite?!

https://github.com/blindsidenetworks/scalelite/issues/208#issuecomment-632778244
