### ISSUE TITLE
Loadbalancer Prio

### ISSUE THREAD

**Issue by SebastianZiegler** [blindsidenetworks/scalelite#136]
Hello,

we have a little problem an looking for a solution. At the moment we had 5 BBB server behind scalelite 
bbb1 - bbb5. bbb1 - bbb3 are older real hardware devices with 12 cores (not so fast) and bbb4 and bbb5 are very fast virtual devices (8 cores). They are added to scalelite in order of their names.

Now some of our teachers produces recordings in the evening, that results in bbb1 had a lot of ffmpeg jobs and not finshed in the morning. Over night bbb1 had an average load of 15% so not all cores do rendering.

Now my question: Is the a way to change which bbb servers are served first (maybe the order the added?). Or can we change this in another way. 

best regards
Sebastian

**Comment by einhirn** [comment]
There is a discussion about this in #113 and #108. There also is a Pull Request for 108 that was denied because the team wants to investigate further before implementing something to this effect themselves. I don't know what happened to the PR for 113 which might help in your case...

**Comment by defnull** [comment]
We maintain our own fork with #113 and #115 applied and the firsts tests seem promising.

**Comment by SebastianZiegler** [comment]
Thanks for that so far, works fine. 

But the second problems is still present, the first server that will be uses in my case from above is bbb1, is there a way to change that?
