### ISSUE TITLE
BBB server: [load: unavailable &offline]

### ISSUE THREAD

**Issue by ntatgss** [blindsidenetworks/scalelite#137]
I ran into this after add 2 bbb servers to the scalelite balancer:

> (id: 59d9043c-9cbe-4b33-b965-b20db2c28683
> 	url: https://bbb1.myserver/bigbluebutton/
> 	secret: 0a5dfa4f1f629e04b577d3a1959a333169f692b053be6bbe40be78a4119dyx
> 	enabled
> 	load: unavailable
> 	offline
> id: 875a7b59-b199-4f8d-a7aa-3ac382c038a8
> 	url: https://bbb2.myserver/bigbluebutton/
> 	secret: 0a5dfa4f1f629e04b577d3a1959a333169f692b053be6bbe40be78a4119dyx
> 	enabled
> 	load: unavailable
> 	offline)

I tried ./bin/rake servers:enable[59d9043c-9cbe-4b33-b965-b20db2c28683]  but it did not change. How to make it online and available?

**Comment by SebastianZiegler** [comment]
is the poll service running. Maybe poll all server manually 

./bin/rake poll:all

**Comment by ntatgss** [comment]
I think it's not running:

> ~ $ ./bin/rake poll:all
> D, [2020-04-08T09:32:09.131481 #80] DEBUG -- : Polling meetings
> D, [2020-04-08T09:32:09.131714 #80] DEBUG -- : Polling servers
> D, [2020-04-08T09:32:09.151886 #80] DEBUG -- : Polling Server id=59d9043c-9cbe-4b33-b965-b20db2c28683
> W, [2020-04-08T09:32:09.268996 #80]  WARN -- : Failed to get server id=59d9043c-9cbe-4b33-b965-b20db2c28683 status: internalError: Response did not include returncode
> I, [2020-04-08T09:32:09.269461 #80]  INFO -- : Server id=59d9043c-9cbe-4b33-b965-b20db2c28683 offline load: unavailable
> D, [2020-04-08T09:32:09.269525 #80] DEBUG -- : Polling Server id=875a7b59-b199-4f8d-a7aa-3ac382c038a8
> W, [2020-04-08T09:32:09.385260 #80]  WARN -- : Failed to get server id=875a7b59-b199-4f8d-a7aa-3ac382c038a8 status: internalError: Response did not include returncode
> I, [2020-04-08T09:32:09.385466 #80]  INFO -- : Server id=875a7b59-b199-4f8d-a7aa-3ac382c038a8 offline load: unavailable

**Comment by ntatgss** [comment]
Before the bbb1 was installed by bbb-install.sh (without greenlight). the bbb2 was installed with greenlight (bbb-install.sh -g). I did turn down the greenlight (docker-compose down) and set the sharedsecret of both bbb1 and bbb2 to the LOADBALANCER SECRET of Scalelite Server.

**Comment by ntatgss** [comment]
I fixed them already, the ./bin/rake servers now show:

> id: cea7581a-5ab1-4e13-a992-2234f31ed677
> 	url: https://bbb1.myserver/bigbluebutton/api
> 	secret: 0a5dfa4f1f629e04b577d3a1959a333169f692b053be6bbe40be78a41191dyx
> 	enabled
> 	load: 0.0
> 	online
> id: a01853f5-4bc8-442f-814f-0cef664ce94a
> 	url: https://bbb2.myserver/bigbluebutton/api
> 	secret: 0a5dfa4f1f629e04b577d3a1959a333169f692b053be6bbe40be78a4119dyx
> 	enabled
> 	load: 0.0
> 	online

However, on the scalelite.myserver Home:

> Server Error
> Invalid BigBlueButton Endpoint and Secret

**Comment by agustinmono** [comment]
i had the same issue, try adding /api at the end of the url

**Comment by agustinmono** [comment]
I dont think its a good idea have bigbluebutton and scalelite in the same server
They usually work like this
http://prntscr.com/rvict2

**Comment by ntatgss** [comment]
> I dont think its a good idea have bigbluebutton and scalelite in the same server
> They usually work like this
> http://prntscr.com/rvict2

I fixed it by adding /api at the end. But still the error of BBB endpoint. I setup BBB separately with the Scalelite server. But the Greenlight is on the Scalelite server too.
