### ISSUE TITLE
cant transfer files

### ISSUE THREAD

**Issue by agustinmono** [blindsidenetworks/scalelite#141]
I have this error please help! when i run 

root@bbb-02:/# sh scalelite_batch_import.sh
scalelite_batch_import.sh: 15: scalelite_batch_import.sh: [[: not found
sudo: ./post_publish/scalelite_post_publish.rb: command not found
scalelite_batch_import.sh: 15: scalelite_batch_import.sh: [[: not found
sudo: ./post_publish/scalelite_post_publish.rb: command not found

**Comment by rabser** [comment]
Did you changed the script in any way ?
This is a bash error: take a look at the script syntax correctness.

**Comment by agustinmono** [comment]
@rabser no, i didnt i just nano nameoffile and paste the content, saved and tried to run the srcipt

**Comment by agustinmono** [comment]
Cab you merge this issue? I really have no clue Whats happenign 
https://github.com/blindsidenetworks/scalelite/issues/129

**Comment by agustinmono** [comment]
root@bbb-01:~# sudo -n -u bigbluebutton touch /mnt/scalelite-recordings/var/bigbluebutton/spool/222
touch: cannot touch '/mnt/scalelite-recordings/var/bigbluebutton/spool/222': Permission denied

**Comment by ntatgss** [comment]
> root@bbb-01:~# sudo -n -u bigbluebutton touch /mnt/scalelite-recordings/var/bigbluebutton/spool/222
> touch: cannot touch '/mnt/scalelite-recordings/var/bigbluebutton/spool/222': Permission denied

I have the same error when run 
`sudo -n -u bigbluebutton touch /mnt/scalelite-recordings/var/bigbluebutton/spool/222`

What did you do to resolve it?

**Comment by agustinmono** [comment]
@ntatgss 
Check here https://github.com/blindsidenetworks/scalelite/issues/90

and 

here https://github.com/blindsidenetworks/scalelite/issues/129#issuecomment-612101115

**Comment by ntatgss** [comment]
I did all that, edit the files needed but still same error. I think I have problem with this:

> This will create a file ~/.ssh/scalelite.pub with the public key, you will have to add that public key to the authorized_keys file on the destination system.
> 
> You can then edit the file ~/.ssh/config and add a section to configure the user and key to use. It will look something like this:
> 
> Host scalelite-recording.example.com
>         User scalelite-spool
>         IdentityFile ~/.ssh/scalelite

When I do ssh scalelite-recording.example.com the terminal ask for my password for scalelite-spool on LB server!

**Comment by agustinmono** [comment]
I didnt use that system, I ve created a NFS mounted direcotry

Dont know about that

**Comment by ntatgss** [comment]
> I didnt use that system, I ve created a NFS mounted direcotry
> 
> Dont know about that

Okay I misunderstood the guide, I did both setup, quick question, did you place this code at the end of scalelite_post_publish.rb

` extra_rsync_string = extra_rsync_opts.join(' ') 
  puts("Adding extra rsync options:  #{extra_rsync_string} ")

  puts("Transferring recording archive to #{spool_dir}")
  system('sg','scalelite-spool', '-c', "rsync --verbose --protect-args #{extra_rsync_string} #{archive_file} #{spool_dir}") \
    || raise('Failed to transfer recording archive')`

**Comment by rabser** [comment]
You should let we know which method you have chosen: NFS or SSH ?
If you are using NFS only, then take  look at issue #90, because you should change the primary group of bigbluebutton process before doing rsync.
If you are using SSH, then you should only check if the bigbluebutton user can do an ssh with only keys.
In either method, the troubles are in configuring them correctly, it's not an issue of scalelite, so this could not be the best way of getting proper support for.

**Comment by ntatgss** [comment]
> You should let we know which method you have chosen: NFS or SSH ?
> If you are using NFS only, then take look at issue #90, because you should change the primary group of bigbluebutton process before doing rsync.
> If you are using SSH, then you should only check if the bigbluebutton user can do an ssh with only keys.
> In either method, the troubles are in configuring them correctly, it's not an issue of scalelite, so this could not be the best way of getting proper support for.

I am using NFS only now, please hlep me with this "you should change the primary group of bigbluebutton process before doing rsync". I added the codes in #90 to the end of scalelite_post_publish.rb. Now it is like this (added to the end):

```
archive_file = "#{work_dir}/#{meeting_id}.tar"
begin
  puts('Creating recording archive')
  FileUtils.mkdir_p(work_dir)
  FileUtils.cd(published_dir) do
    system('tar', '--create', '--file', archive_file, *format_dirs) \
      || raise('Failed to create recording archive')
  end

  puts("Transferring recording archive to #{spool_dir}")
  system('rsync', '--verbose', '--protect-args', *extra_rsync_opts, archive_file, spool_dir) \
    || raise('Failed to transfer recording archive')
ensure
  FileUtils.rm_f(archive_file)
end

extra_rsync_string = extra_rsync_opts.join(' ')
puts("Adding extra rsync options:  #{extra_rsync_string} ")

puts("Transferring recording archive to #{spool_dir}")
system('sg','scalelite-spool', '-c', "rsync --verbose --protect-args #{extra_rsync_string} #{archive_file} #{spool_dir}") \
  || raise('Failed to transfer recording archive')

```

**Comment by rabser** [comment]
And does it works ? try it ...

**Comment by ntatgss** [comment]
> And does it works ? try it ...

It works. Thank you a lot @rabser . I made the user Bigbluebutton to a PRIMARY group and then it runs.


The playback (recordings) is played at http://scalelite.myserver.com/playback/presentation/2.0/playback.html?meetingId=...

I did customize the playback.html and playback.js on all my bbb servers. 

Quick question: How to customize that on Scalelite?

**Comment by agustinmono** [comment]
> Quick question: How to customize that on Scalelite?

same here

**Comment by ntatgss** [comment]
> > Quick question: How to customize that on Scalelite?
> 
> same here

I guess it is handled by the Scalelite-api docker, so we need to customize it by building local image for Scalelite-api docker.

**Comment by thisismsreddy** [comment]
@ntatgss quick question,  "I made the user Bigbluebutton to a PRIMARY group and then it runs."  how to I add  Bigbluebutton user  to a PRIMARY group ?

**Comment by rexon07** [comment]
> > And does it works ? try it ...
> 
> It works. Thank you a lot @rabser . I made the user Bigbluebutton to a PRIMARY group and then it runs.
> 
> The playback (recordings) is played at http://scalelite.myserver.com/playback/presentation/2.0/playback.html?meetingId=...
> 
> I did customize the playback.html and playback.js on all my bbb servers.
> 
> Quick question: How to customize that on Scalelite?

@ntatgss can you please explain this part " I made the user Bigbluebutton to a PRIMARY group and then it runs." 
thanks in advance
