### ISSUE TITLE
Scalelite: What is the proper way to mount NFS shared volume?

### ISSUE THREAD

**Issue by mbile** [blindsidenetworks/scalelite#145]
Hello,
I have successfully installed Scalelite and added two servers(VC5 and VC6). When I record sessions, I can see recordings only from VC5. I have installed Greenlight on the VC5 server. I think that something is wrong with the way I setup NFS shared volume. I have installed nfs servers on the BBB servers and NFS client on Scalelite Server. I have used the mount point in the documents: /mnt/scalelite-recordings for the BBB servers and Scalelite. 
On the Scalelite, for the mount points to be persistent. I have added in the /etc/fstab like this:

x.x.x.9:/mnt/scalelite-recordings    /mnt/scalelite-recordings   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0
x.x.x.10:/mnt/scalelite-recordings    /mnt/scalelite-recordings   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0

After running this command:
mount -a
I could see both mount points using df -h command:
x.x.x.9:/mnt/scalelite-recordings   48G  9.2G   36G  21% /mnt/scalelite-recordings
x.x.x.10:/mnt/scalelite-recordings   48G  9.2G   36G  21% /mnt/scalelite-recordings

After a while, the mount point of the second BBB server(x.x.x.10) disappears but The first mount is persistent.  If I run mount -a again both of them show up again. I tried to search a way I can automount all NFS mount points but to no avail.

On the Scalelite(NFS client), I am mounting the remote servers to the same local directory of /mnt/scalelite-recordings. Is this the way I am supposed to do? 
I did not mount on the BBB servers since they are nfs servers although in the docs I have seen this:
"A shared volume should be mounted via NFS on the following systems:

BigBlueButton servers
Host system for scalelite-nginx Docker container
Host system for scalelite-recording-importer Docker container"
Is the Scalelite NFS server or NFS client? Just I am confused here!

On the BBB servers(NFS servers), this is how I have allowed the remote connection in /etc/exports:
/mnt/scalelite-recordings   *(rw,sync,no_root_squash)

Here's the content of scalelite.yml on each BBB servers:

cat /usr/local/bigbluebutton/core/scripts/scalelite.yml

work_dir: /var/bigbluebutton/recording/scalelite
spool_dir: /mnt/scalelite-recordings/var/bigbluebutton/spool

I did not use "Transfer using rsync over SSH" section. 

What am I missing here? Can someone please guide me?

Thanks.

**Comment by mbile** [comment]
Everything is working now for me. The Scalelite server is the NFS server and the BBB servers are clients. That is where I had it wrong. Hope someone will help this information.

**Comment by WinkieWinkie** [comment]
Hi @mbile I am about to do my setup of Scallite and i bookmarked your post because i also had an issue understanding this setup but your last comment confirmed it's as you mentioned. But am a bit confused on the scalelite_recording_transfer.rb script mentioned in the docs. Where can i can get the contents to this script or how is it setup been at it for a few days trying to understand but no avail. Any leads?

**Comment by mbile** [comment]
Hi,
You can find it here:


https://github.com/blindsidenetworks/scalelite/tree/master/bigbluebutton

Regards,

**Comment by mbile** [comment]
You may check this as well:
#90
