### ISSUE TITLE
Configuring the BigBlueButton recording transfer

### ISSUE THREAD

**Issue by mohamedelashhab** [blindsidenetworks/scalelite#147]
I installed scalelite and i have 4 polls , every thing work fine and all polls online and connected but the published records not tranfered to main server scalelite i have a trouble with transfer configuration please help

**Comment by agustinmono** [comment]
FUCKIGN SOLVED THE PROBLEM! AFTER 4 DAYS IT WAS JUST A DUMB CONFIG


This is what I done, no luck making it work, but maybe you can try 
https://vitux.com/install-nfs-server-and-client-on-ubuntu/

Server NFS Side - Scalelite:

 `sudo apt install nfs-kernel-server`
`sudo mkdir -p /mnt/scalelite-recordings`
`sudo chown nobody:nogroup /mnt/scalelite-recordings`
`sudo chmod 777 /mnt/scalelite-recordings`
`sudo nano /etc/exports
`
Inside exports, one line by BBB IP, this is the most important part, in the documentation says ,
(rw,sync,no_subtree_check), insted you need to: 

/mnt/scalelite-recordings Client_IP_BBB(rw,sync,subtree_check)

`sudo exportfs -a`

`sudo systemctl restart nfs-kernel-server`

`sudo ufw allow from [clientIP or clientSubnetIP] to any port nfs`


Client NFS Silde - BigBlueButton

`sudo apt-get update`
`sudo apt-get install nfs-common`
`sudo mkdir -p /mnt/scalelite-recordings`
`sudo mount serverIP:/mnt/scalelite-recordings /mnt/scalelite-recordings`

Jumped to : https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md


Now that its working on one server ill try to replicate to my 8 bbb servers, I need to sleep first! 

Good luck

**Comment by agustinmono** [comment]
This erros show upo when i run the script  

`sudo sh scalelite_batch_import.sh`

root@bbb-01:/# sudo sh scalelite_batch_import.sh
scalelite_batch_import.sh: 15: scalelite_batch_import.sh: [[: not found
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Transferring recording for 05a733aeda9e727f47f0d7103486ad8151e332d2-1586463351690 to Scalelite
Found recording format: presentation/05a733aeda9e727f47f0d7103486ad8151e332d2-1586463351690
Creating recording archive
Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool
05a733aeda9e727f47f0d7103486ad8151e332d2-1586463351690.tar
rsync: mkstemp "/mnt/scalelite-recordings/var/bigbluebutton/spool/.05a733aeda9e727f47f0d7103486ad8151e332d2-1586463351690.tar.JuWehx" failed: Permission denied (13)

**Comment by agustinmono** [comment]
root@bbb-01:~# sudo -n -u bigbluebutton touch /mnt/scalelite-recordings/var/bigbluebutton/spool/222
touch: cannot touch '/mnt/scalelite-recordings/var/bigbluebutton/spool/222': Permission denied

**Comment by secretreal26** [comment]
Hi, I understand that @rabser solved this but I could not do it after adding strings another error I get but I think I added or changed wrong so I asked to @rapser

You can check :
[https://github.com/blindsidenetworks/scalelite/issues/90](url)

**Comment by agustinmono** [comment]
Link not working

**Comment by agustinmono** [comment]
I did it and now it works thanks a lot

just some issue, the records are not showing up in the greenligh front end, how can I check that its working

**Comment by rabser** [comment]
If you are using NFSv4 as scalelite recording spool filesystem, you should verify that the domain information on either NFS server and client are coeherent and you should check that in either NFS server and client there are the SAME users with the SAME userid.
But this is not about scalelite, it's about configuring NFS.

**Comment by agustinmono** [comment]
How can i check that, can you give me a hand there?
Thabks

**Comment by mohamedelashhab** [comment]
i want a help in Transfer using rsync over SSH section @agustinmono 
i have done all steps you showed me at the top and works fine but i want your help in the section of Transfer using rsync over SSH

**Comment by mohamedelashhab** [comment]
@agustinmono 
sudo chown -R bigbluebutton:bigbluebutton /mnt/scalelite-recordings/var/bigbluebutton/spool
changing ownership of '/mnt/scalelite-recordings/var/bigbluebutton/spool': Operation not permitted

**Comment by agustinmono** [comment]
I dont know really, i just usted the NFS . Didnt use rsync over ssh

**Comment by mohamedelashhab** [comment]
@agustinmono  i used nfs like you
could you tell me  how  old records works ?

**Comment by mohamedelashhab** [comment]
wher I run sudo sh scalelite_batch_import.sh
get that Can't open scalelite_post_publish.rb

**Comment by agustinmono** [comment]
first run this commands on the scalelite server (needs to be a different server that bigbluebutton)

```
# Create the spool directory for recording transfer from BigBlueButton
mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/spool
chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/spool
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/spool

# Create the temporary (working) directory for recording import
mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
chown 1000:1000 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite

# Create the directory for published recordings
mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/published
chown 1000:1000 /mnt/scalelite-recordings/var/bigbluebutton/published
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/published

# Create the directory for unpublished recordings
mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/unpublished
chown 1000:1000 /mnt/scalelite-recordings/var/bigbluebutton/unpublished
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/unpublished




Then 


do this
https://github.com/blindsidenetworks/scalelite/issues/90

**Comment by agustinmono** [comment]
also you can check my issues 
https://github.com/blindsidenetworks/scalelite/issues/129
https://github.com/blindsidenetworks/scalelite/issues/141

**Comment by mohamedelashhab** [comment]
thank you for your help @agustinmono 
after i configured what you mentioned me at the top i got that

scalelite_batch_import.sh: 16: scalelite_batch_import.sh: [[: not found
Transferring recording for 04816973751d104d6b2743bc80b9eaa2e86262d9-1586707448002 to Scalelite
Found recording format: presentation/04816973751d104d6b2743bc80b9eaa2e86262d9-1586707448002
Creating recording archive
Adding extra rsync options:
Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool

*********
and nothing happend after i was waiting 1 hour

**Comment by agustinmono** [comment]
can you post the output of 

`ls  /mnt/scalelite-recordings/var/bigbluebutton/spool`

**Comment by mohamedelashhab** [comment]
@agustinmono 
when i run ls /mnt/scalelite-recordings/var/bigbluebutton/spool
it take long  time running and i should close the terminal

**Comment by agustinmono** [comment]
Try rebooting the server

after that if keeps try unmounting the partition and mount again

**Comment by mohamedelashhab** [comment]
@agustinmono 
after rebooting the output 
scalelite_batch_import.sh: 16: scalelite_batch_import.sh: [[: not found
Transferring recording for efb5d35affdb74825af0b83c81cf7aac78936f30-1586943754000 to Scalelite
Found recording format: presentation/efb5d35affdb74825af0b83c81cf7aac78936f30-1586943754000
Creating recording archive
Adding extra rsync options:
Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool
rsync: change_dir#3 "/mnt/scalelite-recordings/var/bigbluebutton" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(712) [Receiver=3.1.1]
./post_publish/scalelite_post_publish.rb:67:in `<main>': Failed to transfer recording archive (RuntimeError)

**Comment by mohamedelashhab** [comment]
@agustinmono 
when i  run script give me 
scalelite_batch_import.sh: 16: scalelite_batch_import.sh: [[: not found
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Transferring recording for ffd81b599a40efb9306cb1fe2334b7d5f165a8d1-1586680305091 to Scalelite
Found recording format: presentation/ffd81b599a40efb9306cb1fe2334b7d5f165a8d1-1586680305091
Creating recording archive
Adding extra rsync options:
Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool
ffd81b599a40efb9306cb1fe2334b7d5f165a8d1-1586680305091.tar
sent 5,633,500 bytes  received 35 bytes  11,267,070.00 bytes/sec
total size is 5,632,000  speedup is 1.00

but when i run  ls /mnt/scalelite-recordings/var/bigbluebutton/spool
give me nothing

**Comment by mohamedelashhab** [comment]
@rabser 
@agustinmono 
when i  run script give me 
scalelite_batch_import.sh: 16: scalelite_batch_import.sh: [[: not found
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Transferring recording for ffd81b599a40efb9306cb1fe2334b7d5f165a8d1-1586680305091 to Scalelite
Found recording format: presentation/ffd81b599a40efb9306cb1fe2334b7d5f165a8d1-1586680305091
Creating recording archive
Adding extra rsync options:
Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool
ffd81b599a40efb9306cb1fe2334b7d5f165a8d1-1586680305091.tar
sent 5,633,500 bytes  received 35 bytes  11,267,070.00 bytes/sec
total size is 5,632,000  speedup is 1.00

but when i run  ls /mnt/scalelite-recordings/var/bigbluebutton/spool
give me nothing

**Comment by rabser** [comment]
The transfer happened, if the scalelite-importer did thier job correctly, then the transferred file has to be deleted from the spool: this it right.
Do you checked if the recording is now available from the cluster url ?

**Comment by mohamedelashhab** [comment]
@rabser 
url available but give me record not found after i visited it from moodle
and there is no records in /mnt/scalelite-recordings/var/bigbluebutton/published/presentation after transfering records through scalelite_batch_import.sh

**Comment by rabser** [comment]
At this point i don't know.

**Comment by mohamedelashhab** [comment]
@rabser thank you 
there was a permission problem with scalelite-recordings that abort transferring to published
now it works for chown -R 777

**Comment by revdsam** [comment]
@mohamedelashhab 

I experienced this same issue -- if permissions are not correct, the files do not end up published but the importer deletes the recordings and so you end up with nothing after everything is processed. In my case I did not see any errors reported anywhere, only evidence of a problem is recordings vaporized.

**Comment by farhatahmad** [comment]
Looks like everything was solved here. Thanks for your support @rabser @agustinmono

**Comment by AminaSaif** [comment]
> @mohamedelashhab
> 
> I experienced this same issue -- if permissions are not correct, the files do not end up published but the importer deletes the recordings and so you end up with nothing after everything is processed. In my case I did not see any errors reported anywhere, only evidence of a problem is recordings vaporized.

I think we are experiencing the same, we have noticed that some recordings are no longer available on the shared drive. Let say out of 20 records only 16 are available on Scalelite and 4 are missing!! Can you advise on how to troubleshoot and resolve this issue.

**Comment by german2209** [comment]
> @rabser thank you
> there was a permission problem with scalelite-recordings that abort transferring to published
> now it works for chmod -R 777

Hi,
I'm facing a trouble of permission errors for the recordings transfer.
I have followed and executed every step mentioned above but can't get rid of a Permission denied (13) when executing the scalelite_batch_import.sh 
My recordings never gets to the shared NFS.
Can you share with me how did you setup the permissions in the NFS backend and BBB?
Thanks in advance for your help.

**Comment by rexon07** [comment]
@agustinmono  Hi,

i followed the steps by you regarding NFS and also referred https://vitux.com/install-nfs-server-and-client-on-ubuntu/ 
After running the mount command i get an connection time out error. Can you let me know what might be the issue here.
  https://prnt.sc/tvi4hy

**Comment by rohitcoder** [comment]
@agustinmono  @rexon07  can you help me with this above issue? I am also facing same problem `

`mount.nfs: Connection timed out``

**Comment by rohitcoder** [comment]
@agustinmono  @rabser  @mohamedelashhab i am getting this error while running ``sh scalelite_batch_import.sh`` any idea why?

```
scalelite_batch_import.sh: 15: scalelite_batch_import.sh: [[: not found
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Transferring recording for fcf236af9747db4374c89529d812c361d807681d-1599159500290 to Scalelite
Found recording format: presentation/fcf236af9747db4374c89529d812c361d807681d-1599159500290
Creating recording archive
Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool
fcf236af9747db4374c89529d812c361d807681d-1599159500290.tar

sent 2,581,236 bytes  received 35 bytes  5,162,542.00 bytes/sec
total size is 2,580,480  speedup is 1.00
Adding extra rsync options:   
Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool
rsync: link_stat "/var/bigbluebutton/recording/scalelite/fcf236af9747db4374c89529d812c361d807681d-1599159500290.tar" failed: No such file or directory (2)

sent 16 bytes  received 12 bytes  56.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
./post_publish/scalelite_post_publish.rb:74:in `<main>': Failed to transfer recording archive (RuntimeError)
```

**Comment by andrekutianski** [comment]
> If you are using NFSv4 as scalelite recording spool filesystem, you should verify that the domain information on either NFS server and client are coeherent and you should check that in either NFS server and client there are the SAME users with the SAME userid.
> But this is not about scalelite, it's about configuring NFS.

Is there a recommended configuration for use along with the necessary permissions for scalelite beyond the standard that many are likely to be using?

For example, I use the basic config in `/etc/exports`

```
/mnt/scalelite-recordings 10.0.0.100(rw,sync,no_root_squash)
```

**Comment by ontimond** [comment]
> > If you are using NFSv4 as scalelite recording spool filesystem, you should verify that the domain information on either NFS server and client are coeherent and you should check that in either NFS server and client there are the SAME users with the SAME userid.
> > But this is not about scalelite, it's about configuring NFS.
> 
> Is there a recommended configuration for use along with the necessary permissions for scalelite beyond the standard that many are likely to be using?
> 
> For example, I use the basic config in `/etc/exports`
> 
> ```
> /mnt/scalelite-recordings 10.0.0.100(rw,sync,no_root_squash)
> ```

This NFS config worked for me
`/mnt/scalelite-recordings xxx.xxx.xx.xx(rw,sync,all_squash,anonuid=2000,anongid=2000)`

See [https://serverfault.com/a/241272/532044](https://serverfault.com/a/241272/532044)

**Comment by uzeportal** [comment]
Hello there. I don't know much about these matters. I only have little knowledge of installing bbb servers and scalelite server. I can setup my own scalelite server and bbb servers. But I don't know anything about records. Please help me with this. I would be very happy if you could write the houses step by step.

I have 24 of my own BBB servers. BBB version 2.3 was installed on each virtual server by dividing it into vps on a physical server. I'm also using Scalelite as a load balancer. Previously, we used to download lecture recordings as mp4 while using individual bbb server. However, when I start using scalelite, the records do not appear on the scalelite server. It appears on BBB servers, but these recordings cannot be viewed on moodle and therefore we cannot download them as mp4. For this reason, I stopped using scalelite for now and started using it by duplicating dozens of bbb plugins on the moodle site as a much more difficult method. I am using a BBB plugin for each BBB live lecture room. In the use of Scalelite, how will the records in each bbb server be listed in moodle, what should I do?
  Pls help me.

**Comment by mohamedelashhab** [comment]
Are you tried to follow these comments?

**Comment by mohamedelashhab** [comment]
Are you sure all services works fine?

**Comment by uzeportal** [comment]
**I installed Scalelite according to the instructions in this link:** https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6

**I did what is necessary to activate the Scalelite Registration Function according to the instructions in this link:** https://jffederico.medium.com/scalelite-lazy-deployment-part-ii-ca3e4bf82f8d

Scalelite works fine. It distributes new live lesson requests to bbb servers according to availability. However, I could not register the course.

**Comment by mohamedelashhab** [comment]
Did you mean record not transferred to scalelite server but its on own bbb server?

**Comment by fmasoudy** [comment]
> @rabser thank you
> there was a permission problem with scalelite-recordings that abort transferring to published
> now it works for chmod -R 777

This solved my issue

It should be mentioned in  `https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#setting-up-a-shared-volume-for-recordings`

**Comment by harika1258** [comment]
Hi @fmasoudy



> > @rabser thank you
> > there was a permission problem with scalelite-recordings that abort transferring to published
> > now it works for chmod -R 777
> 
> This solved my issue
> 
> It should be mentioned in [https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#setting-up-a-shared-volume-for-recordings](url)

where we should put this command chmod -R 777  ?

**Comment by fmasoudy** [comment]
I used it on the scalelite-recordings folder and everything went okay for
me.

**Comment by harika1258** [comment]
Thank you so much @fmasoudy 
in the each BBB server or ScaleLite?

**Comment by fmasoudy** [comment]
It should be done once on the mounted volume on scalelite.

**Comment by harika1258** [comment]
@fmasoudy 
I did it. but already not happened! :-(

**Comment by khaclamxd** [comment]
Dear,
I have configured everything OK, connecting scalelite API and moodle successfully. However, like you, in the RECORDINGS display section of BBB it always shows "No Data display". Please share if anyone has solved the problem.
https://prnt.sc/B6DpaAsrwHvr

https://prnt.sc/h1N20ciq3z9U
Sincerely thank you!
