### ISSUE TITLE
scalelite with canvas recording

### ISSUE THREAD

**Issue by secretreal26** [blindsidenetworks/scalelite#149]
Hi,

We are using scalelite with greenlight and canvas.. Greenlight is working without problem and we can user records in greenlight but when use canvas and start recording it does not show canvas after finished session. 
I see some logs one of BBB's

I, [2020-04-12T02:35:31.123848 #30504]  INFO -- : Making callback for recording ready notification
I, [2020-04-12T02:35:31.126170 #30504]  INFO -- : Sending request to https://canvas.mydomain.com/api/v1/courses/1/conferences/11/recording_ready
I, [2020-04-12T02:35:31.515209 #30504]  INFO -- : Callback HTTP request failed: 401 Unauthorized (code 401)
I, [2020-04-12T02:35:31.515269 #30504]  INFO -- : Recording Ready notify ends

We need to setup some config other than greenlight for canvas ?

Regards,

**Comment by ffdixon** [comment]
Check the API call coming back from Canvas for getRecordings (I assume you've setup your own open source version of Canvas).  Look for any errors on that call.

**Comment by secretreal26** [comment]
Thanks for your fast reply, I just setup from https://github.com/instructure/canvas-lms/wiki/Production-Start

**Comment by secretreal26** [comment]
I just look production.log in Canvas for getRecordings and can not see ant error log..

**Comment by secretreal26** [comment]
I understand that my problem is about recording permission. 

Thanks @ffdixon
