### ISSUE TITLE
split html5client from bigbluebutton server

### ISSUE THREAD

**Issue by headria** [blindsidenetworks/scalelite#151]
I want to install html5client on there from bigbbluebutton server. which that mean I want to install html5client in server A and install bigbluebutton on server B is it possible ??? and how can I do it.

**Comment by farhatahmad** [comment]
Hi @headria 

This is the repository for Scalelite. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
