### ISSUE TITLE
Recordings not been published!

### ISSUE THREAD

**Issue by agustinmono** [blindsidenetworks/scalelite#153]
Bigbluebutton its transfering the records into the Spool floder, but nothing happens later, they are not in the published floder. Why?
http://prntscr.com/ry1xrq

**Comment by farhatahmad** [comment]
If they're in the spool directory then the recording-importer isn't running or is not running correctly. Can you check the logs for it? `docker logs scalelite-recording-importer` I believe should return the logs

**Comment by agustinmono** [comment]
I restarted all my services and its working

Just a question if I have multiples greenlights , the records will be visible everywhere right?

**Comment by farhatahmad** [comment]
@agustinmono Greenlight only displays the recordings for the rooms in its database. So if the multiple Greenlights share the same db, then yes, if not then no
