### ISSUE TITLE
Servers Vanishes from Pool

### ISSUE THREAD

**Issue by HossamAhmedHamdi** [blindsidenetworks/scalelite#154]
This happened twice last 2 days I found no servers in the pool and I have to add them again but today I couldn't add any servers before I make reboot to the server and when it came up again I found the servers already in the pool and I didn't have to add them again!.

**Comment by farhatahmad** [comment]
You don't have persistence enabled on your Redis server. Enable it and the servers will stop disappearing

**Comment by HossamAhmedHamdi** [comment]
@farhatahmad 
I've enabled persistence and made reboot to the server and still the same error.

**Comment by HossamAhmedHamdi** [comment]
@farhatahmad 
right now it doesn't accept to add servers at all I'm getting this error 

> rake aborted!
> Redis::CommandError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
