### ISSUE TITLE
Can't join existing meetings on a disabled server

### ISSUE THREAD

**Issue by kurjajuur666** [blindsidenetworks/scalelite#155]
Not really a major issue we can't get around, just noticed something. Tested this with Moodle plugin only.

As far as documentation is concerned, new meetings won't get started on the disabled server and existing meetings will be fine. However, when a user tries to join a running meeting on a disabled server, one would expect the user to join the meeting on the disabled server since they won't be starting a new meeting, but instead they will start a new meeting on another server. Is this expected behavior? Doesn't really work out for people who might join late if a server had to be disabled for some reason. Perhaps something to be considered. Or maybe I don't understand how all of this works.

**Comment by farhatahmad** [comment]
Hi @kurjajuur666, 

What front-end are you using? Some front-ends send a create call right before sending a join call which would lead to the situation you're describing.

**Comment by kurjajuur666** [comment]
Moodle 3.7 with moodle-mod_bigbluebuttonbn (2019042008)

**Comment by farhatahmad** [comment]
@kurjajuur666 Are you able to reproduce this consistently?
