### ISSUE TITLE
How to edit the playback files?

### ISSUE THREAD

**Issue by mabras** [blindsidenetworks/scalelite#156]
Usually I edit the playback HTML, CSS files from BBB server:
```
/var/bigbluebutton/playback/presentation/2.0
```
 Now with Scalelite this different. How can I do that?

Thanks

**Comment by ntatgss** [comment]
Me too, I can not figure out where to edit it

**Comment by rriscado** [comment]
You need mount a host disc in nginx container with presentation folder to edit the files and don't lost changes after docker nginx restart.

Steps:

1. Copy presentation folder from DOCKER Container to LOCAL-FOLDER
> docker cp scalelite-nginx:/var/bigbluebutton/playback/presentation/2.0 /LOCAL-FOLDER/scalelite/presentation_2.0

2. Edit the folow line in /etc/systemd/system/scalelite-nginx.service
> ExecStart=/usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount type=bind,source=${SCALELITE_RECORDING_DIR}/published,target=/var/bigbluebutton/published,readonly **--mount type=bind,source=/LOCAL-FOLDER/presentation_2.0,target=/var/bigbluebutton/playback/presentation/2.0,readonly** $SCALELITE_NGINX_EXTRA_OPTS blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx

3. Reload Systemd configuation
>systemctl daemon-reload

4. Restart Nginx Docker Container
>systemctl restart scalelite-nginx.service

5. Edit your presentation files (CSS, JScript, HTML etc) without restart.
> vi /LOCAL-FOLDER/scalelite/presentation_2.0/.......

**Comment by beri-sela** [comment]
> You need mount a host disc in nginx container with presentation folder to edit the files and don't lost changes after docker nginx restart.
> 
> Steps:
> 
>     1. Copy presentation folder from DOCKER Container to LOCAL-FOLDER
> 
> 
> > docker cp scalelite-nginx:/var/bigbluebutton/playback/presentation/2.0 /LOCAL-FOLDER/scalelite/presentation_2.0
> 
>     1. Edit the folow line in /etc/systemd/system/scalelite-nginx.service
> 
> 
> > ExecStart=/usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount type=bind,source=${SCALELITE_RECORDING_DIR}/published,target=/var/bigbluebutton/published,readonly **--mount type=bind,source=/LOCAL-FOLDER/presentation_2.0,target=/var/bigbluebutton/playback/presentation/2.0,readonly** $SCALELITE_NGINX_EXTRA_OPTS blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx
> 
>     1. Reload Systemd configuration
> 
> 
> > systemctl daemon-reload
> 
>     1. Restart Nginx Docker Container
> 
> 
> > systemctl restart scalelite-nginx.service
> 
>     1. Edit your presentation files (CSS, JScript, HTML etc) without restart.
> 
> 
> > vi /LOCAL-FOLDER/scalelite/presentation_2.0/.......

Thank you for this. You ommitted /scalelite on the source, so that line should look like this:

> > ExecStart=/usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount type=bind,source=${SCALELITE_RECORDING_DIR}/published,target=/var/bigbluebutton/published,readonly **--mount type=bind,source=/LOCAL-FOLDER/scalelite/presentation_2.0,target=/var/bigbluebutton/playback/presentation/2.0,readonly** $SCALELITE_NGINX_EXTRA_OPTS blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx

**Comment by harika1258** [comment]
Thank you so much for this issue
I configured my scalelite based on[ lazy scalelite](https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6), and I don't have /etc/systemd/system/scalelite-nginx.service
how can I apply path change into scalelite-nginx.service  ?
Thanks.
