### ISSUE TITLE
Error: "We could'nt find a meeting with that ID"

### ISSUE THREAD

**Issue by HossamAhmedHamdi** [blindsidenetworks/scalelite#157]
I'm using scalelite with moodle but today I'm keep getting this error 
"We could'nt find a meeting with that ID - perhaps the meeting is not yet running?"
last thing i've done is enabling "persistence" on the Redis server.
https://prnt.sc/rz47db

**Comment by wmchris** [comment]
i can confirm a problem like this. when removing servers this issue can get really problematic, as the scalelite will throw error 500. only solution so far: delete redis and repopulate servers...

we need a cleanup routine for the redis.

**Comment by farhatahmad** [comment]
Did you delete a server without panicking it first? That will leave Redis in an inconsistent state which could cause this error
