### ISSUE TITLE
Multiple post-processing

### ISSUE THREAD

**Issue by penguennoktanet** [blindsidenetworks/scalelite#158]
Hi there,

    I am using Scalelite and multiple BBB servers. My BBB servers are working "very hard" in day time (3-4 meetings in parallel, all recorded, some times more than a hundred per day), "idle" on night time.

    But hence the postprocess script runs videos one-by-one, it can not keep up with the video processing. (Even updating the ffmpeg's thead and speed parameter settings)

    Maybe, in next versions some kind of "idle time slots" and "parallel post-processing" can be implemented to BBB (for an example, between 1:00 am and 8 am, 4 post-process script can be run simultaniously). Of course this will require some "syncronization" between scripts.

    Thanks..

**Comment by rabser** [comment]
But here are listed the issues about scalelite, not BBB: this is the wrong place for your thought, i believe.

**Comment by penguennoktanet** [comment]
You absolutely right. My bad.. :(
