### ISSUE TITLE
Servers disappears from the Scalelite server

### ISSUE THREAD

**Issue by apexstudiosga** [blindsidenetworks/scalelite#159]
I'm getting problem with Redis persistence I think as I need to add the servers manually every couple of hours and even with Redis persistence is enabled I'm still having my servers to disappear.

I've double checked all the settings and checked the persistence is enabled as below.

```
root@ip-xx-xx-xx-xx:/home/ubuntu# redis-cli CONFIG GET save
1) "save"
2) "900 1 300 10 60 10000"
root@ip-xx-xx-xx-xx:/home/ubuntu# redis-cli CONFIG GET appendonly
1) "appendonly"
2) "yes"
```

**Comment by ngthienlinh** [comment]
Your redis server may be hacked if you public the default port 6379 and didn't set password. If this is the case, you should change the port or set a password for redis server.

**Comment by farhatahmad** [comment]
You'd need to look into your Redis server. The only reason for them to disappear would be if someone deleted them, or if persistence isn't enabled (or applied)
