### ISSUE TITLE
Records is not visible in Moodle

### ISSUE THREAD

**Issue by apexstudiosga** [blindsidenetworks/scalelite#160]
I had only one bbb server but I've migrated to Scalelite and it's working now so I moved old recordings from old bbb server "/var/bigbluebutton/published/" directory to "/mnt/scalelite-recordings/var/bigbluebutton/published/" as well as "unpublished" but I didn't know where to move "recording/raw" folder till now however none of the recordings is visible inside moodle and I've restarted the server also tried to run "./bin/rake recordings:update" from docker but got this error "D, [2020-04-15T07:30:29.740020 #749] DEBUG -- :   Recording Load (0.2ms)  SELECT "recordings".* FROM "recordings" WHERE "recordings"."published" = $1  [["published", false]]".

So am I missing something?

**Comment by SebastianZiegler** [comment]
i think you habe to use the import script 
https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#configuring-the-bigbluebutton-recording-transfer

**Comment by farhatahmad** [comment]
Yeah the recordings need to be imported into Scalelite's database. The link sent above has the correct steps
