### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by wagnerfelix** [blindsidenetworks/scalelite#161]
I would like to use scalelite without a letscrypt cert. 

So I created a /etc/default/scalelite configuration:

```
URL_HOST=example.de
SECRET_KEY_BASE=BLA
LOADBALANCER_SECRET=BLEM
DATABASE_URL=irrelevant
REDIS_URL=running on localhost
SCALELITE_TAG=v1
SCALELITE_RECORDING_DIR=/mnt/bbb-recordings/var/bigbluebutton
RECORDING_SPOOL_DIR=/mnt/bbb-recordings/var/bigbluebutton/spool
RECORDING_WORK_DIR=/mnt/bbb-recordings/var/bigbluebutton/recording/scalelite
RECORDING_PUBLISH_DIR=/mnt/bbb-recordings/var/bigbluebutton/published
RECORDING_UNPUBLISH_DIR=/mnt/bbb-recordings/var/bigbluebutton/unpublished
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS="--mount type=bind,source=/etc/ssl/example.de/,target=/etc/nginx/ssl,readonly"

```
I have a valid certificate (/etc/ssl/example.de/live/example.de/fullchain.pem) and private key (/etc/ssl/example.de/live/example.de/privkey.pem). If I start the scalelite.target and check the scalelite-nginx service I get a certificate error.

```
2020/04/15 09:51:45 [emerg] 7#7: cannot load certificate "/etc/nginx/ssl/live/example.de/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/live/example.de/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/live/example.de/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/live/example/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
The Certificates are "chmod 600" for key and "chmod 644" for the public cert. Owner for both is root.

Any help is much appreciated!

**Comment by SebastianZiegler** [comment]
the target in SCALELITE_NGINX_EXTRA_OPTS should be something like this:
=/etc/nginx/ssl/live/<your dns name> that the name of URL_HOST

Had the same issue during install

**Comment by wagnerfelix** [comment]
Hi, thanks to a colleague that helped me I got it to work. The bind mount directory structure that i had was wrong.

In the scalelite defaults:

```
URL_HOST=example.de
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS="--mount type=bind,source=/etc/ssl,target=/etc/nginx/ssl,readonly"
```

Then in `/etc/ssl/` create a directory `live` so `/etc/ssl/live`. In the live directory there
needs to be a directory with the `URL_HOST` so in this case `/etc/ssl/live/example.de`.
In that directory there should be your public key with all intermediate certificates (fullchain.pem) and your private key (privkey.pem).

Another important issue ist that in the fullchain.pem the first certificate is the public key followed by the intermediate certificates else you get an error.

**Comment by cod3r0k** [comment]
Hi, 

> Hi, thanks to a colleague that helped me I got it to work. The bind mount directory structure that i had was wrong.
> 
> In the scalelite defaults:
> 
> ```
> URL_HOST=example.de
> NGINX_SSL=true
> SCALELITE_NGINX_EXTRA_OPTS="--mount type=bind,source=/etc/ssl,target=/etc/nginx/ssl,readonly"
> ```
> 
> Then in `/etc/ssl/` create a directory `live` so `/etc/ssl/live`. In the live directory there
> needs to be a directory with the `URL_HOST` so in this case `/etc/ssl/live/example.de`.
> In that directory there should be your public key with all intermediate certificates (fullchain.pem) and your private key (privkey.pem).
> 
> Another important issue ist that in the fullchain.pem the first certificate is the public key followed by the intermediate certificates else you get an error.

Hi, You mean that we must create a certificate by ourself and the `https://github.com/blindsidenetworks/scalelite/blob/ba89f22b6050b80499311c730da261eed97ff1fb/docker-README.md#web-frontend-scalelite-api-and-scalelite-nginx` guideline is not create it?

**Comment by cod3r0k** [comment]
Scalelite code not automatically create a SLL? Could you help me? @wagnerfelix @SebastianZiegler @kepstin @ritzalam

**Comment by wagnefel** [comment]
As far as I know (and I am not a blindside developer) rather than like the standard BBB-Install where you can choose to either have a certificate using letsencrypt (automatically) or create one yourself, scalelite only has the option to use certificates that one creates yourself (either also using letsencrypt or another service).
