### ISSUE TITLE
Rake status totals

### ISSUE THREAD

**Issue by agustinmono** [blindsidenetworks/scalelite#162]
Would be great to have totals in the last row of 
` ./bin/rake status`

http://prntscr.com/s0ogy8

**Comment by ntatgss** [comment]
That should be better than summing. Another quick question: did you deploy each bbb server and customize them one by one, for the total 8 servers you have that will be very crazy!

**Comment by agustinmono** [comment]
I just create 
1 scalelite
1 greenligh
1 solo BBB

and then clone the greenlights and change the IPS and DNS

**Comment by Francisco-veka** [comment]
> Acabo de crear
> 1 scalelite
> 1 greenligh
> 1 solo BBB
> 
> y luego clonar (toda la VM) las luces verdes y cambiar el IPS y DNS

por favor exite una guia paso a paso de como implementar un servidor scalelite, podrias ayudarme por favor
