### ISSUE TITLE
Please include BBB server name in meetings info

### ISSUE THREAD

**Issue by euneuber** [blindsidenetworks/scalelite#166]
I'd like to know which meeting is on which BBB server.
Please add an server name/uri field into the metadata.

**Comment by bwurst** [comment]
Did anyone have had a look at this?
Would scalelite be the right place to att it or should the getMeetings call of BBB always include a server name when called directly?

When I get complaints about any BBB issues, I have to find out on which server the given meeting is to see if that server has trouble. 
I do this by manually asking all servers via API one after another and get the meetings. It would be much better if one API call to scalelite would give me the information which server I have to look at.

**Comment by amalrails** [comment]
The SL version 1.3, will include rake tasks where the meeting/meetings can be searched.
