### ISSUE TITLE
Removing Server results in error 500 on the API

### ISSUE THREAD

**Issue by wmchris** [blindsidenetworks/scalelite#167]
When removing a server the whole cluster can be affected. Even when there was noone using the server at time of removal, there are still remnants of past rooms in the redis. 

Effect:
a lot of rooms get the error of a wrong api key. Only solution so far: delete redis and start from scratch...

**Comment by farhatahmad** [comment]
From the docs:
> Warning: Do not remove a server which has running meetings! This will leave the database in an inconsistent state. You should either wait for all meetings to end, or run the "Panic" function first.

If you are going to delete a server, make sure you panic it first

**Comment by wmchris** [comment]
this also happens when there are no meetings active... thats why i opened this ticket.
