### ISSUE TITLE
How to set a custom landing page for scalelite server

### ISSUE THREAD

**Issue by xscharlie** [blindsidenetworks/scalelite#169]
Hello, 
I want to customize the landing page for scalelite server, currently appears something like this: 
![image](https://user-images.githubusercontent.com/4460285/80039851-06219580-84b6-11ea-8cf7-00252f365690.png)

The scalelite-nginx docker image, is setting up to forward root to scalelite-api service:

```
location/ {
        proxy_pass http://scalelite-api:3000;

        proxy_read_timeout 60s;
        proxy_redirect off;

        proxy_set_header  Host $http_host;

        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
}
```
So, how can I setup a custom web page in root route ( / )?

Thanks in advance!

**Comment by SebastianZiegler** [comment]
u can build your own own site using the bigbluebutton api or you can use greenlight for example

**Comment by farhatahmad** [comment]
Scalelite itself is an api, so you'd be better off building your own front-end and redirecting "/" to that front-end
