### ISSUE TITLE
Scalelite cannot serve recording files in HTTPS behind LB with SSL termination

### ISSUE THREAD

**Issue by RomainNakedCat** [blindsidenetworks/scalelite#170]
Hello,

I have a BBB architecture using Greenlight as front for end users. If a user wants to create a room he connects to greenlight through an HTTPS LB. The LB does the SSL termination then contacts greenlight in HTTP.

When Greenlight wants to contact Scalelite,  it goes through an HTTPS LB then LB contacts Scalelite in HTTP. 

Everythings work fine except when an user wants to get a record file. if NGINX_SSL is not set inside scalelite-nginx, Greenlight will receive HTTP link. It works when it clicks on "presentation button" LB will redirect HTTP request to HTTPS request but the thumbnail will raise an SSL Warning inside the web browser.

You should consider to evaluate X-Forwarded-Proto header instead of check if the container received the requested over HTTP or HTTPS.

**Comment by farhatahmad** [comment]
Hi @RomainNakedCat 

This should be fixed by #139
