### ISSUE TITLE
Webhook over scalelite

### ISSUE THREAD

**Issue by ilcapitino** [blindsidenetworks/scalelite#171]
How to use webhook over scalelite

**Comment by farhatahmad** [comment]
Scalelite itself doesn't support webhooks. You'll need to make the webhook calls directly on each individual BigBlueButton server

**Comment by dariob** [comment]
would be a great feature!

**Comment by dariob** [comment]
or at least would be useful if create room api response contains the bbb server that host the room, so we can call webhooks on the right server
