### ISSUE TITLE
Check the status fail when 1 of the servers down

### ISSUE THREAD

**Issue by longlnk** [blindsidenetworks/scalelite#176]
Hello,

Check the status of the entire deployment when 1 of the servers failed

Example, I have 5 server meeting, from meeting1 to meeting5

![image](https://user-images.githubusercontent.com/15074179/80299374-0e334b00-87be-11ea-88ad-29fe5fc05f12.png)

Meeting1 down, check the status will fail
![image](https://user-images.githubusercontent.com/15074179/80299403-49ce1500-87be-11ea-9d5a-673b3ebea4be.png)

Is there any way that it still displays information without removing meeting1?
Please help me

**Comment by farhatahmad** [comment]
Hi @longlnk,

This was fixed in v1.0.1. Can you update and see if this issue still happens?
