### ISSUE TITLE
Scalelite do not transfer to another meeting server when a meeting server is having a meeting failure

### ISSUE THREAD

**Issue by longlnk** [blindsidenetworks/scalelite#177]
Hello,

- I have 5 meeting server and meeting1 server is meeting with named is t3
- Scalelite server Frontend is Greenlight 
![image](https://user-images.githubusercontent.com/15074179/80299603-e3e28d00-87bf-11ea-9b20-cd74973122d7.png)
![image](https://user-images.githubusercontent.com/15074179/80299620-02488880-87c0-11ea-8f2d-0813098540bd.png)

After I stop meeting1 server, I go to the t3 meeting from Scalelite and Error message as shown
![image](https://user-images.githubusercontent.com/15074179/80299646-36bc4480-87c0-11ea-9b39-ad78141abc65.png)

Please help me

**Comment by farhatahmad** [comment]
Did you disable the server while t3 was still running? If so, you need to make sure you panic a server first before you disable it
