### ISSUE TITLE
Scalelite do not apply PORT environmet variable from config!

### ISSUE THREAD

**Issue by alxvll** [blindsidenetworks/scalelite#178]
I try change port for sclelite-api in config /etc/default/scalelite and
restart target: systemctl restart scalelite.target but new port is no applied.

**# docker ps | grep scalelite-api**
1c5dbe35a568 blindsidenetwks/scalelite:v1-api "bin/start" 6 minutes ago Up 6 minutes                    3000/tcp scalelite-api

**Config is simple: /etc/default/scalelite**
URL_HOST=myweb.name
SECRET_KEY_BASE=641f393cfcd0cf0f273fcd4f5f0abbc0ba7cfd81c7bf9323abf88
LOADBALANCER_SECRET=9f4d49617d4fd2eba68ddb41ce74b7504e313fb28acd8d476
DATABASE_URL=postgresql://scalelite:password@127.0.0.1:5433
REDIS_URL=redis://127.0.0.1:6379
SCALELITE_TAG=v1
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
PORT=9292

**Systemd service scalelite-api started properly:**
 systemctl status scalelite-api
● scalelite-api.service - Scalelite API
   Loaded: loaded (/etc/systemd/system/scalelite-api.service; enabled; vendor preset: enabled)
   Active: active (running) since Вс 2020-04-26 18:54:14 CEST; 4s ago
  Process: 22700 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-api (code=exited, status=0/SUCCESS)
  Process: 22679 ExecStartPre=/usr/bin/docker rm scalelite-api (code=exited, status=0/SUCCESS)
  Process: 22654 ExecStartPre=/usr/bin/docker kill scalelite-api (code=exited, status=1/FAILURE)
 Main PID: 22726 (docker)
    Tasks: 11
   Memory: 28.4M
      CPU: 144ms
   CGroup: /system.slice/scalelite-api.service
           └─22726 /usr/bin/docker run --name scalelite-api --env-file /etc/default/scalelite --network scalelite --mount type=bind

docker[22700]: Digest: sha256:7d4e472711c8f10b884facc9eeb13f544cc29b467d83926a542f8ab7a08a9dfe
docker[22700]: Status: Image is up to date for blindsidenetwks/scalelite:v1-api
docker[22700]: docker.io/blindsidenetwks/scalelite:v1-api
systemd[1]: Started Scalelite API.
docker[22726]: Puma starting in single mode...
docker[22726]: * Version 4.3.3 (ruby 2.6.6-p146), codename: Mysterious Traveller
docker[22726]: * Min threads: 5, max threads: 5
docker[22726]: * Environment: production
docker[22726]: * Listening on tcp://0.0.0.0:9292
docker[22726]: Use Ctrl-C to stop

I try to use BIND instead of PORT:
`BIND=tcp://0.0.0.0:9292`
I have same result!

Please tell me how i can set different port for api?

**Comment by farhatahmad** [comment]
Hi @alxvll 

Thanks for reporting this.

> docker[22726]: * Listening on tcp://0.0.0.0:9292

So it looks like the Rails application is listening on the right port. The only issue is that nginx seems to be hardcoded to 3000 (https://github.com/blindsidenetworks/scalelite/blob/master/nginx/conf.d/scalelite.common#L2).

That'll need to be fixed and point at the PORT env variable instead.
