### ISSUE TITLE
Panicking a server fails because of missing moderator password.

### ISSUE THREAD

**Issue by defnull** [blindsidenetworks/scalelite#179]
BBBs `end` API requires the moderator password, which the `panic` rake task does not provide. The meetings are removed from redis, but not actually ended.

https://github.com/blindsidenetworks/scalelite/blob/76105c117c051334277578799c098dfe1313cac4/lib/tasks/servers.rake#L67

This results in inconsistent state: Scalelite does not know about the meeting, will deny that it exists if asked directly (via `getMeetingInfo` or `isMeetingRunning`) but still includes it in a `getMeetings` call.

**Comment by farhatahmad** [comment]
This was supposed to be fixed on the BigBlueButton side. If they don't change it, Scalelite will need to start storing moderatorPasswords that are passed on create

**Comment by kepstin** [comment]
I guess we're not gonna get this fixed in the upstream BBB any time soon, so we're gonna have to start storing the moderator passwords.
