### ISSUE TITLE
URL issues ???

### ISSUE THREAD

**Issue by amassaro** [blindsidenetworks/scalelite#180]
I am still having either a scalelite (config??) issue or I am not sure where it breaks down. If I put either of my BBB servers into greenlight they work correctly by themselves. But once I switch the url to the scalelite one I am getting an error. I have set all the URLs multiple times, double and triple checked the secrets. In fact they are all set the same from greenlight to scalelite to each BBB server.

![image](https://user-images.githubusercontent.com/1584313/80526450-9a24ae80-8947-11ea-8223-bd68e2c41c52.png)

Here is my scalelite server list
```
~ $ ./bin/rake servers
id: 2f4f4283-67ce-496a-a459-180084f7ffd4
        url: https://bbb2.mybbbserver.com/bigbluebutton/api
        secret: XXXXXXXXX
        enabled
        load: 0.0
        online
id: f1be8152-9806-45fb-aa7b-3a68ebdf5e45
        url: https://bbb1.mybbbserver.com/bigbluebutton/api
        secret: XXXXXXXXX
        enabled
        load: 0.0
        online
```
I have tried both `https://scalelite.mybbbserver.com/bigbluebutton/` and `https://scalelite.mybbbserver.com/bigbluebutton/api/` into .env file in greenlight but I keep getting the following error
```
ERROR: [bd046570-e52e-4361-8d9a-d28654f40f7e] BigBlueButtonException: Invalid response body. Is the API URL correct? "https://scalelite.mybbbserver.com/bigbluebutton/api", version 0.8
```

Also my scalelite endpoint appears to respond properly?
https://scalelite.mybbbserver.com/bigbluebutton/api
```
<response>
  <returncode>SUCCESS</returncode>
  <version>2.0</version>
  <build>v1.0.1</build>
</response>
```

Any ideas???

**Comment by amassaro** [comment]
This issue seems to be related to me disabling and removing a server without panicking. Which led to redis still having some data stored that was causing issue. I ended up having to flush the entire redis cache and re-add/enable all servers and scalelite started working properly again. It seems as if we need some sort of management api to resolve this problem in a more elegant manner.

**Comment by pbdco** [comment]
Been there, done that! Thanks bro! @amassaro 

Solved with:
`docker exec -it container-name redis-cli FLUSHALL`

In my case:
`docker exec -it redis redis-cli FLUSHALL`

_And remember always panic before removing a server!_

**Comment by laserrapt0r** [comment]
Ouch. I had one single user with the error message and couldnt explain why. BBB < 2.3.1 had the bug that inactive users where not disconnected. I've restarted und updated a server on Friday with a session that was existing for 3 days. I guess this caused the issue.
