### ISSUE TITLE
API to manage servers

### ISSUE THREAD

**Issue by rriscado** [blindsidenetworks/scalelite#181]
Can we manage scalelite by API?
It's good for Add, Remove, Enable, Disable and Panc a Server with automations.

**Comment by amassaro** [comment]
+1

**Comment by congthang1** [comment]
API quite simple we just need to install a simple server (like Nodejs) to run list server commands and send responses. Hope this will be integrated soon.

**Comment by farhatahmad** [comment]
Released in 1.5.1
