### ISSUE TITLE
scalelite_batch_import.sh only imports published recordings

### ISSUE THREAD

**Issue by odenbach** [blindsidenetworks/scalelite#182]
Hi,

I just moved from a single BBB server to our new cluster. When migrating the existing recordings with the script `scalelite_batch_import.sh` I noticed that only published recordings were transferred to the cluster. All unlisted recordings are now invisible for the users.

How can I also transfer those recordings? Users might want to switch them to published later.

Thanks for this awesome project,

Christopher

**Comment by farhatahmad** [comment]
HI @odenbach,

Thanks for reporting this. Yes you are correct. It currently only imports published recordings. We'll need to extend it to check for unpublished recordings as well

**Comment by jfederico** [comment]
@odenbach @amalrails I have the impression that this was already fixed, wasn't?

**Comment by farhatahmad** [comment]
fixed here https://github.com/blindsidenetworks/scalelite/pull/614
