### ISSUE TITLE
Unable to access server

### ISSUE THREAD

**Issue by rriscado** [blindsidenetworks/scalelite#183]
When 1 server is down, the API call return the folow error, until the server status change to Offline by poll process.

`
<response>
<returncode>FAILED</returncode>
<messageKey>internalError</messageKey>
<message>Unable to access server.</message>
</response>
`

**Comment by farhatahmad** [comment]
Did you update to v1.0.1? I believe this may have been fixed

**Comment by rriscado** [comment]
> Did you update to v1.0.1? I believe this may have been fixed

Yes!

This return code is on getMeetings API Call
