### ISSUE TITLE
Docker multi-stage build command?

### ISSUE THREAD

**Issue by lightweight** [blindsidenetworks/scalelite#184]
I've created a fork of the Scalelite project with the aim of creating a set of Scalelite containers (slightly modifying the multi-stage Dockerfile included in the project) that make it easier to set up recording management by rationalising the UID for the bigbluebutton users on the containers... I'm able to build the containers using, for example, `docker build -t oeru/scalelite .`  in my fork of the codebase... but I cannot work out how you've tagged your stages to allow the images to be referenced (in my case, from within a docker-compose.yml config) via, for example, `blindsidenetwks/scalelite:v1-nginx` or `blindsidenetwks/scalelite:master-recordings-importer`. 

I've had a few attempts at tagging the image I've created but I clearly don't "get" the way I'm supposed to do it to allow the different stages to be designated as images in a docker-compose.yml... Always getting "manifest unknown" errors, so I'm clearly doing something wrong. 

If you're able to provide an example of the build command you're using to create the multi-stage image, I'd be grateful!

**Comment by farhatahmad** [comment]
We build the separate images using Gitlab. You can see the exact commands we run here: https://github.com/blindsidenetworks/scalelite/blob/master/.gitlab-ci.yml#L59

If you look through the next 5 or 6 docker build commands, you'll see each individual component being built

**Comment by lightweight** [comment]
Many thanks. Trying it now.

**Comment by anmol1991** [comment]
How to build separate scalelite images using gitlab-ci.yml  ??

**Comment by matiasilva** [comment]
Scroll up :)

**Comment by lightweight** [comment]
For what it's worth, wrote this little script to speed things up: 

```
#!/bin/bash

# Build these containers...

ORG=oeru
BASE=scalelite
TARGETS="build api poller recording-importer bbb-playback nginx"
DB="docker build"
DP="docker push"
echo "create containers"

for TARGET in $TARGETS 
do
    echo
    echo "************ start $TARGET *************"
    echo "Building docker container $ORG/$BASE-$TARGET"
    $DB --target $TARGET --tag $ORG/$BASE-$TARGET .
    echo "Pushing $ORG/$BASE-$TARGET to Docker Hub"
    $DP $ORG/$BASE-$TARGET
    echo "************ $TARGET done *************"
done
```

**Comment by anmol1991** [comment]
Thanks a lot !
