### ISSUE TITLE
Webhook for Scalelite?

### ISSUE THREAD

**Issue by ntatgss** [blindsidenetworks/scalelite#187]
I implemented webhook on BBB servers to call StartSession from my frontend. Everything works fine but when I started replacing the BBB servers with the Scalelite Server, the error happened:

> getJoinUrl, error:Create hook error

How should I manage this?

**Comment by dariob** [comment]
+1

**Comment by farhatahmad** [comment]
Webhooks are a little bit outside the scope of Scalelite. Scalelite was meant as a way to run BigBlueButton servers at scale. As a result there are components that are present in BigBlueButton that may not be present in Scalelite.
