### ISSUE TITLE
Add access realms

### ISSUE THREAD

**Issue by TheJJ** [blindsidenetworks/scalelite#196]
A BBB-Cluster balanced by scalelite can be used by multiple clients (greenlight, moodle, mattermost, ...), but they all have the same visibility of the rooms/recordings/... as they have all full access through the token.

Instead, the access should be **divided into realms**, where each realm is separated from the others, and has separate access tokens.

That way, the balancing happens globally for the backend meeting servers, but the frontends can't see the data of the others.

The implementation is probably quite easy: Each created room is assigned a realm, and thus only visible there (same for its recordings, ...).

**Comment by farhatahmad** [comment]
I'm not quite sure this is in the scope of Scalelite. The same way a BigBlueButton server doesn't have "realms", I don't think Scalelite should either. 

Each front-end is responsible for showing its own meetings and recordings

**Comment by TheJJ** [comment]
The use-case would be this: You have a BBB-node cluster with a scalelite as gateway. Access to this cluster is now performed from various frontends of different owners, a university chair's mattermost instance, the university-global moodle instance, a department-wide greenlight instance, ...

All those frontends are from different operators, but the BBB-cluster is provided for all of them. The chair should not see or access meetings from the university-global moodle, for example.

To cover this use-case, this "realms" approach is an extension of #115 but with assigning a meeting to a secret.
