### ISSUE TITLE
BBB Instance Structure

### ISSUE THREAD

**Issue by haeferer** [blindsidenetworks/scalelite#199]
Hi, 

Very nice work. Exactly whats needed in corona times. 

We try to build the same for our school (800) on an existing Planning system (not Moodle). 
But we got into problems, may someone can gave me a hint.

If we are creating a Meeting on a BBB Instance, and build a JOIN Link, the join link cant be used (returns a 401 on the BBB instance, for session not found).

It seems in our installation the BBB instance needs an additional session-cookie (beside the API connection) which seems to be managed by greenlight

I have looked in your systeme picture. The only connection between ManagementServer and BBB Server is the API Connection. There seems to be no COOKIE-Sharing via the ClientBrowser, the moodle and the BBB instance.

But it seems this cookie sharing is needed to Join a Meeting in our installation

Would be nice if someone can gave us a hint

Thx

Andreas

**Comment by IamLuksha** [comment]
Hey.

We also somehow tried to create a meeting on the BBB, and then make a connection through ScaleLite. But that will not work.
ScaleLite stores the created rooms in redis. When join, it checks in redis, if not, then an error. But through getMeetings ScaleLite sees the created meeting on the BBB itself

**Comment by haeferer** [comment]
> Hey.
> 
> 
> 
> We also somehow tried to create a meeting on the BBB, and then make a connection through ScaleLite. But that will not work.
> 
> ScaleLite stores the created rooms in redis. When join, it checks in redis, if not, then an error. But through getMeetings ScaleLite sees the created meeting on the BBB itself

Do you know what the problem is? 

There seems to be a cookie based session needed between greenlight and the BBB instance. 

If i look at the system picture here there is no connection between Moodle and the BBB .

I create a meeting and a join link using the api, but the link means - no session found - . 

The same error can be produced if you create and join a meeting over greenlight and remove the greenlight cookie 

So there seems to be some session sharing between greenlight and bbb, so you can’t
Join without going through greenlight ???


Thx for your help

Andreas

**Comment by IamLuksha** [comment]
Is greenlight set to scalelite?
Or didn’t you configure it?

Server interaction diagram:
<img width="441" alt="Screen Shot 2020-05-09 at 20 29 58" src="https://user-images.githubusercontent.com/18416207/81480684-de5f5b00-9233-11ea-882f-a91c46765d61.png">

**Comment by haeferer** [comment]
No, I have a BBB installation, including greenlight, and try to automate the BBB behind greenlight.

Maybe it’s simple some kind of security (maybe implemented in the NGINX) to block join links not coming from a greenlight client. This would be plausible, cause there is no “onetime” join link in BBB, an if you share your link with someone else he can also join as you .... (security hole)

Maybe this is my problem....

**Comment by haeferer** [comment]
We try to bind different BBB installations from different companys together, so they can be used by schools (for free, using only some resources), without building an paying a Large Single Cluster

**Comment by haeferer** [comment]
I will look if this security is build into the NGINX (seems to be the simplest way). Maybe we can change this implementation to ONETIME Join links

**Comment by IamLuksha** [comment]
You need to configure greenlight to work with scalelite.
In the greenlight settings, enter secretkey scalelite.
There is now setting up a local server BBB

**Comment by haeferer** [comment]
Solved. BBB needs a shared JSession. This behavior can be changed (since BBB 2.2) by changing allowJoinWithoutSession in bigbluebutton.properties
