### ISSUE TITLE
Need possibility to set and overwrite parameters in create api call

### ISSUE THREAD

**Issue by christmart** [blindsidenetworks/scalelite#204]
We need a possibility to force e.g. to disable recordings in create api calls where we can't configure this in frontends like greenlight, mattermost etc.

In bigbluebutton_api_controller.rb:157 there is a line where MAX_MEETING_DURATION is set and in line 366 some params are filtered. Is this the place where more options could be implemented?

I would like to set 

record
autoStartRecording
allowStartStopRecording

I am not familiar with ruby, so I need some help here for a quick hack in the code.
In the long run a configurable solution via .env would be great.

Any hints?

**Comment by farhatahmad** [comment]
You can actually just do it exactly as `MAX_MEETING_DURATION` does it. `MAX_MEETING_DURATION` has 1 extra step where it only sets it if the passed duration value is higher than the max which you can ignore
