### ISSUE TITLE
Use Threads to connect in BBB Servers

### ISSUE THREAD

**Issue by rriscado** [blindsidenetworks/scalelite#207]
Hello, 

Whenever scalelite need to connect to BBB servers, does it sequentially.
For example for "status" and "poll:all" events.

If I have a very large list of servers, and each of these servers has many rooms, this time can be very high.

If there are offline servers in the list, for each of these servers, the default TIMEOUT=10 seconds will be waited before connecting to the next server in the list.

The idea is to connect in parallel on all servers by threads, optimizing the time to obtain BBB information when there is a large number of servers.

I opened Pull Request https://github.com/blindsidenetworks/scalelite/pull/201 to create this thread connection for the command "status" but Travis CI indicates problems in lines that are not part of my commit.

Since I don't have a lot of knowledge in Ruby, I preferred not to do others Pull Requests.

Can you apply this concept for connections to All BBB Servers?

**Comment by ryprfpryr** [comment]
+1

**Comment by ffdixon** [comment]
> If I have a very large list of servers, and each of these servers has many rooms, this time can be very high.

Can you define 'very large'?  What numbers do you need to support?

**Comment by lonesomewalker** [comment]
This has so many other reasons why this should be done.

Non-responding servers because under load:
- heavy used (running ~1k users gives the API some delay)
- DDoS (we have some customers which experience these issues...)
- processing of recordings (depends on modifications, but we already had some servers)

**Comment by amalrails** [comment]
closed with #428
