### ISSUE TITLE
Scalelite load balancer functionality works, but it doesn't show meetings record list on servers

### ISSUE THREAD

**Issue by MrCapitalist** [blindsidenetworks/scalelite#208]
Hi :((
I'm confused about installation documents of Scalelite. These steps are very very confusing and I can't understand what shoud I do :/ Please help me. I've been trying for about a week.
How can I use Scalelite completely? I could install scalelite incompletely and it works only as Load Balancer but I can't use meeting record functionality

In [Before you begin](https://github.com/blindsidenetworks/scalelite#before-you-begin) I know about all options exept "How docker containers work"!

I setted up 2 BBB server that can run seperatly (without scalelite) very well
Then I install scalelite by using [this instruction](https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6), added my BBB servers to it and used scalelite load balancer functionality with its help. That site explains much better than scalelite documentation but it's not complete because there isn't any instruction for transfer and save meetings records to NFS volume.

I even setup NFS server on scalelite server and mount it in BBB server without any problem but I can't continue. Understanding other section in very difficult for me :(((

After setup NFS, when I want to do [it](https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#configuring-the-bigbluebutton-recording-transfer), I can't [install .rb or .yml](https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/README.md#installation) file on my BBB server. I search about install rb and found I must [install Ruby](https://linuxhint.com/install_ruby_ubuntu/), but when I want to run `ruby scalelite_post_publish.rb` I get this message:
`/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
scalelite_post_publish.rb:30:in `<main>': Meeting ID was not provided (RuntimeError)
`

For install scalelite.yml I fount that I must [install Docker Compose](https://stackoverflow.com/questions/44364916/how-to-open-run-yml-compose-file) and Docker Engine, then rename scalelite.yml to docker-compose.yml. But after install them and run `docker-compose up` I get this error:

`ERROR: In file './docker-compose.yml', service 'work_dir' must be a mapping not a string.
`

Now how can I install scalelite?! Is there any simple documentaion for it?

**Comment by MrCapitalist** [comment]
Hi again
I can't install `scalelite_post_publish.rb` and `scalelite.yml` on my BBB server yet.

https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/README.md#installation

How can I pass this level?

**Comment by alkanis** [comment]
Hi, you just have to copy the files on the BBB. 
Make sure scalelite_post_publish.rb is executable, and scalelite.yml is readable. 
The folders's permission setup in scalelite.yml needs to be bigbluetbutton:bigbluebutton

**Comment by MrCapitalist** [comment]
Thanks a lot. I continued installation steps, installed nginx, installed SSL by using Let's Encrypt Cerbot, config `/etc/default/scalelite`, but have another problem. 

I found this [instruction PDF](https://events.ubuntunet.net/event/29/attachments/201/246/Installing_and_Scaling_BBB.pdf) about scalelite and installed PostgreSQL by using this command:

`sudo apt-get install postgresql postgresql-contrib`

Now, how can I setup database? I don't know what do I should enter for `DATABASE_URL`

When I use `DATABASE_URL=postgresql://IPofScalelite:5432`, in [Initialize the scalelite-api Database](https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md#initialize-the-scalelite-api-database) after enter this:
`docker exec -it scalelite-api bin/rake db:setup`

I get this message:

`could not connect to server: Operation timed out
        Is the server running on host "MY_HOST_IP" and accepting
        TCP/IP connections on port 5432?
Couldn't create 'scalelite' database. Please check your configuration.
rake aborted!
PG::ConnectionBad: could not connect to server: Operation timed out
        Is the server running on host "MY_HOST_IP" and accepting
        TCP/IP connections on port 5432?
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/pg-1.2.2/lib/pg.rb:58:in `initialize'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/pg-1.2.2/lib/pg.rb:58:in `new'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/pg-1.2.2/lib/pg.rb:58:in `connect'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:889:in `new_connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `checkout_new_connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:912:in `try_to_checkout_new_connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:873:in `acquire_connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:595:in `checkout'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:439:in `connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1121:in `retrieve_connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:238:in `retrieve_connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:206:in `connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:126:in `create'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:476:in `each'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:475:in `each'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create
(See full trace by running task with --trace)
`

My settings in `/ect/default/scalelite` are:

`URL_HOST=MY_HOST_NAME
SECRET_KEY_BASE=MY_SECRET_KEY_BASE
LOADBALANCER_SECRET=MY_SECREY_KEY
DATABASE_URL=postgresql://MY_HOST_IP:5432
REDIS_URL=redis://redis:6379
SCALELITE_TAG=v1
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly`

**Comment by MrCapitalist** [comment]
Can anybody help me?! Is there any tutorial video? Text? How can I continue my installation?

**Comment by schoasch10** [comment]
you can use this guide:
https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6

i got stuck in the beginning too - this guide made it very easy for me

**Comment by MrCapitalist** [comment]
> you can use this guide:
> https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6
> 
> i got stuck in the beginning too - this guide made it very easy for me

Thank you for your suggestion but I told in first message I found it and I could setup scalelite by using it, but on that status, I couldn't use meeting record functionality and I can only use load balancer functionality because in this way we don't setup any database or radis to keep or transfer any records in every BBB  server.

**Comment by schoasch10** [comment]
Use the script and it will do everything for you and then you can also use recordings too

**Comment by MrCapitalist** [comment]
Witch script?

**Comment by MrCapitalist** [comment]
Do you mean that if I do all the steps mentioned above, there is no need to set any other options?

**Comment by schoasch10** [comment]
this guide:
https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6
it´s very automatic - you just need to setup shared volume for recordings and you are good to go

**Comment by MrCapitalist** [comment]
Thank you. I'm doing it again.. But when I create an LVM partition and setup a NFS server on it in `/mnt/scalelite-recordings` mount point (for example), how can I set it as scalelite redordings spool? I don't see any option for NFS in this tutorial

**Comment by MrCapitalist** [comment]
Hi @schoasch10 
Thank you again. I installed scalelite again according to mentioned instructions and it works well as in the past. I use wordpress to show my recorded sessions, when I set server1 address and secret code in wordpress admin panel, records list shows in frontend, but when I enter scalelite address and secret in wordpress admin panel, it doesn't show any record.
This is my problem with scalelite. How setup scalelite to get records list of every server that session was recorded on it?

**Comment by farhatahmad** [comment]
You have to move your recordings from your BigBlueButton server to your Scalelite server.

https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#configuring-the-bigbluebutton-recording-transfer 

The link above has the steps you need to do that

**Comment by schoasch10** [comment]
also you better setup up a shared recording path like in this guide

https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md

**Comment by MrCapitalist** [comment]
@farhatahmad @schoasch10 
Thanks a lot. I set up both of instrauctions that you give me before except [this step](https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/README.md#transfer-using-rsync-over-ssh). But I set up NFS. Do I need to setup "Transfer using rsync over SSH" too?

I found some topics and some useful posts like [this](https://github.com/blindsidenetworks/scalelite/issues/90#issue-586086357), [this](https://github.com/blindsidenetworks/scalelite/issues/129#issuecomment-612160218),[this](https://github.com/blindsidenetworks/scalelite/issues/129#issuecomment-612101115), [this](https://github.com/blindsidenetworks/scalelite/issues/129#issuecomment-612160218) and made mentioned changes.
But now I have two problem:

1- When I record a session, it doesn't show on frontend untill I manually run `scalelite_batch_import.sh` from this path: `/usr/local/bigbluebutton/core/scripts`

2- When I run this file, it show me some errors + RuntimeError and transfer only 5 of 393 records. You can check errors in this link: https://pasteid.fledix.com/h6bl
(I have permission to write in that folder. I checked it by enter `touch test.txt` command)

**Comment by MrCapitalist** [comment]
I changed `/usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb`

from

`archive_file = "#{work_dir}/#{meeting_id}.tar"
begin
  puts('Creating recording archive')
  FileUtils.mkdir_p(work_dir)
  FileUtils.cd(published_dir) do
    system('tar', '--create', '--file', archive_file, *format_dirs) \
      || raise('Failed to create recording archive')
  end

  puts("Transferring recording archive to #{spool_dir}")
  system('rsync', '--verbose', '--protect-args', *extra_rsync_opts, archive_file, spool_dir) \
    || raise('Failed to transfer recording archive')
ensure
  FileUtils.rm_f(archive_file)
end

extra_rsync_string = extra_rsync_opts.join(' ') 
  puts("Adding extra rsync options:  #{extra_rsync_string} ")

  puts("Transferring recording archive to #{spool_dir}")
  system('sg','scalelite-spool', '-c', "rsync --verbose --protect-args #{extra_rsync_string} #{archive_file} #{spool_dir}") \
    || raise('Failed to transfer recording archive')`

to

`archive_file = "#{work_dir}/#{meeting_id}.tar"
begin
  puts('Creating recording archive')
  FileUtils.mkdir_p(work_dir)
  FileUtils.cd(published_dir) do
    system('tar', '--create', '--file', archive_file, *format_dirs) \
      || raise('Failed to create recording archive')
  end

extra_rsync_string = extra_rsync_opts.join(' ') 
  puts("Adding extra rsync options:  #{extra_rsync_string} ")

  puts("Transferring recording archive to #{spool_dir}")
  system('sg','scalelite-spool', '-c', "rsync --verbose --protect-args #{extra_rsync_string} #{archive_file} #{spool_dir}") \
    || raise('Failed to transfer recording archive')
ensure
  FileUtils.rm_f(archive_file)
end`

and run `scalelite_batch_import.sh` from this path: `/usr/local/bigbluebutton/core/scripts` again. Permission denied error didn't show but errors changed to these:

https://pasteid.fledix.com/tl7i

and only new records transfer well

**Comment by MrCapitalist** [comment]
To fix `Gem::ConfigMap is deprecated` error, I've [downgraded gem version](https://github.com/rubygems/rubygems/issues/3068#issuecomment-596205194) to v3.0.6:

`sudo gem update --system 3.0.6`

After that, when I run `scalelite_batch_import.sh` it transfered new records without any problem. I've forced to skip all of my previous records.

But I want to run `scalelite_batch_import.sh` every hour (cron.hourly) automatically and delete transfered records from BBB server. How can I do that?

**Comment by MrCapitalist** [comment]
I tested it again, everything is OK ^_^
There is no need to change anything. 

@alkanis @schoasch10 @farhatahmad Thanks a lot for your help. 🌺

**Comment by crkdown** [comment]
> I tested it again, everything is OK ^_^
> There is no need to change anything.
> 
> @alkanis @schoasch10 @farhatahmad Thanks a lot for your help. 🌺

Hello, in my case mount the NFS everything perfect, send the recording package to the shared system as .tar but in the session management instance it does not show anything. https://g.dongee.com/E0ub09xb

If you know how to repair it, I appreciate it

root@scalelite:/mnt/scalelite-recordings/var/bigbluebutton/spool# pwd
/mnt/scalelite-recordings/var/bigbluebutton/spool
root@scalelite:/mnt/scalelite-recordings/var/bigbluebutton/spool# ll
total 122236
drwxrwxr-x  2 dongee 2000         7 may 26 00:28 ./
drwxr-xr-x+ 6 root   root         6 may 25 23:06 ../
-rw-r--r--+ 1    998  998    972800 may 25 23:22 8c31ee3fd3a2459acc1cbd05b75cc49a0e9c4fbb-1590448751003.tar
-rw-r--r--+ 1    998  998 121763840 may 25 23:08 988955c17af3a0cf89566a084919a3f1b77194db-1590439209537.tar
-rw-r--r--+ 1    998  998   1320960 may 25 23:40 b0656691bfc3b6d4f4fda6c2237497fcf02aef27-1590449831891.tar
-rw-r--r--+ 1    998  998    563200 may 26 00:21 b0656691bfc3b6d4f4fda6c2237497fcf02aef27-1590452209505.tar
-rw-r--r--+ 1    998  998    112640 may 26 00:22 d54fdcb69c8381d0766189b69a99594ec31e4dc6-1590452295542.tar

**Comment by MrCapitalist** [comment]
I am checking sessions again and it seems still have problem. records are ready in `/var/bigbluebutton/published/presentation/` directory, but they haven't transfered to scalelite and they don't show in wordpress frontend! >_< 

I even ran `scalelite_batch_import.sh` manually, presents folder copied to `/mnt/scalelite-recordings/var/bigbluebutton/published/presentation` but they don't show of frontend!! :((

**Comment by jayarajito** [comment]
Hi Please any one help how to setup Scalelite for BBB.
I unable to understand the steps

**Comment by matiasilva** [comment]
https://github.com/blindsidenetworks/scalelite#getting-help
