### ISSUE TITLE
Error 401 not authorized

### ISSUE THREAD

**Issue by vicman** [blindsidenetworks/scalelite#211]
Hi friends,
Today I configured scalelite, but I have a problem.
 The room creation works fine, but when i want to join like moderator bbb show me error 401.

If I made the same procedure directly over the meeting instance works fine. 

What do I do? 
I 'm using the php api, and mconf show the same error. 
Thanks

**Comment by farhatahmad** [comment]
Can you try making the calls directly to the BigBlueButton server? Are you getting the same error?
