### ISSUE TITLE
How to use loadMultiplier ?

### ISSUE THREAD

**Issue by arthurd2** [blindsidenetworks/scalelite#212]
Hey guys, 
can you feed us with more examples of how to use the `loadMultiplier` feature?

In my case, I have 2 servers (A and B) with X cores and 1 server (C) with 2X cores.
How should I set their `loadMultiplier`?

Should I consider the bigger server as 1 and the rest of them as its ratio?
* A(2), B(2) and C(1)

**Comment by farhatahmad** [comment]
> Should I consider the bigger server as 1 and the rest of them as its ratio?

Yes that's correct. The loadMultiplier will make Scalelite think a server is more loaded then it actually is, meaning that it will try to avoid creating meetings on that server. The higher the loadMultiplier, the less meetings will be created. As an example if Server A is 2x stronger than Server B, Server A should have `loadMultiplier=1` and Server B has `loadMultiplier=2`.

**Comment by arthurd2** [comment]
Nice.
I'm using the `latest` docker version, from early May.
But it seems it doesn't have the `rake servers:loadMultiplier[id,newLoadMultiplier]` function yet.
Or it's deprecated?

![image](https://user-images.githubusercontent.com/2431590/82703368-288c0780-9c4a-11ea-89c0-ab429294f4cb.png)

**Comment by farhatahmad** [comment]
I don't believe the latest docker image is being built correctly. I suggest using either `v1-<component name>` or `master-<component name>`
