### ISSUE TITLE
getRecordings error with PG cluster

### ISSUE THREAD

**Issue by GremL1N** [blindsidenetworks/scalelite#213]
I haven't records in my setup.
When frontend (Greenlight) request `getRecordings` with `meetingID` parameter, ScaleliteApi usualy response with 
```
<hash>
<status type="integer">500</status>
<error>Internal Server Error</error>
</hash>
```
So Greenlight show "Endpoint or secret" error. And `BigBlueButtonException: Invalid response body. Is the API URL correct?...` in logs.

I think this is Redis answer for empty cache, but not sure.
Here
https://github.com/blindsidenetworks/scalelite/blob/5c60e14d8c3addedf959faf9dc0562ad5fe7a4e1/app/controllers/bigbluebutton_api_controller.rb#L249
return is empty or nil or error in my case i think. I can't debug deeply because don't understand where logs or STDOUT of docker image (scalelite-api and scalelite-nginx).

Sometimes the response is right:
```
<response>
<returncode>SUCCESS</returncode>
<recordings> </recordings>
<messageKey>noRecordings</messageKey>
<message>There are not recordings for the meetings</message>
</response>
```

Greenlight request recordings in many pages so this is big trouble for it.

**Comment by GremL1N** [comment]
scalelite-api show this error:
```
[a63bb222-5315-4127-b9a4-308c26b7e392] ActionView::Template::Error (PG::DuplicatePstatement: ERROR:  prepared statement "a1" already exists
):
[a63bb222-5315-4127-b9a4-308c26b7e392]     3: xml.response do
[a63bb222-5315-4127-b9a4-308c26b7e392]     4:   xml.returncode 'SUCCESS'
[a63bb222-5315-4127-b9a4-308c26b7e392]     5:   xml.recordings do
[a63bb222-5315-4127-b9a4-308c26b7e392]     6:     @recordings.each do |recording|
[a63bb222-5315-4127-b9a4-308c26b7e392]     7:       xml.recording do
[a63bb222-5315-4127-b9a4-308c26b7e392]     8:         xml.recordID recording.record_id
[a63bb222-5315-4127-b9a4-308c26b7e392]     9:         xml.meetingID recording.meeting_id
[a63bb222-5315-4127-b9a4-308c26b7e392]
[a63bb222-5315-4127-b9a4-308c26b7e392] app/views/bigbluebutton_api/get_recordings.xml.builder:6
[a63bb222-5315-4127-b9a4-308c26b7e392] app/views/bigbluebutton_api/get_recordings.xml.builder:5
[a63bb222-5315-4127-b9a4-308c26b7e392] app/views/bigbluebutton_api/get_recordings.xml.builder:3
[a63bb222-5315-4127-b9a4-308c26b7e392] app/controllers/bigbluebutton_api_controller.rb:254:in `get_recordings'
```

**Comment by GremL1N** [comment]
So. I'm using cloud instance of Postgresql cluster.
Rails docs says:

> By default Active Record uses database features like prepared statements and advisory locks. You might need to disable those features if you're using an external connection pooler like PgBouncer:

```
production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false
```

It works for me. But `systemctl restart scalelite.target` rebuild images so i need to do it every restart\reboot

Can you add somthing like:
```
default: &default
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  prepared_statements: <%= ENV.fetch('PREPARED_STATEMENT') {false} %>
  timeout: 5000
  adapter: postgresql
  encoding: unicode
```
to `config/database.yml`?

**Comment by farhatahmad** [comment]
I think the underlying issue here is that Scalelite doesn't properly handle the case where there are no recordings

**Comment by GremL1N** [comment]
scalelite correct respond when no recordings.
