### ISSUE TITLE
End Meeting using panic - missing moderator password?

### ISSUE THREAD

**Issue by wmchris** [blindsidenetworks/scalelite#218]
Very strange behaviour. If i panic a server, i get a hell lot of entries like 

Clearing Meeting id=7d73c5532575057c1daf1ff4e0edcfb285785714
WARNING: Could not end meeting id=7d73c5532575057c1daf1ff4e0edcfb285785714: invalidPassword: You must supply the moderator password for this call.

**Comment by farhatahmad** [comment]
We're going to need to store the meeting passwords in the database since BigBlueButton doesn't support ending conferences without the password. 

You can ignore those warnings as the important part (deleting the meeting from Scalelite's db) is still done

**Comment by amalrails** [comment]
Closed with #466
