### ISSUE TITLE
Issue with scalelite-recording-importer

### ISSUE THREAD

**Issue by schoasch10** [blindsidenetworks/scalelite#219]
Hi, i used this guide to setup scalelite:

Worked like a charm and connected BBB-Servers afterwards.
After that i used this one to mount an nfs share for my recordings:
https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md

It works out so far that thee BBB-Severs are creating the file in the spool directory.
But it seems thaht the scalelite-recording importer doest no process the files.
what could i do?
Is there a log file for the recording importer?

This is the section from the docker-compose.yml file regarding the recording importer

`scalelite-recording-importer:
    image: ${SCALELITE_REPO:-blindsidenetwks}/scalelite:${SCALELITE_TAG:-v1}-recording-importer
    container_name: scalelite-recording-importer
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:password@postgres:5432/scalelite?pool=5}
    volumes:
      - ${SCALELITE_RECORDING_DIR-/mnt/scalelite-recordings/var/bigbluebutton}:/var/bigbluebutton
      - ${SCALELITE_RECORDING_DIR-/mnt/scalelite-recordings/var/bigbluebutton}/spool:/var/bigbluebutton/spool
    depends_on:
      - postgres
      - redis
      - scalelite-api
    logging:
      driver: journald
`

**Comment by davidpesce** [comment]
Execute the following command on your scalelite instance:
```
sudo docker logs scalelite-recording-importer
```

That'll pull up the logs for that container.

**Comment by schoasch10** [comment]
thanks for the hint with the log file
thats´s the output:

`D, [2020-05-18T07:47:59.834362 #6] DEBUG -- : Checking for existing files…
D, [2020-05-18T07:47:59.834434 #6] DEBUG -- : Starting file monitor…
I, [2020-05-18T08:05:34.606900 #6]  INFO -- : Exiting recording importer on sign                                       al: SIGTERM
I, [2020-05-18T08:06:11.532856 #7]  INFO -- : Monitoring /var/bigbluebutton/spoo                                       l for new recording files
D, [2020-05-18T08:06:11.533015 #7] DEBUG -- : Checking for existing files…
D, [2020-05-18T08:06:11.533244 #7] DEBUG -- : Starting file monitor…
`
why is the latest output from 3 days ago?
he's looking in /var/bigbluebutton/spool for recordings - but that path doenst exist, doesnt it?

**Comment by farhatahmad** [comment]
Looks like the recording importer isn't looking in the correct place. Can you post your docker-compose file again but formatted correctly so that it's easier to read?

**Comment by schoasch10** [comment]
I was thinking the same way.
i just used the file from the script.
am i right that i need to change the path from "var/bigbluebutton" to "/mnt/scaleliterecordings/..."
(i just thought that the var/bigbluebutton path was somehow related to a special docker thing)

so i can use the real path in the docker-compose file?

This is my config:

`scalelite-nginx:
    image: ${SCALELITE_REPO:-blindsidenetwks}/scalelite:${SCALELITE_TAG:-v1}-nginx
    container_name: scalelite-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log/nginx/:/var/log/nginx
      - ./data/certbot/conf:/etc/nginx/ssl
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx/scalelite:/etc/nginx/conf.d/scalelite
      - ${SCALELITE_RECORDING_DIR-/mnt/scalelite-recordings/var/bigbluebutton}/published:/var/bigbluebutton/published
    environment:
      - NGINX_SSL=${NGINX_SSL-true}
      - URL_HOST=${URL_HOST}
    depends_on:
      - scalelite-api

  scalelite-api:
    image: ${SCALELITE_REPO:-blindsidenetwks}/scalelite:${SCALELITE_TAG:-v1}-api
    container_name: scalelite-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./log/scalelite/:/app/log
      - ${SCALELITE_RECORDING_DIR-/mnt/scalelite-recordings/var/bigbluebutton}:/var/bigbluebutton
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - LOADBALANCER_SECRET=${LOADBALANCER_SECRET}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:xxxxxx/scalelite?pool=5}
      - URL_HOST=${URL_HOST}
    depends_on:
      - postgres
      - redis
    logging:
      driver: journald

  scalelite-poller:
    image: ${SCALELITE_REPO:-blindsidenetwks}/scalelite:${SCALELITE_TAG:-v1}-poller
    container_name: scalelite-poller
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:xxxxx/scalelite?pool=5}
    depends_on:
      - postgres
      - redis
      - scalelite-api
    logging:
      driver: journald

  scalelite-recording-importer:
    image: ${SCALELITE_REPO:-blindsidenetwks}/scalelite:${SCALELITE_TAG:-v1}-recording-importer
    container_name: scalelite-recording-importer
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATABASE_URL=${DATABASE_URL:-postgres://xxxxxx:5432/scalelite?pool=5}
    volumes:
      - ${SCALELITE_RECORDING_DIR-/mnt/scalelite-recordings/var/bigbluebutton}:/var/bigbluebutton
      - ${SCALELITE_RECORDING_DIR-/mnt/scalelite-recordings/var/bigbluebutton}/spool:/var/bigbluebutton/spool
    depends_on:
      - postgres
`

**Comment by farhatahmad** [comment]
What's `SCALELITE_RECORDING_DIR` set to in your `/etc/default/scalelite` file?

**Comment by schoasch10** [comment]
there is no `etc/default/scalelite file`

i used this script to install:

[https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6](url)

any othe location where this file could be stored?

**Comment by farhatahmad** [comment]
In that case it would be the `.env` file

**Comment by schoasch10** [comment]
ah got it thank you.
i looked in the .env file and indeed the path is wrong.
I corrected it but the docker-compose file and the recorder-importer has not the updated path yet.
how can i make the changes in the .env file effective?
by the way: thank you very very much for the assistance

**Comment by farhatahmad** [comment]
If you're using the docker-compose method then just `docker-compose down` and `docker-compose up -d`
