### ISSUE TITLE
How can I enable automatic recording deletion?

### ISSUE THREAD

**Issue by Cistoge** [blindsidenetworks/scalelite#220]
Hello,

in the bottom of https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md you suggest to enable automatic recording deletion after a successful recording transfer, for saving disk space. How can that automatic deletion be enabled?

Regards
  Christoph

**Comment by ichdasich** [comment]
See https://github.com/bigbluebutton/bigbluebutton/issues/9202#issuecomment-621099469 and https://github.com/bigbluebutton/bigbluebutton/issues/9202#issuecomment-621974168

**Comment by Cistoge** [comment]
So, automatic recording deletion is not supposed to remove from a BigBluebutton server the recording files that have already been present before recording transfer to scalelite?

**Comment by farhatahmad** [comment]
Duplicate #168
