### ISSUE TITLE
scalelite-nginx.service [emerg] 6#6: cannot load certificate 

### ISSUE THREAD

**Issue by avkovalevs** [blindsidenetworks/scalelite#222]
Hello all,
I'm trying to install scalelite using official docs https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md but have I couple of issues with scalelite-nginx.service and scalelite-api initialization DB.

'A' record already exists for the domain. The firewall is opened. 
When I start scalelite-nginx.service I get an error:
root@jeff1:~# systemctl start scalelite-nginx.service
root@jeff1:~# systemctl status scalelite-nginx.service
● scalelite-nginx.service - Scalelite Nginx
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-05-22 07:47:06 EDT; 9s ago
  Process: 4243 ExecStart=/usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount type=bind,source=${SCALEL
  Process: 4214 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
  Process: 4196 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=1/FAILURE)
  Process: 4165 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
 Main PID: 4243 (code=exited, status=1/FAILURE)

May 22 07:47:06 jeff1.academyofmine.net docker[4243]: Startup script was run as init, re-execing using tini.
May 22 07:47:06 jeff1.academyofmine.net docker[4243]: Generating templated nginx configuration...
May 22 07:47:06 jeff1.academyofmine.net docker[4243]: Using SSL configuration template.
May 22 07:47:06 jeff1.academyofmine.net docker[4243]: Starting nginx periodic reload process...
May 22 07:47:06 jeff1.academyofmine.net docker[4243]: Starting nginx...
May 22 07:47:06 jeff1.academyofmine.net docker[4243]: 2020/05/22 11:47:06 [emerg] 6#6: cannot load certificate "/etc/nginx/ssl/live/jeff1.academyofmine.net/fullchain.pem": BIO_new_file() fai
May 22 07:47:06 jeff1.academyofmine.net docker[4243]: nginx: [emerg] cannot load certificate "/etc/nginx/ssl/live/jeff1.academyofmine.net/fullchain.pem": BIO_new_file() failed (SSL: error:02
May 22 07:47:06 jeff1.academyofmine.net systemd[1]: scalelite-nginx.service: Main process exited, code=exited, status=1/FAILURE
May 22 07:47:06 jeff1.academyofmine.net systemd[1]: scalelite-nginx.service: Unit entered failed state.
May 22 07:47:06 jeff1.academyofmine.net systemd[1]: scalelite-nginx.service: Failed with result 'exit-code'.

I can't get clearly understand from official guides the process of issuance SSL certificate. 
Which component should initiate the SSL cert issuance (this scalelite-nginx container, another container or me)? I know that the certbot usually used for that. But I don't see this image there and the description about SSL cert at the docs. 

The second issue with docker exec -it scalelite-api bin/rake db:setup
root@jeff1:~# docker exec -it scalelite-api bin/rake db:setup
could not translate host name "jeff1" to address: Name does not resolve
Couldn't create 'scalelite' database. Please check your configuration.
rake aborted!
PG::ConnectionBad: could not translate host name "jeff1" to address: Name does not resolve
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/pg-1.2.2/lib/pg.rb:58:in `initialize'

root@jeff1:~# cat /etc/default/scalelite 
URL_HOST=jeff1.academyofmine..net
DATABASE_URL=postgresql://scalelite:somepass@external_ip:5432/scalelite
REDIS_URL=redis://redis
SCALELITE_TAG=v1
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly
LETSENCRYPT_EMAIL=dev@academyofmine.com
LETSENCRYPT_STAGING=0
How to resolve both issues?
Thank you in advance.

**Comment by elifdez** [comment]
change
DATABASE_URL=postgresql://scalelite:somepass@external_ip:5432/scalelite
to
DATABASE_URL=postgresql://scalelite:somepass@external_ip:5432

**Comment by elifdez** [comment]
and check /etc/hosts
127.0.0.1       localhost
127.0.0.1       jeff1

**Comment by avkovalevs** [comment]
But if I want network access to PostgreSQL in the case when PostgreSQL and Scalelite located separately.

**Comment by elifdez** [comment]
DATABASE_URL=postgresql://scalelite:somepass@external_ip:5432
I've this confiiguration and works ok to me in a separated network.

in this file: **pg_hba.conf** add this line: 
**host    scalelite       scalelite    scalelite_ip/32       md5**

in p**ostgresql.conf** change 
listen_addresses = 'localhost' 
to
listen_addresses = '*'
