### ISSUE TITLE
Media device error when launching Scalelite. Works fine with BBB server directly

### ISSUE THREAD

**Issue by yc01** [blindsidenetworks/scalelite#224]
Has anyone seen this error when launching a new meeting in scalelite ? It only happens through scalelite but if I launch a session directly using one of the BBB servers, everything works great. 

Using scalelite, I get this error on Chrome and Firefox both when trying to connect Audio: 

```
> There was an issue with your media devices
> Did you give permission for access to your microphone? Note that a dialog should appear when you try to join audio, asking for your media device permissions, please accept that in order to join the audio conference. If that is not the case, try changing your microphone permissions in your browser's settings.
```

**Comment by codegeek1001** [comment]
It was related to iframe code on our end. Will close now.
