### ISSUE TITLE
Install and run Scalelite services without Docker

### ISSUE THREAD

**Issue by aguerson** [blindsidenetworks/scalelite#225]
Hi guys, 
I try to use Scalelite without Docker.
I have already installed 3 BBB server
I have installed a greenlight frontend ( who works without docker https://github.com/bigbluebutton/greenlight/issues/1112 )
I have installed my own postgreSQL database ( the same used for greenlight )
Now I need some help to launch Scalelite

What I have done 

I started with a ubuntu 18.04 (bionic)

1) create a user bigbluebutton
2) install ruby 2.6.6 with rbenv with some gem

```
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
exec $SHELL
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
exec $SHELL
rbenv install 2.6.6
rbenv global 2.6.6
gem install bundler
rbenv rehash
gem install bigdecimal
rbenv rehash
gem install json
rbenv rehash
git clone https://github.com/rbenv/rbenv-vars.git ~/.rbenv/plugins/rbenv-vars
rbenv rehash
```
3) install few apt package

```
apt-get install curl
apt-get install 
apt-get install apt-file git-core zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common libffi-dev nodejs yarn language-pack-en language-pack-fr
apt-get install software-properties-common net-tools gettext tzdata
apt-get install libxslt1-dev libxslt1.1
apt-get install libpq5 libpq-dev
apt-get install libxml2 libxml2-dev
apt-get install postgresql-client-common postgresql-client-11
```

4) Then I try to deploy scalelite

```

git clone git://github.com/blindsidenetworks/scalelite.git /opt/bigbluebutton/scalelite_prod/
cd /opt/bigbluebutton/scalelite_prod
git init
I modified Gemfile and Gemfile.lock to use rails 6.0.3.1 ( security issue )
bundle config build.nokogiri --use-system-libraries
bundle install --deployment --without development:test
RAILS_ENV=production bundle exec rake db:schema:load
RAILS_ENV=production bundle exec rake db:migrate

gem uninstall rake
gem install rake -v "13.0.1"
```

The database seems ready, but I don't know what to do next.

I have already install a REDIS server and a NFS server.

Is there someone to help me to run all the scalelite services ?
Do I need to start rails ?
Do I need to install nginx as proxy in front of scalelite ? ( I already have nginx for greenlight... )

Thanks in advance,
Regards,

**Comment by aguerson** [comment]
@farhatahmad @ffdixon Could you help me ?

**Comment by rabser** [comment]
Why are you trying to install a software package avoiding the package developer's instructions ?

**Comment by aguerson** [comment]
Hi @rabser , Docker is really good for a dev env to have the same thing everywhere.
In a prod env, we/you can't use docker. You need to know how the application works.
That why I try to run Scalelite without docker.
I think, I am at the end to run Scalelite without docker, but I need some help to be sure.
Everything works with Rake.
rails seems to not be used.
So do I need to launch a rake process ? ( really 3 ) and that's ok, or I missed something ?
Regards,

**Comment by rabser** [comment]
Why this ?
Docker was thinked for simplify the deploy in production environment, not for development purposes (cfr. .
All the best of breed internet company/service run their service dockerized, and i'm talking about  google, facebook, twitter... 
Anyway, I cannot answer to your question because i'm confident in choices done by the scalelite developers in writing the right environment for running this service in the distributed dockerfile. If you want to unpack it, just take care of the Dockerfile and you can rebuild back the environment, but be sure to choose the same choices that were done by the leader programmers.
I think, honestly, that this is not an issue, if you want to change the way scalelite works, you can do a fork, but then you need to get out the solutions by yourself.

**Comment by aguerson** [comment]
` I cannot answer to your question because i'm confident in choices done by the scalelite developers in writing the right environment `

I understand the choice.
I have already read the dockerfile and I just need to validate what I understood.

Maybe you can answer to my question without being in overhang with the devs of Scalelite.

At the end of the dockerfile I can read 

```
CMD [ "bin/start-recording-importer" ]
=> rake recordings:watch["$RECORDING_IMPORT_POLL","$RECORDING_IMPORT_POLL_INTERVAL"]
CMD [ "bin/start-poller" ]
=> rake poll["$POLL_INTERVAL"]
CMD [ "bin/start" ]
=> puma -C config/puma.rb "$@"
```

So, the listening daemon is puma ? Do I need to install a nginx proxy in front of puma ?

**Comment by rabser** [comment]
Scalelite is built on multiple containers (the Dockerfile is divided in "section") and one of them launch a nginx server that will serve the external API of scalelite.

**Comment by aguerson** [comment]
Sure, I am not very familiar with ruby / rake env. But there's a first time for everything ;)

**Comment by rabser** [comment]
For the intrinsic nature of containers, there are usually no impossibile problems in using "matrioska containers". 
Other things are the different flavors of tools around containers, like docker or lxd. Reading the documentation on the web about Virtuozzo 7 (dated 2016, i hope that some updates were done in the meantime)  and docker and it's supported, note that the choice for overlayfs which is mentioned as "new/experimental" in 2016, is now the default for docker.
So why not give it a try ?
