### ISSUE TITLE
Cluster with 50 BBB servers

### ISSUE THREAD

**Issue by ugenkudupudi** [blindsidenetworks/scalelite#230]
We have plans to setup 50 BBB servers using scalelite and need information on how to have more than 1 load balancer. 

Each BBB server will have 16GB and 8 core. 

Any help or advice in this regard is deeply appreciated.

**Comment by ffdixon** [comment]
This isn't an issue/feature request, but more of a discussion.  We invite you to join our bigbluebutton-setup mailing list and engage the community there.  

https://bigbluebutton.org/support/community/
