### ISSUE TITLE
BBB servers for scalelite

### ISSUE THREAD

**Issue by codingchallenge** [blindsidenetworks/scalelite#231]
Hi All,

  How to setup multiple BBB servers with SSL without assigning a separate domain for each BBB server? 
I want to keep adding/removing BBB servers to scalelite according to my demand. It is not possible to register so many domains for each BBB server. But BBB server instructions mention that we need a domain in order to use SSL. How does this work with Scalelite ? 

Please provide suggestions. 

Thank you.

**Comment by avkovalevs** [comment]
Hi,
you need only one domain and any 'A' records for this domain. One 'A' record per each BBB server.

**Comment by codingchallenge** [comment]
Hi,

   Thank you for the response. Could you provide any pointers for any 'A' records or any documentation on this one ?

**Comment by ffdixon** [comment]
See
 
 https://en.wikipedia.org/wiki/List_of_DNS_record_types

**Comment by codingchallenge** [comment]
Since I am planning to use the same DNS for bunch of bbb servers, I need to use individual ip addresses to access each bbb server separately. 

But I am not able to access bbb server using public ip address assigned to the machine. I can only access it with the DNS attached to it. 
How can i change bbb server to be able to access with the https://ipaddress 

I need to add each of these bbb servers to my scalelite server.

**Comment by congthang1** [comment]
Yes this is needed when we use autoscaling, if ssl needed only way is to programmatically (like Route 53 on AWS) point the sub domain to the IP of  a new server and update the ssl certificate there. SSL certificate should be for whole domain (including all subdomain) and it should work.
