### ISSUE TITLE
ScaleLite Blocking host trouble

### ISSUE THREAD

**Issue by kodwick** [blindsidenetworks/scalelite#232]
I've installed all as discribed, after that installed and configured Reverse nginx proxy server and now i'm gettin this kind of error while try to eneter from moodle to scalelite: Blocked host: XXX.X.XXX.XXX
To allow requests to XXX.X.XXX.XXX, add the following to your environment configuration:
config.hosts << "XXX.X.XXX.XXX" And i dunno where to need to implement this fix)) 
Allready placed it in env file of scalelite (unfortunatley it not helped) 
ScaleLite was instaqlled in docker by this manual: https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6

So need some advice how to solve it)

**Comment by kodwick** [comment]
Wel yes? but do i need to type https://....... or can type ...example....?

**Comment by kodwick** [comment]
Well*

**Comment by farhatahmad** [comment]
If your website is `https://bbb.example.com` then set it to `URL_HOST=bbb.example.com`

**Comment by kodwick** [comment]
Well i've allready set this )

**Comment by kodwick** [comment]
But I thought, I need to enter name of balancer server in host_url and not my bbb server.

**Comment by kodwick** [comment]
So as I understand, that no one'll help me with this trouble?

**Comment by farhatahmad** [comment]
> To allow requests to XXX.X.XXX.XXX

That looks like an IP address and not a url (which it should be). Are you doing something weird with DNS or NGINX?

**Comment by kodwick** [comment]
Hello!

Well yes, now i have nginx reverse proxy. ScaleLite and BBB server is on
one external white IP

пт, 5 июн. 2020 г. в 21:24, Ahmad Farhat <notifications@github.com>:

**Comment by kodwick** [comment]
So any suggestions? And i not so cleary understand what is happen, when i try to configure reverse nginx on servername of Scale it giving an error "can't find srv...blah-blah... in upstream"

**Comment by pbdco** [comment]
Hi @jfederico we are using https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6

Is it you Scalelite docker version up to date with current official Scalelite release? How does it update?

Thank you in advance for your great work.
