### ISSUE TITLE
Scalelite auto-enables server regardless whenever it was disabled manually or no

### ISSUE THREAD

**Issue by baltuonis** [blindsidenetworks/scalelite#233]
When I disable the server manually (let's say we don't want to accept any new meetings & prepare it for the maintenance), scalelite poller enables it automatically.

https://github.com/blindsidenetworks/scalelite/blob/master/lib/tasks/poll.rake#L46

That makes it impossible to remove/shutdown a server gracefully.

Suggestion: keep a record whenever the server was disabled manually or because of failing healthchecks

**Comment by Davka** [comment]
Same problem here. 

You have to be pretty quick to avoid throwing any participants out of the meeting unnecessarily.

**Comment by farhatahmad** [comment]
That probably shouldn't be happening. I think the poller should just disable offline servers and set online servers to only online (not enabled)
