### ISSUE TITLE
Not able to add bbb server with ip address to scalelite

### ISSUE THREAD

**Issue by codingchallenge** [blindsidenetworks/scalelite#237]
Hello All,

   I have scalelite installed and working when I add bbb server as follows:

docker exec -i scalelite-api bundle exec rake servers:add[https://bbb1.example.com/bigbluebutton/api/,bbb-secret]

But If i add the same bbb server using the public ip address as follows:

docker exec -i scalelite-api bundle exec rake servers:add[https://IPAddress/bigbluebutton/api/,bbb-secret]

The bbb server is offline on the scalelite server.

How can i add server using the IP Address to the scalelite server ? 

Thank you very much for the support. Great product solving lots of challenging problems :)

**Comment by farhatahmad** [comment]
Is the BigBlueButton available externally at `https://IPAddress/bigbluebutton/api/`? Scalelite needs to be able to individually reach every BigBlueButton Server that you add

**Comment by wolbernd** [comment]
My guess would be that the Ip Address is not part of your SSL Certificate and thus scalelite refuses to open a https connection to it.
