### ISSUE TITLE
help for migration from standalone installation to scalelite

### ISSUE THREAD

**Issue by margmz** [blindsidenetworks/scalelite#238]
To migrate users and rooms from one working greenlight + bigbluebutton installation to another functional scalelite installation with 3 bigbluebutton servers. I can copy the recordings of the videos, I can migrate user and room information to the new greenlight. But in addition I would need to add to the scalelite database, the information of the recordings, right? In the recordings and playback_formats tables, right? Is there a script that does this?

**Comment by farhatahmad** [comment]
The recordings can be migrated into Scalelite using the batch import script 

https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#configuring-the-bigbluebutton-recording-transfer

Assuming you have everything running in Scalite, It will automatically import all the required data
