### ISSUE TITLE
Not able to find error logs in scalelite-api

### ISSUE THREAD

**Issue by smtkhaitan** [blindsidenetworks/scalelite#240]
Hi,
I am getting **An unhandled lowlevel error occurred. The application logs may have details.**, when I am trying to access **http://<hostname_for_scalelite_server>/bigbluebutton/api** from my chrome browser.

Seems like there is some issue in my setup, but I am not able to find the location where I can look for the logs in the **scalelite-api docker.** Can someone please point me to the logs ?

**Comment by smtkhaitan** [comment]
can someone please help ?

**Comment by farhatahmad** [comment]
`docker logs scalelite-api` should give you the application logs

**Comment by smtkhaitan** [comment]
Thanks
