### ISSUE TITLE
Scalelite with different frontends

### ISSUE THREAD

**Issue by glu000** [blindsidenetworks/scalelite#243]
Hi,
I want to setup Scalelite with 2 (or more) different Greenlight instances with different databases / different settings. Purpose is, to have different GL-servers for different clients. Every server has it's own URL (like meet.client1.com, meet.client2.com, etc.) with different settings und customization of Greenlight. All GL servers should use the same BBB-cluster with scalelite

Is this possible?

Regards
Guenter

**Comment by github-luckow-org** [comment]
yes. why not? Take a look at #115 With this patch it is possible to use different secrets for different frontends. IMHO a big improvement.
