### ISSUE TITLE
Q: Dial in in cluster environments - FreeSWITCH configuration

### ISSUE THREAD

**Issue by github-luckow-org** [blindsidenetworks/scalelite#244]
Do we have a concept or best practice for "dial in" in cluster environments? 
conference bridge, FreeSWITCH

**Comment by wolbernd** [comment]
Nothing official but there is an issue in greenlight in which a possible solution is described:
https://github.com/bigbluebutton/greenlight/issues/1645#issuecomment-632013396

**Comment by github-luckow-org** [comment]
cool. thank you :)
