### ISSUE TITLE
Scalelite with bbb-lti

### ISSUE THREAD

**Issue by hoang000147** [blindsidenetworks/scalelite#245]
Hi, I plan to setup scalelite for load balancing bigbluebutton servers. However, I wonder that if I use scalelite, can I use LTI to integrate bbb with LMS systems? Because it seems that scalelite only works with bbb frontend like Greenlight or Moodle, but LTI works differently from those frontends.

Regards
Hoang

**Comment by basisbit** [comment]
Yes, you can use Scalelite between the LTI and your BBB servers.
When configuring the LTI, instead of entering the address of the BBB server and its secret, enter the address + secret from the scalelite server.

**Comment by basisbit** [comment]
@hoang000147 why did you ask this question three times (once here in the issue tracker and twice in the forum / mailing list)?

**Comment by hoang000147** [comment]
Thanks for your answer. I asked 3 times just to increase the chance to have someone answer since every times I asked before, no one answered

**Comment by omerurhan** [comment]
Hi, I am working on scalelite and open edx lti integration. You currently answer is it posibble but I tried to do it by changing the secret and lti url,  I got "unsupported request" output from the scalelite API. Can you explain this integration in more detail? Thank you.
