### ISSUE TITLE
Published Folder on BBB Server

### ISSUE THREAD

**Issue by SebastianZiegler** [blindsidenetworks/scalelite#247]
Hi everyone,

don't know if this is the right place or the bbb git. My problem is, I have 5 BBB server behind scalelite, everythings works fine. Recordings are copied but the published recording still exists on BBB server so I get an problem with disk usage.
Is it save to clear the /var/bigbluebutton/published folders if the files are copied to scalelite nfs? 
A good way to do this would be here: https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/scalelite_post_publish.rb

Has anybody done something allready?

best regards
Sebastian

**Comment by yilmazali32** [comment]
I have same problem
