### ISSUE TITLE
sometimes BBB node disabled after restart

### ISSUE THREAD

**Issue by andy-igoshin** [blindsidenetworks/scalelite#248]
scalelite 1.0.3

sometimes after restarting BBB nodes one of them becomes "disabled/online".

maybe it is connected with unsuccessful fix of "Fix a bug that caused the poller to re-enable disabled servers".

**Comment by mabeyj** [comment]
This has happened to me as well. I have a test environment that restarts every day. I upgraded to 1.0.3 a couple days ago, and today a server was disabled.

It looks like when the health check fails, it panics the server: https://github.com/blindsidenetworks/scalelite/blob/8b4830ced5a609028fed6270efd14e8bb11a8615/lib/tasks/poll.rake#L58

Which disables the server: https://github.com/blindsidenetworks/scalelite/blob/e1d63bfd078105220f898c825bdd8a03e0993809/lib/tasks/servers.rake#L72

Then when the server comes back online, it remains disabled.

**Comment by RonZ-dev** [comment]
Same here. Have daily powerdowns of the complete environment and some servers werent available after poweron. Because checking every morning is to much of a hassle, I altered the start procedure. BBB machines come online before the Scalelite server now.
Haven't had any issues yet.
