### ISSUE TITLE
Scalelite sending users to offline server

### ISSUE THREAD

**Issue by MirzaAreebBaig** [blindsidenetworks/scalelite#249]
Hey,
We have been using BBB with Scalelite 
Our frontend creates a token ( [bigbluebutton token=”aa2817f3a1e1″] ) to send users to there specific room once some of our servers gets offline or disabled (due to schedule uptime/downtime) from the scalelite still it sends users to the same server creating an error of its currently not possible to create a room in this server we need to recreate the token again to send user to any online server 
in this scenario if we panic the BBB server from the scalelite it does solve this issue of creating meetings on offline server but this only works for 4-5 times after that the only option we are left with recreating token orelse the scalelite continuously send users to offline server.

Scalelite Version: v1.0.3
BigBlueButton Version: v2.2.12
Running on EC2

Thank You

**Comment by farhatahmad** [comment]
duplicate #202
