### ISSUE TITLE
What about the Dial-In-Phone

### ISSUE THREAD

**Issue by premmohantyagi** [blindsidenetworks/scalelite#259]
What about the Dial-In-Phone
If we are sending the communication Email to the users to attend the meeting then we should be aware previously about the Server(Dial-In-Phone) where we will connect the meeting

**Comment by matiasilva** [comment]
Hi @premmohantyagi. Thanks for posting this. Could you go into more detail about this issue? Is it a feature request, a bug or?

**Comment by premmohantyagi** [comment]
@matiasilva What about the Dial-In-Phone, if will plane 3 Servers, we should use single Dial-In-Phone for all the servers or different-2 Phone for every server

**Comment by farhatahmad** [comment]
This has been posted and answered before
