### ISSUE TITLE
Got issue is scalelite 

### ISSUE THREAD

**Issue by premryp** [blindsidenetworks/scalelite#260]
I have setup the scalelite while accessing url I got this issue

Blocked host: domain.com
To allow requests to domain.com, add the following to your environment configuration:
config.hosts << "domain.com"

**Comment by matiasilva** [comment]
Hi @premryp. Please don't duplicate issues. We already saw your request in the other issue. If you could close this one, that'd be great.

**Comment by premryp** [comment]
Sure sorry for repeating it

**Comment by premryp** [comment]
closing it.
