### ISSUE TITLE
Modifying the playback.js of Scalelite

### ISSUE THREAD

**Issue by mbile** [blindsidenetworks/scalelite#263]
Hello everyone,

It was easy to change the text of playback.js and the BBB logo on the previous versions of Scalelite. After upgrading Scalelite to the latest version, I am unable to change the playback.js as well as the logo. Can someone please help?

Thanks in advance.

**Comment by pbdco** [comment]
Same here. Please help.

**Comment by farhatahmad** [comment]
I believe you mean BigBlueButton and not Scalelite, in which case, please open the issue in that repo instead
