### ISSUE TITLE
Scalelite-API.Service Failed 

### ISSUE THREAD

**Issue by zarniaungegov** [blindsidenetworks/scalelite#264]
Dear All,

I have created three bbb servers and one scalelite load balancer for our elearning platform. I can add bbb servers with http and they are enabled and online. However, the scalelite-api and scalelite-nginx services are not active ( running).

Please suggest me how to solve this issue

**Comment by farhatahmad** [comment]
Can you send some logs from the containers not working? `docker logs container_name` should work
