### ISSUE TITLE
Maximum number of bbb servers

### ISSUE THREAD

**Issue by namanmanish** [blindsidenetworks/scalelite#265]
Is there a limit to how many bbb server can scalelite support at once and how many maximum concurrent  requests can be handled with its minimum requirements(4 CPU core and 8 GB RAM)

**Comment by matiasilva** [comment]
The limit (if any) is probably beyond anything you can exhaust. I've heard of schools using Scalelite with 1000+ servers, so you should be fine. 

> concurrent requests

For the BBB servers, you should test this as every installation is operating under different conditions. For Scalelite, I suppose the answer is the same, any limit is probably too high for you to exhaust anyway.

**Comment by namanmanish** [comment]
Thanks a lot

**Comment by matiasilva** [comment]
Please close this issue then :-)
