### ISSUE TITLE
Unit scalelite.target could not be found

### ISSUE THREAD

**Issue by kodwick** [blindsidenetworks/scalelite#267]
Trying to check update for scaleLite, but when I enter systemctl restart scalelite.target, it answered that "Unit scalelite.target could not be found" 
ScaleLite was installed with docker as it described in  https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6

**Comment by farhatahmad** [comment]
Just do a `docker-compose down` `docker-compose up -d`
