### ISSUE TITLE
Scalelite Recording Not Showing

### ISSUE THREAD

**Issue by aliasghar004** [blindsidenetworks/scalelite#268]
> I tested it again, everything is OK ^_^
> There is no need to change anything.
> 
> @alkanis @schoasch10 @farhatahmad Thanks a lot for your help. 🌺

Hello, in my case mount the NFS everything perfect, send the recording package to the shared system as .tar but in the session management instance it does not show anything. https://g.dongee.com/E0ub09xb

If you know how to repair it, I appreciate it

root@scalelite:/mnt/scalelite-recordings/var/bigbluebutton/spool# pwd
/mnt/scalelite-recordings/var/bigbluebutton/spool
root@scalelite:/mnt/scalelite-recordings/var/bigbluebutton/spool# ll
total 122236
drwxrwxr-x  2 dongee 2000         7 may 26 00:28 ./
drwxr-xr-x+ 6 root   root         6 may 25 23:06 ../
-rw-r--r--+ 1    998  998    972800 may 25 23:22 8c31ee3fd3a2459acc1cbd05b75cc49a0e9c4fbb-1590448751003.tar
-rw-r--r--+ 1    998  998 121763840 may 25 23:08 988955c17af3a0cf89566a084919a3f1b77194db-1590439209537.tar
-rw-r--r--+ 1    998  998   1320960 may 25 23:40 b0656691bfc3b6d4f4fda6c2237497fcf02aef27-1590449831891.tar
-rw-r--r--+ 1    998  998    563200 may 26 00:21 b0656691bfc3b6d4f4fda6c2237497fcf02aef27-1590452209505.tar
-rw-r--r--+ 1    998  998    112640 may 26 00:22 d54fdcb69c8381d0766189b69a99594ec31e4dc6-1590452295542.tar

_Originally posted by @crkdown in https://github.com/blindsidenetworks/scalelite/issues/208#issuecomment-633752125_

**Comment by aliasghar004** [comment]
I am also stuck here from a week. 
spool directory got around 70GB but other directories are empty.

**Comment by matiasilva** [comment]
Without mentioning the issue, nobody can know what you were referencing except for maybe the three mentioned, even then people forget. Include the issue #

**Comment by aliasghar004** [comment]
Closing as Issue 269 is Same.
