### ISSUE TITLE
Recording now Showing on Front End 

### ISSUE THREAD

**Issue by aliasghar004** [blindsidenetworks/scalelite#269]
Dear All,
i have implemented Scalelite (single Host with Dockerized deployment) with 5 BigBlueButton using the  https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6.
everything working ok but i am having issue with Recording.
/mnt/scalelite-recordings/var/bigbluebutton/spool$ directory is full of .tar file.
other folders are empty. like published, unpublished, recording.

further i also got some database error on scalelite_recording_importer container as below

I, [2020-07-04T08:49:57.249550 #6]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824.tar
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/cursor.xml
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/slides_new.xml
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/shapes.svg
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/logo.png
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1593422239867/
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1593422239867/thumbnails/
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1593422239867/thumbnails/thumb-2.png
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1593422239867/thumbnails/thumb-1.png
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1593422239867/slide-1.png
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1593422239867/textfiles/
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1593422239867/textfiles/slide-2.txt
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1593422239867/textfiles/slide-1.txt
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1593422239867/slide-2.png
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/captions.json
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/video/
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/video/webcams.webm
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/panzooms.xml
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/deskshare.xml
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/presentation_text.json
presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/metadata.xml
I, [2020-07-04T08:49:57.268251 #6]  INFO -- : Found metadata file: presentation/bea8a430e6428fe5d25345f950c236498b0a70f5-1593422239824/metadata.xml
E, **[2020-07-04T08:49:57.280687 #6] ERROR -- : Failed to import recording: FATAL:  password authentication failed for user "postgres"**
**W, [2020-07-04T08:49:57.281022 #6]  WARN -- : /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/pg-1.2.2/lib/pg.rb:58:in `initialize': FATAL:  password authentication failed for user "postgres" (PG::ConnectionBad)**
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/pg-1.2.2/lib/pg.rb:58:in `new'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/pg-1.2.2/lib/pg.rb:58:in `connect'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:889:in `new_connection'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `checkout_new_connection'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:912:in `try_to_checkout_new_connection'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:873:in `acquire_connection'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:595:in `checkout'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:439:in `connection'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1121:in `retrieve_connection'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:238:in `retrieve_connection'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:206:in `connection'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:212:in `transaction'
	from /srv/scalelite/app/models/recording.rb:85:in `create_from_metadata_xml'
	from /srv/scalelite/lib/recording_importer.rb:24:in `block (3 levels) in import'
	from /srv/scalelite/lib/recording_importer.rb:21:in `each'
	from /srv/scalelite/lib/recording_importer.rb:21:in `block (2 levels) in import'
	from /usr/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
	from /usr/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	from /srv/scalelite/lib/recording_importer.rb:17:in `block in import'
	from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /srv/scalelite/lib/recording_importer.rb:16:in `import'
	from /srv/scalelite/lib/tasks/recordings.rake:16:in `block (4 levels) in <main>'
	from /srv/scalelite/lib/tasks/recordings.rake:15:in `each'
	from /srv/scalelite/lib/tasks/recordings.rake:15:in `block (3 levels) in <main>'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
	from /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'

**Comment by matiasilva** [comment]
You've opened two issues for the same problem it seems? Close one.

**Comment by aliasghar004** [comment]
yes, Closed other one

**Comment by dgidevwcc** [comment]
I'm getting this exact same issue. If you find a resolution, I'd be grateful if you updated this issue

**Comment by dgidevwcc** [comment]
Hi alisghar004

I think I've figured this out.  I've had to reset the postgre password

- Run docker ps
- Find the container ID relating to the postgre DB
- docker exec -it <CONTAINERID> bash
- psql -U postgres
- \password
Set the password to whatever you need
- exit
- exit
Ensure your .env file has the new password
- cd to your scalelite-run directory
- docker-compose down
- docker-compose up -d

**Comment by aliasghar004** [comment]
> Hi alisghar004
> 
> I think I've figured this out. I've had to reset the postgre password
> 
> * Run docker ps
> * Find the container ID relating to the postgre DB
> * docker exec -it  bash
> * psql -U postgres
> * \password
>   Set the password to whatever you need
> * exit
> * exit
>   Ensure your .env file has the new password
> * cd to your scalelite-run directory
> * docker-compose down
> * docker-compose up -d

Thats great,
let me also giva it a try. 
i will get back once done

**Comment by Schmidie64** [comment]
@dgidevwcc did you install scalelite via the "scalelite lazy deploment"-setup?

**Comment by aliasghar004** [comment]
Yes, installed through scalelite lazy deploment"-setup

**Comment by aliasghar004** [comment]
@dgidevwcc , thanks for guide, 
here is my reviews after following the above changing password.
1. recording immidiately started to published.
2. Only new recording are being published while old one are not publishing.
3. today after almost 4 days, recording publishing stopped. i reset the password again and the published folder is being modified with new recordings. but old recordings are not being published.

**Comment by Schmidie64** [comment]
in this case, your should check the docker-compose.yml file. By default the postgres port is open for the whole internet. I've already create a pull request to fix the issue but it's not merged currently. But you can fix it by your own. Here is the PR with the necessary changes: https://github.com/jfederico/scalelite-run/pull/1/files

**Comment by aliasghar004** [comment]
what could be the reason for not publishing old recordings? any workaround.

**Comment by aliasghar004** [comment]
so i am done with recording issue. all recording including month old recordings processed and showing up in Moodle.
here is what i done.

1: updated the password of postgres as mentioned above by @dgidevwcc 
2. Updated .env file and added POSTGRES_USER=xxxxx and POSTGRES_PASSWORD=xxx

further i am still facing issue in recording if i docker-compose down and again docker-compose up, i again get postgres error.
so i reset the password again in postgres container and all recording started publishing.

i think it could be a bug due to which postgress password needs to reset after restarting container.

closing the issue and will wait for its solution after any update.
