### ISSUE TITLE
How to use SSL without Let's Encrypt

### ISSUE THREAD

**Issue by emanuelhaine** [blindsidenetworks/scalelite#275]
Hello,

Where I work we have a paid SSL certificate and we'd like to know how to use the SSL certificate feature without Let's Encrypt.

**Comment by matiasilva** [comment]
Hi, this is an issue for the forums: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton

**Comment by LoicBonavent** [comment]
Hello,

In your case, you can follow these instructions (see French documentation : https://www.memoinfo.fr/tutoriels-linux/configurer-lets-encrypt-apache/) :
- create a live directory and assign the rights.
For example :
_sudo mkdir /home/user/ssl/live/scalelite.domain.com -p
sudo chown user:2000 /home/user/ssl -R_

- put your certificate's private key in the directory _/home/user/ssl/live/scalelite.domain.com_, and rename it as _privkey.pem_

- put the concatenation of all certificates in the same directory, and rename it as _fullchain.prem_

If you use **Nginx** or **Apache >= 2.4.8**, it's enough.
If you use **Apache < 2.4.8**, you need to add _cert.pem_ (server certificate) and _chain.pem_ (other certificates, except the server certificate).

- secure the key
_sudo chmod 0660 /home/user/ssl/live/scalelite.domain.com/privkey.pem_

- restart services and check status
_sudo systemctl restart scalelite.target
sudo systemctl status scalelite-recording-importer.service_

I hope this helps.

Loïc
