### ISSUE TITLE
How to increase speed of scalelite-recording-importer?

### ISSUE THREAD

**Issue by victorvoltarelli** [blindsidenetworks/scalelite#276]
Hello guys.

Im trying to find a way to increase speed of scalelite-recording-importer, actually the spool directory of my storage dir have more than 2k of .tar files, in 8 hours scalelite just process like 40 or 50 files.

Anyone know how to speed this up?

Thank you.

**Comment by defnull** [comment]
The importer does not do much. It just unpacks the tar archive to a temporary directory, reads the xml file, then moves some files around. Most of that is IO bound, so make sure your network file system is faster than a pendrive and everything should be fine.

I'd guess you were hit by #239. If anything goes wrong while importing a recording (e.g. database down), then the tar-file will not be touched again until you restart the importer.

**Comment by farhatahmad** [comment]
As mentioned above, the importer doesn't really do anything other than tar/untar and move files. You're probably running into other issues related to the importer

**Comment by bayden10** [comment]
@farhatahmad  yes, in my case I switched from RSYNC to shared NFS mount no further delays.
