### ISSUE TITLE
scalelite-api.service: Failed with result 'exit-code' 

### ISSUE THREAD

**Issue by rexon07** [blindsidenetworks/scalelite#277]
● scalelite-api.service - Scalelite API
   Loaded: loaded (/etc/systemd/system/scalelite-api.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-07-20 11:07:51 CEST; 1s ago
  Process: 3267 ExecStart=/usr/bin/docker run --name scalelite-api --env-file /etc/default/scalelite --network scalelite --mount type=bind,source=${SCALELITE_RECORDING_
  Process: 3240 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-api (code=exited, status=0/SUCCESS)
  Process: 3219 ExecStartPre=/usr/bin/docker rm scalelite-api (code=exited, status=0/SUCCESS)
  Process: 3193 ExecStartPre=/usr/bin/docker kill scalelite-api (code=exited, status=1/FAILURE)
 Main PID: 3267 (code=exited, status=1/FAILURE)

Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3267]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/configuration.rb:246:in `app'
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3267]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/runner.rb:155:in `load_and_bind'
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3267]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/single.rb:98:in `run'
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3267]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3267]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cli.rb:80:in `run'
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3267]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/bin/puma:10:in `<top (required)>'
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3267]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3267]:   /srv/scalelite/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
Jul 20 11:07:51 Ubuntu-1804-bionic-64-minimal systemd[1]: scalelite-api.service: Main process exited, code=exited, status=1/FAILURE
Jul 20 11:07:51 Ubuntu-1804-bionic-64-minimal systemd[1]: scalelite-api.service: Failed with result 'exit-code'.

● scalelite-nginx.service - Scalelite Nginx
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-07-20 11:07:48 CEST; 4s ago
  Process: 3319 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
  Process: 3306 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=0/SUCCESS)
  Process: 3268 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
 Main PID: 3428 (docker)
    Tasks: 13 (limit: 4915)
   CGroup: /system.slice/scalelite-nginx.service
           └─3428 /usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount type=bind,s

Jul 20 11:07:48 Ubuntu-1804-bionic-64-minimal docker[3319]: v1-nginx: Pulling from blindsidenetwks/scalelite
Jul 20 11:07:48 Ubuntu-1804-bionic-64-minimal docker[3319]: Digest: sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxx
Jul 20 11:07:48 Ubuntu-1804-bionic-64-minimal docker[3319]: Status: Image is up to date for blindsidenetwks/scalelite:v1-nginx
Jul 20 11:07:48 Ubuntu-1804-bionic-64-minimal docker[3319]: docker.io/blindsidenetwks/scalelite:v1-nginx
Jul 20 11:07:48 Ubuntu-1804-bionic-64-minimal systemd[1]: Started Scalelite Nginx.
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3428]: Startup script was run as init, re-execing using tini.
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3428]: Generating templated nginx configuration...
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3428]: Using SSL configuration template.
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3428]: Starting nginx periodic reload process...
Jul 20 11:07:50 Ubuntu-1804-bionic-64-minimal docker[3428]: Starting nginx...

**Comment by rexon07** [comment]
i ran the below command : "systemctl restart scalelite.target" and then run "systemctl status scalelite-nginx.service"

Now the error that iam getting :

● scalelite-nginx.service - Scalelite Nginx
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-07-17 15:04:06 CEST; 10s ago
  Process: 26082 ExecStart=/usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount ty
  Process: 26012 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
  Process: 25999 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=1/FAILURE)
  Process: 25962 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
 Main PID: 26082 (code=exited, status=125)

Jul 17 15:04:03 Ubuntu-1804-bionic-64-minimal docker[25999]: Error: No such container: scalelite-nginx
Jul 17 15:04:05 Ubuntu-1804-bionic-64-minimal docker[26012]: v1-nginx: Pulling from blindsidenetwks/scalelite
Jul 17 15:04:05 Ubuntu-1804-bionic-64-minimal docker[26012]: Digest: sha256:fb80a8288b7a9d4b99daf938761d367f071621915ab696cb36e110be43e9c693
Jul 17 15:04:05 Ubuntu-1804-bionic-64-minimal docker[26012]: Status: Image is up to date for blindsidenetwks/scalelite:v1-nginx
Jul 17 15:04:05 Ubuntu-1804-bionic-64-minimal docker[26012]: docker.io/blindsidenetwks/scalelite:v1-nginx
Jul 17 15:04:05 Ubuntu-1804-bionic-64-minimal systemd[1]: Started Scalelite Nginx.
Jul 17 15:04:06 Ubuntu-1804-bionic-64-minimal docker[26082]: docker: Error response from daemon: driver failed programming external connectivity on endpoint scalelite-n
Jul 17 15:04:06 Ubuntu-1804-bionic-64-minimal docker[26082]: time="2020-07-17T15:04:06+02:00" level=error msg="error waiting for container: context canceled"
Jul 17 15:04:06 Ubuntu-1804-bionic-64-minimal systemd[1]: scalelite-nginx.service: Main process exited, code=exited, status=125/n/a
Jul 17 15:04:06 Ubuntu-1804-bionic-64-minimal systemd[1]: scalelite-nginx.service: Failed with result 'exit-code'.
lines 1-19/19 (END)

**Comment by rexon07** [comment]
hi I executed the below command :
systemctl restart scalelite.target" and then run "systemctl status scalelite-nginx.service

now the error is :

● scalelite-nginx.service - Scalelite Nginx
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-07-17 15:08:55 CEST; 3s ago
  Process: 26491 ExecStart=/usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount ty
  Process: 26386 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
  Process: 26373 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=0/SUCCESS)
  Process: 26335 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
 Main PID: 26491 (code=exited, status=125)

Jul 17 15:08:52 Ubuntu-1804-bionic-64-minimal docker[26373]: scalelite-nginx
Jul 17 15:08:53 Ubuntu-1804-bionic-64-minimal docker[26386]: v1-nginx: Pulling from blindsidenetwks/scalelite
Jul 17 15:08:53 Ubuntu-1804-bionic-64-minimal docker[26386]: Digest: sha256:fb80a8288b7a9d4b99daf9387d367f07162b36e110be43e9c693
Jul 17 15:08:53 Ubuntu-1804-bionic-64-minimal docker[26386]: Status: Image is up to date for blindsidenetwks/scalelite:v1-nginx
Jul 17 15:08:53 Ubuntu-1804-bionic-64-minimal docker[26386]: docker.io/blindsidenetwks/scalelite:v1-nginx
Jul 17 15:08:53 Ubuntu-1804-bionic-64-minimal systemd[1]: Started Scalelite Nginx.
Jul 17 15:08:55 Ubuntu-1804-bionic-64-minimal docker[26491]: docker: Error response from daemon: driver failed programming external connectivity on endpoint scalelite-n
Jul 17 15:08:55 Ubuntu-1804-bionic-64-minimal docker[26491]: time="2020-07-17T15:08:55+02:00" level=error msg="error waiting for container: context canceled"
Jul 17 15:08:55 Ubuntu-1804-bionic-64-minimal systemd[1]: scalelite-nginx.service: Main process exited, code=exited, status=125/n/a
Jul 17 15:08:55 Ubuntu-1804-bionic-64-minimal systemd[1]: scalelite-nginx.service: Failed with result 'exit-code'.

**Comment by rexon07** [comment]
I followed the instructions in one of the threads
: https://groups.google.com/g/bigbluebutton-dev/c/wV7r5Wnw6Ho

 scalelite-nginx.service - Scalelite Nginx
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-07-17 15:32:29 CEST; 10s ago
  Process: 27349 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
  Process: 27336 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=0/SUCCESS)
  Process: 27295 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
 Main PID: 27460 (docker)
    Tasks: 13 (limit: 4915)
   CGroup: /system.slice/scalelite-nginx.service
           └─27460 /usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443 --mount type=bind,

Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal docker[27349]: v1-nginx: Pulling from blindsidenetwks/scalelite
Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal docker[27349]: Digest: sha256:xxxxxx
Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal docker[27349]: Status: Image is up to date for blindsidenetwks/scalelite:v1-nginx
Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal docker[27349]: docker.io/blindsidenetwks/scalelite:v1-nginx
Jul 17 15:32:29 Ubuntu-1804-bionic-64-minimal systemd[1]: Started Scalelite Nginx.
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Startup script was run as init, re-execing using tini.
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Generating templated nginx configuration...
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Using SSL configuration template.
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Starting nginx periodic reload process...
Jul 17 15:32:31 Ubuntu-1804-bionic-64-minimal docker[27460]: Starting nginx...

Now the status is active but still an error:
scalelite-nginx (code=exited, status=1/FAILURE)

is ideal or anything need be fixed?
thanks

**Comment by farhatahmad** [comment]
Whats the output of `docker logs scalelite-api`
