### ISSUE TITLE
 600 concurrent participants in one BBB session

### ISSUE THREAD

**Issue by cod3r0k** [blindsidenetworks/scalelite#279]
Hi, the scalelite tries to balance each BBB server. But does it satisfy my needs? 
I want to create a session with 600 up to 800 participants in one BBB session. does it handle it? what do you suggest me?

**Comment by matiasilva** [comment]
Hi, that's impossible. Scalelite is meant to distribute high loads of users onto different BBB servers, it is not meant to amplify the capacity of one server in one session. The maximum recommended limit for users is 100, anything above is sort of a "you are at your own risk" and your call may crash if you do. That said, I have seen some people manage 200 but by heavily reducing features like only allowing 1 webcam.

**Comment by cod3r0k** [comment]
> Hi, that's impossible. Scalelite is meant to distribute high loads of users onto different BBB servers, it is not meant to amplify the capacity of one server in one session. The maximum recommended limit for users is 100, anything above is sort of a "you are at your own risk" and your call may crash if you do. That said, I have seen some people manage 200 but by heavily reducing features like only allowing 1 webcam.

Thank you so much. Do you have any open source alternative option for that amount of participants?

**Comment by matiasilva** [comment]
By "open source" I'm assuming you mean free :-), and no there isn't. In any case, I think you're looking for some live streaming platform like YouTube or Twitch to do what you need.
