### ISSUE TITLE
Can scalelite balance users over a meeting?

### ISSUE THREAD

**Issue by aloisogomes** [blindsidenetworks/scalelite#280]
Yes i know, questions must be placed on StackOverflow, but scalelite isn't hot tagged and this question can lead others understand better if scalelite can help them.

Imagine two servers running bbb and a third just running scalelite. Ok everything ready! 

Server 1 - has Meeting1 - Scalelite deliver firsts attendees to it and admin want share it job to server 2 handle new joins

Finally my question is: Two servers can operate together as one: Meeting1 handled by two or more servers, and attendee A under server 1 interact with attendee B under server 2?

**Comment by matiasilva** [comment]
Hi, that's impossible due to the nature of how BBB works. Also, as far as I'm aware, I don't think there's an official stackoverflow for BBB so you should post stuff like this in the mailing lists :)

**Comment by aloisogomes** [comment]
@matiasilva Thanks for answer, =D
