### ISSUE TITLE
Error response from daemon: invalid mount config for type "bind": bind source path does not...

### ISSUE THREAD

**Issue by cod3r0k** [blindsidenetworks/scalelite#281]
Hi, it occurs this problem. Is there any mistake?

When I want to run `systemctl status scalelite-api.service scalelite-nginx.service` in https://github.com/blindsidenetworks/scalelite/blob/ba89f22b6050b80499311c730da261eed97ff1fb/docker-README.md#web-frontend-scalelite-api-and-scalelite-nginx , it will be depicted as below:

```
   Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-07-19 02:41:10 +0430; 4min 24s ago
  Process: 16731 ExecStart=/usr/bin/docker run --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 8
  Process: 16474 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
  Process: 16450 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=1/FAILURE)
  Process: 16430 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
 Main PID: 16731 (code=exited, status=125)

Jul 19 02:41:09 scl1 docker[16474]: a87bd868317f: Pull complete
Jul 19 02:41:10 scl1 docker[16474]: Digest: sha256:fb80a8288b7a9d4b99daf938761d367f071621915ab696cb36e110be43e9c693
Jul 19 02:41:10 scl1 docker[16474]: Status: Downloaded newer image for blindsidenetwks/scalelite:v1-nginx
Jul 19 02:41:10 scl1 docker[16474]: docker.io/blindsidenetwks/scalelite:v1-nginx
Jul 19 02:41:10 scl1 systemd[1]: Started Scalelite Nginx.
Jul 19 02:41:10 scl1 docker[16731]: docker: Error response from daemon: invalid mount config for type "bind": bind source path does not
Jul 19 02:41:10 scl1 docker[16731]: See 'docker run --help'.
Jul 19 02:41:10 scl1 systemd[1]: scalelite-nginx.service: Main process exited, code=exited, status=125/n/a
Jul 19 02:41:10 scl1 systemd[1]: scalelite-nginx.service: Unit entered failed state.
Jul 19 02:41:10 scl1 systemd[1]: scalelite-nginx.service: Failed with result 'exit-code'.


```

**Comment by rexon07** [comment]
looks like issue with ssl path check this readme : https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md

**Comment by cod3r0k** [comment]
> looks like issue with ssl path check this readme : https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md

Thanks @rexon07 , But I don't know how to create ssl certificate in server which not have standalone nginx for connecting to letsencrypt server in cerbot.

You mean, I install nginx and install certificate and uninstall nginx ? (because we have another nginx in docker of scalelite, isn't it?)

**Comment by rexon07** [comment]
when i got this issue i installed nginx and installed the ssl certificate. after which i stopped the installed nginx. which worked for me.

**Comment by cod3r0k** [comment]
> when i got this issue i installed nginx and installed the ssl certificate. after which i stopped the installed nginx. which worked for me.

Thanks, do you do this for each month? (because each month it must be update)
