### ISSUE TITLE
BBB server is not online, it is offline?

### ISSUE THREAD

**Issue by cod3r0k** [blindsidenetworks/scalelite#282]
Hi, How could we change our server to be online?

You know, we use our BBB server with Greenlight and also API but it is not available in scalelite....

  STATE    STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS
***SVR03*****    enabled  offline         0      0                0       0
***SVR02*****  enabled  offline         0      0                0       0
***SVR01*****  enabled  offline         0      0                0       0

**Comment by matiasilva** [comment]
@cod3r0k, please don't use the issue tracker for posting support questions. You're better off in the mailing lists, follow these instructions: https://docs.bigbluebutton.org/2.2/getting-help.html.
