### ISSUE TITLE
Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by rexon07** [blindsidenetworks/scalelite#284]
Hi, i have set up all docker containers, But while checking the status of systemctl status scalelite-poller.service  getting the following error :
 ● scalelite-poller.service - Scalelite Meeting Status Poller
   Loaded: loaded (/etc/systemd/system/scalelite-poller.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-07-21 08:29:43 CEST; 2h 30min ago
 Main PID: 9694 (docker)
    Tasks: 14 (limit: 4915)
   CGroup: /system.slice/scalelite-poller.service
           └─9694 /usr/bin/docker run --name scalelite-poller --env-file /etc/default/scalelite --network scalelite blindsidenetwks/scalelite:v1-poller

Jul 21 10:55:56 Ubuntu-1804-bionic-64-minimal docker[9694]: W, [2020-07-21T08:55:56.277764 #6]  WARN -- : Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUS
Jul 21 10:56:56 Ubuntu-1804-bionic-64-minimal docker[9694]: D, [2020-07-21T08:56:56.302668 #6] DEBUG -- : Polling meetings
Jul 21 10:56:56 Ubuntu-1804-bionic-64-minimal docker[9694]: D, [2020-07-21T08:56:56.303018 #6] DEBUG -- : Polling servers
Jul 21 10:56:56 Ubuntu-1804-bionic-64-minimal docker[9694]: W, [2020-07-21T08:56:56.304549 #6]  WARN -- : Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUS
Jul 21 10:57:56 Ubuntu-1804-bionic-64-minimal docker[9694]: D, [2020-07-21T08:57:56.365209 #6] DEBUG -- : Polling meetings
Jul 21 10:57:56 Ubuntu-1804-bionic-64-minimal docker[9694]: D, [2020-07-21T08:57:56.365553 #6] DEBUG -- : Polling servers
Jul 21 10:57:56 Ubuntu-1804-bionic-64-minimal docker[9694]: W, [2020-07-21T08:57:56.367763 #6]  WARN -- : Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUS
Jul 21 10:58:56 Ubuntu-1804-bionic-64-minimal docker[9694]: D, [2020-07-21T08:58:56.409915 #6] DEBUG -- : Polling meetings
Jul 21 10:58:56 Ubuntu-1804-bionic-64-minimal docker[9694]: D, [2020-07-21T08:58:56.410276 #6] DEBUG -- : Polling servers
Jul 21 10:58:56 Ubuntu-1804-bionic-64-minimal docker[9694]: W, [2020-07-21T08:58:56.411955 #6]  WARN -- : Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUS
~
i have installed postgres,scalelite and redis on the same server. 
my redis url is : REDIS_URL=redis://127.0.0.1:6379

please let me know what should be done

**Comment by farhatahmad** [comment]
The IP address here is incorrect. Since the connection is made from inside the docker container, `127.0.0.1` refers to the docker container itself, and not the host machine
