### ISSUE TITLE
I need 10 rooms with 2000 participants in each at the same time

### ISSUE THREAD

**Issue by MostafaHabibi** [blindsidenetworks/scalelite#285]
Hii,

I need 10 rooms with 2000 participants in each at the same time so is it good to one installation on one big server or I should have multiple installation with different rooms in each.
can i use scalelite to handle this rooms with 2000 participants ? how can to do that with scalelite??
Which would be better?

Please help me!

If I need only one server then what should be the configuration?

**Comment by matiasilva** [comment]
Hi, you can find this information on https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements in addition to the FAQs. It is recommended that you keep the participant count for BBB rooms under 100. 2000 would certainly not do.
