### ISSUE TITLE
Re: Scalelite Import successful but shows as " Recording not found " 

### ISSUE THREAD

**Issue by francisrosario** [blindsidenetworks/scalelite#286]
https://scalelite.dlaportal.net/playback/presentation/2.0/playback.html?meetingId=7a6358b85205eceeba9029a48287a0d4ce8ba2cf-1595354699245

It was sucessfully imported from a tar file, but it doesn''t reflect from the frontend it shows like this.
[https://imgur.com/a/IcOgHOP](url)

**Comment by francisrosario** [comment]
Here my .env

### Required by scalelite-api
SECRET_KEY_BASE=HIDDEEEEEN
LOADBALANCER_SECRET=HIDDEEEEEN
#
### Required by scalelite-api and scalelite-poller
# REDIS_URL=
#
### Required by scalelite-api and scalelite-recording-importer
# DATABASE_URL=
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
#
### Required by scalelite-nginx (only When using SSL)
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly
URL_HOST=scalelite.dlaportal.net

**Comment by ferasmonther** [comment]
@francisrosario if its working for you can you help me?
Please note that I have installed the scalelite but recording are not showing
The recording is there on the BBB server but not transferred back through scalelite.
I followed the documentation however it didn’t work.

I need help in fixing this problem

**Comment by francisrosario** [comment]
> @francisrosario if its working for you can you help me?
> Please note that I have installed the scalelite but recording are not showing
> The recording is there on the BBB server but not transferred back through scalelite.
> I followed the documentation however it didn’t work.
> 
> I need help in fixing this problem

It's working fine already using NFS, Kindly please do some research in utilizing NFS in Scalelite Importer. Thanks!

**Comment by etemam** [comment]
Hi 

Same problem here. Import of recording is working but unable to playback

Sincerely

**Comment by matiasilva** [comment]
Make sure you followed the installation instructions correctly.
