### ISSUE TITLE
Some Meetings are forwarded to Bigbluebutton Servers which has been removed from Scalelite.

### ISSUE THREAD

**Issue by aliasghar004** [blindsidenetworks/scalelite#290]
Hi All,

i have removed some bigbluebutton server from Scalelite using 
" docker exec -i scalelite-api bundle exec rake servers:remove[ID]  "
and added new servers and they are working ok, but the issue started when i checked some logs of poller Container and some users are complaing that they don't redirect to BBB Server instead they are redirected to Scalelite.example.com and failed to join meeting
below are some of warning logs

W, [2020-08-05T08:52:29.491784 #3256]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-9153-15517 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
W, [2020-08-05T08:52:29.492816 #3256]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-10415-22780 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
W, [2020-08-05T08:52:29.563663 #3256]  WARN -- : Failed to check meeting id=9cc72e7bc555427e6c5279893216b737dc367655-7532-34271 status: Couldn't find Server with id=6271e874-e4e7-4d37-87d7-00d198b5d252
W, [2020-08-05T08:52:30.173262 #3256]  WARN -- : Failed to check meeting id=73432951307fb7dbd16729a3eab7b6e6eecf2906-7466-5085 status: Couldn't find Server with id=6271e874-e4e7-4d37-87d7-00d198b5d252
W, [2020-08-05T08:52:30.174131 #3256]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-8495-8931 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
W, [2020-08-05T08:52:30.766513 #3256]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-9871-17350 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
W, [2020-08-05T08:52:31.003836 #3256]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-8546-9442 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
W, [2020-08-05T08:52:31.392009 #3256]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-9187-15859 status: **Couldn't find Server with id**=b502ef7b-1525-4c30-b732-ea4dc659bd44
W, [2020-08-05T08:52:32.372563 #3256]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-9122-15207 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
W, [2020-08-05T08:52:34.277931 #3256]  WARN -- : Failed to check meeting id=a43ff2db24a8e86e79a65c835466d1c68ac44f90-7417-34270 status: Couldn't find Server with id=dd576cb2-1ce0-4598-b7e6-08dd3b8e2e93
W, [2020-08-05T08:52:34.870768 #3256]  WARN -- : Failed to check meeting id=71e3e87e3a1ad7b88ccdc3d181a3cb3553d2c151-7386-16280 status: Couldn't find Server with id=dd576cb2-1ce0-4598-b7e6-08dd3b8e2e93

**is there a way i can remove Server ID permanently which are already removed.**

**i also checked that we need to Panic the Server before removing from the cluster so that existing meetings could redirect to New Servers but how can i proceed now as server is already been removed and new Servers are added ?**

Thanks.

**Comment by aakatev** [comment]
Idk if this the answer you are looking for, but you can always remove the servers directly from redis if you have troubles doing so on the application layer.

**Comment by aliasghar004** [comment]
@aakatev can you please elaborate a little as i have no idea about Redis?

**Comment by aakatev** [comment]
The poller uses redis to store data about the pool of bbb servers. Since you run docker in the container, I assume you run redis in a container too. If you run shell in the redis container it most likely has `redis-cli` installed.
For detailed information on redis usge refer to [the official documentation](https://redis.io/topics/quickstart).

**Comment by aliasghar004** [comment]
So now i have found the way to remove the Server from Redis. which are actually creating problem.
i just want to confirm that is there any consequences of removing the Server key directly from Redis ? as this is a production server and a lot of meetings are in progress these days.

**Comment by aliasghar004** [comment]
Removed server from redis manually but still getting same warnings.

**Comment by aliasghar004** [comment]
scalelite-poller                | 2020-08-07T11:11:02.661550000Z W, [2020-08-07T11:11:02.661196 #6]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-10257-21210 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
scalelite-poller                | 2020-08-07T11:11:02.661936000Z W, [2020-08-07T11:11:02.661687 #6]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-9187-15859 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
scalelite-poller                | 2020-08-07T11:11:02.720948000Z W, [2020-08-07T11:11:02.720609 #6]  WARN -- : Failed to check meeting id=a43ff2db24a8e86e79a65c835466d1c68ac44f90-7417-34270 status: Couldn't find Server with id=dd576cb2-1ce0-4598-b7e6-08dd3b8e2e93
scalelite-poller                | 2020-08-07T11:11:04.416549000Z W, [2020-08-07T11:11:04.416265 #6]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-10261-21250 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
scalelite-poller                | 2020-08-07T11:11:04.416841000Z W, [2020-08-07T11:11:04.416607 #6]  WARN -- : Failed to check meeting id=d5278a34344c2fbc67b5907c62f111d267a5c135-7733-16229[10971] status: Couldn't find Server with id=6271e874-e4e7-4d37-87d7-00d198b5d252
scalelite-poller                | 2020-08-07T11:11:04.908378000Z W, [2020-08-07T11:11:04.906766 #6]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-10415-22780 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
scalelite-poller                | 2020-08-07T11:11:05.322543000Z W, [2020-08-07T11:11:05.321990 #6]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-8546-9442 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
scalelite-poller                | 2020-08-07T11:11:05.485165000Z W, [2020-08-07T11:11:05.484767 #6]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-9122-15207 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
scalelite-poller                | 2020-08-07T11:11:05.542317000Z W, [2020-08-07T11:11:05.541968 #6]  WARN -- : Failed to check meeting id=71e3e87e3a1ad7b88ccdc3d181a3cb3553d2c151-7386-16280 status: Couldn't find Server with id=dd576cb2-1ce0-4598-b7e6-08dd3b8e2e93
scalelite-poller                | 2020-08-07T11:11:05.927333000Z W, [2020-08-07T11:11:05.926938 #6]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-9153-15517 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
scalelite-poller                | 2020-08-07T11:11:07.343397000Z W, [2020-08-07T11:11:07.342736 #6]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-8495-8931 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
scalelite-poller                | 2020-08-07T11:11:07.394227000Z W, [2020-08-07T11:11:07.393741 #6]  WARN -- : Failed to check meeting id=9cc72e7bc555427e6c5279893216b737dc367655-7532-34271 status: Couldn't find Server with id=6271e874-e4e7-4d37-87d7-00d198b5d252
scalelite-poller                | 2020-08-07T11:11:07.395247000Z W, [2020-08-07T11:11:07.394269 #6]  WARN -- : Failed to check meeting id=174a8a6af3a75ba88cdb489a8817d6315cc9164c-9871-17350 status: Couldn't find Server with id=b502ef7b-1525-4c30-b732-ea4dc659bd44
scalelite-poller                | 2020-08-07T11:11:07.569103000Z W, [2020-08-07T11:11:07.568738 #6]  WARN -- : Failed to check meeting id=73432951307fb7dbd16729a3eab7b6e6eecf2906-7466-5085 status: Couldn't find Server with id=6271e874-e4e7-4d37-87d7-00d198b5d252

**Comment by aakatev** [comment]
So, your error is coming from [this part](https://github.com/blindsidenetworks/scalelite/blob/4ada1ec09dc31dd65808805ef7c62fc04f64131e/lib/tasks/poll.rake#L81-L105). You removed the servers, butt the meetings associated with it are still stored in redis. You can remove them similarly to [how it is done in the Scalelite](https://github.com/blindsidenetworks/scalelite/blob/4ada1ec09dc31dd65808805ef7c62fc04f64131e/app/models/meeting.rb#L64-L65), but manually.

Also, I re-read your problem description:
>...some users are complaing that they don't redirect to BBB Server instead they are redirected to Scalelite.example.com and failed to join meeting...
Issue with poller is not related to the problem your user experience. Do you have any logs on the api?

**Comment by aliasghar004** [comment]
Thanks @aakatev  for guidance, i have resolved the issue.
below are steps i followed

docker exec -it redis /bin/sh
redis-cli
KEYS *
DEL [KEY]
then removed the keys which were related to old removed servers and meetings.

all warning are gone now.

for other issue"redirecting to scalelite" i will collect the logs and will create a seperate issue.
Thanks so much
