### ISSUE TITLE
Lower priority for servers that are processing recordings / dynamic value

### ISSUE THREAD

**Issue by ryprfpryr** [blindsidenetworks/scalelite#291]
[ENHANCEMENT REQUEST]

**Scalelite should take into consideration the CPU load AND/or if the servers are processing recordings, in order to dinamically set a priority on loadMultiplier for each one, so Scalelite can detect which servers are processing recordings and bring them down on priority dinamically.**

Apart from:

```
Number of meetings
Number of users
Number of streams

```
Scalelite should take into consideration also:

`Is Recording_processing= true or false?`

If true, Scalilite lowers the priority value on loadMultiplier dinamically.

The recording queue value could be sent by this command on each server:
`echo $(ls -la /var/bigbluebutton/recording/status/sanity | wc -l )`

If $>0 then tell Scalelite this server is Recording_processing=true.

Any sugestions?

Related to #99

**Comment by farhatahmad** [comment]
I could see the benefit of this, but it's a pretty tricky solution that begins with BigBlueButton making `recording_processing?` a value that can be read through an API call (which is currently not possible). Until that's done, Scalelite can't really do anything

**Comment by ryprfpryr** [comment]
Hi @farhatahmad , in the meantime as a workaround we could use this in a "is_recording?_check" script:

`echo $(ls -la /var/bigbluebutton/recording/status/sanity | wc -l )`

If the number is >3 then, recording_processing=true.

**Comment by matiasilva** [comment]
This would have to be run on each server though and then somehow relayed back to Scalelite, and adding it to an API response would make the most sense.

Also, why 3?

**Comment by ryprfpryr** [comment]
> This would have to be run on each server though and then somehow relayed back to Scalelite, and adding it to an API response would make the most sense.

I know the ideal solution would be trhough API, but maybe we could use this workaround meanwhile until we have this API call developed.

> Also, why 3?

For some reason BBB always throws 3 even when there's no recordings processing when using the given command. So, if the given output is e.g. 5 it means there are 2 recordings on processing queue. I invite you to try it yourself, it works like a charm.

**Comment by amalrails** [comment]
@ryprfpryr have you asked for this feature in BBB forum?
