### ISSUE TITLE
How Can Speed UP & Optimizing NFS

### ISSUE THREAD

**Issue by mailalaki** [blindsidenetworks/scalelite#293]
hi, how can i speed up & optimizing nfs for faster import recordings? It's too slow for me!

**Comment by matiasilva** [comment]
Look at your pipeline, what are the weak points? Are your machines all internally connected?

**Comment by mailalaki** [comment]
no, its external. the scalelite server is in the Netherlands and the nfs server is in Iran. i think the long distance between them and the presence of many intermediaries has slowed down the connection. it's true?

**Comment by matiasilva** [comment]
Sounds like it.
