### ISSUE TITLE
Transfer selected exiting recordings to scalelite

### ISSUE THREAD

**Issue by mailalaki** [blindsidenetworks/scalelite#294]
Hi, Is it possible to transfer selected exiting recordings to Scalelite server instead of batch transferring all recordings via `scalelite_batch_import.sh` script?

**Comment by mailalaki** [comment]
Oh, I found the solution:
`sudo -n -u bigbluebutton ruby ./post_publish/scalelite_post_publish.rb -m "$record_id"`.

**Comment by matiasilva** [comment]
Close the issue then please.

**Comment by mailalaki** [comment]
ok, sorry
