### ISSUE TITLE
API-Error (500) after deleting servers with meetings

### ISSUE THREAD

**Issue by werk21** [blindsidenetworks/scalelite#295]
After deleting servers with running (or stale) meetings the API gives an 500 error:

GET /bigbluebutton/api/getRecordings?meetingID=XXXXXX&checksum=YYYYYY HTTP/1.1" 500 131 "-" "Ruby" "-"

Are there maybe orphaned infos in the database and SL runs in an error while trying to request the deleted server?

best regards ky.

**Comment by aakatev** [comment]
Have looked at the logs?

**Comment by farhatahmad** [comment]
You really shouldn't delete a server with meetings on it without doing a panic first. You'll need to manually go into Redis and delete the meetings

**Comment by werk21** [comment]
Then see https://github.com/blindsidenetworks/scalelite/issues/235 for deleting meetings from database.

We had this issue after panic the server and get this error described here https://github.com/blindsidenetworks/scalelite/issues/218 and https://github.com/blindsidenetworks/scalelite/issues/179
