### ISSUE TITLE
No servers are currently available

### ISSUE THREAD

**Issue by human-bieng** [blindsidenetworks/scalelite#296]
Hello there 
I have installed Scalelite successfully & i added two bbb servers
`<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
<build>v1.0.5</build>
</response>`
Scalelite status shows that both bbb servers enabled & active as shown 
`Running via Spring preloader in process 7577
id: 6d3617c2-699d-4ba5-84c0-b7f5288d3f72
        url: https://demo.domain1.com/bigbluebutton/api
        secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        enabled
        load: 0.0
        load multiplier: 1.0
        online
id: 90d1781c-f09c-4a0e-9b35-1dcda4a25847
        url: https://demo2.domain.com/bigbluebutton/api
        secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        enabled
        load: 0.0
        load multiplier: 1.0
        online`
But when test to connect to scalelite server directly i couldnt be able to create a new room & i got the following warning messages from "scalelite-api" docker container as shown 
`W, [2020-08-15T15:06:04.297396 #6]  WARN -- : [c09863c5-c1b4-4480-b215-5ff49af00444] No servers are currently available`
I have tested creating room from api-mate & from wordpress BBB admin plugin but both are not working 
I uses scalelite URL_HOST & LOADBALANCER_SECRET when i try to connect to scalelite
Also if i tested to enter to any server directly the number of users get incremented as shown 
`./bin/rake status
        HOSTNAME         STATE   STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS
 demo.domain.com       enabled  online         1      1                1       0
 demo2.domain.com      enabled  online         1      1                1       0`
I wasted more than one day without success to find how to solve this issue 
No firewall enabled because it is a testing architecture & i have scalelite on one vps & postgresql & redis on second vps & nfs on third vps
What could be the reason for this ? Where else i should search ? 
Any help will be appreciated
Thanks in advance

**Comment by aakatev** [comment]
When you run `./bin/rake servers`, are servers status online?
If not, one obvious reason is url was not provided in the correct form.

**Comment by human-bieng** [comment]
> 
> 
> When you run `./bin/rake servers`, are servers status online?
> If not, one obvious reason is url was not provided in the correct form.

Hello brother 
Yeah servers are online & enabled 
Also if i connect directly to bbb servers without scalelite the status shows that users are exists in bbb rooms
Which means that Scalelite completey working but couldnt create room when using it
So what could be the problem ?

**Comment by aakatev** [comment]
Any more logs from scalelite api or other scaleleite containers?

**Comment by human-bieng** [comment]
The problem get solved by changing repository of scalelit from "https://github.com/blindsidenetworks/scalelite" to "https://github.com/jfederico/scalelite-run"

**Comment by human-bieng** [comment]
Now after changing repository scalelite is working as expected

**Comment by aakatev** [comment]
Glad to hear. Would you kindly close the issue since it is resolved.
