### ISSUE TITLE
scalelite API long answer 

### ISSUE THREAD

**Issue by ZAZmaster** [blindsidenetworks/scalelite#297]
I installed scalelite with one BBB server, everything works, but when i send eg getMeetingInfo, scalelite returns it with a delay of 5-10 seconds, but when I send getMeetingInfo to BBB server directly, then the delay is less than a second. There are no errors or warnings in the log files. Network between servers is 10Gb.

**Comment by farhatahmad** [comment]
The only thing Scalelite does is:
- Find the server that the meeting is using
- Send getMeetingInfo to that server
- Respond with the response from that server

If you only have 1 BigBlueButton Server then there's probably an issue with your machines. Did you make sure your machines have the recommended specs in the docs?
