### ISSUE TITLE
bigbluebutton user which mentioned is not recognized

### ISSUE THREAD

**Issue by cod3r0k** [blindsidenetworks/scalelite#299]
Hi, in https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#setting-up-directory-structure-and-permissions you mentioned that each BBB server have `bigbluebutton` user. But when I run `install-bbb.sh` script, it is just done by root user.
What should I do now?

`
The docker containers that operate on recording files use a fixed UID value of 1000. A fresh BigBlueButton server install will usually have a “bigbluebutton” user with UID 997, but this UID is not guaranteed.
`

**Comment by farhatahmad** [comment]
Whats the output of `cut -d: -f1,3 /etc/passwd | grep bigbluebutton` on your BigBlueButton server?
