### ISSUE TITLE
Greenlight in the Scalelite

### ISSUE THREAD

**Issue by harika1258** [blindsidenetworks/scalelite#305]
I installed 4 Bigbluebutton server...., I'd ike to install Scalelite for load balancing.
Do I need install Greenlight into 4 server before config Scalelite load balancing [based on this instruction? ](https://docs.bigbluebutton.org/greenlight/gl-customize.html)

**Comment by matiasilva** [comment]
It's up to you. Most people install Greenlight once and connect to the Scalelite API from there.

**Comment by harika1258** [comment]
You mean, I can don't install Greenlight on the 4 server? In this case how can I create rooms and manage them?

**Comment by farhatahmad** [comment]
Nope. Only install 1 Greenlight, 1 Scalelite and the 4 BigBlueButton servers

**Comment by harika1258** [comment]
Thanks Farhat, Which one servers should be installed 1 Greenlight?

**Comment by matiasilva** [comment]
That's up to you. Greenlight and Scalelite are both Rails applications so it's definitely possible to install them on the same server. I wouldn't recommend installing Greenlight on any one of the BigBlueButton servers. You can also choose to install them on separate servers. The concern with installing them on the same server is to make sure you configure your nginx server blocks correctly to have one for the Scalelite endpoint and the other for your Greenlight home page.

**Comment by harika1258** [comment]
Thanks Matiasilva...., what is your idea Farhat?

**Comment by farhatahmad** [comment]
Exactly what Matias said :)

**Comment by harika1258** [comment]
So, I'm still confused. Which server should I install the Greenlight on now? 
1-one of the BigblueButton servers?
2-Scalelite server?
3-Empty server?
which one?

**Comment by harika1258** [comment]
Farhat, You said, I just install 1 Greenlight. How can I config it for 4 Bigbluebutton server?  I mean in the .env file, how these box fill?
BIGBLUEBUTTON_ENDPOINT=? 
BIGBLUEBUTTON_SECRET=?
SAFE_HOSTS=?

**Comment by harika1258** [comment]
Silva, Do you have any idea?

**Comment by harika1258** [comment]
> Exactly what Matias said :)

Farhat, You said, I just install 1 Greenlight. How can I config it for 4 Bigbluebutton server? I mean in the .env file, how these box fill?
BIGBLUEBUTTON_ENDPOINT=?
BIGBLUEBUTTON_SECRET=?
SAFE_HOSTS=?

**Comment by harika1258** [comment]
> That's up to you. Greenlight and Scalelite are both Rails applications so it's definitely possible to install them on the same server. I wouldn't recommend installing Greenlight on any one of the BigBlueButton servers. You can also choose to install them on separate servers. The concern with installing them on the same server is to make sure you configure your nginx server blocks correctly to have one for the Scalelite endpoint and the other for your Greenlight home page.

Do you have idea about install Greenlight on the seperate machine? how can I config .env and https???

**Comment by harika1258** [comment]
> > Exactly what Matias said :)
> 
> Farhat, You said, I just install 1 Greenlight. How can I config it for 4 Bigbluebutton server? I mean in the .env file, how these box fill?
> BIGBLUEBUTTON_ENDPOINT=?
> BIGBLUEBUTTON_SECRET=?
> SAFE_HOSTS=?

I filled them, but I have problem with https, because I don't have /etc/bigbluebutton/nginx/greenlight.nginx. and config it for reply to https!, do you have any idea?

**Comment by harika1258** [comment]
> That's up to you. Greenlight and Scalelite are both Rails applications so it's definitely possible to install them on the same server. I wouldn't recommend installing Greenlight on any one of the BigBlueButton servers. You can also choose to install them on separate servers. The concern with installing them on the same server is to make sure you configure your nginx server blocks correctly to have one for the Scalelite endpoint and the other for your Greenlight home page.

Silva, I guess we can't install Greenlight on separate server. Because we will have problem with SSL handling and also connect 4 bbb server to one Greenlight. If you and Farhat have another idea, let me know....

**Comment by matiasilva** [comment]
You can install Greenlight on a separate server. By reading your comments, it seems you have a fundamental misunderstanding of how Scalelite, Greenlight and BigBlueButton all work together. I encourage you to re-read the documentation or seek commercial support for your installation.

**Comment by harika1258** [comment]
Matias, I read all docs, and Install Greenlight in the separate server. how can I accomplish 4 bigbluebutton server to it?
I still confused about SAFE_HOSTS=? in the .ebv file 
Thanks in advance describe ho can I do?
Thanks in advance...
