### ISSUE TITLE
HA Topology

### ISSUE THREAD

**Issue by frahman80** [blindsidenetworks/scalelite#307]
Quick question. Which topology will work?

Topology 1:
<a href="https://ibb.co/GPrDXYx"><img src="https://i.ibb.co/GPrDXYx/Scalelite-1.png" alt="Scalelite-1" border="0"></a>

Topology 2:
<a href="https://ibb.co/fFT2mwp"><img src="https://i.ibb.co/fFT2mwp/Scalelite-2.png" alt="Scalelite-2" border="0"></a>

Cheers!

**Comment by farhatahmad** [comment]
#1 is correct for Scalelite. Depending on your infrastructure, make sure you go with HA deployments of Redis a Postgres as well

**Comment by frahman80** [comment]
@farhatahmad Thank you for the clarification. Very much appreciated.

Btw, is there a default/custom prefix for Redis keys? Sorry for my limited knowledge of Ruby in advance.
