### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by yelhouti** [blindsidenetworks/scalelite#312]
Hi,

I'm working on a helm chart that that installs all what is needed for scalelite to work (except the bbb servers since 1. there is no good docker image for bbb, 2. they are often installed on a standalone server)

My question is would I need 2 images (the api and nginx one) or the api one is enough as long as my ingress forwards traffic to 3000. Is there some special config I will need to add serve recordings, and if yes, would any of you be kind enough to put it in place.

Thanks in advance

**Comment by aakatev** [comment]
I use Caddy with Scalelite API, so yeah you can just use ingress service pointing to 3000 and be good to good. I cannot really help on the recording side of the things though.
PS I would be interested to see BBB stack on Kubernetes. Let me know if you need more help with anything.

**Comment by yelhouti** [comment]
Here is a first version: https://github.com/elhoutico/charts/tree/master/charts/scalelite

it doesn't install bbb as there no really good docker image for bbb + bbb is pretty consuming and you often need many baremetal servers, so installing with ansible makes more sense.

I'm working on ansible playbook that uses our chart + installs bbb...

**Comment by aakatev** [comment]
Cheers! It is very helpful.
Yes, I was trying to deploy bbb to k8s, but had an issue setting up networking between all the dependent applications in a single deployment.

**Comment by yelhouti** [comment]
@aakatev here is the ansible playbook that does it all:
installs bbb servers using ansible on bare metal servers, and installs scalelite and all its dependencies in your k8s cluster.

https://github.com/elhoutico/bbb-scalelite-ansible-k8s

Spent few days on this, but I'm glad I did
