### ISSUE TITLE
"No servers are configured" in the Scalelite loadbalancer

### ISSUE THREAD

**Issue by harika1258** [blindsidenetworks/scalelite#313]
Hi everybody...
I have successfully installed Scalelite but later I have found that I have this issues.
I have added 4 BBB servers to the pool and it worked perfectly and output of "./bin/rake servers" is:

HOSTNAME  STATE   STATUS MEETINGS USERS LARGEST MEETING VIDEOS
v1.x.com       enabled  online      0                 0           0           0              0
v2.x.com       enabled  online      0                 0           0           0              0
v3.x.com       enabled  online      0                 0           0           0              0
v4.x.com       enabled  online      0                 0           0           0              0

 but **after a while** when I try to start a meeting, the browser displays this error: "Oops, there was an error when starting the meeting!"
When I check the servers that I have added from the command line in the load balancer, this is what I see: 
~ $ ./bin/rake servers
"No servers are configured"
I don't know why the configured servers are not persistent. 
In the redis server : output redis-cli ping ---------> PONG and I change my redis.conf 
for persistance:
**stop-writes-on-bgsave-error no
appendonly yes**

**Comment by farhatahmad** [comment]
If your servers are disappearing, then it means you do not correctly have persistence enabled for Redis. https://redis.io/topics/persistence might be a good doc to read

**Comment by harika1258** [comment]
Thanks Farhad.
I read redis log file and find out my work dir in the real time change periodically to  /var/spool/cron and get this error :
 Failed opening the RDB file root (in server root dir /var/spool/cron) for saving: Permission denied!
then I wrote a firewall role to deny access to redis via out.
And everything is OK.
Thanks.
