### ISSUE TITLE
Scalelite recording are not available 

### ISSUE THREAD

**Issue by ferasmonther** [blindsidenetworks/scalelite#315]
I have installed the scalelite but recording are not showing
The recording is there on the BBB server but not transferred back through scalelite.
I followed the documentation however it didn’t work.

I need help in fixing this problem

**Comment by matiasilva** [comment]
If you need urgent help, please contact commercial support: https://github.com/blindsidenetworks/scalelite#getting-help.

**Comment by farhatahmad** [comment]
The documentation is correct, so more than likely you are missing some steps. If you'd like help, you need to provide a lot more information so that someone can help pinpoint your problem
