### ISSUE TITLE
How to define when to switch to another BBB

### ISSUE THREAD

**Issue by aguerson** [blindsidenetworks/scalelite#316]
Hi guys,
I found this in file **app/models/server.rb**

```
# Find the server with the lowest load (for creating a new meeting)
  def self.find_available
    with_connection do |redis|
      id, load, hash = 5.times do
        ids_loads = redis.zrange('server_load', 0, 0, with_scores: true)
        raise RecordNotFound.new("Couldn't find available Server", name, nil) if ids_loads.blank?

        id, load = ids_loads.first
        hash = redis.hgetall(key(id))
        break id, load, hash if hash.present?
      end
      raise RecordNotFound.new("Couldn't find available Server", name, id) if hash.blank?

      hash['id'] = id
      hash['enabled'] = true # all servers in server_load set are enabled
      hash['load'] = load
      hash['online'] = (hash['online'] == 'true')
      new.init_with_attributes(hash)
    end
  end
```

But I don't undertsand on which factor scalelite decide to switch to another BBB server.
I have BBB monster server, I would like to have a kind of barrier or limit or something else ?

For exemple what I have

bundle exec rake servers
```
id: 2fb83208-bla-bla-bla
	url: https://bbb3.domain/bigbluebutton/api/
	secret: privatepwd3
	enabled
	load: 0.0
	load multiplier: 9.0
	online
id: 99966eb7-bla-bla-bla
	url: https://bbb2.domain/bigbluebutton/api/
	secret: privatepwd2
	enabled
	load: 0.0
	load multiplier: 1.0
	online
id: 7b02820e-bla-bla-bla
	url: https://bbb1.domain/bigbluebutton/api/
	secret: privatepwd1
	enabled
	load: 0.0
	load multiplier: 3.0
	online
```
When I start a new meeting, scalelite use this one 2fb83208-bla-bla-bla with the max load multiplier ( 9.0 ). Is that normal ?

bundle exec rake status

```
      HOSTNAME       STATE   STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS 
 bbb1.domain  enabled  online         0      0                0       0 
 bbb2.domain  enabled  online         0      0                0       0 
 bbb3.domain  enabled  online         0      0                0       0 
```

Regards,
Aurélien.

**Comment by farhatahmad** [comment]
Scalelite will always pick the server with the lowest load. If the load on all servers is the same (in this case 0), it will pick the first one that Redis returns to it (which is normally the first one added I believe)

**Comment by aguerson** [comment]
OK, I understood.

It is a kind of round-robin.

But the first time, the meetings is launch on the first bbb instance returned by the function described on the top, even if the bbb instance is less powerful ( big load multiplier ). Some help ?

**Comment by farhatahmad** [comment]
Since the load for all is 0, it will just pick the first server that it gets, regardless of the loadMultiplier. You might be able to hack your way around it by removing the servers and adding them back in order of most powerful to weakest - that way, the most powerful is returned the first time

**Comment by aguerson** [comment]
Can we imagine to set a trigger or just a value to specify the first bbb to use ( just the first time ) a kind of start meeting order to force one specific order. ( 1 / 2 / 3 / etc... ) Then the load multiplier will do his work

In my case I added bbb1, bbb2 and bbb3 in this order. The load multiplier on bbb3 is the strongest ( 9 ), and scalelite decided to start the first scalelite meeting on bbb3 and not bbb1 ( the first bbb added ).

**Comment by aguerson** [comment]
I precise that I changed the  load multiplier on bbb3 after, so the last modified is bbb3

**Comment by farhatahmad** [comment]
Scalelite originally was designed to loadbalance equal BigBlueButton servers. The loadMultiplier was added in later on to help with sys admins who couldn't get equal servers.

In your case, I don't imagine we're going to add that level of control to the order in which meetings are created. I suggest exploring different combinations to see which 1 results in the desired result
