### ISSUE TITLE
How to automatically delete old Recordings in scalelite

### ISSUE THREAD

**Issue by foranastes** [blindsidenetworks/scalelite#317]
I did't find a way to delete old recordings in scalelite.
Please help me.

**Comment by matiasilva** [comment]
You could write a cron job to delete entries and corresponding recordings depending on their age.

**Comment by foranastes** [comment]
Anybody did it?Any examples will be really helpful ---- On Mon, 07 Sep 2020 11:35:53 +0530  notifications@github.com  wrote ----
You could write a cron job to delete entries and corresponding recordings depending on their age.

**Comment by matiasilva** [comment]
Read the documentation for BigBlueButton, a quick search gives you this bash script you can work off of: https://docs.bigbluebutton.org/2.2/customize.html#delete-recordings-older-than-n-days

**Comment by foranastes** [comment]
That's working only in BBB server. Not in scalelite

**Comment by matiasilva** [comment]
Sure, but you can modify the bash script.

**Comment by falahatnejadwork** [comment]
This Code is work for me:

#!/bin/bash
URI=URL # your scalelite server url like: loadbalancer.test.test
SALT=SALT # your scalelite server secret
MAX_AGE=30

MAX_DATE=$(date -I -d "-$MAX_AGE days")

for MEET in $( docker exec -u postgres postgres psql -d scalelite -c "SELECT record_id FROM recordings WHERE starttime < '$MAX_DATE';"); do

LINK="deleteRecordingsrecordID=$MEET$SALT"

KEY=$(echo -n "$LINK" | openssl sha1 |awk '{print $2}')

FLINK="https://$URI/bigbluebutton/api/deleteRecordings?recordID=$MEET&checksum=$KEY"
echo "deleting $MEET"
curl $FLINK
done

**Comment by MrCapitalist** [comment]
> This Code is work for me:
> 
> #!/bin/bash URI=URL # your scalelite server url like: loadbalancer.test.test SALT=SALT # your scalelite server secret MAX_AGE=30
> 
> MAX_DATE=$(date -I -d "-$MAX_AGE days")
> 
> for MEET in $( docker exec -u postgres postgres psql -d scalelite -c "SELECT record_id FROM recordings WHERE starttime < '$MAX_DATE';"); do
> 
> LINK="deleteRecordingsrecordID=$MEET$SALT"
> 
> KEY=$(echo -n "$LINK" | openssl sha1 |awk '{print $2}')
> 
> FLINK="https://$URI/bigbluebutton/api/deleteRecordings?recordID=$MEET&checksum=$KEY" echo "deleting $MEET" curl $FLINK done

Yes, it works for me too. Thanks for sharing this useful script.
