### ISSUE TITLE
problem connecting scalelite to greenlight

### ISSUE THREAD

**Issue by khaledkhz** [blindsidenetworks/scalelite#318]
hi.
i had installed scalelite (hostname:lb) and 2 bbb servers (hostnames: bbb & bbb1) and i installed greenlight on bbb server.
i edit ".env" file in greenlight directory on bbb server  and changed "BIGBLUEBUTTON_ENDPOINT" and "BIGBLUEBUTTON_SECRET" with scalelite server information. but when i create room in greenlight, greenlight creats all of them on bbb server(the server that greenlight is installed).
after changing .env file i restart greenlight.
after this i also cahnged "SECRET_KEY_BASE" in .env with the scalelite server information, but it doesnt solve the problem.
when i connect scalelite to wordpress,it works fine.
any idea?did i omit something?

**Comment by farhatahmad** [comment]
Make sure you restart Greenlight after changing the `.env` by running 
```
docker-compose down
docker-compose up -d
```
