### ISSUE TITLE
Scalelite behind reverse proxy

### ISSUE THREAD

**Issue by pbdco** [blindsidenetworks/scalelite#324]
We're using the Lazy deployment (Dockerized version) of Scalelite, and we were wondering if it could work behind an Nginx reverse proxy, and how should configure it.

**Comment by pbdco** [comment]
Anyone looking into this: it is 100% possible and Scalelite is working fine behind a reverse proxy (nginx in my case). 
I will post the detailed steps how to configure coming soon.

**Comment by anddegs** [comment]
hello pbdco.. how did you manage to do this?can you share your changes in the nginx or in apache
