### ISSUE TITLE
Publishing spooled recordings 

### ISSUE THREAD

**Issue by parsa25eng** [blindsidenetworks/scalelite#326]
Hi there. I have some BBB servers behind the Scalelite server and I have had some old recordings on each BBB server. By using "scalelite_batch_import.sh" I could transfer old recordings to /spool directory of Scalelite. 
Now, my question is that the publishing process will be performed automatically or I have to untar each archive file to "/published"directory of the Scalelite server?

**Comment by farhatahmad** [comment]
Once the batch importer imports them into the spool directory the Scalelite recording importer should automatically pick up those files and manually import them into Scalelite

**Comment by parsa25eng** [comment]
thanks for your response @farhatahmad ,
In my case, once the Scalelite has been installed, the recording importer working correctly. But, after a while, the imported recording has not been extracted. 
I have used Moodle for joining the session and seeing the recording. when this event has occurred, the recording links disappeared on moodle.

**Comment by parsa25eng** [comment]
After a couple of days finally, I figure out the problem and fix it.
the problem was the password authentication for potgress database.
Following [https://github.com/blindsidenetworks/scalelite/issues/269#issuecomment-655432652](url) I changed the password of postgres database and set the new password in the "docker-compose.yml" for "scalelite-recording-importer" and "scalelite-api". So, the contents of "spool" directory automatically decompressed in the "publish/presentation" directory and recordings links have appeared in the Moodle frontend.
