### ISSUE TITLE
Recording scripts problem with BBB-2.3-Dev

### ISSUE THREAD

**Issue by Rahimimojtaba** [blindsidenetworks/scalelite#327]
Recently I configured the scalelite on BigBlueButton-2.3-dev. I found numerous problem for the recording scripts.
One of the issues was on BigBlueButton that I wasn't able to run the batch import script due to some permission issue and I just followed up the following thread and fix it.
https://github.com/blindsidenetworks/scalelite/issues/90
If it's the correct solution, I don't know why Scalelite team didn't fix it in the main codes.
The second issue is about the scalelite post publish script. ---> scalelite_post_publish.rb
It's not working and don't transfer the recordings automatically. After some investigation, I found some error logs in bbb-rap-resque-worker.service
It seems that mentioned service wasn't able to run post publish script correctly.
Below is the error lines:
Sep 25 17:59:19 bbb4 bbb-rap[30695]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
**Sep 25 17:59:19 bbb4 bbb-rap[30695]: /usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb:29:in `<main>': invalid option: -f (OptionParser::InvalidOption)**
**Sep 25 17:59:19 bbb4 bbb-rap[30695]: Exit status: 1**
**Sep 25 15:59:19 bbb4 bbb-rap[30695]: Post publish script /usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb/scalelite_post_publish failed**
Sep 25 17:59:19 bbb4 bbb-rap[30695]: Task: Getting external meeting id
Sep 25 17:59:19 bbb4 bbb-rap[30695]: Task: Getting meeting metadata

I think there is some issue when bbb-rap-resque-worker sent -f option to scalelite_post_publish.rb, as it has the following line in service file:
ExecStart=/bin/sh -c '**/usr/bin/rake -f** ../Rakefile resque:workers >> /var/log/bigbluebutton/bbb-rap-worker.log'

Is the any solution to figure it out these issues?

**Comment by ffdixon** [comment]
Did you fix the issue?
