### ISSUE TITLE
Recording disappear in Front end app 

### ISSUE THREAD

**Issue by faridsaif** [blindsidenetworks/scalelite#330]
i was install scalelite lazy deployment a week age from this manual:
https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6
every this was ok, the load balancer and recording-importer works correctly but suddenly all recording session disappear.
i'm searching in recording-importer log with :
`sudo docker logs scalelite-recording-importer`
and find Error :  **ERROR -- : Failed to import recording: FATAL:  password authentication failed for user "postgres"**
then i search for solution and find this from #269 :

-  Run docker ps
- Find the container ID relating to the postgre DB
- docker exec -it bash
- psql -U postgres
- \password
- Set the password to whatever you need
- exit
- exit
- Ensure your .env file has the new password
- cd to your scalelite-run directory
- docker-compose down
- docker-compose up -d

i do that but recording not shown yet. i checked recording-import log again and that authentication error not shown at the end of file, but still was in middle of importing process, seems like the recording-importer cant access Database but still doing extracting recording file in publish folder 
anyone can help me pleaseee???

snipping from my current scalelite-recording-importer log is:

presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1601450815210/slide-4.png
presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1601450815210/slide-10.png
presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1601450815210/slide-11.png
presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1601450815210/slide-12.png
presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/panzooms.xml
presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/shapes.svg
presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/video/
presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/video/webcams.webm
presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/presentation_text.json
I, [2020-10-01T18:20:26.729368 #6]  INFO -- : Found metadata file: presentation/01faa802fb37414afb8cbf1a9d75098d93f42220-1601450815192/metadata.xml
**E, [2020-10-01T18:20:26.761791 #6] ERROR -- : Failed to import recording: FATAL:  password authentication failed for user "postgres"**
I, [2020-10-01T18:20:26.761995 #6]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248.tar
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/captions.json
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/deskshare.xml
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/metadata.xml
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/cursor.xml
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/slides_new.xml
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/presentation/
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/presentation/287a52e9308e32245cd4d006d456ea0956541821-1601539194656/
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/presentation/287a52e9308e32245cd4d006d456ea0956541821-1601539194656/slide-23.png
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/presentation/287a52e9308e32245cd4d006d456ea0956541821-1601539194656/slide-5.png
presentation/0ef9ed6e804cadebb8ebc44eca8e9a89cfda8fc3-1601537630248/presentation/287a52e9308e32245cd4d006d456ea0956541821-1601539194656/slide-28.png

**Comment by matiasilva** [comment]
>  anyone can help me pleaseee???

The best way to get help is to ask respectfully and patiently. Not like this.

Password authentication is still failing. Is your postgres server still live? Can you access it using `psql`? Take some time to properly debug the issue, please.

**Comment by faridsaif** [comment]
> The best way to get help is to ask respectfully and patiently. Not like this.

thanks for your answer and sorry for my misbehavior

> Password authentication is still failing. Is your postgres server still live? Can you access it using psql? Take some time to properly debug the issue, please.

yes. postgres server is the same scalelite server . as i said, i can access psql from docker and change password with solution (that i mentioned above). but problem not solved

**Comment by faridsaif** [comment]
ok, i'm done with recording issue.
after days and hours searching and trying different solutions, i found this instruction:
1) change postgres Password with above instruction
2) bypass postgres password authentication with:
- Run docker ps
- Find the container ID relating to the postgre DB
- docker exec -it <container ID> bash
- vi /var/lib/postgres/data/pg_hba.conf
- in the last line, modify: host  all   all   all  md5  to host all all all trust
- docker-compose down and docker-compose up -d
 i hope above instruction helps anyone who have same problem
