### ISSUE TITLE
Stale file in scalelite-api

### ISSUE THREAD

**Issue by goudal-emmk** [blindsidenetworks/scalelite#331]
The problem is the following :
- on the machine that run the scalelite-api docker the filesystem is nfs mounted on the host.
- after some time when requesting to display a recording, the recording files are not found.
- when running a shell in the docker instance, listing the directory gives a stale-file.
- the recordings file system is still available on the computer, but not on the docker instance.

It seems that this is a kind of docker problem, after searching on internet it seems that the solutions are either to add a noforget option in mergefs, either to directly mount the nfs filesystem in the docker instance.

**Comment by farhatahmad** [comment]
Are you using the docker compose? or the Scalelite instructions? This shouldn't happen with the stock instructions
