### ISSUE TITLE
Question: How to integrate a single BBB server in a scalelite instalation ?

### ISSUE THREAD

**Issue by parreitu** [blindsidenetworks/scalelite#334]
I currently have a single BBB server and my intention is to add the balancer. In the readme I see how to install it from scratch, but it is not clear to me what would be the process of integrating the current BBB server into a configuration with scalelite .

In the current server I have recordings made, I have the greenlight database with registered users and previous recordings, etc.

I would like to go from an installation with a single server to another installation with several, but without losing the information I have now and without the users noticing the change.

Thanks !!

**Comment by matiasilva** [comment]
1. Install Scalelite on a separate server
2. Transfer your recordings to Scalelite using the import script
3. Add your BigBlueButton server's secret and information to Scalelite per the documentation
4. Replace the current secret and API endpoint in Greenlight with your new Scalelite ones

If your users have already saved certain recording URLs, then there's nothing you can do about that. They will definitely still work, but they won't be magically redirected to your new Scalelite endpoint.
