### ISSUE TITLE
Scalelite Recording on moodle

### ISSUE THREAD

**Issue by mailanoopsingh95** [blindsidenetworks/scalelite#339]
Since I have Installed Moodle, Scalelite & BigBluebutton Servers
I have Installed Scalelite from https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6

The BigBlueButton Live Session is working perfectly with scalelite

Could you guide the exact Step By Step Process to Pull Recordings from BigBlueButton Server To Scalelite, So that it can be displayed on Moodle

Thanks

**Comment by farhatahmad** [comment]
https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#configuring-the-bigbluebutton-recording-transfer

**Comment by mailanoopsingh95** [comment]
i tried to follow the link and process.. still i am unable to get recordings
could you guide the step by step process for the same

**Comment by mailanoopsingh95** [comment]
![Capture](https://user-images.githubusercontent.com/72740517/97293242-6aad1b00-1872-11eb-9110-3e6e28086791.JPG)


after making this command 

bigbluebutton@ip-xxx-xx-xx-xxx:/$ mkdir -p ~/.ssh
mkdir: cannot create directory ‘//.ssh’: Permission denied

how to resolve this

**Comment by YassineBaggar** [comment]
Hi @mailanoopsingh95 

mkdir: cannot create directory ‘//.ssh’: Permission denied

You find a solution for this?

**Comment by andrekutianski** [comment]
> https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#configuring-the-bigbluebutton-recording-transfer

@farhatahmad the question is about the ssh key for bigbluebutton user for ssh transfer records. As this is not a regular user he does not have a home dir and when you try to create the ssh key return this error: 

```ssh
bigbluebutton@meetroom02:/$ mkdir -p ~/.ssh ; chmod 0700 ~/.ssh
mkdir: cannot create directory ‘//.ssh’: Permission denied
chmod: cannot access '//.ssh': No such file or directory
```

**Comment by igmancera** [comment]
mailanoopsingh95 

with root change the permitions of pub file, then after with bbb user you should generate the priv key
