### ISSUE TITLE
İf too many users wants to join rooms at the same time (4000 users), sometimes scalelite.api stop working.

### ISSUE THREAD

**Issue by erkanyetik26** [blindsidenetworks/scalelite#340]
İf too many users wants to join rooms at the same time (4000 users), sometimes scalelite.api stop working. I checked some log files but i didnt see anythink. Which log files should i check? 
We have 100 bbb server in the pool.

**Comment by farhatahmad** [comment]
When using Scalelite at that level, you'll probably want to install multiple Scalelite servers behind a network loadbalancer to help with traffic
