### ISSUE TITLE
scalelite access error

### ISSUE THREAD

**Issue by liuhetongzi** [blindsidenetworks/scalelite#341]
I have installed scalelite success and add bigbluebutton into scalelite。But When I access scalelite in browser error。What should I do。Thanks very much。

scalelite:
![image](https://user-images.githubusercontent.com/23496061/95969042-d211a680-0e40-11eb-93ea-ce300593a786.png)

access in browser
![image](https://user-images.githubusercontent.com/23496061/95969122-e9509400-0e40-11eb-8b25-bf9c5efe0046.png)

access bigbluebotton alone success
![image](https://user-images.githubusercontent.com/23496061/95969294-1a30c900-0e41-11eb-8927-2a41766899e5.png)

I have edit greenlight .env 
![image](https://user-images.githubusercontent.com/23496061/95969448-5106df00-0e41-11eb-8b02-8ecb8b92eb19.png)

The BIGBLUEBUTTON_SECRET is the same with LOADBALANCER_SECRET。I already restart greenlight 。

My /etc/default/scalelite
![image](https://user-images.githubusercontent.com/23496061/95969547-75fb5200-0e41-11eb-93b5-ef750340a945.png)

**Comment by farhatahmad** [comment]
That's expected. Make the request to `scalelite.efivestar.com/bigbluebutton/api` instead
