### ISSUE TITLE
Online servers deleted automatically

### ISSUE THREAD

**Issue by faridsaif** [blindsidenetworks/scalelite#342]
hello
i was installed Scalelite Lazy Deployment from [here](https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6) with 9 servers. it's work correctly but after some days, around a week, all servers deleted automatically. i run this command:
`docker exec -i scalelite-api bundle exec rake servers`
and return:
> No servers are configured

if i add servers again, system works correctly, but after some days, servers deleted again
thanks for your support

**Comment by aguerson** [comment]
check your redis base. It is just an idea

**Comment by faridsaif** [comment]
@aguerson  thanks for your response. redis config automatically with sacalelite lazy deployment. what should i check?

**Comment by aguerson** [comment]
I don't use docker install. I have my own redis base. But The bbb servers are stored in the redis base. You have to verify if your redis base is persisting.

What I found for you 
```
Scaling BigBlueButton

Setup a Redis Cache
• Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker.
• You can install Redis on a dedicated server or install it on the same server as Scalelite.
• Ubuntu’s default repositories contain Redis packages, so we can install these easily using the apt packaging system.:

sudo apt-get update

sudo apt-get install redis-server

Next is to enable Redis to start on system boot

sudo systemctl enable redis-server.service

• You can configure Redis as you need by editing redis.conf file which is well documented
• You have to enable Redis remote login like this:

bind 0.0.0.0 or
bind IPofScalelite

• You can easily install Redis using docker allowing access only from Scalelite docker network and enabling persistence on your Redis server:

First create Redis’s env file /etc/default/redis with content of: REDIS_DATA_DIR=/mnt/redis

Then run the docker container:

/usr/bin/docker run --name redis --env-file /etc/default/redis --network scalelite --hostname redis -v ${REDIS_DATA_DIR}:/data redis redis-server --appendonly yes

• This will save alot of time you would have spent why Redis is not persisting the servers you configure on Scalelite. Set the redis_url in Scalelite env file /etc/default/scalelite:

REDIS_URL=redis://redis
```

**Comment by faridsaif** [comment]
@aguerson thanks again
i read your solution and found key point that cause my  problem: my redis configuration not persistence. so i should enable persistence mode in redis config. but i cant find this config in docker

**Comment by aguerson** [comment]
;)
Sorry, I don't use docker. I have my own redis base. More secure for me in this context.
