### ISSUE TITLE
bbb domain redirect

### ISSUE THREAD

**Issue by liuhetongzi** [blindsidenetworks/scalelite#345]
I have add bbb to scalelite like bbb1.com and bbb2.com.When I create a meeting1 , it redirect bbb1.com.When I create a meeting2, The browser redirect bbb2.com.  The domain switch from bbb1.com to bbb2.com.Is this correct? domain switch seems strange. I don't want to domain redirect。I want the domain is always bbb1.com. And scalelite will auto distribute bbb1.com or bbb2.com in background. Is this possible?  Thanks..

meeting1:
![image](https://user-images.githubusercontent.com/23496061/96678318-0c7cc580-13a4-11eb-9774-5c00ad48c2fb.png)
meeting2:
![image](https://user-images.githubusercontent.com/23496061/96678332-13a3d380-13a4-11eb-84ff-25aade8bad08.png)
scalelite:
![image](https://user-images.githubusercontent.com/23496061/96678401-2fa77500-13a4-11eb-856b-d59554c90583.png)

**Comment by mk-hs** [comment]
Short answer: No.

That behaviour is correct, since the meetings are being created on their respective BBB servers, one after another. The URL changes because the meeting is taking place on either bbb1.domain.com or bbb2.domain.com. When the session is over, you get redirected back to your Scalelite domain.
I'm guessing you want a single domain for several BBB-Servers, which isn't possible. Each Server needs their own FQDN.

**Comment by matiasilva** [comment]
I know this can be done, I've seen it on existing deployments -- question is how?

**Comment by liuhetongzi** [comment]
> I know this can be done, I've seen it on existing deployments -- question is how?

Hi，Do you know how to do it？

**Comment by liuhetongzi** [comment]
> Short answer: No.
> 
> That behaviour is correct, since the meetings are being created on their respective BBB servers, one after another. The URL changes because the meeting is taking place on either bbb1.domain.com or bbb2.domain.com. When the session is over, you get redirected back to your Scalelite domain.
> I'm guessing you want a single domain for several BBB-Servers, which isn't possible. Each Server needs their own FQDN.

Yes ， I  want a single domain for several BBB-Servers， When I want add a bbb-server into scalelite， I ask for a domain， If I have 100 bbb-servers， I ask for 100 domains， It's troublesome  for me。

**Comment by matiasilva** [comment]
You can use subdomains..you don't need to buy 100 domains.

**Comment by liuhetongzi** [comment]
> You can use subdomains..you don't need to buy 100 domains.

Yes， I  can use subdomains，I just wonder If I can use a single domain for several BBB-Servers and how to do it。

**Comment by matiasilva** [comment]
Me too :)

**Comment by farhatahmad** [comment]
You can't use a single domain - you can get a wildcard certificate and use it for each domain so that you can get similar urls, but because of how everything communicates with each other, the domains need to be unique
