### ISSUE TITLE
Servers disappeared from scalelite and now do not works anymore

### ISSUE THREAD

**Issue by rabser** [blindsidenetworks/scalelite#348]
Hi, 
 i'm running the latest scalelite available
This morning all servers in scalelite disappeared, the server list was empty. No other errors along the 4 servers involved (1Scalelite+3BBB). I tried adding the servers again, but now i get

 Failed to get server id=b5d65b6d-0068-4ebf-b2cd-f1109eb20ae4 status: internalError: Response did not include returncode

for every server, but the servers are normally up&running and reachable from inside the scalelite-poller container (checked with a wget). I double checked the BBB secrets and they are the right ones.

Apart from the disappearing without any intervention, what it's happening now ? Some hints ?

**Comment by rabser** [comment]
Ok, I've managed to re-add correctly the servers, the server url must include the "/bigbluebutton/api/" path: now in a panic, I didn't read enough in deep the docs.
But why the servers were removed? There is anywhere an auto-remove which starts on specific conditions?

**Comment by farhatahmad** [comment]
The only way that I know that would cause the servers to disappear is if you did not enable persistence on your Redis Server

**Comment by rabser** [comment]
As usual, you're right. The Redis server had troubles about persistence. when doing the periodic write down of the database to file, 
Changing some system-wide preferences, as suggested in some posts, the problem seems gone away.
Thanks a lot for your kind reply.

**Comment by hokascha** [comment]
> As usual, you're right. The Redis server had troubles about persistence. when doing the periodic write down of the database to file,
> Changing some system-wide preferences, as suggested in some posts, the problem seems gone away.
> Thanks a lot for your kind reply.

Would you share what you did to make it work? Same problem here...

**Comment by rabser** [comment]
sure, from #369 :

I solved it by adding to the redis server in /etc/sysctl.d/40-redis.conf (create the file if do not exists)

vm.overcommit_memory =1 

and rebooted the server.

**Comment by Zvangi** [comment]
applied this but my servers still disappear on their own

> sure, from #369 :
> 
> I solved it by adding to the redis server in /etc/sysctl.d/40-redis.conf (create the file if do not exists)
> 
> vm.overcommit_memory =1
> 
> and rebooted the server.

Any ideas why? I don't use lazy development.
