### ISSUE TITLE
Scalelite api crashes with BBB 2.3alpha2 servers

### ISSUE THREAD

**Issue by penguennoktanet** [blindsidenetworks/scalelite#350]
I am using 20 bbb 2.3alpha2 servers with scalelite. But scalelite api crashes offen. I traced the log files and not found anything. I repeated the last request before the crash, but it did not crashed again. The detailed log file is below.
[bug.log](https://github.com/blindsidenetworks/scalelite/files/5437629/bug.log)

**Comment by farhatahmad** [comment]
Can you confirm that 2.2 servers work correctly in your deployment?
