### ISSUE TITLE
Installation Complete - Recording not Showing on Moodle / Scalelite

### ISSUE THREAD

**Issue by mailanoopsingh95** [blindsidenetworks/scalelite#353]
Hello here i would like to describe about the steps that I used during installation. Please let me know if i missed any strep

1. **Installed Scalelite** from https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6
added these lines to .env
SECRET_KEY_BASE=f6f36f07be03b9c9683269b14e14648f137323fad568a80c1ac25c83776fb0f6fda82fece9513b465c59ce8df6fe4ff8d54e8b836fab806b34107c8cb1aedf4c
LOADBALANCER_SECRET=31aebcbbbb774c0c5445191ccc0b32fc280505983952015d
URL_HOST=my domain.com
NGINX_SSL=true

2. **Installed BigBlueButton** wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s mydomain.com -e my@email.com -g -c stun1.l.google.com:19302

3. **Added BigBlueButton Server** on scalelite & enabled them

4. **On BigBlueButton server**, ran these commands to create the group and add the bigbluebutton user to the group:

-Create a new group with GID 2000
groupadd -g 2000 scalelite-spool
-Add the bigbluebutton user to the group
usermod -a -G scalelite-spool bigbluebutton

mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/spool
chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/spool
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/spool

mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
chown 1000:1000 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite

mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/published
chown 1000:1000 /mnt/scalelite-recordings/var/bigbluebutton/published
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/published

mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/unpublished
chown 1000:1000 /mnt/scalelite-recordings/var/bigbluebutton/unpublished
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/unpublished

After which i gave **chmod -R 777 mnt** to get full permission

**scalelite_post_publish.rb: install to the directory /usr/local/bigbluebutton/core/scripts/post_publish** lines show below
https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/scalelite_post_publish.rb

**scalelite.yml: install to the directory /usr/local/bigbluebutton/core/scripts** lines described below

- Local directory for temporary storage of working files
work_dir: /var/bigbluebutton/recording/scalelite
- Directory to place recording files for scalelite to import
spool_dir: /mnt/scalelite-recordings/var/bigbluebutton/spool

5. **On Scalelite Server**

Create the spool directory for recording transfer from BigBlueButton
mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/spool
chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/spool
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/spool

Create the temporary (working) directory for recording import
mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
chown 1000:1000 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite

Create the directory for published recordings
mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/published
chown 1000:1000 /mnt/scalelite-recordings/var/bigbluebutton/published
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/published

Create the directory for unpublished recordings
mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/unpublished
chown 1000:1000 /mnt/scalelite-recordings/var/bigbluebutton/unpublished
chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/unpublished

After which i gave **chmod -R 777 mnt** to get full permission

**Conclusion:** I can see  .tar files on Bigbluebutton : /mnt/scalelite-recordings/var/bigbluebutton/spool
But i cannot find any recoding file on Scalelite Server

Could you please tell me which step i missed or what mistake i made here

Thanks in Advance

**Comment by parreitu** [comment]
I've the same problem. If I change the Moodle configuration in order to connect with the BBB server, I can see the recordings, but not from the scalelite server. 

The /mnt/scalelite-recordings/ folder is empty ....

Thanks !

**Comment by andrekutianski** [comment]
@mailanoopsingh95 the link that you refer to is not the official install documentation. I recommend following the readme of this repository.

Do you have [set up a shared volume for recordings](https://github.com/blindsidenetworks/scalelite#setup-a-shared-volume-for-recordings)?

After configuring your Scalelite you need to configure the import script on each BBB server like described here https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/README.md#scalelite-recording-transfer-scripts-for-bigbluebutton
