### ISSUE TITLE
Unable to make Join call - unsupported_request as HTML

### ISSUE THREAD

**Issue by jainvipin69** [blindsidenetworks/scalelite#354]
We are getting below error on making join api call to bbb

Nov 01 09:10:37 s10894979 docker[24917]: D, [2020-11-01T09:10:37.189085 #6] DEBUG -- : [e4e693e3-1b61-4cb7-b650-ff241544c669] Creating meeting 12345994 on BigBlueButton server f756a89d-4f0d-4361-929
Nov 01 09:10:37 s10894979 docker[24917]: I, [2020-11-01T09:10:37.858204 #6]  INFO -- : [e4e693e3-1b61-4cb7-b650-ff241544c669] Completed 200 OK in 672ms (Views: 0.4ms | Allocations: 1513)
Nov 01 09:10:49 s10894979 docker[24917]: I, [2020-11-01T09:10:49.187462 #6]  INFO -- : [b1329010-4ba8-44e9-a426-bd9bf3b1064d] Started POST "/bigbluebutton/api/join?fullName=vipin12&meetingID=1234599
Nov 01 09:10:49 s10894979 docker[24917]: I, [2020-11-01T09:10:49.189522 #6]  INFO -- : [b1329010-4ba8-44e9-a426-bd9bf3b1064d] Processing by ErrorsController#unsupported_request as HTML
Nov 01 09:10:49 s10894979 docker[24917]: I, [2020-11-01T09:10:49.189707 #6]  INFO -- : [b1329010-4ba8-44e9-a426-bd9bf3b1064d]   Parameters: {"fullName"=>"vipin12", "meetingID"=>"12345994", "redirect
Nov 01 09:10:49 s10894979 docker[24917]: I, [2020-11-01T09:10:49.190895 #6]  INFO -- : [b1329010-4ba8-44e9-a426-bd9bf3b1064d] Completed 200 OK in 1ms (Views: 0.4ms | Allocations: 178)

**Comment by farhatahmad** [comment]
`POST "/bigbluebutton/api/join?fullName=vipin12&meetingID=1234599` Im not sure what front-end you're using, but the join request has to be a GET, not a POST
