### ISSUE TITLE
VM resource for balancer and bbb server

### ISSUE THREAD

**Issue by hmahdi-s** [blindsidenetworks/scalelite#355]
How much should reserve for balancer? considering redis + postgres + balancer in a server
How much should reserve for each bbb server?
![Screen Shot 1399-08-11 at 5 41 38 PM](https://user-images.githubusercontent.com/32895169/97805207-f7d4e300-1c69-11eb-8c08-5083caf649d1.png)
![Screen Shot 1399-08-11 at 5 41 23 PM](https://user-images.githubusercontent.com/32895169/97805211-f99ea680-1c69-11eb-8e4d-1bdafa282ced.png)

**Comment by ffdixon** [comment]
If you add up the requirements at

  https://github.com/blindsidenetworks/scalelite

you probably want to do an 8 CPU core server.

**Comment by hmahdi-s** [comment]
@ffdixon 
I read it before. but situation was about how to create suitable VM and how much should reserve for a bbb server.
Because I had an experience that i create VM with the requirement but it doesn't support even 80 users. 
I understand that I must reserve 30Ghz from cpu.
actually VPS can not support. it must be VDS. but I'm not sure How many Ghz should spread for each.

**Comment by ffdixon** [comment]
For the BigBlueButton server's minimum requirements, see

 https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements
