### ISSUE TITLE
Question: Is it possible to share the same public ip address with all servers used with scalelite ?

### ISSUE THREAD

**Issue by parreitu** [blindsidenetworks/scalelite#356]
In order to install BBB with Scalelite, we need some servers, each with their own FQDN

- 1 Turn Server
- 1 Greenligh server
- 1 Moodle Server (optional)
- 1 Scalelite Server
- N BBB Servers, in our case 3 Servers

If each server need a Public IP address, we need at least 7 Public IP addresses. 

Do you know if it is posible to share the same IP address using solutions like Traefik ?

Thanks

**Comment by farhatahmad** [comment]
As far as I know, you need 7 unique IPs to get it all running correctly. You could install Greenlight on one of the BigBlueButton servers to save 1 IP, but for a deployment of this level, I would suggest separating everything

**Comment by mohgh** [comment]
You could share the public IPs of BBB servers with the Scalelite server. You have to install HA proxy on your Scalelite server and route the traffic to the private IP of the BBB server based on the domain name of the BBB server.
You need a separate public IP for the Turn server(s).
