### ISSUE TITLE
communication between balancer, postgresql and redis in a server

### ISSUE THREAD

**Issue by hmahdi-s** [blindsidenetworks/scalelite#360]
If postgresql and redis were install in balancer server. how is the communication? 
Postgres and redis are not installed by docker. in this case must set public ip? or can use 127.0.0.1:5432 for postgres and 127.0.0.1:6379 for redis?

**Comment by farhatahmad** [comment]
I don't believe they need to be public IPs, but you wouldn't be able to access them at `127.0.0.1`. Since Scalelite runs in docker containers, `127.0.0.1` refers to the container itself.
