### ISSUE TITLE
Recording has changed visibility from public to unlisted when recording is rebuilt.

### ISSUE THREAD

**Issue by denwerko** [blindsidenetworks/scalelite#363]
Hello, we run scalelite with 13 nodes, tens of GB of recordings, I noticed this issue that recordings, that had visibility as public set in greenlight had visibility changed upon issuing and finishing bbb-record --rebuildall , that was requested due to accidentally deleting recording by teacher. 

Steps to recreate:
1 create recording in bbb
2 mark recording as public in greenlight
3 on node, that has recordings raw data, issue command bbb-record --rebuild MEETING_ID (or bbb-record --rebuildall )
4 recording is now unlisted in greenlight

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Scalelite. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
