### ISSUE TITLE
scalelite-poller.service error

### ISSUE THREAD

**Issue by hmahdi-s** [blindsidenetworks/scalelite#365]
scalelite.target is enabled and active but  scalelite-poller.service has error:

   Loaded: loaded (/etc/systemd/system/scalelite-poller.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-11-06 22:48:41 UTC; 14s ago
  Process: 2787 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-poller (code=exited, status=1/FAILURE)
  Process: 2774 ExecStartPre=/usr/bin/docker rm scalelite-poller (code=exited, status=1/FAILURE)
  Process: 2750 ExecStartPre=/usr/bin/docker kill scalelite-poller (code=exited, status=1/FAILURE)
 Main PID: 26135 (code=exited, status=1/FAILURE)

Nov 06 22:48:30 balancer systemd[1]: Starting Scalelite Meeting Status Poller...
Nov 06 22:48:31 balancer docker[2750]: Error response from daemon: Cannot kill container: scalelite-poller: No such container: scalelite-poll
Nov 06 22:48:31 balancer docker[2774]: Error: No such container: scalelite-poller
Nov 06 22:48:41 balancer docker[2787]: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.i
Nov 06 22:48:41 balancer systemd[1]: scalelite-poller.service: Control process exited, code=exited status=1
Nov 06 22:48:41 balancer systemd[1]: scalelite-poller.service: Failed with result 'exit-code'.
Nov 06 22:48:41 balancer systemd[1]: Failed to start Scalelite Meeting Status Poller.
~

**Comment by andrekutianski** [comment]
this smell a docker problem

**Comment by farhatahmad** [comment]
Yeah, seems like your machine was unable to reach Docker - either due to Docker itself or due to your machine
