### ISSUE TITLE
Scalelite forgots BBB-Instances

### ISSUE THREAD

**Issue by bernxa** [blindsidenetworks/scalelite#366]
On two consecutive days I noticed that Scalelite "forgot" the instances I added with ./bin/rake servers:add and activated with ./bin/rake servers:enable. A query of ./bin/rake status showed me that no more BBB instances were stored.

I followed the readme.md in this repository. In the logs I could not find anything usable via docker logs scalelite-api.

Does anyone else know this behavior? How can I turn it off?

**Comment by matiasilva** [comment]
Definitely a duplicate of other issues.

**Comment by bernxa** [comment]
Duplicate of an other issue? If so, I apologize. But please link me to the other error so I can read what it is and how I solve the problem.
