### ISSUE TITLE
scalelite-api use single core CPU

### ISSUE THREAD

**Issue by aliyousefiaan** [blindsidenetworks/scalelite#367]
Hi there,

A long time ago I set up Scalelite on a CentOS VPS (8GB Ram, 4 Core CPU). Also, I add 14 BBB instances to this machine.

One thing I realize these days is the Scalelite-API container only uses one core CPU.

The docker stats command result:

af71b586c1ae        scalelite-api                  99.13%              4.065GiB / 7.638GiB   53.22%

It shows the container only uses one core CPU cause the VPS CPU usage is about 25%.

Using these environment variables:
WEB_CONCURRENCY=16
RAILS_MAX_THREADS=10
didn't help.

Responding to some commands like: 
./bin/rake status
or Get Recordings has some delay.

Since I have a script that extracts meeting information from this API, I need to have no delay in response.

How we can allocate more CPU for this container? Or could we run more of this container then define them on the Nginx container?

**Comment by farhatahmad** [comment]
You could always run multiple containers and route through NGINX, but at 14 BigBlueButton servers, you really should not be having CPU problems. Are you running anything other than Scalelite on the machine?
