### ISSUE TITLE
distinguish and limit routing for certain `create` api requests

### ISSUE THREAD

**Issue by emamirazavi** [blindsidenetworks/scalelite#368]
Hello,
I want to distinguish, limit and moderate balancing(routing function) for certain `api:create` requests. for example i want to route all `create` meeting requests containing `preferredSever=bbb100` to `bbb100.example.org` and make `bbb100` server `customized` in pool of servers that `scalite` does not route to it by default. or is there a solution to create two groups of pools with two names: group1 and group2? Create requests containing `group=group1` routed to group1 pool and others routed to group2 pool! My problem is about the method of balancing. It's based on number of classes(sessions). Number of participants of our sessions are in minimum and maximum numbers! like 4 or 30 participants. We don't know how to route light sessions and big sessions to appropriate servers!  I'm using bigbluebutton plugin of moodle and don't want to change the plugin code very much. Can anybody help me by an idea or a solution? 
many many thanks.

**Comment by hostbbb** [comment]
Is/Can moodle send the maxParticipants param on the meeting create for a meeting.

**Comment by emamirazavi** [comment]
This is useful so that we don't want to scale BBB. In scaling algorithm, count of rooms per server is not comprehensive solution. Assume rooms with varied participants. 3 rooms with 4 participants and other 10 rooms with 30 participants. servers with max room count equal 4. resources are not used correctly and i some cases with more participants resources will have overloads. It may we have a server with 3 rooms with 4 participants and one room with 30 participants. In this case we have almost 150-30-3*12 empty spaces to participate more participants and more rooms in server and we can not distribute meetings optimal to our servers.

**Comment by farhatahmad** [comment]
Scalelite is currently only meant to be used for a single tenant and therefore does not have any of the features you're asking about above
