### ISSUE TITLE
Scalelite fails to create meetings with available servers online

### ISSUE THREAD

**Issue by GhaziTriki** [blindsidenetworks/scalelite#369]
Got an issue with servers today showing the message below, I confirm there is online servers.
```
<response>
<returncode>FAILED</returncode>
<messageKey>internalError</messageKey>
<message>Could not find any available servers.</message>
</response>
```

**Comment by christmart** [comment]
More info for this issue:

rake status gives multiple online servers:

bbb-71.rlp.net   enabled   online         0      0                0       0
bbb-176.rlp.net  enabled   online         0      0                0       0

tests with api-mate directly to these servers work without a problem

**Comment by christmart** [comment]
The same problem just surfaced again on our test installation.
We got rid of the problem in our production installation by clearing redis, reinstalling all bbb-nodes and reregister them in scalelite.

I think there must be a problem in the calculation of available servers.

How can we debug that?

**Comment by rabser** [comment]
In my recent experience, redis goes in readonly mode after errors about periodic "bgsave" task.
 
I solved it by adding to the redis server in /etc/sysctl.d/40-redis.conf (create the file if do not exists) 

```
vm.overcommit_memory =1 
```

and rebooted the server.

**Comment by christmart** [comment]
I can't find "bgsave" anywere in the redis logs. Where did you see it?

**Comment by GhaziTriki** [comment]
Can it be linked to https://github.com/blindsidenetworks/scalelite/issues/313 ?

**Comment by rabser** [comment]
In the redis logs, but i can't assure that your problem is the same as mine.

**Comment by rabser** [comment]
Yes, i think that my suggestions are the solution to #313...

**Comment by christmart** [comment]
I don't think that this is the same problem. 
I did not find messages about bgsave in the logs and I don't have servers disappearing from scalelite.

New installation of the BBB server again resolved the issue.
But I fear that it will happen again.

**Comment by farhatahmad** [comment]
The only way this is possible is if somehow Scalelite is unable to find any available servers. An available server is basically the enabled server with the lowest possible load. If you can replicate this, some logs from redis and scalelite-api would be helpful

**Comment by farhatahmad** [comment]
Going to close
