### ISSUE TITLE
Scalelite has no delete from recordings?

### ISSUE THREAD

**Issue by AnthonyVidal** [blindsidenetworks/scalelite#373]
I did a record delete test with the BBB API and I don't see the expected results.

1. Delete recording with API:
![image](https://user-images.githubusercontent.com/6953533/99722069-1adeff80-2a7e-11eb-94e6-79793bc6008a.png)

2. Review of deleted recording in bbb server is OK:
![image](https://user-images.githubusercontent.com/6953533/99722083-229ea400-2a7e-11eb-8561-9e1043829d10.png)

3. Allow several minutes to validate, and the recording is still not deleted from the scalelite server:
![image](https://user-images.githubusercontent.com/6953533/99722177-4661ea00-2a7e-11eb-9e81-da2f96244fba.png)
Recording is not erased on scalelite server

So? is there a proper procedure to delete old recordings on scalelite server?

**Comment by farhatahmad** [comment]
Are you making the `deleteRecordings` call to Scalelite? or to the BigBlueButton server? 

Scalelite deletes the recording file in the shared volume and not the one on the BigBlueButton server

**Comment by AnthonyVidal** [comment]
I was doing it on the client bbb server, but I understand now that I have to put together a process that deletes on the bbb server and on the scalelite server.

![image](https://user-images.githubusercontent.com/6953533/100166104-e0b09c00-2e89-11eb-9c43-3d588797e132.png)
There should be some way to delete on both servers

**Comment by farhatahmad** [comment]
Once you move them to Scalelite you should delete them from your BigBlueButton server (as mentioned in the docs)
