### ISSUE TITLE
remve servers from pool

### ISSUE THREAD

**Issue by abbas13375** [blindsidenetworks/scalelite#374]
Hi.
i setup scalite and this work successfully.

so i added 3 servers to pool. but after time my servers remove automaticly in scalelite and i can't create meetings. 

when  run this command:
./bin/rake servers

not showing any server that last time added.

pls hellppp.

**Comment by jfederico** [comment]
Hi @abbas13375, this is a pretty old issue, but I think it is covered already, isn't?

**Comment by amalrails** [comment]
closing the issue since no response.
