### ISSUE TITLE
scalelite-api sometimes fails to start

### ISSUE THREAD

**Issue by christmart** [blindsidenetworks/scalelite#376]
Sometimes scalelite-api systemd unit fails to start with these errors:

Nov 25 09:13:47 scalelite-schulen-01 docker[114349]: * Environment: production
Nov 25 09:13:50 scalelite-schulen-01 docker[114349]: ! Unable to load application: Errno::ENOENT: No such file or directory - bs_fetch:atomic_write_cache_file:rename
Nov 25 09:13:50 scalelite-schulen-01 docker[114349]: bundler: failed to load command: puma (/srv/scalelite/vendor/bundle/ruby/2.6.0/bin/puma)
Nov 25 09:13:50 scalelite-schulen-01 docker[114349]: Errno::ENOENT: No such file or directory - bs_fetch:atomic_write_cache_file:rename

Restarting the unit normaly fixes the problem at the first try but not always.

I have no idea what the problem is.

**Comment by christmart** [comment]
scalelite v1.0.8 running with docker-ce 5:19.03.8~3-0~debian-buster

**Comment by farhatahmad** [comment]
Sounds more like an environment problem than a Scalelite problem. If I had to guess, it looks like an issue connecting to Redis, but I'm not positive. Maybe try spinning up an external Redis to see if that fixes it?

**Comment by christmart** [comment]
Our scalelite already connects to an external redis server.
