### ISSUE TITLE
Change timeout

### ISSUE THREAD

**Issue by pedped** [blindsidenetworks/scalelite#377]
I am using many PDF for pre presentation, 

when I want to create a meeting, It take time download the PDF on servers, so I need to change timeout to avoid timeout

there is a file that manage timeout :

**https://github.com/blindsidenetworks/scalelite/blob/master/app/controllers/concerns/api_helper.rb**

there are two parameters

  REQUEST_TIMEOUT = 10
  CHECKSUM_LENGTH = 40

I want to change   REQUEST_TIMEOUT to 60, but I do not know how can I do that while my Scalelite is in production, 
Where is this file and how can I change that?

**Comment by farhatahmad** [comment]
You'll need to fork the code locally and build your own docker images to make that happen. Even if the pdf takes a long time to load, it really shouldn't be taking over 10s to achieve that, especially since the pdf is downloaded happens after the meeting is created
