### ISSUE TITLE
Scalelite / BigBlueButton servers do not import/transfer recorded sessions

### ISSUE THREAD

**Issue by lonesomewalker** [blindsidenetworks/scalelite#379]
We have several instances with scalelite/bbb running so far, most of them are working smooth, but on more and more instances the recordings are not transfered correctly.

Unfortunately, when looking in the bbb logs:
```
I, [2020-12-01T15:52:43.646018 #17198]  INFO -- : Running post publish script scalelite_post_publish
I, [2020-12-01T15:52:43.646078 #17198]  INFO -- : Task: Getting external meeting id
I, [2020-12-01T15:52:43.646085 #17198]  INFO -- : Task: Getting meeting metadata
I, [2020-12-01T15:52:43.689612 #17198]  INFO -- : Executing: ruby post_publish/scalelite_post_publish.rb -m 244b0191de3573143b0a5fccf40d10f0272cbd8e-1606819633347
I, [2020-12-01T15:52:43.733206 #17198]  INFO -- : Transferring recording for 244b0191de3573143b0a5fccf40d10f0272cbd8e-1606819633347 to Scalelite
I, [2020-12-01T15:52:43.733245 #17198]  INFO -- : Found recording format: presentation/244b0191de3573143b0a5fccf40d10f0272cbd8e-1606819633347
I, [2020-12-01T15:52:43.733266 #17198]  INFO -- : Creating recording archive
I, [2020-12-01T15:52:43.895783 #17198]  INFO -- : Adding extra rsync options:   
I, [2020-12-01T15:52:43.895848 #17198]  INFO -- : Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool
I, [2020-12-01T15:52:43.901215 #17198]  INFO -- : 244b0191de3573143b0a5fccf40d10f0272cbd8e-1606819633347.tar
I, [2020-12-01T15:52:47.770022 #17198]  INFO -- : 
I, [2020-12-01T15:52:47.770098 #17198]  INFO -- : sent 342,161,085 bytes  received 35 bytes  76,035,804.44 bytes/sec
I, [2020-12-01T15:52:47.770115 #17198]  INFO -- : total size is 342,077,440  speedup is 1.00
I, [2020-12-01T15:52:47.806234 #17198]  INFO -- : Success?: true
I, [2020-12-01T15:52:47.806293 #17198]  INFO -- : Process exited? true
I, [2020-12-01T15:52:47.806300 #17198]  INFO -- : Exit status: 0
```
The bbb server is connected by NFS, read/write possible, always up/available, also scalelite.

Also as you can see, the logfile says nothing strange.

Any clues where to look at? Anybody experiencing the same issue?

And yes, the spool directory is empty, no tar files there :-/

**Comment by farhatahmad** [comment]
Did you try restarting Scalelite? Restarting the recording-importer should fix the issue

**Comment by lonesomewalker** [comment]
Restarting importer, initiating re-transfer, watch moving tar files to scalelite server, works.

Okay, but it would be good to know why this happens, because this not only happened on one/all server/s so i would not think this is a configuration issue. Unfortunately i can't provide usefull logs, because as you can see on the logfile entry above: BBB server says: transfered.

Will watch this, and if there is more occurance i'll reopen.


Thanks.
