### ISSUE TITLE
Scalelite is sending Outbound Traffic Continuously

### ISSUE THREAD

**Issue by kumar-m-ecot** [blindsidenetworks/scalelite#381]
Hi,

I made the scalelite setup by referring the documentation. However, scalelite is trying to send some outbound traffic on port 54321 and 6379 continuously due to which my cloud provider is assuming this activity as suspicious leading to my IP getting blocked. Can somebody please help why this is happening exactly and how I can fix this?
output of ngrep on port 6379:
T 172.20.0.3:6379 -> 172.20.0.7:34928 [AP] #14
*8.
$3.
url.
$53.
https://edetronik-bbb1.ecosmob.net/bigbluebutton/api/.
$6.
secret.
$42.
hMKFrYvvfjeYqxDFy7gL2041iRxQhhfhTgFBFWPDHA.
$6.
online.
$4.
true.
$15.
load_multiplier.
$3.
1.0.
:1.
$1.
0
Please help!

**Comment by farhatahmad** [comment]
The outbound requests to `54321` are to the Postgres DB and to `6379` are to Redis. Not sure why you're hosting provider is blocking that, but those are extremely standard ports to communicate on. I would check with them to see why that's happening and if you can get around it. 

Also - you've pasted your BigBlueButton server secret in plain text, meaning anyone can access your server. I highly suggest you remove it from your post and then change it

**Comment by kumar-m-ecot** [comment]
Thanks @farhatahmad for the clarification about the outbound requests. However, I would like to mention one thing here. The scalelite server's IP is sending outbound traffic not to a single IP but to a whole range of IP's continuously. I would like to show you what our Provider shared with us due to which they are considering this to be suspicious.

Reason:           Server locked for performing network scans

 ##########################################################################
> #               Netscan detected from host  XXX.XXX.XXX.XXX               #
> ##########################################################################
>
> time                                protocol src_ip                      src_port      dest_ip            dest_port
> ---------------------------------------------------------------------------
> Mon Oct 12 07:14:46 2020 TCP  XXX.XXX.XXX.XXX 45890 =>   172.26.221.92 6379
> Mon Oct 12 07:14:46 2020 TCP  XXX.XXX.XXX.XXX 45846 =>   172.26.221.93 6379
> Mon Oct 12 07:36:11 2020 TCP  XXX.XXX.XXX.XXX 52048 =>   172.31.225.92 6379
> Mon Oct 12 07:36:11 2020 TCP  XXX.XXX.XXX.XXX 59620 =>   172.31.225.93 6379
> Mon Oct 12 07:36:14 2020 TCP  XXX.XXX.XXX.XXX 38238 =>   172.31.228.25 6379
> Mon Oct 12 07:36:15 2020 TCP  XXX.XXX.XXX.XXX 54784 =>   172.31.228.27 6379
> Mon Oct 12 07:36:15 2020 TCP  XXX.XXX.XXX.XXX 39618 =>   172.31.228.30 6379
> Mon Oct 12 07:36:15 2020 TCP  XXX.XXX.XXX.XXX 52816 =>   172.31.228.70 6379
> Mon Oct 12 07:36:15 2020 TCP  XXX.XXX.XXX.XXX 57706 =>   172.31.228.71 6379
> Mon Oct 12 07:36:15 2020 TCP  XXX.XXX.XXX.XXX 33704 =>  172.31.228.180 6379
> Mon Oct 12 07:36:15 2020 TCP  XXX.XXX.XXX.XXX 38734 =>  172.31.228.181 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 39560 =>  172.31.228.205 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 44422 =>  172.31.228.208 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 48948 =>  172.31.228.209 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 36170 =>  172.31.228.210 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 51886 =>  172.31.228.211 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 38644 =>  172.31.228.213 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 42594 =>  172.31.228.215 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 45308 =>  172.31.228.216 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 34944 =>  172.31.228.218 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 38506 =>   172.31.229.56 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 42128 =>   172.31.229.57 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 39784 =>   172.31.229.58 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 49714 =>   172.31.229.59 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 47570 =>   172.31.229.60 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 37180 =>   172.31.229.61 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 35990 =>   172.31.229.62 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 39212 =>   172.31.229.63 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 40558 =>   172.31.229.67 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 44248 =>   172.31.229.68 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 43406 =>   172.31.229.69 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 48076 =>   172.31.229.70 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 53570 =>   172.31.229.71 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 57432 =>  172.31.229.160 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 41622 =>  172.31.229.161 6379
> Mon Oct 12 07:36:16 2020 TCP  XXX.XXX.XXX.XXX 43920 =>  172.31.229.178 637..

(Here XXX.XXX.XXX.XXX is Scalelite server's IP)

Your suggestions are appreciated. Also if some kind of blog or documentation is available with you for the scalelite setup with greenlight, then can you please share that with me?

Thanks in advance.

**Comment by kfern** [comment]
Same here. Our connectivity provider advised us that the server could be participating in a DDos attack

**Comment by kumar-m-ecot** [comment]
Hi @farhatahmad 

Can you help in this matter please?

**Comment by t-markmann** [comment]
Have a look at this: 

https://medium.com/@falahatnejad.work/please-note-that-ce7773103373

If you install scalelite by this way, you must follow this instructions:

1- open the file "docker-compose.yml" by type command:

nano /root/scalelite-run/docker-compose.yml

then in line 14 change "127.0.0:5432:5432" for postgress ports to "127.0.0.1:5432:5432"

2- open the file "pg_hba.conf" by type the command :

nano /var/lib/docker/volumes/scalelite-run_postgres-data/_data/pg_hba.conf

then in line 95 change the "md5" to "trust"


Restart everything with
docker-compose down
docker-compose up -d

You could additionally work with UFW rules or IPTables, but the problem should be solved by setting the above config.
