### ISSUE TITLE
Issue scalelite docker network

### ISSUE THREAD

**Issue by SebastianZiegler** [blindsidenetworks/scalelite#382]
Hello,

is there a way to change the default scalelite docker from 172.18.0.0/16 to something different? We use a 172.18.1.0/24 network in our organisation, what leads to the problem, that the user in this network cannot access scalelite.
Tried by define the /etc/docker/deamon.json but this only works for one docker adapter. Has anybody an idea?

Thx

**Comment by erisd** [comment]
This ist part of your Docker Network Configuration...
