### ISSUE TITLE
error 404 for Loading all recording

### ISSUE THREAD

**Issue by hmahdi-s** [blindsidenetworks/scalelite#385]
I'm using Greenlight for frontend. At the beginning recording list was working for admin. but now when I click on recording after while,i get 404 error!
may it happened because of number of recording files?
I'm sure the recording process doesn't have error and everyone can see own recorded meeting.
I try to restart Greenlight by docker-compose down and docker-compose up -d. but it wasn't efficient.

**Comment by farhatahmad** [comment]
Are you talking about the Server Recordings page? If so, see the note here: https://docs.bigbluebutton.org/greenlight/gl-admin.html#server-recordings

**Comment by hmahdi-s** [comment]
@farhatahmad 
No.
the recording process working fine. every user can see own recorded files. but when i click on recording as user i see 404 error.
 I think getRecording method not working true in scalelite.

**Comment by hmahdi-s** [comment]
Restart scalelite solved this problem.
