### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by chezmohamed** [blindsidenetworks/scalelite#386]
Hello I managed to deploy Scalelite by following the tutorial:
https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6
I noticed that this method is diferent than that of official documentation
Is this method which is on this tutorial reliable for a production environment?
for the management of 3 bigbluebutton servers only
thank you

**Comment by cmersinli** [comment]
hi , @chezmohamed  
yes it is reliable . I have been using it for a long time for a production environment.
I must say it's better than the original document

**Comment by chezmohamed** [comment]
Great
A big thank you for your reply
