### ISSUE TITLE
Unpublished recordings

### ISSUE THREAD

**Issue by parsa25eng** [blindsidenetworks/scalelite#388]
Hi. 
I have some BBB servers behind a Scalelite.
My recording repository has worked well for some months. recently I have some reports from users that some of the recordings are not available. when I checked the Scalelite, I saw that some contents under the "unpublished" directory. usually, when a recording is prepared on a BBB server, it is transferred to the "spool" directory of Scalelite and then extracted to the "published" directory.
Now, my question is why this issue has happened and how I can fix it?
thanks.

**Comment by farhatahmad** [comment]
You could try republishing the recordings

https://docs.bigbluebutton.org/dev/recording.html#republish-recordings
