### ISSUE TITLE
letsencrypt 

### ISSUE THREAD

**Issue by chezmohamed** [blindsidenetworks/scalelite#390]
I managed to install scalelite using the official documentation: https://github.com/blindsidenetworks/scalelite/
everything works impeccable.
I just have how to activate https using letsencrypt with automatic certificate renewal?
does anyone have a tutorial to follow to ensure the security of nginx in https?
do i have to use a certbot container? if so how do I make it work with nginx
Thank you

**Comment by ds2020italy** [comment]
I did this procedure and works:

apt install letsencrypt
systemctl status certbot.timer
sudo certbot certonly --standalone --agree-tos --preferred-challenges http -d domain.ext

**Comment by chezmohamed** [comment]
it works wonderfully thank you very much
another question:
Does the certificate renew itself automatically or do I have to redo this procedure before expiration?
Thank you again

**Comment by ds2020italy** [comment]
I'm not an expert but on Ubuntu it should renew itself automatically. For this reason, in the second command I indicated (systemctl status certbot.timer) we ask the system to verify the correct functioning of the timer.
Let me know

**Comment by chezmohamed** [comment]
OK we'll see
Thank you so much

**Comment by farhatahmad** [comment]
@ds2020italy Thank you for sharing

**Comment by ds2020italy** [comment]
It's a pleasure
