### ISSUE TITLE
scalelite-recording-importer does not import recordings

### ISSUE THREAD

**Issue by glu000** [blindsidenetworks/scalelite#395]
I used these instructions to setup a scalelite server (part 1 and 2): https://jffederico.medium.com/scalelite-lazy-deployment-part-ii-ca3e4bf82f8d I did not change any default values or paths

After recording a meeting, the BBB-server successfully processes the recording and transfers the .tar file with rsync to the scalelite server and I can see it there:

    ls /var/bigbluebutton/spool/
    fb1154e0f1270a0301b9efd208e82afd0e9b4bfc-1610229669589.tar

Also the docker container `scalelite-recording-importer` is up and running. 

    docker ps                             
    CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS          PORTS                                      NAMES
    89e8b0cd0f50   blindsidenetwks/scalelite:v1-nginx                "/etc/nginx/start -g…"   20 minutes ago   Up 20 minutes   
    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   scalelite-nginx
    4dbdf4e326a3   blindsidenetwks/scalelite:v1-recording-importer   "bin/start-recording…"   20 minutes ago   Up 20 minutes                                              scalelite-recording-importer
    b5fb32035144   blindsidenetwks/scalelite:v1-poller               "bin/start-poller"       20 minutes ago   Up 20 minutes                                              scalelite-poller
    088caf68b94d   blindsidenetwks/scalelite:v1-api                  "bin/start"              20 minutes ago   Up 20 minutes   3000/tcp                                   scalelite-api
    b3f362c1e543   certbot/certbot                                   "/bin/sh -c 'trap ex…"   21 minutes ago   Up 21 minutes   80/tcp, 443/tcp                            certbot
    3e443469676b   redis:5.0-alpine                                  "docker-entrypoint.s…"   21 minutes ago   Up 20 minutes   6379/tcp                                   redis
    1e6a32193e91   postgres:11.5-alpine                              "docker-entrypoint.s…"   21 minutes ago   Up 20 minutes   5432/tcp                                   postgres`

Based on the info in the logfile everything seems to be OK. The importer is monitoring the correct spool-directory

    sudo docker logs scalelite-recording-importer
    I, [2021-01-09T22:31:36.860178 #7]  INFO -- : Monitoring /var/bigbluebutton/spool for new recording files
    D, [2021-01-09T22:31:36.860316 #7] DEBUG -- : Checking for existing files… 
    D, [2021-01-09T22:31:36.860350 #7] DEBUG -- : Starting file monitor…

But it seems, that the file in the spool-directory is not processed by scalelite, because the working directory keeps empty:

    ls /var/bigbluebutton/recording/scalelite
    root@scalelite:/var/bigbluebutton# 

Any ideas what could be wrong?

One more info: `SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings` is set in `/etc/default/scalelite`

**Comment by Davka** [comment]
Do the BBB nodes write successfully to the spool directory?

**Comment by Davka** [comment]
Remove `FileUtils.mkdir_p (spool_dir)` from scalelite_post_publish.rb and try again


#400

**Comment by glu000** [comment]
Removing `FileUtils.mkdir_p (spool_dir)` does not help.
