### ISSUE TITLE
nginx: could not add new SSL session to the session cache while SSL handshaking

### ISSUE THREAD

**Issue by lonesomewalker** [blindsidenetworks/scalelite#397]
After debugging further, the logfile says:
[alert] 869#869: *4201234 could not allocate new session in SSL session shared cache "ScaleliteSSL" while SSL handshaking, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:443

When entering docker container, session cache is set to 2M, consider raising that to at least 10M.

**Comment by crosscodr** [comment]
I run into this issue too.
Increasing the session cache would help a lot!

**Comment by crosscodr** [comment]
When I look to the nginx-ssl-template, I would assume, that a ssl_session_timeout of `1d` is much to long for a `10m` ssl_session_cache.
https://github.com/blindsidenetworks/scalelite/blob/master/nginx/conf.d/scalelite-ssl.template#L23

**Comment by lonesomewalker** [comment]
Just have a look at all the other config files... there are more parts which can (and should) be improved...

**Comment by ffdixon** [comment]
Let us know the suggestions you have for other parts.  Scalelite is under active development.
