### ISSUE TITLE
joining running session is blocked if all servers are disabled

### ISSUE THREAD

**Issue by christmart** [blindsidenetworks/scalelite#398]
All servers where disabled to not let any new conferences be started on all servers.
Users who wanted to join a conference which was started before all servers where disabled get
"An error occured" like when the secrets are wrong or when you try to start a new conference when all servers are disabled.

To reproduce:

- start and join a new conference
- disable all servers in scalelite
- try to join this conference from another window/browser/user

expected bahavior:

- it should be possible to join an already running conference even if the server was disabled after starting the conference.

Greeting
Christoph

**Comment by Nemental** [comment]
I can confirm this behavior.

**Comment by mschwrdtnr** [comment]
Since Release 1.1 it is not intended to join meetings of disabled servers but this problem still exists for the new state `cordon` as in #620 mentioned. I think this issue can closed and #620 schould be fixed.
