### ISSUE TITLE
Scalelite cluster using 1-2 public addresses

### ISSUE THREAD

**Issue by avkovalevs** [blindsidenetworks/scalelite#399]
During deployment of 3 BBB nodes with Scalelite  node we were faced with the fact that there are not so many public addresses as we need.  Is it possible to use one public ip (with any DNS names) for the BBB and Scalelite nodes and the second public ip for the coturn node? As I know, Scalelite node has  the Nginx and it will redirect traffic to BBB nodes.  However, there are doubts about the Freeswitch software.  Could you please explain what the deployment options are with a pair of public addresses?
Do we need to do SSL termination on Scalelite Nginx  and forward http traffic to BBB nodes?
Thanks, Alex

**Comment by farhatahmad** [comment]
> Is it possible to use one public ip (with any DNS names) for the BBB and Scalelite nodes and the second public ip for the coturn node?

Unfortunately not. You need a public IP for each BigBlueButton server and for each Scalelite server you plan on running
