### ISSUE TITLE
Scalelite and ufw: which ports are used?

### ISSUE THREAD

**Issue by ethpi** [blindsidenetworks/scalelite#404]
Thanks for your great work on scalelite. 

Unfortunately I'm not familar whith scalelite but I managed to setup a scalelite server properly with this manual: [https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6](https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6)
Now I'd like to add a firewall with ufw. Which ports have to be open for scalelite?

**Comment by andrekutianski** [comment]
External ports used are only 80 and 443

![image](https://user-images.githubusercontent.com/5316107/105720102-cf275700-5f01-11eb-8331-67c9e7151c45.png)

**Comment by ethpi** [comment]
When no meeting runs on my servers I'll activate ufw. Thanks.

**Comment by andrekutianski** [comment]
> When no meeting runs on my servers I'll activate ufw. Thanks.

Whether you have meetings running or not these will be the ports used by Scalelite ;)

**Comment by ethpi** [comment]
You are totally right. It works great. 
But I'm really worried, because there is a whole school with about 1000 students who want to use BBB. And if I make a mistake, the "whole school is locked" and I will receive many many mails. 
Thanks.
