### ISSUE TITLE
running meeting not found 

### ISSUE THREAD

**Issue by moonesque** [blindsidenetworks/scalelite#407]
There is a running meeting on a bbb instance, direct API calls to the bbb instace using the said meetingID work with no problem, I can see the meeting info or join the meeting.
API calls to scalelite using the meetingID return notFound.
This seems rather strange, because I can see the meeting in a getMeetings call to scalelite, but I can't use the meetingID to make an API call.
Note the meetingID in the browser address bar being the same in the attached screenshots, one being an API call to bbb instance(vc1.namaja.digital) and the other being to scalelite(namaja.digital/vc).

![scalelite](https://user-images.githubusercontent.com/20132372/106019780-46164880-60d8-11eb-9a84-5d44d859fa86.jpg)
![direct](https://user-images.githubusercontent.com/20132372/106019808-4ca4c000-60d8-11eb-864f-978e8a5ff068.jpg)

**Comment by andrekutianski** [comment]
Here Scalelite brings the Meeting Info correctly.

![image](https://user-images.githubusercontent.com/5316107/106047036-dac17c00-60c1-11eb-9b1a-893e49f1990a.png)

**Comment by moonesque** [comment]
I'm sure it does. It works correctly mostly in my experience as well, but I've encountered some cases where scalelite responds with notFound, like the one I sent evidence of. Any idea what could this be about or what I should look into?

**Comment by farhatahmad** [comment]
Your best bet is to check the poller to see why its not pick up that meeting. If you run `docker logs scalelite-nginx | grep <MEETING_ID>`  you may find some information there
