### ISSUE TITLE
Monitoring Scalelite

### ISSUE THREAD

**Issue by VeNoMZiTo** [blindsidenetworks/scalelite#409]
Hello, is there any way to monitor every  server connected to Scalelite at the same time? without having to monitor them one by one

**Comment by crazy-daddy** [comment]
Yes and no.
You can't grab one stream provided by scalelite. You can however aggregate the information of all the servers. See https://bigbluebutton-exporter.greenstatic.dev/#multiple-bigbluebutton-servers-dashboard

**Comment by farhatahmad** [comment]
You can also get a quick overview of all servers using the `rake status` command https://github.com/blindsidenetworks/scalelite#check-the-status-of-the-entire-deployment
