### ISSUE TITLE
One room maximum per BBB server

### ISSUE THREAD

**Issue by lakano** [blindsidenetworks/scalelite#413]
Hello,

Thanks for your great work!

As we never really known how much a room could increase in the next minutes/hours in resources (video, participants...), the current scalelite behaviour doesn't fully works for our case.

Our idea is to have a pool of BBB servers, and to never add more than one room per BBB server. So, we keep a good quality even if some room grow or request more video in few minutes/hours. 

Is it possible to limit scalelite in this way ? 

Regards

**Comment by crazy-daddy** [comment]
But what should scalelite do if there are more rooms than servers?

By default it should already assign 1 room to each server and then cycle through the servers again, adding 1 more room. So given a sufficiently large pool of servers, it should work out of the box.

**Comment by lakano** [comment]
> But what should scalelite do if there are more rooms than servers?

In theory this shouldn't happen, because we should have enough servers in the pool. We have a planning of meetings, so we can always reserve enough servers.  

> By default it should already assign 1 room to each server and then cycle through the servers again, adding 1 more room. So given a sufficiently large pool of servers, it should work out of the box.

Ok thanks, because I've seen in some issues there is others metrics used to decide.
