### ISSUE TITLE
Remove recorded files older than N days in Scalelite

### ISSUE THREAD

**Issue by hmahdi-s** [blindsidenetworks/scalelite#417]
Is there any script to remove older recorded files as cron job like [bbb server](https://docs.bigbluebutton.org/2.2/customize.html#delete-recordings-older-than-n-days)?

**Comment by atikulbd** [comment]
Yes. Here is the url:
```
https://docs.bigbluebutton.org/2.2/customize.html#delete-recordings-older-than-n-days
```
Put the code inside:
```
/etc/cron.daily/bbb-recording-cleanup
```
And set permission to **755**
```
chmod +x /etc/cron.daily/bbb-recording-cleanup
```

You can change the value of ***MAXAGE*** to specify how many days of recordings you want to preserve.
Done

**Comment by hmahdi-s** [comment]
@atikulbd 
I wrote that link. 
But i want to remove recorded files from scalelite server. not BBB server

**Comment by atikulbd** [comment]
Ah! My mistake.
I will write a script for **Scalelite** and send you here shortly.

**Comment by hmahdi-s** [comment]
@atikulbd 
That's kind of you
Thank you

**Comment by amg-web** [comment]
here the script:
`#/bin/bash
URI=domain
SALT=SALT
MAX_AGE=60

MAX_DATE=$(date -I -d "-$MAX_AGE days")

for MEET in $(sudo -u postgres -H -- psql -d scalelite -c "SELECT record_id FROM recordings WHERE starttime < '$MAX_DATE';"); do

LINK="deleteRecordingsrecordID=$MEET$SALT"

KEY=$(echo -n "$LINK" | openssl sha1 |awk '{print $2}')

FLINK="https://$URI/bigbluebutton/api/deleteRecordings?recordID=$MEET&checksum=$KEY"
echo "deleting $MEET"
curl $FLINK
done`

**Comment by faust64** [comment]
In your for look, I think you should also remove the recording from filesystem:

```
#/bin/bash

URI=domain
SALT=SALT

MAX_AGE=60
MAX_DATE=$(date -I -d "-$MAX_AGE days")

for MEET in $(sudo -u postgres -H -- psql -d scalelite -c "SELECT record_id FROM recordings WHERE starttime <'$MAX_DATE';")
do
    LINK="deleteRecordingsrecordID=$MEET$SALT"
    KEY=$(echo -n "$LINK" | openssl sha1 | awk '{print $2}')
    FLINK="https://$URI/bigbluebutton/api/deleteRecordings?recordID=$MEET&checksum=$KEY"
    echo "deleting $MEET"

    curl "$FLINK"

## OR, querying the scalelite-api container directly:
#    curl --header "Host: $URI" \
#        --header "X-Forwarded-Proto: https" \
#        "http://127.0.0.1:3000/bigbluebutton/api/deleteRecordings?recordID=$MEET&checksum=$KEY"
##//

    rm -fr "/var/bigbluebutton/published/presentation/$MEET"
done
```

**Comment by amg-web** [comment]
> I think you should also remove the recording from filesystem,
no. files are removed by API

**Comment by faust64** [comment]
oh, nevermind then. Thanks!

**Comment by mikesrus** [comment]
> In your for loop, I think you should also remove the recording from filesystem, ... something like:
> 
> ```
> #/bin/bash
> 
> URI=domain
> SALT=SALT
> RECS_ROOT=/var/bigbluebutton
> 
> MAX_AGE=60
> MAX_DATE=$(date -I -d "-$MAX_AGE days")
> 
> for MEET in $(sudo -u postgres -H -- psql -d scalelite -c "SELECT record_id FROM recordings WHERE starttime <'$MAX_DATE';")
> do
>     LINK="deleteRecordingsrecordID=$MEET$SALT"
>     KEY=$(echo -n "$LINK" | shasum | awk '{print $1}')
>     FLINK="https://$URI/bigbluebutton/api/deleteRecordings?recordID=$MEET&checksum=$KEY"
>     echo "deleting $MEET"
> 
>     curl "$FLINK"
> 
> ## OR, querying the scalelite-api container directly:
> #    curl --header "Host: $URI" \
> #        --header "X-Forwarded-Proto: https" \
> #        "http://127.0.0.1:3000/bigbluebutton/api/deleteRecordings?recordID=$MEET&checksum=$KEY"
> ##//
> 
>     rm -fr "$RECS_ROOT/published/presentation/$MEET"
> done
> ```

Hi, I'm trying to use your script to delete old recordings from scalelite and the files on disk are indeed being deleted.
But it seems that using the api does not remove the record from the database

if I follow the link myself 
`https://scalelite.domain.com/bigbluebutton/api/deleteRecordings?recordID=d5dv978ea1b39ef725cdf9vab03e8ffd0b67ae3c-1598893521671&checksum=7va600a5595847a3Vf66v2f0716b88fe6V39c535`
then I constantly get
```
<response>
<returncode>SUCCESS</returncode>
<deleted>true</deleted>
</response>
```
although logically it should be the first time, and then I should get 

```
<response>
  <returncode>FAILED</returncode>
  <messageKey>notFound</messageKey>
  <message>We could not find recordings</message>
</response>
```
but this is not happening.
where am I going wrong?

**Comment by amg-web** [comment]
api marks record as deleted in db
but record remains in db
