### ISSUE TITLE
Change IP Address

### ISSUE THREAD

**Issue by atikulbd** [blindsidenetworks/scalelite#418]
Dear **Scalelite** team,
I need help in an awkward situation. I've configured **Scalelite** with 6 **BBB** servers for a school and the server is in production use. 
Suddenly, the Datacenter said they mistakenly assigned the IP subnet (I purchased) to me which is in production use and asked to change the IP/subnet.
Class already started, lots of recording data inside server. If I change the IP address of Scalelite server and the **BBB** servers, will it affect the service? I use hostname rather than IP for **BBB** servers like:
```
srv1.school.com
srv2.school.com
srv3.school.com
```
And, for **Scalelite**,
```
sc.school.com
```
For DB (**PostgreSQL**):
```
db.school.com
```

I didn't change IP of **Scalelite**, **BBB** previously and don't know the consequences.
What is the proper way to change IP of both **Scalelite** and **BBB** servers? What commands should I use?

**Comment by lonesomewalker** [comment]
DNS is the key to go.
Scalelite doesn't care about IP addresses.
If the hostnames resolve, everything will work fine.

**Comment by atikulbd** [comment]
Thank you Walker. I've never seen such a kind **support agent** like you.
```
Thank you again for your kind support.
```
I will leave a **5-star** (_Excellent_) support feedback.
**Have a lovely day!**
