### ISSUE TITLE
Adapt scalelite for our use case 

### ISSUE THREAD

**Issue by lakano** [blindsidenetworks/scalelite#429]
Hello,

In our case, room could start with only 5 persons inside for few hours, but can grow to 100 to 200 later in the day, on the same room... so it's not good with current scalelite strategy.

We creating a tool, to make a planning of meetings, with date, hours, number of maximum expected users, so we can manage the best method of where to put each room, based on the invitation link.

What is your advice for the best solution for us to include our logic in the Scalelite server choice decision ?  

Regards

**Comment by mschwrdtnr** [comment]
Hey @lakano is your calendar open source? This sounds interesting.

**Comment by lakano** [comment]
@mschwrdtnr It's an internal tools linked to others specific stuff to a client, so it's really specific and not a generic tool, but may be we can try to split it or to extract a part and release it in open source.

**Comment by mschwrdtnr** [comment]
Maybe this can be a combination with https://github.com/bigbluebutton/greenlight/issues/1009.

Let me know if you publish something like you mentioned. Maybe I can participate 😄
