### ISSUE TITLE
scalelite_post_publish.rb fails

### ISSUE THREAD

**Issue by relecand** [blindsidenetworks/scalelite#449]
```
I, [2021-02-24T18:37:38.343811 #32477]  INFO -- : Executing: ruby post_publish/scalelite_post_publish.rb -m 00b182d7ae9edb5d19fe22a7d5ea3f820f501add-1614187924586
I, [2021-02-24T18:37:38.400083 #32477]  INFO -- : /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /usr/local/bigbluebutton/lib/recordandplayback (LoadError)
I, [2021-02-24T18:37:38.400143 #32477]  INFO -- : 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
I, [2021-02-24T18:37:38.400168 #32477]  INFO -- : 	from post_publish/scalelite_post_publish.rb:23:in `<main>'
```

Related to 

- https://github.com/blindsidenetworks/scalelite/commit/5cfb817471032cd0aadde2a452b3c662ebe358bb
- https://github.com/blindsidenetworks/scalelite/pull/447/commits

BBB 2.2.31

All the best,

Christian

**Comment by relecand** [comment]
in /usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb

I changed 

`require File.expand_path('../../../lib/recordandplayback', __dir__)`

to

`require File.expand_path('../../../core/lib/recordandplayback', __dir__)`

Then it worked.

**Comment by jfederico** [comment]
Thanks @relecand. It should actually be

`require File.expand_path('../../lib/recordandplayback', __dir__)`
