### ISSUE TITLE
Release 1.0.10?

### ISSUE THREAD

**Issue by tibroc** [blindsidenetworks/scalelite#460]
Hey guys,

there is a `1.0.10` version of scalelite out there (on dockerhub and as tag). Is this not yet official or pending in any way?

**Comment by ichdasich** [comment]
This has to be put out with release notes (and those for 1.0.9 must be updated); Things changed around recording import (see #448; Guess it might have to do with newly introduced variables.)

**Comment by jfederico** [comment]
Correct @ichdasich. 1.0.10 was meant to be released today, but it had to be anticipated on Friday due a some deployments broken in production. But it is missing the release notes


We are going to change the flow for releases too as there are some breaking changes coming up that may lead to a new minor version, so 1.0 may end up being branched.
