### ISSUE TITLE
Server poll problem

### ISSUE THREAD

**Issue by penguennoktanet** [blindsidenetworks/scalelite#461]
This problem is in 1.0.10 version and I think this is related to SL-83 (https://github.com/blindsidenetworks/scalelite/commit/acb04670dd9e6e7c7e6522a811e8bf83237c9702) .

We have 20 BBB servers with a scalelite. Today, a new semester started. Before it we upgraded the software versions. But with 1.0.10 scalelite-api service is not running smoothly. It sometimes runs perfectly, sometimes not works.

I traced the problem to polling mechanism.  On poller logs there are many logs like;
WARN -- : Failed to get server id=dca0eeb1-1531-4abf-b245-ca62bb732c4b status: Net::OpenTimeout
WARN -- : Failed to check meeting id=1de378f594a0275b77e6f31ed758fc0172333307-6320-53234 status: execution expired (I know this one is releated to meetings, but had seen with server id)

But servers are ok with CPU load of %60-70. I think the default times are too low and they need to be increased little.

Thanks.

**Comment by jfederico** [comment]
By default CONNECT_TIMEOUT is set to 5 and RESPONSE_TIMEOUT to 10, but both can now be configured.

See https://github.com/blindsidenetworks/scalelite/commit/acb04670dd9e6e7c7e6522a811e8bf83237c9702

Before this change the polling was done using REQUEST_TIMEOUT=10 for both open_timeout and read_timeout. If you want it to be as before just set up CONNECT_TIMEOUT=10

**Comment by penguennoktanet** [comment]
Thanks. I missed that these are configuable.
