### ISSUE TITLE
Adding tools for supporting autoscaling

### ISSUE THREAD

**Issue by UrNas** [blindsidenetworks/scalelite#462]
Hi

I am trying to run cron job inside scalite load balancer machine to check how many users are online in BBB server , if the number of users more then 25. than the  cron job send message to cloud function and the cloud function add new BBB server machine to scalite pool.

the idea is. I do not want to add 10 machines to pool and let them running all time  because that increase the cost,  is possible to shutdown all machines except one it always running  and than add extra servers  one by one based on number of users

**Comment by jfederico** [comment]
Scale Lite as it is does not have any support for auto-scaling. 

But, if you already have all the wiring for spinning on and off servers upon a get request, it would not be difficult to create a rake task (out of the current poll) and a starter (out of the current start-poller) for doing that polling and triggering that request you need.

**Comment by andrekutianski** [comment]
maybe having this suggestion #289 will help accomplish your need?

**Comment by pielonet** [comment]
Hi,
We developped this functionnality as an external project to Scalelite : [DiViM-S](https://gitlab.com/arawa/DiViM-S). It is currently compatible only with the French Hoster Scaleway. It could be made compatible with your hosting service as well. PLease contact me if needed.
Kind regards,
Thierry

**Comment by farhatahmad** [comment]
Server Management API has been added to 1.5.1
