### ISSUE TITLE
inconsistent response times

### ISSUE THREAD

**Issue by penguennoktanet** [blindsidenetworks/scalelite#468]
Last 2 days, my scalelite server started to response inconsistently. I have a log output of scalelite-api below for 3 getMeetings requests for 20 BBB servers and with no active meeting. Time varies between  0.5 seconds to 15 seconds.

Any pointers? 

I, [2021-03-01T20:19:36.311878 #6]  INFO -- : [a9426785-611a-47f3-bd2a-3163668e5d1b] Started GET "/bigbluebutton/api/getMeetings?checksum=CHECKSUM" for 92.204.53.242 at 2021-03-01 20:19:36 +0000
I, [2021-03-01T20:19:36.313414 #6]  INFO -- : [a9426785-611a-47f3-bd2a-3163668e5d1b] Processing by BigBlueButtonApiController#get_meetings as XML
I, [2021-03-01T20:19:36.313569 #6]  INFO -- : [a9426785-611a-47f3-bd2a-3163668e5d1b]   Parameters: {"checksum"=>"CHECKSUM"}
I, [2021-03-01T20:19:42.711432 #6]  INFO -- : [a9426785-611a-47f3-bd2a-3163668e5d1b] Completed 200 OK in 6398ms (Views: 0.4ms | ActiveRecord: 0.0ms | Allocations: 26339)
I, [2021-03-01T20:19:44.559092 #6]  INFO -- : [305d991b-e2d6-426a-b6ae-98b88ed87c19] Started GET "/bigbluebutton/api/getMeetings?checksum=CHECKSUM" for 92.204.53.242 at 2021-03-01 20:19:44 +0000
I, [2021-03-01T20:19:44.560274 #6]  INFO -- : [305d991b-e2d6-426a-b6ae-98b88ed87c19] Processing by BigBlueButtonApiController#get_meetings as XML
I, [2021-03-01T20:19:44.560303 #6]  INFO -- : [305d991b-e2d6-426a-b6ae-98b88ed87c19]   Parameters: {"checksum"=>"CHECKSUM"}
I, [2021-03-01T20:19:59.863861 #6]  INFO -- : [305d991b-e2d6-426a-b6ae-98b88ed87c19] Completed 200 OK in 15303ms (Views: 0.4ms | ActiveRecord: 0.0ms | Allocations: 32734)
I, [2021-03-01T20:20:05.915101 #6]  INFO -- : [4bc6323f-7f6a-4ce4-a4ca-9257f7056dce] Started GET "/bigbluebutton/api/getMeetings?checksum=CHECKSUM" for 92.204.53.242 at 2021-03-01 20:20:05 +0000
I, [2021-03-01T20:20:05.916589 #6]  INFO -- : [4bc6323f-7f6a-4ce4-a4ca-9257f7056dce] Processing by BigBlueButtonApiController#get_meetings as XML
I, [2021-03-01T20:20:05.916742 #6]  INFO -- : [4bc6323f-7f6a-4ce4-a4ca-9257f7056dce]   Parameters: {"checksum"=>"CHECKSUM"}
I, [2021-03-01T20:20:06.476438 #6]  INFO -- : [4bc6323f-7f6a-4ce4-a4ca-9257f7056dce] Completed 200 OK in 559ms (Views: 0.5ms | ActiveRecord: 0.0ms | Allocations: 16483)

**Comment by jfederico** [comment]
I would check the POLL_INTERVAL variables introduced in the last two releases. If you are running 1.0.9, update to 1.0.10, that is making it work in the way it was https://github.com/blindsidenetworks/scalelite/pull/454/files

Keep in mind that in 1.0.10 there is still one variable you must have manually defined as it does not have a default value (in that release). That is RECORDING_DISABLED=false, but only if you have recordings in your deployment.
