### ISSUE TITLE
GET_MEETINGS_API_DISABLED has no effect in Docker Setup

### ISSUE THREAD

**Issue by BrutalBirdie** [blindsidenetworks/scalelite#473]
Using this Setup https://github.com/jfederico/scalelite-run

I added this to the docker-compose.yml of the `scalelite-api`:

https://github.com/jfederico/scalelite-run/blob/b4da8beaa4936664f4348f2c1f88e705634465f7/docker-compose.yml#L61-L66

```yml
- GET_MEETINGS_API_DISABLED=${GET_MEETINGS_API_DISABLED}
```
and added this to the `.env` file as well:

```
### Optional Disable get Meetings API
GET_MEETINGS_API_DISABLED=true
```

Stepping inside the container:

```bash
~/scalelite-run# docker exec -it scalelite-api /bin/sh
~ $ printenv
RAILS_LOG_TO_STDOUT=1
DATABASE_URL=postgres://nope:nope@postgres:5432/scalelite?pool=5
HOSTNAME=74645ae8b116
SHLVL=1
HOME=/srv/scalelite
LOADBALANCER_SECRET=nope
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
BUILD_NUMBER=v1.0.10
URL_HOST=this.domain.tld
RAILS_ENV=production
SECRET_KEY_BASE=nope
GET_MEETINGS_API_DISABLED=true
PWD=/srv/scalelite
REDIS_URL=redis://redis:6379
```

```
$ echo $GET_MEETINGS_API_DISABLED
true
```

But testing with https://mconf.github.io/api-mate/ the getmeetings and get meetingsinfo still works.

From reading:
https://github.com/blindsidenetworks/scalelite/search?q=GET_MEETINGS_API_DISABLED
I am no ruby dev, but from reading that code it looks like it checks if if the environment variable `GET_MEETINGS_API_DISABLED` is true and the changes the route to disable the api.
https://github.com/blindsidenetworks/scalelite/blob/3f7e73b4bb3ada31beafc9502b94eaa6b9a9821d/config/routes.rb#L10-L13

**Comment by amalrails** [comment]
@BrutalBirdie the get _meetings_disabled api responds with the message "'There are not recordings for the meetings", i tried testing with https://mconf.github.io/api-mate/ , created few meetings and called get_meetings api, it responded with 'There are not recordings for the meetings' message. Is that what you tried too?

**Comment by BrutalBirdie** [comment]
Strange.
Now `getMeetings` returns
```xml
<response>
<script/>
<returncode>SUCCESS</returncode>
<messageKey>noMeetings</messageKey>
<message>No meetings were found on this server.</message>
</response>
```
I know for a fact there are multible meetings running behind this scalelite (around 5 Meetings / Rooms are active)
But is this the correct output?
From code:
https://github.com/blindsidenetworks/scalelite/blob/acb04670dd9e6e7c7e6522a811e8bf83237c9702/app/controllers/bigbluebutton_api_controller.rb#L134-L137

But when I run `getMeetingInfo` I get

```xml
<response>
<script/>
<returncode>SUCCESS</returncode>
<meetingName>github-issue-demo</meetingName>
<meetingID>github-issue-demo</meetingID>
<internalMeetingID>0fee0a57c760f44609bd686aa90be2b443ba050c-1614764960434</internalMeetingID>
<createTime>1614764960434</createTime>
<createDate>Wed Mar 03 09:49:20 UTC 2021</createDate>
<voiceBridge>70018</voiceBridge>
<dialNumber>613-555-1234</dialNumber>
<attendeePW>github-issue-demo</attendeePW>
<moderatorPW>github-issue-demo</moderatorPW>
<running>true</running>
<duration>0</duration>
<hasUserJoined>true</hasUserJoined>
<recording>false</recording>
<hasBeenForciblyEnded>false</hasBeenForciblyEnded>
<startTime>1614764960451</startTime>
<endTime>0</endTime>
<participantCount>1</participantCount>
<listenerCount>0</listenerCount>
<voiceParticipantCount>1</voiceParticipantCount>
<videoCount>0</videoCount>
<maxUsers>0</maxUsers>
<moderatorCount>1</moderatorCount>
<attendees>
<attendee>
<userID>w_u1pfpvg52n92</userID>
<fullName>github-issue-demo</fullName>
<role>MODERATOR</role>
<isPresenter>true</isPresenter>
<isListeningOnly>false</isListeningOnly>
<hasJoinedVoice>true</hasJoinedVoice>
<hasVideo>false</hasVideo>
<clientType>HTML5</clientType>
</attendee>
</attendees>
<metadata> </metadata>
<isBreakout>false</isBreakout>
</response>
```
From your message @amalrails 
> the get _meetings_disabled api responds with the message "'There are not recordings for the meetings"

Which does not match with my above output of `getMeetings`

I not sure if this now works as intended.
This option is really important to me, since I host in Germany and need to comply with DSGVO / GDPR since this setup is meant to be a shared BigBlueButton Cluster.

**Comment by BrutalBirdie** [comment]
Adding the `docker-compose logs` from one `getMeetings` call

```
scalelite-api                   | I, [2021-03-03T10:07:53.280770 #6]  INFO -- : [0092e8ae-7434-49f0-a04a-1c78f5253464] Started GET "/bigbluebutton/api/getMeetings?checksum=e1b909be772f49e15e0151a69f89a8b63f444be8" for 172.27.0.7 at 2021-03-03 10:07:53 +0000
scalelite-api                   | I, [2021-03-03T10:07:53.282377 #6]  INFO -- : [0092e8ae-7434-49f0-a04a-1c78f5253464] Processing by BigBlueButtonApiController#get_meetings_disabled as XML
scalelite-api                   | I, [2021-03-03T10:07:53.282481 #6]  INFO -- : [0092e8ae-7434-49f0-a04a-1c78f5253464]   Parameters: {"checksum"=>"e1b909be772f49e15e0151a69f89a8b63f444be8"}
scalelite-api                   | D, [2021-03-03T10:07:53.282760 #6] DEBUG -- : [0092e8ae-7434-49f0-a04a-1c78f5253464] The get meetings api has been disabled
scalelite-api                   | I, [2021-03-03T10:07:53.283931 #6]  INFO -- : [0092e8ae-7434-49f0-a04a-1c78f5253464] Completed 200 OK in 1ms (Views: 0.5ms | ActiveRecord: 0.0ms | Allocations: 176)
scalelite-api                   | I, [2021-03-03T10:07:53.370971 #6]  INFO -- : [b524cf1e-e11a-467e-b654-4e8d3eee506d] Started GET "/favicon.ico" for 172.27.0.7 at 2021-03-03 10:07:53 +0000
scalelite-api                   | I, [2021-03-03T10:07:53.372556 #6]  INFO -- : [b524cf1e-e11a-467e-b654-4e8d3eee506d] Processing by ErrorsController#unsupported_request as
scalelite-api                   | I, [2021-03-03T10:07:53.372653 #6]  INFO -- : [b524cf1e-e11a-467e-b654-4e8d3eee506d]   Parameters: {"any"=>"favicon"}
scalelite-api                   | I, [2021-03-03T10:07:53.373802 #6]  INFO -- : [b524cf1e-e11a-467e-b654-4e8d3eee506d] Completed 200 OK in 1ms (Views: 0.4ms | ActiveRecord: 0.0ms | Allocations: 166)
```

From the this log it seems it worked as intended.
Hmmm.

I guess this issue could be closed since it seems to work.
Still this leaves me a bit confused since it did not work initially.

**Comment by amalrails** [comment]
@BrutalBirdie this  get _meetings_disabled api  response was intentionally set to  match with bbb. It shouldn't have had the problem you faced initially. Will keep a watch on this & close this issue for now.
