### ISSUE TITLE
post_publish_scalelite.rb, rsync and Ensure Spool Directory Exists

### ISSUE THREAD

**Issue by andy-igoshin** [blindsidenetworks/scalelite#475]
I, [2021-03-03T13:16:19.858020 #12197]  INFO -- : Executing: ruby post_publish/scalelite_post_publish.rb -m 7ac2afb016996be04b8c3a692406024bb45e16db-1614747051253
I, [2021-03-03T13:16:20.123307 #12197]  INFO -- : /usr/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - bigbluebutton@bbb.edu.vsu.ru: (Errno::EACCES)
I, [2021-03-03T13:16:20.123361 #12197]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
I, [2021-03-03T13:16:20.123372 #12197]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
I, [2021-03-03T13:16:20.123382 #12197]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
I, [2021-03-03T13:16:20.123390 #12197]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
I, [2021-03-03T13:16:20.123398 #12197]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
I, [2021-03-03T13:16:20.123406 #12197]  INFO -- :       from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
I, [2021-03-03T13:16:20.123414 #12197]  INFO -- :       from post_publish/scalelite_post_publish.rb:73:in `<main>'
I, [2021-03-03T13:16:20.127253 #12197]  INFO -- : Success?: false
I, [2021-03-03T13:16:20.127274 #12197]  INFO -- : Process exited? true
I, [2021-03-03T13:16:20.127284 #12197]  INFO -- : Exit status: 1
W, [2021-03-03T13:16:20.127526 #12197]  WARN -- : Post publish script post_publish/scalelite_post_publish.rb failed

**Comment by andy-igoshin** [comment]
the cause of this error is commit

https://github.com/blindsidenetworks/scalelite/commit/a02dcde77e7d93ed950fbe3037b005d029a255b9

**Comment by jfederico** [comment]
Fixed with https://github.com/blindsidenetworks/scalelite/releases/tag/v1.0.11
