### ISSUE TITLE
downgrade scalelite to 1.0.8

### ISSUE THREAD

**Issue by Thaer83** [blindsidenetworks/scalelite#478]
Recently, we have a problem with importing recordings from the spool directory to published. It seems that the problem is with the new version 1.0.10. How can we downgrade to version 1.0.8

**Comment by mk-hs** [comment]
Set `SCALELITE_TAG=v1.0.8 `in` /etc/default/scalelite` and restart scalelite.

**Comment by Thaer83** [comment]
Thanks for your kind response @mk-hs. It is working properly now
