### ISSUE TITLE
[Recording-importer] Temporary folder to store podcast/presentation archive

### ISSUE THREAD

**Issue by CedrX** [blindsidenetworks/scalelite#480]
I wonder if this line 
 1 --> `Dir.mktmpdir(Rails.configuration.x.recording_work_dir) do |tmpdir|`
in lib/recording_importer.rb should be  
2 --> `Dir.mktmpdir(nil,Rails.configuration.x.recording_work_dir) do |tmpdir|` 

In the first line Dir.mktmpdir uses the _only first_ argument as a pattern and it creates a temporary folder like /tmp/value-of- Rails.configuration.x.recording_work_dir-without-slashes
In the second version it uses the value of Rails.configuration.x.recording_work_dir as temporary folder

This is the behavior that i have observed

Regards

**Comment by amalrails** [comment]
this has been fixed [](https://github.com/blindsidenetworks/scalelite/blob/38bdfe13f699236b73109225b0a60f7a31194a61/lib/recording_importer.rb#L20)
