### ISSUE TITLE
[poller] Poller shows zero meetings immediately after disabling server

### ISSUE THREAD

**Issue by sporhincak** [blindsidenetworks/scalelite#481]
When running command 

> docker exec -it scalelite-api ./bin/rake status

number of meetings was shown for "disabled online" servers. Now, immediately after running
> docker exec -t scalelite-api ./bin/rake servers:disable[ID]

status shows 0 meetings 0 users, even if there is still meeting running on servers.

Screenshot from our zabbix, parsing results of ./bin/rake status, showing numbers users drop immediately after issuing servers:disable for bbb-nodes1-7:
![2021-03-11-141726_606x566_scrot](https://user-images.githubusercontent.com/80465161/110793589-17fa5b80-8275-11eb-98e2-b5f9aedb09aa.png)
docker inspect:
[poller_docker_inspect.txt](https://github.com/blindsidenetworks/scalelite/files/6123230/poller_docker_inspect.txt)

**Comment by amalrails** [comment]
@sporhincak docker exec -it scalelite-api ./bin/rake status only considers servers that are online & enabled, and for the offline servers 0 is returned as value, so this behavior is intentional.

**Comment by sporhincak** [comment]
Well, as far as I remember, it returned real number of conferences and users on server when server was disabled. We were using it to check if server can be updated/rebooted. 

It even is written in readme https://github.com/blindsidenetworks/scalelite/blob/4f07019c7776c8e5ddc9a8de5c21276c35fbb612/README.md

"Disable a server
./bin/rake servers:disable[id]
Mark the server as disabled. When a server is disabled, no new meetings will be started on the server. Any existing meetings will continue to run until they finish. The *Poll process continues to run on disabled servers to update the "Online" status and detect ended meetings.* This is useful to "drain" a server for updates without disrupting any ongoing meetings."

**Comment by jfederico** [comment]
@amalrails can you reference the PR where this behaviour was changed?
