### ISSUE TITLE
scalelite-recording-importer dont import recordings from spool dir

### ISSUE THREAD

**Issue by matiri132** [blindsidenetworks/scalelite#482]
I have this error in the logs:

``I, [2021-03-11T17:08:26.265984 #7]  INFO -- : Monitoring /var/bigbluebutton/spool for new recording files

D, [2021-03-11T17:08:26.266236 #7] DEBUG -- : Checking for existing files…

E, [2021-03-11T17:08:26.270694 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.271095 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.271492 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.272490 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.272886 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.273289 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.273723 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.274098 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.274460 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.274839 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

E, [2021-03-11T17:08:26.275192 #7] ERROR -- : Failed to import recording: undefined method `casecmp?' for nil:NilClass

D, [2021-03-11T17:08:26.275542 #7] DEBUG -- : Starting file monitor…
``

The spool_dir is correctly configured. 
And all the services are working ok.

**Comment by andrekutianski** [comment]
What are your scalelite and BBB versions? Maybe this can related to #448

**Comment by matiri132** [comment]
This worked! Thaks you!
