### ISSUE TITLE
Question: Send notifications when a recording is ready?

### ISSUE THREAD

**Issue by sparse91** [blindsidenetworks/scalelite#485]
BigBlueButton has ability to send notification when recording is ready. This is implemented in Moodle plugin.
How can we do this with Scalelite?

**Comment by jfederico** [comment]
Hi @sparse91 none of the post BBB process scripts is implemented in SL, recording ready is one of them. We are considering to work on that in the next few weeks, but it is not defined what version this is going to be.

I am going to tag it as a feature request though as it is indeed in the internal roadmap already

**Comment by labomatik** [comment]
I guess this is the PR related to this:

**Comment by jfederico** [comment]
@labomatik correct. And it is going to be part of 1.1. We are just completing the last round of testing before releasing as stable.
