### ISSUE TITLE
direct access to recordings

### ISSUE THREAD

**Issue by mohamedelashhab** [blindsidenetworks/scalelite#486]
I am working on moodle with scalelite and 10 bbb servers , I want to allow only authenticated users of certain course to access recordings and disallow direct link to recordings

**Comment by jfederico** [comment]
Hi @mohamedelashhab,
Right now there is no way to accomplish that, neither on BBB nor SL. Although it has been implemented by other applications. We have this in the roadmap and likely you will see it coming in the next few weeks (months perhaps).

And sorry for the labeling confusion @amalrails is precisely the one who is working on that feature :D.

**Comment by ichdasich** [comment]
In the meantime, you can take a look at https://github.com/ichdasich/bbb-rec-perm as an interim solution.

**Comment by amalrails** [comment]
This feature is now  available in   SL v.1.2 https://github.com/blindsidenetworks/scalelite/blob/master/protectedrecordings_README.md

**Comment by christmart** [comment]
bbb-playback does not verify the token. So you can still share the URL which is displayed while playing the recording.
