### ISSUE TITLE
Greenlight doesn't forward users when the meeting has started

### ISSUE THREAD

**Issue by strickes** [blindsidenetworks/scalelite#490]
Hi,

I setup a Scalelite Cluster with 5 BBB Servers attached. Greenlight is running on the same server as Scalelite and everything is working fine except when a user is trying to join before the Moderator is starting the meeting.
The User is still in the "The meeting hasn't started yet. You will automatically join when the meeting starts" screen. However if the moderator has joined first everybody will get into the meeting.

I have the following Nginx Config placed under /scalelite-run/data/nginx/scalelite/greenlight-conf

> 
location ~ ^/(b$|b/) {
  proxy_pass          http://greenlight-v2:80;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_http_version  1.1;
}
location ~ ^/b/cable$ {
  proxy_pass          http://greenlight-v2:80;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_set_header    Upgrade           $http_upgrade;
  proxy_set_header    Connection        "Upgrade";
  proxy_http_version  1.1;
  proxy_read_timeout  6h;
  proxy_send_timeout  6h;
  client_body_timeout 6h;
  send_timeout        6h;
}
location ~ /preupload_presentation$ {
  client_max_body_size 30m;
  proxy_pass          http://greenlight-v2:80;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_http_version  1.1;
}
location /rails/active_storage {
  return 301 /b$request_uri;
}
location = / {
    return 307 /b;
}
location = /favicon.ico {
    alias /var/www/favicon.ico;
}

I think it has somehow to do with the /b/cable entry. Anybody got a solution for this?

**Comment by mk-hs** [comment]
I've had a similar problem before. When you check the console log on the affected client, you'll see that the b/cable connection returns 404. 

I think the config line I copied back then was faulty, so it might be enough to just rewrite the cable line.
Otherwise you can see if  just `location = /b/cable {` works for you.

**Comment by farhatahmad** [comment]
This is a greenlight issue and not a Scalelite one. See: https://github.com/bigbluebutton/greenlight/issues/1259 https://github.com/bigbluebutton/greenlight/issues/1724
