### ISSUE TITLE
load calculation in readme wrong

### ISSUE THREAD

**Issue by svoeth** [blindsidenetworks/scalelite#491]
in v1.0.11 the load calculation has been chaged to user count instead of meeting count.

The Readme has been updated with the two new variables for this feature but everywhere else it still says, that load is calculated by meetingamount.

**Comment by jfederico** [comment]
Thanks @svoeth PRs for documentation are always welcome

**Comment by amalrails** [comment]
The documentation will be updated in the newer release.
