### ISSUE TITLE
getMeetings returns FAILED if one of the nodes is not available

### ISSUE THREAD

**Issue by PhMemmel** [blindsidenetworks/scalelite#498]
If one of the BBB nodes is not running a getMeetings call to the scalelite API returns FAILED with messageKey "internalError" and message "Unable to access server".

I don't think this is intended behaviour. If one node is down (intentionally or not) I still wanna see all the meetings from my other nodes in the scalelite getMeetings call.

Additional info: This even happens when I disable a node for maintenance and there aren't any meetings left on it. So when I run maintenance on one node I would have to "rake remove" and add the node again afterwards which I don't really want to do.

tested on v1.0.11

**Comment by amalrails** [comment]
hi @PhMemmel, when you disable the server it remains online but disabled, i believe that's causing this issue. You can use the servers:panic option instead of servers:disable for achieving the same.

**Comment by PhMemmel** [comment]
Thanks for the "panic hint", will try.

However, the main issue I wanted to report here is the fact that getMeetings fails when one node for example crashes (the administrative aspect of disabling is just a side effect): If a BBB node fails the whole getMeetings call of the scalelite returns FAILED. That's not the intended behaviour, is it?

**Comment by amalrails** [comment]
@PhMemmel if a bbb node fails then ideally the poller should update it as offline, which should in turn prevent this issue.

**Comment by PhMemmel** [comment]
@amalrails Thank you, you're right. As soon as they poller runs, getMeetings returns a valid response again. It is working as intended.

So, this issue is basically about getMeetings failing when poller hasn't run yet since a BBB node went offline which probably is not really an issue, so I'm gonna close it.

If you wanna track the issue of getMeetings failing for at a maximum of POLL_INTERVAL seconds in the case of a node going offline, feel free to reopen or open a new one:
Maybe it's possible to trigger the poller if getMeetings would fail before it's actually returning the FAILED answer to update the status of the BBB node. A failing getMeetings answer is at least confusing for third party apps accessing the API.
