### ISSUE TITLE
Is it possible to see meerings id from Scalelite?

### ISSUE THREAD

**Issue by 4ong** [blindsidenetworks/scalelite#499]
Is it possible to see meerings id from Scalelite?
For rooms from different servers.
Thanks!

**Comment by amalrails** [comment]
not sure what exactly you need but you can use the rails console to see all the meetings from scalelite.

**Comment by 4ong** [comment]
Thanks, I found that http://yourserver.com/bigbluebutton/api/getMeetings?checksum=1234 request seems to work for my case
