### ISSUE TITLE
Toggle video and presentation swap missing in fullscreen view

### ISSUE THREAD

**Issue by christmart** [blindsidenetworks/scalelite#508]
After switching to fullscreen view while watching a recorded presentation in scalelite (1.0.10) only the video camera is visible. 
The slides or a screenshare is not vissible.
Also the button "Toggle video and presentation swap" is missing.
This seams to have changed with a recent version.
At the lower right corner of the fullscreen display there is only the mute button, the volume control and the toggle fullscreen button.
Also the tooltip is "Click to play or pause the playback" anywere on the control bar on the lower edge of the fullscreen.

**Comment by amalrails** [comment]
Hi @christmart the above mentioned issues  are related to BBB, so please post it in the BBB forum. Scalelite is just a load balancer which facilitates the connection to a bbb server.
