### ISSUE TITLE
Need a Possible Solution

### ISSUE THREAD

**Issue by nidhin215** [blindsidenetworks/scalelite#512]
We have recently lost our bbb nodes attached to our scalelite instance in the OVH DC fire. We have the recordings in the NFS server, how can we move this to a new scalelite setup?

Can we transfer the recordings from old NFS server to the new NFS server and will these show up while fetching the recordings?

**Comment by andrekutianski** [comment]
Do you have a scalelite database backup?

**Comment by nidhin215** [comment]
> Do you have a scalelite database backup?

Yes, we do have a backup. But for the time being we have setup another one and we need to merge the old one with the new one. Is it possible to merge the database?

**Comment by faust64** [comment]
On a blank setup, the scalelite database is pretty much empty. The `schema_migrations` table would include a `version`. The other tables don't have any record.
If you do have a backup, you could probably just load it over a freshly initialized database.
If your new setup already processed some recordings of its own, there may be some IDs to rewrite before you could import that backup ...
