### ISSUE TITLE
Changing server load multiplier does not work as described in readme.

### ISSUE THREAD

**Issue by valmarku** [blindsidenetworks/scalelite#513]
Scalelite is quite fresh install, about two weeks old. Is there something we might have missed, or is it a bug ?

```
~ $ ./bin/rake servers:loadMultiplier[2d595e00-be10-4fcf-a223-6e816fdd85a4,1] --trace
rake aborted!
Don't know how to build task 'servers:loadMultiplier' (See the list of available tasks with `rake --tasks`)
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task_manager.rb:59:in `[]'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:159:in `invoke_task'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/srv/scalelite/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
./bin/rake:9:in `<main>'
```

**Comment by amalrails** [comment]
@valmarku what version of SL are you using?

**Comment by valmarku** [comment]
Funnily enough I can't see the reply here, but got a notification by email.
> @valmarku what version of SL are you using?

The repository is set to be this same one:
image: ${SCALELITE_REPO:-blindsidenetwks}/scalelite:latest-api

and version check shows:
<version>2.0</version>
<build>v1.0</build>

**Comment by jfederico** [comment]
I don't know if the version is the problem, but I would advise you to use an actual version instead of latest. Particularly if you have this in production. I don;t think latest is being built right now.

The version v1.0 would be the safest, you would only get automatic updates from v1.0-stable, or if you want to be more specific check the releases and chose the one you prefer. Release v1.0.12.1 is the latest stable.
