### ISSUE TITLE
Scalelite ignores BBB Server status: disabled, offline and removed

### ISSUE THREAD

**Issue by playernine** [blindsidenetworks/scalelite#525]
Test Environment:

Scalelite: 1.0.12.1
Greenlight: release-2.8.2.2 

some BBB servers 2.2.28 to 2.2.36

1. I started a session in Greenlight, 
2. stopped that session
3. disabled the server I got at point 1
4. startet a new BBB session in greenlight on the same room as on point 1.
5. scalelite starts the session on the disabled server.

./bin/rake poll:servers does not change that.
./bin/rake poll:all does not change that.

Than I put the BBB itself offline.
Again I use the room from point 1
scalelite leads my browser to the dead BBB and the browser waits until an timeout.

At last, i removed the the BBB Server completely from scalelite.

Now if I again start a session on room from point 1 I get an Error message from greenlight:

Server Error
Invalid BigBlueButton Endpoint and Secret

In greenlight production.log I see: 
2021-04-09 14:11:11 +0000 - ERROR: [xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxx] [xxx.xxx.xxx.xxx] BigBlueButtonException: Invalid response body. Is the API URL correct? "https://my.scalelite.de/bigbluebutton/api", version 0.8

**Comment by amalrails** [comment]
@playernine how did you put the BBB itself offline?

**Comment by playernine** [comment]
> @playernine how did you put the BBB server offline?

I used `bbb-conf --stop`

**Comment by christmart** [comment]
You can try the script from https://gitlab.rlp.net/zdvsysunix-public/bbb/bbb-helper/-/blob/main/monitoring/redis-scalelite to see if you also have inconsitencies in your redis database. Maybe it is a similar issue like #542 .

**Comment by amalrails** [comment]
@playernine to avoid this issue you could have panic the server, which would have drained all the existing meetings in SL. bbb-conf --stop would only stop that server but wouldn't remove its dependencies in SL, so that's why we have old meetings pointing to the offline server. Yea server:remove should drain all meetings from that server, right now its just removing the server and which causes some meetings referencing the old server.

**Comment by amalrails** [comment]
@playernine closing this issue as the latest version of SL resolves the server:disable issue you have mentioned.
When you stop the bbb-server the SL poller polls it for `SERVER_HEALTHY_THRESHOLD` times and does a panic after that to clear the meetings.
Also a server in SL should be removed only when it has no more meetings in it.

**Comment by playernine** [comment]
Thanks for the info.
SERVER_HEALTHY_THRESHOLD default is 1
INTERVAL for polling default is 60

maybe I should enable the DNS cache on the scalelite server since an unreachable DNS would lead to an panic, if I understand the behavior correctly.

Does SL a panic if the BBB service is unreachable at all, or only if the BBB Server responds to ping, while the BBB Service does not respond?

Short term network issues could lead to a panic otherwise.
