### ISSUE TITLE
scalelite don't import new records to spool folder ?

### ISSUE THREAD

**Issue by mohamedelashhab** [blindsidenetworks/scalelite#528]
i have scalelite server and 10 bbb servers but suddenly scalelite server don't import new records to the spool

**Comment by andrekutianski** [comment]
what do you get in the logs?

**Comment by mk-hs** [comment]
Try restarting scalelite-recording-importer.

**Comment by jfederico** [comment]
what version are you running? beta.2?

**Comment by jfederico** [comment]
I suppose this issue is solved. Closing due inactivity
