### ISSUE TITLE
Scalelite Load balancer meeting distribution issue 

### ISSUE THREAD

**Issue by Wadut-777** [blindsidenetworks/scalelite#538]
We are running Scalelite setup with 6 BBB server. Now when the meeting started most of the meeting assign to srv1 which reach the cpu utilization very high. whereas other servers are assign with less not of meeting. Is there any possible solution that can equal distribute meetings or can I set max no of meeting per server.

Below are the statics -

 srv1.example.com  enabled  online         8    256               43       5 
 srv2.example.com  enabled  online         4    151               41       3 
 srv3.example.com  enabled  online         3    109               39       2 
 srv4.example.com  enabled  online         2     82               41       2 
 srv5.example.com  enabled  online         2     36               34       1 
 srv6.example.com  enabled  online         0      0                0       0

**Comment by sparse91** [comment]
I think this is because your meetings start in the same time. Try decreasing POLL_INTERVAL to 5s or lower.

**Comment by Wadut-777** [comment]
Thank you. Issue now resolve.
