### ISSUE TITLE
Scalelite recording ready callback

### ISSUE THREAD

**Issue by goten1996** [blindsidenetworks/scalelite#539]
Hi,  

This message is regarding Send notification to users when recording is ready from moodle LMS. I have enabled this from moodle and also enabled the script post_publish_recording_ready_callback from bbb server end but I'm not able to receive any notifications. 

The problem here is, the callback is coming from bbb but we are using scalelite to process the recording so I'm not able to get any callback from scalelite.... Could you please help me with this? Or any suggestion from your side would be greatly appreciated. 

Is there any way of getting callback from scalelite?  If so then kindly please let me know

**Comment by jfederico** [comment]
Hi @goten1996 there was not, until last Friday.

You can update your deployment to [v1.1-beta.4](https://github.com/blindsidenetworks/scalelite/releases/tag/v1.1-beta.4) and that should give you the feature you are looking for. There is nothing else that needs to be configured, but you are going to need to run migrations.
