### ISSUE TITLE
support 40,000 client

### ISSUE THREAD

**Issue by freehussain** [blindsidenetworks/scalelite#541]
hello,

can i use scalite to support large number for my university of 40000 student? can we run multi instances of scalite??

**Comment by christmart** [comment]
We had about 50000 participants at the same time via scalelite on about 500 servers. 
You might have to look into the timeout settings in scalelite.

**Comment by freehussain** [comment]
@christmart 

thank you for reply, but how can we do this?
i have school that has 4000 student and one scalite  server, if the concurrent around 1000 the scalite process is 100% for 12 core

so if we have 40,000 student then we need at least 10 scalite server, how these server should connect to each other? can you please give my an idea

**Comment by christmart** [comment]
We use Docker Swarm to run at the moment 24 scalelite-api instances on 8 virtual machines. 
So each server has 3 scalelite-api instances and one scalelite-nginx instance. 
Each nginx is behind our load balancer. But it could also be used with round robin DNS.

Each scalelite instance is configured with:

RAILS_MAX_THREADS=100
RAILS_MIN_THREADS=20
WEB_CONCURRENCY=8

You can have a look at our swarm configuration here: https://gitlab.rlp.net/zdvsysunix-public/bbb/bbb-helper/-/tree/main/Docker-Swarm

Docker Swarm does automatic load balancing and connects all the components with its internal network which spans all the docker swarm instances.

**Comment by freehussain** [comment]
thank you @christmart 

i will try it
