### ISSUE TITLE
Unable to play recording

### ISSUE THREAD

**Issue by Wadut-777** [blindsidenetworks/scalelite#543]
After upgrading Scalelite with below details my greenlight frontend is not able to access scalelite. Its showing endpoint error. 

SCALELITE_REPO=blindsidenetwks
SCALELITE_TAG=v1.0.12.1-bionic230-amazonlinu

Is there any other change require

SCALELITE_TAG=v1.1 is not woring

**Comment by amalrails** [comment]
@Wadut-777 have you tried with recent more versions? i tried with v1.1 versions and they were working fine.

**Comment by Wadut-777** [comment]
For me V1.1 is not working. After changing tag V1.1 all container stop working.

**Comment by Wadut-777** [comment]
Below are the code added /etc/default/scalelite. But after restart my container stop working. I tried to run db:migrate but its showing saclelite-api does not exist.

SCALELITE_REPO=blindsidenetwks
SCALELITE_TAG=v1.1
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly
POLL_INTERVAL=3
RECORDING_IMPORT_POLL=true
RECORDING_IMPORT_POLL_INTERVAL=5

**Comment by faust64** [comment]
Could you clarify what do you mean?
I've been quite fearful to upgrade a production deployment, applying some PR I submitted earlier today.
Now, I can confirm, after going from the last v1 tag in dockerhub (5 weeks old), to v1.1-beta.4: everything works great
No need to change your environment. The db:migrate step can be run afterwards, all containers would properly start on top of the previous DB.

You say that some containers are not starting, yet you did not post any logs: what's going on in there? Have you checked?
I'm not familiar with that `/etc/default/scalelite`: is it normal to mention v1.1, which is still in beta (shouldn't this be v1.1-beta.4, maybe? Any relation to the image tag you would pull starting your containers?

Sounds like a configuration issue. 1.1-beta4 works just great. Even building the API from the last master -- shipping my PR -- works fine.
