### ISSUE TITLE
v1.0-bionic230-alpine-nginx does not run nginx

### ISSUE THREAD

**Issue by dirk-hl** [blindsidenetworks/scalelite#548]
I deploy scalite via systemd with the environment variables in /etc/default/scalelite:
SCALELITE_REPO=blindsidenetwks
SCALELITE_TAG=v1.0-bionic230-alpine
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS="--mount type=bind,source=/etc/ssl,target=/etc/nginx/ssl,readonly"

Nginx does not run and I got the error:

# docker logs scalelite-nginx
Startup script was run as init, re-execing using tini.
Generating templated nginx configuration...
Using SSL configuration template.
/etc/nginx/start: line 27: can't open /etc/nginx/conf.d/scalelite-ssl.template: no such file
Starting nginx periodic reload process...
Starting nginx...

With SCALELITE_TAG=v1.0 nginx starts correctly, but I can't use BBB 2.3 with recordings, error 404 for playback.

How can I run scalelite-v1.0-bionic230?

**Comment by dirk-hl** [comment]
I found this similar issue: https://github.com/blindsidenetworks/scalelite/issues/523
How can I correct it when I start the containers from systemd?

**Comment by jfederico** [comment]
You were absolutely right. There is a new "patch" release, see https://github.com/blindsidenetworks/scalelite/releases/tag/v1.0.12.2

You can simply go back to tag `v1.0-bionic230-alpine`
