### ISSUE TITLE
1.1-rc.1: rake servers doesn't show correct disable/enable status

### ISSUE THREAD

**Issue by PhMemmel** [blindsidenetworks/scalelite#550]
After upgrading to 1.1-rc.1 the rake task `servers` doesn't reflect the enabled/disabled state of the servers properly. After disabling a server it's showing `disabled` like it's supposed to do, but after enabling the server it keeps saying `disabled`.

Tried without success:
- manually polling
- restarted scalelite.target
- removing and readding multiple servers

However, the `status` task still reflects the state properly. New meetings are properly created by scalelite on the "disabled" servers. So it looks like this is just a visual bug in the `servers` task.

**Comment by amalrails** [comment]
@PhMemmel thanks for pointing out this bug, yea its a visual bug will push the fix soon. 
Also i m assuming you meant "enabled" and not 'disabled' in the statement "New meetings are properly created by scalelite on the "disabled" servers."

**Comment by PhMemmel** [comment]
Thanks @amalrails.

By writing "disabled" (including quotes) I was talking about the servers which are listed as disabled in the servers rake task, but apparently are enabled (because I can create new meetings and they are listed as enabled in status task).

**Comment by jfederico** [comment]
@amalrails I pointed out the problem yesterday. The issue is that enable/disable should not wait until the next poll to update the state. They should trigger the poll manually.

@PhMemmel it works as it is, but what I found is that you need to wait for two polls to be completed in order to see the actual state.

**Comment by PhMemmel** [comment]
@jfederico Thanks for the hint. There might be something weird with my setup as well...

I just saw that my poller didn't make it through the update, so I fixed that by restarting it: It is running now.

However, servers rake task in scalelite-api docker container still shows servers as disabled despite poller is now polling properly (and definitely has polled more than twice).

**Comment by jfederico** [comment]
@PhMemmel yeah, thank for confirming that. The fix was applied. You can pull from master. Simply use `master` as the version tag

**Comment by PhMemmel** [comment]
@jfederico Pulled from master, seems to be fixed for me. Disabling and enabling works as expected, status is properly reflected in rake servers task. Thanks a lot!

**Comment by PhMemmel** [comment]
sorry, reopening until released :-)

Feel free to close this whenever you think it's time
