### ISSUE TITLE
Buggy statuses in Scalelite 1.1

### ISSUE THREAD

**Issue by pielonet** [blindsidenetworks/scalelite#559]
Hi,
 I installed Scalelite 1.1 today.

The `./bin/rake status` command reports incoherent statuses !

Example for a specific server which is poweredoff (`offline`):
`./bin/rake servers` command reports status 'offline' (which is correct) for that server.
`./bin/rake status` command reports status 'online' (which is incorrect) for that server.

**Comment by pielonet** [comment]
To add to this :

If I disable server (`./bin/rake/server:disable[id]`), the `status` command reports the following (which is correct)
```
           HOSTNAME             STATE   STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS 
 <id>  disabled  offline         0      0                0       0 
```
Then if I enable the server (`./bin/rake/server:enable[id]`), the `status` command reports the following (which is incorrect)
```
           HOSTNAME             STATE   STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS 
 <id>  enabled  online         0      0                0       0 
```

**Comment by Davka** [comment]
You have to use 

/bin/rake servers:cordon[id]

**Comment by pielonet** [comment]
You're right BUT The problem is the same if I use `cordon` :

Example with an `online` and `enabled` server :
```
~ $ ./bin/rake servers:cordon[id]
~ $ ./bin/rake status
           HOSTNAME              STATE   STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS 
 <id>  cordoned  online         0      0                0       0 
```
Then after one minute delay state is `disabled` (correct) and status is `offline` (incorrect)
```
~ $ ./bin/rake status
           HOSTNAME              STATE    STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS 
 <id> disabled  offline         0      0                0       0 
```

**Comment by amalrails** [comment]
@pielonet thanks for pointing out this issue. A pr has been raised for the fix and will be merged soon.
