### ISSUE TITLE
Host rewrite non-functional

### ISSUE THREAD

**Issue by lonesomewalker** [blindsidenetworks/scalelite#565]
When importing the published presentations, scalelite doesn't rewrite the metadata.xml according to the current location.
Means: instead of scalelite URL the old BBB server URL is still there and used.

This should be corrected since the presentation can be already deleted on BBB side for saving space (cronjob), but it is not wanted to have it deleted in scalelite.

**Comment by mk-hs** [comment]
That field gets ignored, you can delete the presentation off the bbb-server and it will still be available in Scalelite.
