### ISSUE TITLE
Question: How to move scalelite from one server to another with new IP and DNS ? 

### ISSUE THREAD

**Issue by gizmo1-11** [blindsidenetworks/scalelite#566]
Hallo,
we have to move a scalelite-installation (1.0) from one server to another server. The new server will have a different IP and DNS.
Is this possible keeping all records and databases ?
What would be the best way ? Better to change first IP and DNS on the old server and than move ?

Thanks

**Comment by amalrails** [comment]
hi @gizmo1-11 yes it can be done. Can you elaborate further on how are you multiple components including DB deployed?

**Comment by gizmo1-11** [comment]
We have just one scalelite-server with the standard-installation. Everything is on this server. The 5 containers scalelite-recording-importer, scalelite-poller, scalelite-nginx, scalelite-api and redis are running there.

**Comment by gizmo1-11** [comment]
... and postgresql.

**Comment by amalrails** [comment]
@gizmo1-11 i guess you will need to take the db_dump then and migrate to the new server.

**Comment by gizmo1-11** [comment]
a DB-copy on filesystem is not good ? Not a scalelite-question ... but if I can get some help here ;-)

**Comment by amalrails** [comment]
@gizmo1-11 not sure what exactly you need. Closing this issue since its outside the scalelite scope.
