### ISSUE TITLE
Recording are not getting published in published folder of scalelite server (V1.1)

### ISSUE THREAD

**Issue by shrusolanki** [blindsidenetworks/scalelite#568]
After upgrading the scalelite to the latest version v1.1 recording are getting processed but not available mnt/scalelite-recordings/var/bigbluebutton/published/presentation folder.  This was working with version v1.0.12.1

below are logs from scalelite-poller
`D, [2021-05-25T17:23:54.553471 #8] DEBUG -- : Polling servers
W, [2021-05-25T17:23:54.555515 #8]  WARN -- : Failed to check meeting id=153b163741f4a6db3fc4939d8b4bf38fb6d4a7bb-19-172 status: Couldn't find Server with id=87756cde-d09e-4d5d-887a-c7f0c337a562
D, [2021-05-25T17:23:54.556341 #8] DEBUG -- : Polling Server id=4b9f9518-79a1-475c-aa71-937400a69ade
D, [2021-05-25T17:23:54.557079 #8] DEBUG -- : Polling Server id=c9039c29-a531-4346-bec8-0c82a39f2fe9
D, [2021-05-25T17:23:54.557573 #8] DEBUG -- : Polling Server id=9062c713-b092-4aa9-8ea9-6698f73cabfb
`

logs from scalelite-recording-importer (dont see any errors)
`" WHERE "playback_formats"."recording_id" = $1 AND "playback_formats"."format" = $2 ORDER BY "playback_formats"."format" ASC LIMIT $3  [["recording_id", 6], ["format", "presentation"], ["LIMIT", 1]]
D, [2021-05-25T17:18:55.380788 #10] DEBUG -- :   PlaybackFormat Create (0.5ms)  INSERT INTO "playback_formats" ("recording_id", "format", "url", "length") VALUES ($1, $2, $3, $4) RETURNING "id"  [["recording_id", 6], ["format", "presentation"], ["url", "/playback/presentation/2.0/playback.html?meetingId=e3fc8b480b39b6fbf351eab2ef73743999bd9b47-1621963023120"], ["length", 0]]
D, [2021-05-25T17:18:55.381083 #10] DEBUG -- : #<PlaybackFormat id: 6, recording_id: 6, format: "presentation", url: "/playback/presentation/2.0/playback.html?meetingId...", length: 0, processing_time: nil>
D, [2021-05-25T17:18:55.387070 #10] DEBUG -- :   Thumbnail Load (0.3ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 ORDER BY "thumbnails"."sequence" ASC  [["playback_format_id", 6]]
D, [2021-05-25T17:18:55.389873 #10] DEBUG -- :    (2.6ms)  COMMIT
D, [2021-05-25T17:18:55.396966 #10] DEBUG -- :   CallbackData Load (0.2ms)  SELECT "callback_data".* FROM "callback_data" WHERE "callback_data"."meeting_id" = $1 LIMIT $2  [["meeting_id", "be42e3a4dae3088ec8e3768683abe0e7b83133a2-19-173"], ["LIMIT", 1]]
D, [2021-05-25T17:18:55.443772 #10] DEBUG -- :   Recording Load (0.3ms)  SELECT "recordings".* FROM "recordings" WHERE "recordings"."id" = $1 LIMIT $2  [["id", 6], ["LIMIT", 1]]
D, [2021-05-25T17:18:55.444507 #10] DEBUG -- :   CallbackData Load (0.2ms)  SELECT "callback_data".* FROM "callback_data" WHERE "callback_data"."meeting_id" = $1 LIMIT $2  [["meeting_id", "be42e3a4dae3088ec8e3768683abe0e7b83133a2-19-173"], ["LIMIT", 1]]
`

**Comment by amalrails** [comment]
@shrusolanki are able to ssh from your bbb-server to scalelite machine? Have only faced this issue when their was an ssh issue.

**Comment by shrusolanki** [comment]
@amalrails I am able to SSH and recording are getting transferred from bbb-server to scalelite server. once it is transferred scalelite is processing the recording but I dont see it inside  mnt/scalelite-recordings/var/bigbluebutton/published/presentation folder

**Comment by amalrails** [comment]
@shrusolanki have you checked inside the unpublished folder? is the RECORDING_IMPORT_UNPUBLISHED flag set to true?

**Comment by shrusolanki** [comment]
Hi @amalrails  where can I find RECORDING_IMPORT_UNPUBLISHED  flag on scalelite?

This time I have upgraded scalelite to latest version v1.1.1.0, even this is causing the same issue.

**Comment by shrusolanki** [comment]
@amalrails RECORDING_IMPORT_UNPUBLISHED  flag is set to false.

**Comment by amalrails** [comment]
@shrusolanki what version of bbb servers are you using?

**Comment by lonesomewalker** [comment]
I would bet: latest BBB and latest Scalelite -> with the current NFS setup this won't work, because devs have changed uid/gid from bigbluebutton

**Comment by amalrails** [comment]
@shrusolanki are you still facing the issue?
