### ISSUE TITLE
After update scalelite to v1.1.1 dont' publish record on spool directory

### ISSUE THREAD

**Issue by dirk-hl** [blindsidenetworks/scalelite#573]
I have 5 nodes BigBlueButton Server 2.2.36 with Scalelite 1.0.12.2 and and everything is working. Now I update Scalelite to Version v1.1.1 to prepare for BBB 2.3 and the scalelite-recording-importer fails. The tar files in share spool directory dont have publish.

Scalelite is with systemd deployed and I use a external NFS-storage with following mount-parameter on Scalelite server and each BBB server:
xxx.xxx.xxx.xxx:/vol_scalelite_recordings  /mnt/scalelite-recordings/ nfs     rw,nfsvers=3,noatime,sync,intr 0 0

The scalelite-recording-importer throws the following error message, the directory structure and permissions are set up as described in https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md:

I, [2021-05-30T06:26:38.043851 #7]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826.tar
presentation/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826/
presentation/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826/video/
tar: can't make dir presentation/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826/video: Permission denied
tar: can't create directory 'presentation/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826/video': Permission denied
presentation/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826/video/webcams.webm
tar: can't open 'presentation/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826/video/webcams.webm': No such file or directory
E, [2021-05-30T06:26:38.078522 #7] ERROR -- : Failed to import recording: Failed to extract tar file: /var/bigbluebutton/spool/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826.tar
W, [2021-05-30T06:26:38.078857 #7]  WARN -- : /srv/scalelite/lib/recording_importer.rb:22:in `block (2 levels) in import': Failed to extract tar file: /var/bigbluebutton/spool/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826.tar (RecordingImporter::RecordingImporterError)
        from /usr/lib/ruby/2.7.0/fileutils.rb:139:in `chdir'
        from /usr/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
        from /srv/scalelite/lib/recording_importer.rb:20:in `block in import'
        from /usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
        from /srv/scalelite/lib/recording_importer.rb:19:in `import'
        from /srv/scalelite/lib/tasks/recordings.rake:17:in `block (4 levels) in <main>'
        from /srv/scalelite/lib/tasks/recordings.rake:16:in `each'
        from /srv/scalelite/lib/tasks/recordings.rake:16:in `block (3 levels) in <main>'
        from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
        from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
        from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
        from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
        from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
        from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
        from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
        from /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
		
I don't know where to look anymore, after a downgrade to Scalite v1.0 everything works again.

**Comment by jfederico** [comment]
Hi @dirk-hl the issue is permissions, 
See:

```
tar: can't make dir presentation/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826/video: Permission denied
tar: can't create directory 'presentation/e86472638d0caadeede00a0cb34687c6811ceaae-1622355702826/video': Permission denied
```

if you give the proper ones to the directory it will work.

But not sure why exactly is this happening to you. We'll take a look on our end, but you could start by checking the permissions in those directories.

**Comment by dirk-hl** [comment]
Yes, I have seen the permission denied problems. But with a local directory path in the test environment, everything works with exactly the same permissions, just like with the v1.0.x version. Only the combination Scalelite v1.1.1 with /mntscalelite-recordings/ via NFS creates the permission error.
In which directory is the tar archive unpacked?

**Comment by jfederico** [comment]
It depends of you installation. Wherever you defined in your 'RECORDING_WORK_DIR'. If you did not define it or jusy poy/paste from the README, it would be `/var/bigbluebutton/recording/scalelite`. Then as you may know, they are placed wherever you defined your `SCALELITE_RECORDING_DIR=` variable. Again, if you just copy/paste the examples from the README, it would be `/mnt/scalelite-recordings/var/bigbluebutton`.

I could not reproduce your error, but a couple of things you can try so you help me narrow it down.

1. Make sure you are using the latest version of the script https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/scalelite_post_publish.rb, if it is different please try it with this one.
2. If that still does not work, please try this image `blindsidenetwks/SL-141` by seting your variable `SCALELITE_TAG` to `SL-141`

Also, can you share the permissions you have in your mounted volume and subdirectories?

**Comment by jfederico** [comment]
One more thing, something we just came across wiith a deployment based on NFS was precisely that the permissions were overridden by rsync. There are ways to worarround, but the cleanest is to add the modifiers used by rsync.

In BigBlueButton, you set up the file `/usr/local/bigbluebutton/core/scripts/scalelite.yml`, where you define precisely the working_dir and the spool_dir. You can add these extra_rsync_options so the permissions are preserved as you manually defined in your mounted NFS volume.
```
work_dir: /var/bigbluebutton/recording/scalelite
spool_dir: /mnt/scalelite-recordings/var/bigbluebutton/spool
extra_rsync_opts: ["-av", "--no-owner", "--chmod=F664"]
```

**Comment by dirk-hl** [comment]
I use the latest version  of the script https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/scalelite_post_publish.rb

I test the image SL-141, but no improvement.

I set the extra_rsync_opts like your example, but no improvement.

I jump back to version v1.0-bionic230-alpine and everything works as expected.

I think this is a new behaviour with the tar command in scalelite-recording-importer.

**Comment by dirk-hl** [comment]
There was a problem with our NetApp storage. The Vserver Change Ownership Mode must be set to "restricted". This would be the standard NFS behaviour that only root is allowed to do a chown.
The ticket can be closed, thanks for the support, why it worked in the 1.0 version will remain a mystery.
