### ISSUE TITLE
Scalelite 404 not found nginx

### ISSUE THREAD

**Issue by liviraj** [blindsidenetworks/scalelite#579]
I installed/configured the scalelite with three BBB servers and also running all docker containers successfully. But when trying to access the scalelite credentials API mate(https://mconf.github.io/api-mate/) bigbluebutton/api showing Nginx 404 error. 

I used to like this scalelite URL: https://xxx.xxx.xxx/bigbluebutton/api/

Thanks in advance.

**Comment by amalrails** [comment]
@liviraj can you share how you installed/configured scalelite?

**Comment by liviraj** [comment]
I am using systemctl commands to install all services and docker containers. And also I followed the following GitHub link : https://github.com/blindsidenetworks/scalelite

**Comment by amalrails** [comment]
@liviraj are you running your scaelite-api service in port 3000? DId you check the status of scaleite-api?

**Comment by WaelSan** [comment]
@liviraj Did you configured the letsencrypt SSL?.
Can you share the scalelite-nginx and scalelite-api logs?

**Comment by amalrails** [comment]
@liviraj is your problem fixed?
