### ISSUE TITLE
Balance to a specific node

### ISSUE THREAD

**Issue by carlosgarciagomez** [blindsidenetworks/scalelite#582]
Is it possible to balance a specific node at a specific time?
I have three servers and one of them has a special patch.
Can I use some parameter in the scalelite api call that forces to use the specific node that I want?

SCALELITE
|- NODE1
|- NODE2
|- NODE3 (special patch applied)

Regards 

Carlos

**Comment by amalrails** [comment]
@carlosgarciagomez i think you might be looking for this ```The loadMultiplier can be used to give individual servers a higher or lower priority over other servers. A higher loadMultiplier should be placed on the weaker servers. If not passed, it defaults to a value of 1.```.
