### ISSUE TITLE
scalelite-recording-importer not importing new recordings

### ISSUE THREAD

**Issue by orksworld** [blindsidenetworks/scalelite#585]
Hi, scalelite-recording-importer not importing recordings. There is a error "Failed to import recording: PG::UndefinedTable: ERROR:  relation "callback_data" does not exist LINE 8:  WHERE a.attrelid = '"callback_data"'::regclass"

**Comment by amalrails** [comment]
@orksworld you will have to run the migrations. Please read the release document.

**Comment by orksworld** [comment]
Hi, it was working 2 weeks ago, we didn't changed anything. Should we still migrate db?

**Comment by amalrails** [comment]
@orksworld the callback_data changes were added as a part of v1.1 release and for those new db changes to reflect you will have to run the migrations. I'm not sure why you didn't see the issue 2 weeks ago but ideally  you should have had this issue then also.
