### ISSUE TITLE
Problems with install scalite docker v1.1 (and newer)

### ISSUE THREAD

**Issue by RUDI-TERROR** [blindsidenetworks/scalelite#591]
Hello together,

I have Question to setting up the scalite docker container.

in the readme it is described that the 4 docker images (api, poller, nginx and recording-importer) in version 1.0 were replaced in version 1.1 by one image (that includes the 4 images from v1.0). In the manual (https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md), starting from the step "Web Frontend (scalelite-api and scalelite-nginx)", the creation of the services is described. The systemd templates contained in the Github folder https://github.com/blindsidenetworks/scalelite/tree/master/systemd all refer to the individual Docker containers, but not to the combined container as of v1.1: 

root@videolb1:~/scalelite# docker images
REPOSITORY TAG IMAGE ID CREATED SIZE
blindsidenetwks/scalelite v1.1.4 8d7f31b0e141 43 hours ago 84.2MB

How I set up the systemd services from beginning version 1.1? 

Thanks for all,
Rudi

**Comment by amalrails** [comment]
Hi @RUDI-TERROR , there are multiple ways to deploy scalelite. You can also try https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6. As  you pointed out https://github.com/blindsidenetworks/scalelite/tree/master/systemd refers to the individual Docker containers, i think that code has to be updated. Which we will be updating soon(thanks for pointing it). I think for now you just have to set the `SCALELITE_TAG=v1.1` in `/etc/default/scalelite` as mentioned in the document, it should work.

**Comment by RUDI-TERROR** [comment]
Finaly I got it to run! Thank you for your link! And Thanks for the hours and hours of your time for this realy lovley tool! ;-)
