### ISSUE TITLE
Problem joining meeting via Scalelite using POST

### ISSUE THREAD

**Issue by WaelSan** [blindsidenetworks/scalelite#592]
We are using scalelite with GET and everything is ok, but when we tried to use POST we get this error:
```
unsupportedRequest
This request is not supported
```
We are using `v1.1-bionic230-amazonlinux` version

The POST method works perfectly when connecting directly to BBB.

Thanks in advance.

**Comment by amalrails** [comment]
Hi @WaelSan thanks for pointing this out, we will be resolving this issue soon.

**Comment by wmchris** [comment]
as this is a road block for us - any chance to improve the priority on this?
