### ISSUE TITLE
scalelite-recording-importer won't start because permission denied create folder /var/bigbluebutton

### ISSUE THREAD

**Issue by Marco-Total** [blindsidenetworks/scalelite#594]
Hello all,

I have the problem that the Docker scalelite-recording-importer can not be started.

When trying to start the docker via the service set up, I see in the LOG that creating the directory /var/bigbluebutten is not allowed.  In the config I disabled the Recording-Feature, because we wan't use it. What am I doing wrong?

/etc/defaul/scalelite
```
URL_HOST=videolb1.xxx.de
SECRET_KEY_BASE=<64bit-secret>
LOADBALANCER_SECRET=<32bit-secret>
DATABASE_URL=postgresql://scalelite:<password>@192.168.100.10/scalelite
REDIS_URL=redis://:<password>@192.168.100.10

SCALELITE_TAG=v1.1.4
SCALELITE_RECORDING_DIR=/var/local/bbb

NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly

RECORDING_DISABLED=true
RECORDING_IMPORT_POLL=false
```
/etc/systemd/system/scalelite-recording-importer.service
```
[Unit]
Description=Scalelite Recording Importer
After=network-online.target
Wants=network-online.target
Before=scalelite.target
PartOf=scalelite.target
After=scalelite-api.service
After=remote-fs.target
[Service]
EnvironmentFile=/etc/default/scalelite
ExecStartPre=-/usr/bin/docker kill scalelite-recording-importer
ExecStartPre=-/usr/bin/docker rm scalelite-recording-importer
ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-recording-importer
ExecStart=/usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-recording-importer --env-file /etc/default/scalelite --network scalelite --mount type=bind,source=${SCALELITE_RECORDING_DIR},target=/var/bigbluebutton blindsidenetwks/scalelite:${SCALELITE_TAG}-recording-importer
ExecStartPost=/usr/bin/docker image prune -f
[Install]
WantedBy=scalelite.target
```

###
Error Message
```
Jun 28 09:08:44 videolb1 docker[5001]: rake aborted!
Jun 28 09:08:44 videolb1 docker[5001]: Errno::EACCES: Permission denied @ dir_s_mkdir - /var/bigbluebutton/spool
Jun 28 09:08:44 videolb1 docker[5001]: /srv/scalelite/lib/tasks/recordings.rake:9:in `block (2 levels) in <main>'
Jun 28 09:08:44 videolb1 docker[5001]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Jun 28 09:08:44 videolb1 docker[5001]: /usr/bin/bundle:23:in `load'
Jun 28 09:08:44 videolb1 docker[5001]: /usr/bin/bundle:23:in `<main>'
Jun 28 09:08:44 videolb1 docker[5001]: Tasks: TOP => recordings:watch
Jun 28 09:08:44 videolb1 docker[5001]: (See full trace by running task with --trace)
```

The othher dockers running fine:
```
root@videolb1:/home/user# docker ps
CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS          PORTS                                                                      NAMES
0e7bb70aeaf9   blindsidenetwks/scalelite:v1.1-poller   "bin/start-poller"       17 minutes ago   Up 17 minutes                                                                              scalelite-poller
3d535d2ed0d3   blindsidenetwks/scalelite:v1.1-nginx    "/etc/nginx/start -g…"   17 minutes ago   Up 17 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   scalelite-nginx
e1b7dd2364e5   blindsidenetwks/scalelite:v1.1-api      "bin/start"              17 minutes ago   Up 17 minutes   3000/tcp                                                                   scalelite-api
```

Thanks for help,

Rudi

**Comment by amalrails** [comment]
@Marco-Total https://github.com/jfederico/scalelite-run/blob/bc94d63d71627bfc6a9ce27871200ad932174682/init-recordings-scalelite.sh#L23 that should help

**Comment by more-zamani** [comment]
> Hi guys I have the same problem My `scalelite-recording-importer` container could not start. I've upgraded to `v1.5.1.2` of Scalelite
> 
> This is the status of this service: `systemctl status scalelite-recording-importer.service -l`:
> 
> ```
> ● scalelite-recording-importer.service - Scalelite Recording Importer
>    Loaded: loaded (/etc/systemd/system/scalelite-recording-importer.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Fri 2023-07-07 17:24:55 +0430; 6min ago
>   Process: 14606 ExecStartPost=/usr/bin/docker image prune -f (code=exited, status=0/SUCCESS)
>   Process: 14605 ExecStart=/usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-recording-importer --env-file /etc/default/scalelite --network scalelite --mount type=bind,source=${SCALELITE_RECORDING_DIR},target=/var/bigbluebutton blindsidenetwks/scalelite:${SCALELITE_TAG}-recording-importer (code=exited, status=1/FAILURE)
>   Process: 14582 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-recording-importer (code=exited, status=0/SUCCESS)
>   Process: 14566 ExecStartPre=/usr/bin/docker rm scalelite-recording-importer (code=exited, status=0/SUCCESS)
>   Process: 14548 ExecStartPre=/usr/bin/docker kill scalelite-recording-importer (code=exited, status=1/FAILURE)
>  Main PID: 14605 (code=exited, status=1/FAILURE)
> 
> Jul 07 17:24:54 MYDOMAIN.TDL docker[14605]: Errno::EACCES: Permission denied @ dir_s_mkdir - /mnt/scalelite-recordings
> Jul 07 17:24:54 MYDOMAIN.TDL docker[14605]: /srv/scalelite/lib/tasks/recordings.rake:8:in `block (2 levels) in <main>'
> Jul 07 17:24:54 MYDOMAIN.TDL docker[14605]: /srv/scalelite/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
> Jul 07 17:24:54 MYDOMAIN.TDL docker[14605]: /usr/local/bin/bundle:25:in `load'
> Jul 07 17:24:54 MYDOMAIN.TDL docker[14605]: /usr/local/bin/bundle:25:in `<main>'
> Jul 07 17:24:54 MYDOMAIN.TDL docker[14605]: Tasks: TOP => recordings:watch
> Jul 07 17:24:54 MYDOMAIN.TDL docker[14605]: (See full trace by running task with --trace)
> Jul 07 17:24:55 MYDOMAIN.TDL systemd[1]: scalelite-recording-importer.service: main process exited, code=exited, status=1/FAILURE
> Jul 07 17:24:55 MYDOMAIN.TDL systemd[1]: Unit scalelite-recording-importer.service entered failed state.
> Jul 07 17:24:55 MYDOMAIN.TDL systemd[1]: scalelite-recording-importer.service failed.
> [root@storage ~]#
> ```
> 
> and this is the output of `docker logs -f -n 100 scalelite-recording-importer` :
> 
> ```
> rake aborted!
> Errno::EACCES: Permission denied @ dir_s_mkdir - /mnt/scalelite-recordings
> /srv/scalelite/lib/tasks/recordings.rake:8:in `block (2 levels) in <main>'
> /srv/scalelite/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
> /usr/local/bin/bundle:25:in `load'
> /usr/local/bin/bundle:25:in `<main>'
> Tasks: TOP => recordings:watch
> (See full trace by running task with --trace)
> ```
> 
> And `ll /mnt/ /mnt/scalelite-recordings/ /mnt/scalelite-recordings/var/`:
> 
> ```
> /mnt/:
> total 0
> drwxrwxr-x. 3 1000 scalelite-spool 71 May 28 15:05 scalelite-recordings
> 
> /mnt/scalelite-recordings/:
> total 0
> drwxrwxr-x. 3 1000 scalelite-spool 27 Jun 22  2021 var
> 
> /mnt/scalelite-recordings/var/:
> total 0
> drwxrwxr-x. 7 1000 scalelite-spool 84 Aug 16  2021 bigbluebutton
> ```

I fix it by change variables in `/etc/default/scalelite` and comment some of them except one:
```
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
#RECORDING_SPOOL_DIR=/mnt/scalelite-recordings/var/bigbluebutton/spool
#RECORDING_WORK_DIR=/mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
#RECORDING_PUBLISH_DIR=/mnt/scalelite-recordings/var/bigbluebutton/published
#RECORDING_UNPUBLISH_DIR=/mnt/scalelite-recordings/var/bigbluebutton/unpublished
```
