### ISSUE TITLE
changing the domain + own ssl

### ISSUE THREAD

**Issue by shankar-bavan** [blindsidenetworks/scalelite#606]
Hi 
I got 2 questions 
1. How can I change the domain name on scalelite server?
2. How can I use my own ssl certificate. I don't want to use letsencrypt

**Comment by pielonet** [comment]
Hi,
For the personnal domain, here is what you should had to your Scalelite configuration file (`/etc/default/scalelite`)

```
# Alternative with a provided certificate (not letsencrypt)
# Place the fullchain.pem and privkey.pem files in the /etc/nginx/ssl/live/domain.example.com/ folder
# mkdir /etc/nginx/ssl/live/domain.example.com
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/nginx/ssl,target=/etc/nginx/ssl,readonly
```

The domain is declared with `URL_HOST` :+1: 
```
URL_HOST=scalelite.exemple.com
```

Kind regards,
Thierry

**Comment by shankar-bavan** [comment]
Thank you @pielonet
