### ISSUE TITLE
scalelite-recording-importer does not publish records that are in the spool directory

### ISSUE THREAD

**Issue by jetchevers** [blindsidenetworks/scalelite#611]
Hi, all
I have a problem, the "scalelite-recording-importer" process keeps processing a record over and over again indefinitely without giving an error or going to the next record.
The process worked correctly until the last time we downloaded and uploaded the server.

**systemctl status scalelite-recording-importer.service** 

● scalelite-recording-importer.service - Scalelite Recording Importer
   Loaded: loaded (/etc/systemd/system/scalelite-recording-importer.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-07-23 10:30:42 -03; 2min 26s ago
  Process: 7981 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-recording-importer (code=exited, status=0/SUCCESS)
  Process: 7966 ExecStartPre=/usr/bin/docker rm scalelite-recording-importer (code=exited, status=0/SUCCESS)
  Process: 7942 ExecStartPre=/usr/bin/docker kill scalelite-recording-importer (code=exited, status=1/FAILURE)
 Main PID: 8000 (docker)
    Tasks: 11 (limit: 4656)
   CGroup: /system.slice/scalelite-recording-importer.service
           └─8000 /usr/bin/docker run --name scalelite-recording-importer --env-file /etc/default/scalelite --network scalelite --moun
t type=bind,source=/mnt/scalelite-recordings/var/bigbluebutton,target=/var/bigbluebutton blindsidenetwks/scalelite:v1-recording-import
er

Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.620928 #9] DEBUG -- : #<Metadatum id: 157401, recording_id: 16432,
 key: "bbb-context-label", value: "Contab.1 (1016)">
Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.622440 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".
* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-orig
in-version"], ["LIMIT", 1]]
Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.623255 #9] DEBUG -- : #<Metadatum id: 157402, recording_id: 16432,
 key: "bbb-origin-version", value: "3.8.2+ (Build: 20200320)">
Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.624749 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".
* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-orig
in-server-name"], ["LIMIT", 1]]
Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.625516 #9] DEBUG -- : #<Metadatum id: 157403, recording_id: 16432,
 key: "bbb-origin-server-name", value: "campusvirtual.unm.edu.ar">
Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.627037 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".
* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-orig
in"], ["LIMIT", 1]]
Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.627846 #9] DEBUG -- : #<Metadatum id: 157404, recording_id: 16432,
 key: "bbb-origin", value: "Moodle">
Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.629197 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".
* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-cont
ext-name"], ["LIMIT", 1]]
Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.629945 #9] DEBUG -- : #<Metadatum id: 157405, recording_id: 16432,
 key: "bbb-context-name", value: "Contabilidad 1 (1016)">
Jul 23 10:32:47 srv-scalelite docker[8000]: D, [2021-07-23T13:32:47.631294 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".
* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-cont
ext-id"], ["LIMIT", 1]]

**docker logs scalelite-recording-importer**

presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/video/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/video/webcams.webm
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/captions.json
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/deskshare.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/metadata.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/cursor.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/deskshare/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/deskshare/deskshare.webm
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/deskshare.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/logo.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/thumbnails/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/thumbnails/thumb-1.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/textfiles/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/textfiles/slide-1.txt
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/slide-1.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/shapes.svg
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/slides_new.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation_text.json
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/panzooms.xml
I, [2021-07-23T13:30:51.222139 #9]  INFO -- : Found metadata file: presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949
/metadata.xml
D, [2021-07-23T13:30:51.956556 #9] DEBUG -- :    (0.6ms)  BEGIN
D, [2021-07-23T13:30:52.090848 #9] DEBUG -- :   Recording Load (11.6ms)  SELECT "recordings".* FROM "recordings" WHER
E "recordings"."record_id" = $1 LIMIT $2  [["record_id", "7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.132809 #9] DEBUG -- : #<Recording id: 16432, record_id: "7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-162583172...
", meeting_id: "acfa65edcb2fe59b28dd1ad809fb5377d62d58d7-4291-1293...", name: "Clase VIERNES 9 de julio 9 horas ", published: true, pa
rticipants: 25, state: "published", starttime: "2021-07-09 11:55:23", endtime: "2021-07-09 13:56:18", deleted_at: nil>
D, [2021-07-23T13:30:52.170281 #9] DEBUG -- :   Metadatum Load (1.1ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-recording-tags"], ["LIMIT",
1]]
D, [2021-07-23T13:30:52.186600 #9] DEBUG -- : #<Metadatum id: 157399, recording_id: 16432, key: "bbb-recording-tags", value: "">
D, [2021-07-23T13:30:52.188398 #9] DEBUG -- :   Metadatum Load (0.8ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-recording-description"], ["L
IMIT", 1]]
D, [2021-07-23T13:30:52.189214 #9] DEBUG -- : #<Metadatum id: 157400, recording_id: 16432, key: "bbb-recording-description", value: "D
eben presionar el botón \"UNIRSE A LA SESIÓN\" y se...">
D, [2021-07-23T13:30:52.191099 #9] DEBUG -- :   Metadatum Load (0.9ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-context-label"], ["LIMIT", 1
]]
D, [2021-07-23T13:30:52.191873 #9] DEBUG -- : #<Metadatum id: 157401, recording_id: 16432, key: "bbb-context-label", value: "Contab.1
(1016)">
D, [2021-07-23T13:30:52.193322 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin-version"], ["LIMIT",
1]]
D, [2021-07-23T13:30:52.194272 #9] DEBUG -- : #<Metadatum id: 157402, recording_id: 16432, key: "bbb-origin-version", value: "3.8.2+ (
Build: 20200320)">
D, [2021-07-23T13:30:52.195902 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin-server-name"], ["LIMI
T", 1]]
D, [2021-07-23T13:30:52.196784 #9] DEBUG -- : #<Metadatum id: 157403, recording_id: 16432, key: "bbb-origin-server-name", value: "camp
usvirtual.unm.edu.ar">
D, [2021-07-23T13:30:52.198411 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.199280 #9] DEBUG -- : #<Metadatum id: 157404, recording_id: 16432, key: "bbb-origin", value: "Moodle">
D, [2021-07-23T13:30:52.200796 #9] DEBUG -- :   Metadatum Load (0.6ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-context-name"], ["LIMIT", 1]
]
D, [2021-07-23T13:30:52.201713 #9] DEBUG -- : #<Metadatum id: 157405, recording_id: 16432, key: "bbb-context-name", value: "Contabilid
ad 1 (1016)">
D, [2021-07-23T13:30:52.202996 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-context-id"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.203997 #9] DEBUG -- : #<Metadatum id: 157406, recording_id: 16432, key: "bbb-context-id", value: "4291">
D, [2021-07-23T13:30:52.205265 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin-server-common-name"],
 ["LIMIT", 1]]
D, [2021-07-23T13:30:52.206004 #9] DEBUG -- : #<Metadatum id: 157407, recording_id: 16432, key: "bbb-origin-server-common-name", value
: "">
D, [2021-07-23T13:30:52.207453 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-recording-name"], ["LIMIT",
1]]
D, [2021-07-23T13:30:52.208221 #9] DEBUG -- : #<Metadatum id: 157408, recording_id: 16432, key: "bbb-recording-name", value: "Clase VI
ERNES 9 de julio 9 horas ">
D, [2021-07-23T13:30:52.209610 #9] DEBUG -- :   Metadatum Load (0.6ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin-tag"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.210511 #9] DEBUG -- : #<Metadatum id: 157409, recording_id: 16432, key: "bbb-origin-tag", value: "moodle-mod_b
igbluebuttonbn (2019101008)">
D, [2021-07-23T13:30:52.211964 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-context"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.212773 #9] DEBUG -- : #<Metadatum id: 157410, recording_id: 16432, key: "bbb-context", value: "Contabilidad 1
(1016)">
D, [2021-07-23T13:30:52.228992 #9] DEBUG -- :   PlaybackFormat Load (1.0ms)  SELECT "playback_formats".* FROM "playba
ck_formats" WHERE "playback_formats"."recording_id" = $1 AND "playback_formats"."format" = $2 ORDER BY "playback_formats"."format" ASC
 LIMIT $3  [["recording_id", 16432], ["format", "presentation"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.244801 #9] DEBUG -- : #<PlaybackFormat id: 16432, recording_id: 16432, format: "presentation", url: "/playback
/presentation/2.0/playback.html?meetingId...", length: 62, processing_time: nil>
D, [2021-07-23T13:30:52.255203 #9] DEBUG -- :   Thumbnail Load (1.0ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE
 "thumbnails"."playback_format_id" = $1 AND "thumbnails"."sequence" = $2 ORDER BY "thumbnails"."sequence" ASC LIMIT $3  [["playback
_format_id", 16432], ["sequence", 0], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.276699 #9] DEBUG -- :   Thumbnail Load (0.8ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE
 "thumbnails"."playback_format_id" = $1 ORDER BY "thumbnails"."sequence" ASC  [["playback_format_id", 16432]]
D, [2021-07-23T13:30:52.278119 #9] DEBUG -- :    (0.7ms)  COMMIT
I, [2021-07-23T13:30:52.314428 #9]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/7c205d3f31021f8522dd4ec48f2ea4fa
6dbeeef1-1625831723949.tar
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/video/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/video/webcams.webm
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/captions.json
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/deskshare.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/metadata.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/cursor.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/deskshare/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/deskshare/deskshare.webm
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/deskshare.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/logo.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/thumbnails/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/thumbnails/thumb-1.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/textfiles/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/textfiles/slide-1.txt
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/slide-1.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/shapes.svg
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/slides_new.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation_text.json
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/panzooms.xml
I, [2021-07-23T13:30:52.507105 #9]  INFO -- : Found metadata file: presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949
/metadata.xml
D, [2021-07-23T13:30:52.537681 #9] DEBUG -- :    (0.5ms)  BEGIN
D, [2021-07-23T13:30:52.541707 #9] DEBUG -- :   Recording Load (1.3ms)  SELECT "recordings".* FROM "recordings" WHERE
 "recordings"."record_id" = $1 LIMIT $2  [["record_id", "7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.544877 #9] DEBUG -- : #<Recording id: 16432, record_id: "7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-162583172...
", meeting_id: "acfa65edcb2fe59b28dd1ad809fb5377d62d58d7-4291-1293...", name: "Clase VIERNES 9 de julio 9 horas ", published: true, pa
rticipants: 25, state: "published", starttime: "2021-07-09 11:55:23", endtime: "2021-07-09 13:56:18", deleted_at: nil>
D, [2021-07-23T13:30:52.547917 #9] DEBUG -- :   Metadatum Load (1.0ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-recording-tags"], ["LIMIT",
1]]
D, [2021-07-23T13:30:52.549143 #9] DEBUG -- : #<Metadatum id: 157399, recording_id: 16432, key: "bbb-recording-tags", value: "">
D, [2021-07-23T13:30:52.550632 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-recording-description"], ["L
IMIT", 1]]
D, [2021-07-23T13:30:52.551415 #9] DEBUG -- : #<Metadatum id: 157400, recording_id: 16432, key: "bbb-recording-description", value: "D
eben presionar el botón \"UNIRSE A LA SESIÓN\" y se...">
D, [2021-07-23T13:30:52.553086 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-context-label"], ["LIMIT", 1
]]
D, [2021-07-23T13:30:52.554029 #9] DEBUG -- : #<Metadatum id: 157401, recording_id: 16432, key: "bbb-context-label", value: "Contab.1
(1016)">
D, [2021-07-23T13:30:52.555572 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin-version"], ["LIMIT",
1]]
D, [2021-07-23T13:30:52.556455 #9] DEBUG -- : #<Metadatum id: 157402, recording_id: 16432, key: "bbb-origin-version", value: "3.8.2+ (
Build: 20200320)">
D, [2021-07-23T13:30:52.557929 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin-server-name"], ["LIMI
T", 1]]
D, [2021-07-23T13:30:52.558921 #9] DEBUG -- : #<Metadatum id: 157403, recording_id: 16432, key: "bbb-origin-server-name", value: "camp
usvirtual.unm.edu.ar">
D, [2021-07-23T13:30:52.560441 #9] DEBUG -- :   Metadatum Load (0.7ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.561196 #9] DEBUG -- : #<Metadatum id: 157404, recording_id: 16432, key: "bbb-origin", value: "Moodle">
D, [2021-07-23T13:30:52.562583 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-context-name"], ["LIMIT", 1]
]
D, [2021-07-23T13:30:52.563384 #9] DEBUG -- : #<Metadatum id: 157405, recording_id: 16432, key: "bbb-context-name", value: "Contabilid
ad 1 (1016)">
D, [2021-07-23T13:30:52.564842 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-context-id"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.565621 #9] DEBUG -- : #<Metadatum id: 157406, recording_id: 16432, key: "bbb-context-id", value: "4291">
D, [2021-07-23T13:30:52.566963 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin-server-common-name"],
 ["LIMIT", 1]]
D, [2021-07-23T13:30:52.567913 #9] DEBUG -- : #<Metadatum id: 157407, recording_id: 16432, key: "bbb-origin-server-common-name", value
: "">
D, [2021-07-23T13:30:52.569175 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-recording-name"], ["LIMIT",
1]]
D, [2021-07-23T13:30:52.569915 #9] DEBUG -- : #<Metadatum id: 157408, recording_id: 16432, key: "bbb-recording-name", value: "Clase VI
ERNES 9 de julio 9 horas ">
D, [2021-07-23T13:30:52.571298 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-origin-tag"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.572069 #9] DEBUG -- : #<Metadatum id: 157409, recording_id: 16432, key: "bbb-origin-tag", value: "moodle-mod_b
igbluebuttonbn (2019101008)">
D, [2021-07-23T13:30:52.573371 #9] DEBUG -- :   Metadatum Load (0.5ms)  SELECT "metadata".* FROM "metadata" WHERE "me
tadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3  [["recording_id", 16432], ["key", "bbb-context"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.574313 #9] DEBUG -- : #<Metadatum id: 157410, recording_id: 16432, key: "bbb-context", value: "Contabilidad 1
(1016)">
D, [2021-07-23T13:30:52.577710 #9] DEBUG -- :   PlaybackFormat Load (1.0ms)  SELECT "playback_formats".* FROM "playba
ck_formats" WHERE "playback_formats"."recording_id" = $1 AND "playback_formats"."format" = $2 ORDER BY "playback_formats"."format" ASC
 LIMIT $3  [["recording_id", 16432], ["format", "presentation"], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.579082 #9] DEBUG -- : #<PlaybackFormat id: 16432, recording_id: 16432, format: "presentation", url: "/playback
/presentation/2.0/playback.html?meetingId...", length: 62, processing_time: nil>
D, [2021-07-23T13:30:52.582701 #9] DEBUG -- :   Thumbnail Load (1.2ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE
 "thumbnails"."playback_format_id" = $1 AND "thumbnails"."sequence" = $2 ORDER BY "thumbnails"."sequence" ASC LIMIT $3  [["playback
_format_id", 16432], ["sequence", 0], ["LIMIT", 1]]
D, [2021-07-23T13:30:52.585924 #9] DEBUG -- :   Thumbnail Load (0.8ms)  SELECT "thumbnails".* FROM "thumbnails" WHERE
 "thumbnails"."playback_format_id" = $1 ORDER BY "thumbnails"."sequence" ASC  [["playback_format_id", 16432]]
D, [2021-07-23T13:30:52.587212 #9] DEBUG -- :    (0.7ms)  COMMIT
I, [2021-07-23T13:30:52.615486 #9]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/7c205d3f31021f8522dd4ec48f2ea4fa
6dbeeef1-1625831723949.tar
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/video/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/video/webcams.webm
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/captions.json
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/deskshare.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/metadata.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/cursor.xml
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/deskshare/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/deskshare/deskshare.webm
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/deskshare.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/logo.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/thumbnails/
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/thumbnails/thumb-1.png
presentation/7c205d3f31021f8522dd4ec48f2ea4fa6dbeeef1-1625831723949/presentation/d2f6785f0f2ded4a82ec190e64fae59555e6d274-162583172405
9/textfiles/

**Comment by sureronald** [comment]
I have the same exact problem.

**Comment by caglaroflazoglu** [comment]
you can fix it with migration 
docker exec -t scalelite-api bundle exec rake db:migrate

check this issue: #585

**Comment by sureronald** [comment]
@caglaroflazoglu thank you for pointing that out. It fixes the problem. Release [v1.1](https://github.com/blindsidenetworks/scalelite/releases/tag/v1.1) required migration to be run.
