### ISSUE TITLE
bug: user can't join running meetings if all servers are cordoned

### ISSUE THREAD

**Issue by mschwrdtnr** [blindsidenetworks/scalelite#620]
If all servers are cordoned it is not possible to join existing meetings. This issue describes the same behaviour as #398. 

Explanation by @christmart in #398

> 
> 
> All servers where CORDONED to not let any new conferences be started on all servers.
> Users who wanted to join a conference which was started before all servers where CORDONED get
> "An error occured" like when the secrets are wrong or when you try to start a new conference when all servers are CORDONED.
> 
> To reproduce:
> 
>     * start and join a new conference
> 
>     * CORDON all servers in scalelite
> 
>     * try to join this conference from another window/browser/user
> 
> 
> expected bahavior:
> 
>     * it should be possible to join an already running conference even if the server was CORDONED after starting the conference.
> 
> 
> Greeting
> Christoph

**Comment by amalrails** [comment]
@mschwrdtnr we are preventing users to join an existing meeting only if a  server is offline or server is disabled. I tried joining a existing meeting after making the server cordon and i was able to join the meeting. Can you share the error logs for this issue?

**Comment by amalrails** [comment]
@mschwrdtnr also a cordoned server with no load/users gets disabled automatically in the next poll. Maybe that's preventing the join for you.

**Comment by mschwrdtnr** [comment]
Hey @amalrails I did the following:
- Only one registered server in scalelite
- Create and joining a Meeting
- Cordon the server --> Server have status cordoned with one running meeting
- Try joining the meeting --> Error Message "An error occured"

> 
> 
> @mschwrdtnr we are preventing users to join an existing meeting only if a server is offline or server is disabled. I tried joining a existing meeting after making the server cordon and i was able to join the meeting. Can you share the error logs for this issue?

Are all servers in your setup in scalelite `cordoned`? If there is another server who is `enabled` it's possible to join a meeting on the cordoned server. If there is only one registered server it's not possible to join the cordoned server.

> 
> 
> @mschwrdtnr also a cordoned server with no load/users gets disabled automatically in the next poll. Maybe that's preventing the join for you.

I am aware of this functionality and don't mean this.

**Comment by amalrails** [comment]
@mschwrdtnr i tested with only 1 server and it was working. Also join will always happen only on that server, it won't consider any other servers. How are you deploying this? Would be easier to debug if i could see the scalelite-api logs

**Comment by mschwrdtnr** [comment]
@amalrails I will send you the logs until Thursday. Thank you.

**Comment by amalrails** [comment]
thanks @mschwrdtnr. i have one more question: did you have any active users in the meeting when you were trying to join as another user? After how long did you try to rejoin the same meeting? The reason being bbb servers clear out the meetings which dont have any active users after sometime, and the scalelite tries to rejoin the meeting which does not exist in BBB and that could give an error.

**Comment by mschwrdtnr** [comment]
@amalrails I tried to join an active meeting with one active user in it a couple of times. I think 1min after meeting creation and 10-60s after setting the state to cordon.

**Comment by mschwrdtnr** [comment]
@amalrails sorry for the late answer. I don't get any logs from `scalelite-api` in this case.

Maybe it's not the fault of scalelite but from greenlight. There are also no error message but a difference. The greenlight logs look as follows:

**Join a Meeting when Server is not cordoned:**
```
172.**.*.** - - [04/Aug/2021:14:32:26 +0000] "GET /bigbluebutton/api/join?createTime=1628086644162&fullName=Max&join_via_html5=true&meetingID=***&password=***&userID=gl-guest-***&checksum=*** HTTP/1.1" 302 393 "https://***.de/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" "172.**.*.**"
```

**Join a Meeting when Server is cordoned:**
```
172.**.*.** - - [04/Aug/2021:14:33:33 +0000] "GET /bigbluebutton/api/isMeetingRunning?meetingID=***&checksum=** HTTP/1.1" 200 113 "-" "Ruby" "172.**.*.**"
172.**.*.** - - [04/Aug/2021:14:33:33 +0000] "GET /bigbluebutton/api/getRecordings?meetingID=***&checksum=*** HTTP/1.1" 200 203 "-" "Ruby" "1172.**.*.**"
```

**Comment by amalrails** [comment]
@mschwrdtnr are you getting the Error Message: "Wrong Secret or passphrase" while trying to join when the server is in enabled state?

**Comment by mschwrdtnr** [comment]
@amalrails I am getting this error message in greenlight when I want to join an running meeting and the server where the meeting is running is `cordoned` and this server is the only registered in scalelite.

**Comment by amalrails** [comment]
@mschwrdtnr did you try with api-mate? The same scenario but just try joining the meeting using API-mate

**Comment by mschwrdtnr** [comment]
@amalrails surprisingly it works with API-mate.  If I try to join via the invitation link of greenlight, enter my name and try to join I get the error for the same meeting. So it looks like their is something wrong with joining via greenlight if all servers are cordoned. 

I am not familiar with the request which is send from greenlight to bbb. Is this an issue of greenlight or scalelite? ...and should I move this issue to greenlight?

**Comment by jfederico** [comment]
You are right, it appears to be a bug in Greenlight 

I believe before every Join, GL sends a create request to BBB (in this case SL) make sure the meeting exists. It is a way to save one step ( if IsMeetingRunning then Join else createMeeting and Join), this was a practice that was recommended before SL came to play, but in this case it is making the Join request fail because obviously create will fail on cordoned servers.

So you thing this may be happening @farhatahmad ?
