### ISSUE TITLE
recording cycle scalelite bbb 2.3

### ISSUE THREAD

**Issue by gus1185** [blindsidenetworks/scalelite#625]
Help, my scalelite does not process the recordings, it transfers them with scalelite_batch_import from the 2.3 bbb but it stays cycled trying to process 1 recording of 20 or more available. This I found in the scalelite logs.

Aug  3 23:48:40 scale2 docker[17916]: presentation/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068/deskshare.xml
Aug  3 23:48:40 scale2 docker[17916]: presentation/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068/shapes.svg
Aug  3 23:48:40 scale2 docker[17916]: presentation/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068/captions.json
Aug  3 23:48:40 scale2 docker[17916]: presentation/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068/slides_new.xml
Aug  3 23:48:40 scale2 docker[17916]: presentation/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068/video/
Aug  3 23:48:40 scale2 docker[17916]: presentation/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068/video/webcams.webm
Aug  3 23:48:40 scale2 docker[17916]: presentation/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068/panzooms.xml
Aug  3 23:48:40 scale2 docker[17916]: presentation/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068/presentation_text.json
Aug  3 23:48:40 scale2 docker[17916]: I, [2021-08-04T04:48:40.574233 #6]  INFO -- : Found metadata file: presentation/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068/metadata.xml
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.591939 #6] DEBUG -- :   #033[1m#033[35m (0.4ms)#033[0m  #033[1m#033[35mBEGIN#033[0m
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.593894 #6] DEBUG -- :   #033[1m#033[36mRecording Load (0.7ms)#033[0m  #033[1m#033[34mSELECT "recordings".* FROM "recordings" WHERE "recordings"."record_id" = $1 LIMIT $2#033[0m  [["record_id", "7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068"], ["LIMIT", 1]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.595303 #6] DEBUG -- : #<Recording id: 6910, record_id: "7a8096cc5c47a46e3eb445a664b3f038380a633d-162766612...", meeting_id: "iz0bpcv2rinppl6gpcj7xe3vegyptybgcphsyu8c", name: "Home Room", published: true, participants: 1, state: "published", starttime: "2021-07-30 17:28:48", endtime: "2021-07-30 17:31:18", deleted_at: nil>
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.597187 #6] DEBUG -- :   #033[1m#033[36mMetadatum Load (0.6ms)#033[0m  #033[1m#033[34mSELECT "metadata".* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3#033[0m  [["recording_id", 6910], ["key", "bbb-origin"], ["LIMIT", 1]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.597854 #6] DEBUG -- : #<Metadatum id: 291, recording_id: 6910, key: "bbb-origin", value: "Greenlight">
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.598866 #6] DEBUG -- :   #033[1m#033[36mMetadatum Load (0.5ms)#033[0m  #033[1m#033[34mSELECT "metadata".* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3#033[0m  [["recording_id", 6910], ["key", "bbb-origin-server-name"], ["LIMIT", 1]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.599384 #6] DEBUG -- : #<Metadatum id: 292, recording_id: 6910, key: "bbb-origin-server-name", value: "meet7.warriorslabs.com">
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.600375 #6] DEBUG -- :   #033[1m#033[36mMetadatum Load (0.4ms)#033[0m  #033[1m#033[34mSELECT "metadata".* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3#033[0m  [["recording_id", 6910], ["key", "bbb-origin-version"], ["LIMIT", 1]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.600896 #6] DEBUG -- : #<Metadatum id: 293, recording_id: 6910, key: "bbb-origin-version", value: "v2">
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.601891 #6] DEBUG -- :   #033[1m#033[36mMetadatum Load (0.5ms)#033[0m  #033[1m#033[34mSELECT "metadata".* FROM "metadata" WHERE "metadata"."recording_id" = $1 AND "metadata"."key" = $2 LIMIT $3#033[0m  [["recording_id", 6910], ["key", "gl-listed"], ["LIMIT", 1]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.602384 #6] DEBUG -- : #<Metadatum id: 294, recording_id: 6910, key: "gl-listed", value: "false">
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.604349 #6] DEBUG -- :   #033[1m#033[36mPlaybackFormat Load (0.6ms)#033[0m  #033[1m#033[34mSELECT "playback_formats".* FROM "playback_formats" WHERE "playback_formats"."recording_id" = $1 AND "playback_formats"."format" = $2 ORDER BY "playback_formats"."format" ASC LIMIT $3#033[0m  [["recording_id", 6910], ["format", "presentation"], ["LIMIT", 1]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.605159 #6] DEBUG -- : #<PlaybackFormat id: 6911, recording_id: 6910, format: "presentation", url: "/playback/presentation/2.0/playback.html?meetingId...", length: 2, processing_time: nil>
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.607201 #6] DEBUG -- :   #033[1m#033[36mThumbnail Load (0.6ms)#033[0m  #033[1m#033[34mSELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 AND "thumbnails"."sequence" = $2 ORDER BY "thumbnails"."sequence" ASC LIMIT $3#033[0m  [["playback_format_id", 6911], ["sequence", 0], ["LIMIT", 1]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.608829 #6] DEBUG -- :   #033[1m#033[36mThumbnail Load (0.5ms)#033[0m  #033[1m#033[34mSELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 AND "thumbnails"."sequence" = $2 ORDER BY "thumbnails"."sequence" ASC LIMIT $3#033[0m  [["playback_format_id", 6911], ["sequence", 1], ["LIMIT", 1]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.610337 #6] DEBUG -- :   #033[1m#033[36mThumbnail Load (0.5ms)#033[0m  #033[1m#033[34mSELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 AND "thumbnails"."sequence" = $2 ORDER BY "thumbnails"."sequence" ASC LIMIT $3#033[0m  [["playback_format_id", 6911], ["sequence", 2], ["LIMIT", 1]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.612075 #6] DEBUG -- :   #033[1m#033[36mThumbnail Load (0.5ms)#033[0m  #033[1m#033[34mSELECT "thumbnails".* FROM "thumbnails" WHERE "thumbnails"."playback_format_id" = $1 ORDER BY "thumbnails"."sequence" ASC#033[0m  [["playback_format_id", 6911]]
Aug  3 23:48:40 scale2 docker[17916]: D, [2021-08-04T04:48:40.613280 #6] DEBUG -- :   #033[1m#033[35m (0.5ms)#033[0m  #033[1m#033[35mCOMMIT#033[0m
Aug  3 23:48:40 scale2 docker[17916]: I, [2021-08-04T04:48:40.641489 #6]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/7a8096cc5c47a46e3eb445a664b3f038380a633d-1627666128068.tar

**Comment by WinterJV** [comment]
Hola buenos días, 

Podrías intentar reiniciar los procesos a lo mejor y se atasco con algo o encontró un inconveniente que no permite avanzar, trata de cuando lo reinicies mandar un proceso a spool y ver como esta trabajando para que luego puedas mandar todos de golpe sin preocuparte. no soy experto pero podría ayudarte en lo que pueda;).

**Comment by chehwi** [comment]
Hi,

we have the same problem here:

Our environment:
1. Scalelite Loadbalancer current version 1.1.6
2. 10 BBB Servers current version 2.3.9
3. Scalelite and all BBB Servers share common NFS-Storage configured as described in the documentation
4. The recording is transferred correctly from BBB-Server to NFS-Share (/mnt/scalelite-recordings/var/bigbluebutton/spool)
5. Recording-Importer-Service finds the tar file in /mnt/scalelite-recordings/var/bigbluebutton/spool and starts processing
6. Recording-Importer-Service creates temp data directory in /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite - Temp Directory name e.g. "d20210806-6-2woq8v"
7. Temp Directory gets removed
**8. The the whole import starts again and again (Importer-Service going into indefinite loop) see syslog below**

Scalelite Syslog:
`

Aug  6 11:03:14 conf docker[21572]: I, [2021-08-06T09:03:14.477261 #6]  INFO -- : Found metadata file: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/metadata.xml
Aug  6 11:03:14 conf docker[21572]: I, [2021-08-06T09:03:14.516459 #6]  INFO -- : Importing recording from file: /var/bigbluebutton/spool/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078.tar
Aug  6 11:03:14 conf docker[21572]: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/
Aug  6 11:03:14 conf docker[21572]: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/presentation/
Aug  6 11:03:14 conf docker[21572]: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/presentation/logo.png
Aug  6 11:03:14 conf docker[21572]: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1628240423108/
[.... shortened for abbreviation ....]
Aug  6 11:03:14 conf docker[21572]: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/metadata.xml
Aug  6 11:03:14 conf docker[21572]: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/panzooms.xml
Aug  6 11:03:14 conf docker[21572]: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/captions.json
Aug  6 11:03:14 conf docker[21572]: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/presentation_text.json
Aug  6 11:03:14 conf docker[21572]: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/cursor.xml
Aug  6 11:03:14 conf docker[21572]: I, [2021-08-06T09:03:14.727145 #6]  INFO -- : Found metadata file: presentation/5ff1d26062e5b2fa5162b52499e7e2bc3ee153ef-1628240423078/metadata.xml

`

After a short inspection of the source code (`/srv/scalelite/lib/recording_importer.rb` and `/srv/scalelite/app/models/recording.rb`) I think the problem pops up while creating the recording object and the importer just retries again and again (`next if recording.nil?`)

`

    Dir.glob('*/*/metadata.xml').each do |metadata_xml|
      logger.info("Found metadata file: #{metadata_xml}")
      metadata = IO.read(metadata_xml)
      recording, playback_format = Recording.create_from_metadata_xml(metadata)
      next if recording.nil?

      publish_format_dir = "#{Rails.configuration.x.recording_publish_dir}/#{playback_format.format}"
      unpublish_format_dir = "#{Rails.configuration.x.recording_unpublish_dir}/#{playback_format.format}"
      format_dir = publish_format_dir
      if unpublish_status || !recording.published
        format_dir = unpublish_format_dir
        recording.update!(published: false)
      end
      FileUtils.rm_rf("#{publish_format_dir}/#{recording.record_id}")
      FileUtils.rm_rf("#{unpublish_format_dir}/#{recording.record_id}")

      FileUtils.mkdir_p(format_dir)
      FileUtils.mv("#{playback_format.format}/#{recording.record_id}", format_dir, force: true)
    end
    callback_data = CallbackData.find_by(meeting_id: recording.meeting_id)
    callback_data&.update(recording_id: recording.id)
  end

`
I am not a ruby developer so my abilities to fix this are very limited. Can you please give us a hint how to resolve the problem?
Thanks

**Comment by gus1185** [comment]
Solved!

On the scalelite server run the command.

docker exec -i scalelite-api bundle exec rake db: migrate

On the bbb servers update the scalelite_batch_import.sh and scalelite_post_publish.rb files with the information from https://github.com/blindsidenetworks/scalelite/tree/master/bigbluebutton

Thanks!

**Comment by chehwi** [comment]
Hi gus1185,

thanks for your advice.
I have migrated the scalelite db schema as described.
Sadly this does not solve our problem. The problem persists.

@db-devs:
Can you please check if I am on the correct scalelite database schema? Here is my output from
`SELECT * FROM schema_migrations;`

```scalelitedb=# select * from schema_migrations;

version
 20181123180008
 20210425184558
(2 rows)

scalelitedb=#```

Thanks for your help!

**Comment by chehwi** [comment]
Hi @gus1185 ,

thanks for your information. The migration of the database schema solved the issue ;)

Thanks a lot for your help!

**Comment by Zvangi** [comment]
> Solved!
> 
> On the scalelite server run the command.
> 
> docker exec -i scalelite-api bundle exec rake db: migrate
> 
> On the bbb servers update the scalelite_batch_import.sh and scalelite_post_publish.rb files with the information from https://github.com/blindsidenetworks/scalelite/tree/master/bigbluebutton
> 
> Thanks!

I get don't know how to build task 'db:' error when i ran it on scalelite server.

Importer got stuck on a single presentation after upgrading... This really sucks.
