### ISSUE TITLE
Callback HTTP request failed: 400 Bad Request. Caught exception: Signature verification failed (code 400)

### ISSUE THREAD

**Issue by sparse91** [blindsidenetworks/scalelite#635]
Hi
We are using Moodle 3.9 with SL 1.1.7. SL gives this error when trying to send notification:

```
Recording Ready Notify for [149f7b223f48f31aff37887212054db12e577ebe] starts
Making callback for recording ready notification
Sending request to https://moodle-server.com/mod/bigbluebuttonbn/bbb_broker.php?action=recording_ready&bigbluebuttonbn=45539
Callback HTTP request failed: 400 Bad Request. Caught exception: Signature verification failed (code 400)
```

**Comment by amalrails** [comment]
@sparse91 can you verify if the value for Rails.configuration.x.loadbalancer_secrets[0] is same as your scalelite secret?

**Comment by sparse91** [comment]
I'm using LOADBALANCER_SECRETS with multiple secrets.

**Comment by amalrails** [comment]
can you try to open a rails console using `docker exec -it scalelite-api bin/rails c` then run the command `Rails.configuration.x.loadbalancer_secrets[0] `  and verify if the value is same as your scalelite secret?

**Comment by sparse91** [comment]
It is same as first secret but we have multiple : separated secrets. Does scalelite know which one to use?

**Comment by amalrails** [comment]
No SL does not know that but we use the Rails.configuration.x.loadbalancer_secrets[0] as the secret to encode the payload sent to moodle, and that secret should be the same as the one provided to moodle while adding the SL

**Comment by sparse91** [comment]
I have multiple moodles with different secrests. What can I do?

**Comment by amalrails** [comment]
do you have multiple SL?
