### ISSUE TITLE
docker logs scalelite-poller: : Couldn't find Server with id=972c6e83-59ca-42b6-9ab3-4d87ccc2c641

### ISSUE THREAD

**Issue by texh2s00** [blindsidenetworks/scalelite#650]
Docker Ubuntu 
<returncode>SUCCESS</returncode>
<version>2.0</version>
<build>v1.1.7.1</build>
W, [2021-08-30T10:40:42.209584 #6]  WARN -- : Failed to check meeting id=adfc4dc3bde2042ae887760a60473eb3d9134961-891-3873 status: Couldn't find Server with id=**19d1eea9-7c6e-48e5-baac-879ca4d54d73**
W, [2021-08-30T10:40:42.210499 #6]  WARN -- : Failed to check meeting id=07c9139463b0decc128eb3929457b7837d2f006f-1855-4054 status: Couldn't find Server with id=**19d1eea9-7c6e-48e5-baac-879ca4d54d73**
W, [2021-08-30T10:40:42.210788 #6]  WARN -- : Failed to check meeting id=483e3be8a90873cccb13a5224e2450b308e8ff33-518-3987 status: Couldn't find Server with id=**972c6e83-59ca-42b6-9ab3-4d87ccc2c641**
W, [2021-08-30T10:40:42.211758 #6]  WARN -- : Failed to check meeting id=2b9226ae70089759efae0228436a4ddd63516034-1308-2807 status: Couldn't find Server with id=972c6e83-59ca-42b6-9ab3-4d87ccc2c641
D, [2021-08-30T10:40:42.213361 #6] DEBUG -- : Polling Meeting id=5cb564c71a73db4797a7bf624d1d267a46154c93-74-7073 on Server id=0d67d2d4-7dff-489b-a7c0-c065f2435cb9
W, [2021-08-30T10:40:42.221256 #6]  WARN -- : Failed to check meeting id=745727902391deb4662f9af76af035cda746c5ea-1205-2218 status: Couldn't find Server with id=**19d1eea9-7c6e-48e5-baac-879ca4d54d73**
W, [2021-08-30T10:40:42.215099 #6]  WARN -- : Failed to check meeting id=7f953018dc65811ad6660a669b1f887d3c3a6072-26-4885[7522] status: Couldn't find Server with id=**972c6e83-59ca-42b6-9ab3-4d87ccc2c641**

Where is no such servers on my server list... Is what shadow bugs?

**Comment by amalrails** [comment]
@texh2s00 it looks like an old server which had meetings in it, but is removed now. These meetings still exist in the db even though the servers are removed. Not sure on how the servers were removed but to fix this  you will have to clear these meetings.

**Comment by texh2s00** [comment]
allready done, redis cache was igoriuos, i didn't changed server over the year.. but.. now seems no errors. Sorry for spending your time.
