### ISSUE TITLE
Can't use command-line tools after upgrade

### ISSUE THREAD

**Issue by JGallot** [blindsidenetworks/scalelite#653]
Hello,
My server has rebooted and scalelete has made his upgrade alone....sad
I've done the db:migrate and the recordings works but now i can't get the status of my servers :
For exemple, the command :
./bin/rake RAILS_ENV=production REDIS_NAMESPACE=scalite_production status

returns :

rake aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'meetings' for Server.
/usr/share/rvm/gems/ruby-2.6.5/gems/activemodel-6.0.2.2/lib/active_model/attribute_assignment.rb:53:in `_assign_attribute'
/usr/share/rvm/gems/ruby-2.6.5/gems/activemodel-6.0.2.2/lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
/usr/share/rvm/gems/ruby-2.6.5/gems/activemodel-6.0.2.2/lib/active_model/attribute_assignment.rb:43:in `each'
/usr/share/rvm/gems/ruby-2.6.5/gems/activemodel-6.0.2.2/lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
/usr/share/rvm/gems/ruby-2.6.5/gems/activemodel-6.0.2.2/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
/opt/scalelite/app/models/application_redis_record.rb:106:in `init_with_attributes'
/opt/scalelite/app/models/server.rb:190:in `block (2 levels) in all'
/opt/scalelite/app/models/server.rb:178:in `each'
/opt/scalelite/app/models/server.rb:178:in `block in all'
/opt/scalelite/app/models/application_redis_record.rb:133:in `block in with_connection'
/opt/scalelite/lib/redis_store.rb:35:in `block in with_connection'
/usr/share/rvm/gems/ruby-2.6.5/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/usr/share/rvm/gems/ruby-2.6.5/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/usr/share/rvm/gems/ruby-2.6.5/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/usr/share/rvm/gems/ruby-2.6.5/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/usr/share/rvm/gems/ruby-2.6.5/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/opt/scalelite/lib/redis_store.rb:35:in `with_connection'
/opt/scalelite/app/models/application_redis_record.rb:132:in `with_connection'
/opt/scalelite/app/models/server.rb:174:in `all'
/opt/scalelite/lib/tasks/status.rake:10:in `block in <main>'
Tasks: TOP => status
(See full trace by running task with --trace)

A field 'meetings' is missing, how can i fix that ?
Thanks

**Comment by amalrails** [comment]
hi @JGallot , how have you deployed scalelite?

**Comment by amalrails** [comment]
closing this issue, since no response.
