### ISSUE TITLE
how to find the running version

### ISSUE THREAD

**Issue by fireba11** [blindsidenetworks/scalelite#654]
Now this may or may not be a stupid question ...
If i'm pulling scalelite containers with version 1.1-stable, API shows Versions like "<build>v1.1-stable-0438c7a</build>" how do i figure out what release version that is in github to check the changelog?
Apparently that build # gets set when the container gets build
(https://hub.docker.com/layers/blindsidenetwks/scalelite/v1.1-stable/images/sha256-edfaa7a47b0aa3cd5e71a6b183efed9a2d22d4277ea1ef197187fbce046be7fa?context=explore)
But that's not really telling me much now, is it?

**Comment by Nemental** [comment]
The `0438c7a` in `v1.1-stable-0438c7a` is the shortened commit hash. For example you can get the commit and it's version with this link.
https://github.com/blindsidenetworks/scalelite/commit/<insert-commit-hash>

**Comment by amalrails** [comment]
@fireba11 is your query resolved?

**Comment by fireba11** [comment]
@amalrails yes, though figuring out what release version that is is rather unwieldy. at least i got a way to confirm if there is a problem :-)
