### ISSUE TITLE
Upgrade procedure for Scalelite 1.0 to the latest one

### ISSUE THREAD

**Issue by rabser** [blindsidenetworks/scalelite#656]
The documentation says that it's enough a docker pull of the new images, and I cannot find any other requirement.
I tried the upgrade (after a backup of redis and postgresql) but a db:migrate seems needed or I got errors about the protected field missing in the schema: could you kindly confirm this action? Should be run once or many times ?
After the upgrade, the old recordings got 404 not found when viewed (they are listed correctly), only newer recordings are viewable: I'm missing anything ?
The older rooms seem not available anymore too with an error like "room not found": do you have some hints about this weird behaviour ?
Now I got scalelite back to original release, as I can do tests only in nocturn hours...

thanks in advance for any suggestion.

**Comment by pielonet** [comment]
HI,
Effectively, upgrading to 1.1.x requires executing db:migrate, as stated here : https://github.com/blindsidenetworks/scalelite/releases/tag/v1.1

**Comment by rabser** [comment]
Thanks for your kind reply, but as i build the  docker images by myself, I didn't browse the releases page. Maybe this advice should be added to the README.md of the project at the upgrading chapter.

**Comment by rabser** [comment]
Dear all,
 last night I had the time to retry the upgrade procedure from SL 1.0 to SL 1.1.7.1 and was successful.
What's the lesson learned ?
Usually, I build by myself the SL docker images directly from a git clone of SL repo. The upgrade failed because I didn't check out the correct latest stable release (1.1.7.1) and I built the images from 1.2beta (probably not a safe choice in a production environment).
Started SL and applied the db:migrate and all was fine.
 
Another thing I missed was the update of the SL's scripts on the bigbluebutton servers (into the older ones the "-f" parameter check was missing, leading to errors in transmitting the recordings to SL)

I renew my suggestion to integrate the upgrade chapter in the SL's README.md, even only linking the releases' page to get aware of fundamental instruction on how to upgrade written there.

Hope this can help someone else and this issue can be closed.

**Comment by ffdixon** [comment]
Thanks for the feedback -- we also welcome if you want to send a pull request to add an Update section to the  `README.md` based on your experience.

**Comment by rabser** [comment]
Yes, i'll try, but i'm not so used to do PR on github, so I have to understand how to do it.

**Comment by amalrails** [comment]
@rabser We will be releasing the complete updated documentation for SL soon.

**Comment by rabser** [comment]
Hi @amalrails, I was'nt able to do a PR until now (my fault), but if can be useful, the following are some lines I prepared two days ago:

-------
## Upgrading

Before starting the upgrade procedure, a consistent backup of Redis Cache db, PostgreSQL db and recordings is suggested.

Look at the releases' page for special instructions for the target release , e.g. database schema upgrade or anything else and prepare to apply them.
Check for changes between the new scalelite's transferring scripts and the ones on your BBB servers, and prepare to substitute them.

Upgrade Scalelite to the latest version using one command:

`systemctl restart scalelite.target`

To confirm that you have the latest version, enter `http(s)://<scalelite-hostname>/bigbluebutton/api` in your browser and check that the value inside the `<build><\build>` tag is equal to the new version.

Now apply the special instructions (if needed) to your updated scalelite and update the scalelite transferring scripts on all of your BBB servers.
