### ISSUE TITLE
Question about TURNE server with multi BBB 

### ISSUE THREAD

**Issue by chezmohamed** [blindsidenetworks/scalelite#658]
Hello
I have some question about the tune server
how many bigblubutton servers can a TURNE server support?
what are the necessary characteristics for a TURNE server which supports 10 bigbluebutton servers
Thank you

**Comment by ffdixon** [comment]
It's a hard question to answer, but the good part is that a TURN server is mostly CPU and network bound.  You can setup multiple TURN servers with round-robin DNS.  

The best answer is to create a TURN server that is of the same CPU capacity for BigBlueButton and then monitor the TURN servers' CPU and Bandwidth usage during live use (say for 10 BigBlueButton servers).  

You'll then be able to gauge whether the ratio of TURN servers to BigBlueButton servers and adjust the ratio by increasing/decreasing the capacity of the TURN server itself (such as adding/removing CPU cores).

**Comment by chezmohamed** [comment]
thank you for your reply
You are right i will do it 
Thanks
