### ISSUE TITLE
Error when I run scalelite_batch_import.sh

### ISSUE THREAD

**Issue by chezmohamed** [blindsidenetworks/scalelite#663]
at script execution: scalelite_batch_import.sh 

I get the following error:

==========================
root@ip-172-31-19-75:/script# ./scalelite_batch_import.sh
Recording transferring to Scalelite starts
Transferring recording for cfb37e0e3bcdccf5226479b54af046d5cb7d2c81-1631103377016 to Scalelite
Found recording format: presentation/cfb37e0e3bcdccf5226479b54af046d5cb7d2c81-1631103377016
Creating recording archive
Transferring recording archive to /mnt/scalelite-recordings/var/bigbluebutton/spool
cfb37e0e3bcdccf5226479b54af046d5cb7d2c81-1631103377016.tar
rsync: mkstemp "/mnt/scalelite-recordings/var/bigbluebutton/spool/.cfb37e0e3bcdccf5226479b54af046d5cb7d2c81-1631103377016.tar.fv5dxd" failed: Permission denied (13)
sent 614,676 bytes  received 204 bytes  1,229,760.00 bytes/sec
total size is 614,400  speedup is 1.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Traceback (most recent call last):
./post_publish/scalelite_post_publish.rb:75:in `<main>': Failed to transfer recording archive (RuntimeError)

==============================

however I followed the NFS sharing process

======================
the configuration file : /usr/local/bigbluebutton/core/scripts/scalelite.yml 

work_dir: /var/bigbluebutton/recording/scalelite
spool_dir: /mnt/scalelite-recordings/var/bigbluebutton/spool

=========================
someone can help me

**Comment by chezmohamed** [comment]
can anyone help me  ?

**Comment by amalrails** [comment]
@chezmohamed https://unix.stackexchange.com/questions/541200/rsync-permission-denied-13-what-am-i-doing-wrong i think that might help

**Comment by chezmohamed** [comment]
@amalrails Thank you for your help in my case I used the transfer by NFS I do not use the rsync

**Comment by chezmohamed** [comment]
I changed the permission from 755 to 777 and it worked
