### ISSUE TITLE
scalelite-nginx.service - Scalelite Nginx Faile

### ISSUE THREAD

**Issue by cuongnd29** [blindsidenetworks/scalelite#668]
Pls help me. I dont know where error.
status:
"
scalelite-api.service - Scalelite API
     Loaded: loaded (/etc/systemd/system/scalelite-api.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-09-11 10:41:12 UTC; 2min 50s ago
    Process: 19718 ExecStartPre=/usr/bin/docker kill scalelite-api (code=exited, status=1/FAILURE)
    Process: 19725 ExecStartPre=/usr/bin/docker rm scalelite-api (code=exited, status=0/SUCCESS)
    Process: 19732 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-api (code=exited, status=0/SUCCESS)
    Process: 19748 ExecStartPost=/usr/bin/docker image prune -f (code=exited, status=0/SUCCESS)
   Main PID: 19747 (docker)
      Tasks: 9 (limit: 9513)
     Memory: 17.4M
     CGroup: /system.slice/scalelite-api.service
             └─19747 /usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-api --env-file /etc/default/scalelite --network scalelite --mount type=bind,source=/mnt/scalelite-rec>

Sep 11 10:41:17 docker-scalite docker[19747]: [9] * Listening on http://0.0.0.0:3000
Sep 11 10:41:17 docker-scalite docker[19747]: [9] ! WARNING: Detected 1 Thread(s) started in app boot:
Sep 11 10:41:17 docker-scalite docker[19747]: [9] ! #<Thread:0x00007f06d9a7e658 /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection>
Sep 11 10:41:17 docker-scalite docker[19747]: [9] Use Ctrl-C to stop
Sep 11 10:41:17 docker-scalite docker[19747]: [9] - Worker 0 (PID: 12) booted in 0.01s, phase: 0
Sep 11 10:41:17 docker-scalite docker[19747]: [9] - Worker 2 (PID: 21) booted in 0.01s, phase: 0
Sep 11 10:41:17 docker-scalite docker[19747]: [9] - Worker 1 (PID: 16) booted in 0.01s, phase: 0
Sep 11 10:41:17 docker-scalite docker[19747]: [9] - Worker 3 (PID: 27) booted in 0.01s, phase: 0
Sep 11 10:41:17 docker-scalite docker[19747]: [9] - Worker 4 (PID: 39) booted in 0.0s, phase: 0
Sep 11 10:41:17 docker-scalite docker[19747]: [9] - Worker 5 (PID: 46) booted in 0.0s, phase: 0

● scalelite-nginx.service - Scalelite Nginx
     Loaded: loaded (/etc/systemd/system/scalelite-nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2021-09-11 10:41:17 UTC; 2min 45s ago
    Process: 19763 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
    Process: 19802 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=1/FAILURE)
    Process: 19822 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0/SUCCESS)
    Process: 20090 ExecStart=/usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-nginx --env-file /etc/default/scalelite --network scalelite --publish 80:80 --publish 443:443>
    Process: 20091 ExecStartPost=/usr/bin/docker image prune -f (code=exited, status=0/SUCCESS)
   Main PID: 20090 (code=exited, status=125)

Sep 11 10:41:17 docker-scalite docker[19822]: v1.1-nginx: Pulling from blindsidenetwks/scalelite
Sep 11 10:41:17 docker-scalite docker[19822]: Digest: sha256:f06816239b3f7794196f3a11c67fb72c8dc0fc5670fe2d7ee6510acc059b1c38
Sep 11 10:41:17 docker-scalite docker[19822]: Status: Image is up to date for blindsidenetwks/scalelite:v1.1-nginx
Sep 11 10:41:17 docker-scalite docker[19822]: docker.io/blindsidenetwks/scalelite:v1.1-nginx
Sep 11 10:41:17 docker-scalite docker[20091]: Total reclaimed space: 0B
Sep 11 10:41:17 docker-scalite docker[20090]: docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /mnt/scalelite-recordings/var/bigbluebutton/publis>
Sep 11 10:41:17 docker-scalite docker[20090]: See 'docker run --help'.
Sep 11 10:41:17 docker-scalite systemd[1]: Started Scalelite Nginx.
Sep 11 10:41:17 docker-scalite systemd[1]: scalelite-nginx.service: Main process exited, code=exited, status=125/n/a
Sep 11 10:41:17 docker-scalite systemd[1]: scalelite-nginx.service: Failed with result 'exit-code'.
"
etc/default/scalelite:
URL_HOST=scalite-vlu.thinkingschool.vn
SECRET_KEY_BASE=056c97a0aeb489b07193748429546ac637a2bd95c2f0d4721143c72a43c9a417a7f44f276c8057908ead1cc4055026a114ca1124ce3484baa35e7601bb02c567
LOADBALANCER_SECRET=fa48f9546559cdb8f690de2bd8ba4cf90078feba9fc6ddf87a62649c6b4f90d7
DATABASE_URL=postgresql://10.21.27.253:5432
REDIS_URL=redis://10.21.27.253:6379
SCALELITE_TAG=v1.1
SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton
NGINX_SSL=true
SCALELITE_NGINX_EXTRA_OPTS=--mount type=bind,source=/etc/letsencrypt,target=/etc/nginx/ssl,readonly
WEB_CONCURRENCY=6
RAILS_ENV=production

I intall all postgres, redis, scalelite in same server: 10.21.27.253

**Comment by pielonet** [comment]
Hi,
The error is in the logs :

> Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /mnt/scalelite-recordings

You must have a path on the host starting with `/mnt/scalelite-recordings` as declared in your config file : `SCALELITE_RECORDING_DIR=/mnt/scalelite-recordings/var/bigbluebutton`

**Comment by cuongnd29** [comment]
thank so much.
I still have error:
● scalelite-poller.service - Scalelite Meeting Status Poller
     Loaded: loaded (/etc/systemd/system/scalelite-poller.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2021-09-12 03:22:53 UTC; 1min 10s ago
    Process: 2928 ExecStartPre=/usr/bin/docker kill scalelite-poller (code=exited, status=1/FAILURE)
    Process: 2971 ExecStartPre=/usr/bin/docker rm scalelite-poller (code=exited, status=0/SUCCESS)
    Process: 2995 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-poller (code=exited, status=0/SUCCESS)
    Process: 3155 ExecStart=/usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-poller --env-file /etc/default/scalelite --network scalelite blindsidenetwks/scalelite:${SCALE>
    Process: 3156 ExecStartPost=/usr/bin/docker image prune -f (code=exited, status=0/SUCCESS)
   Main PID: 3155 (code=exited, status=1/FAILURE)

Sep 12 03:22:52 docker-scalite docker[3155]: /srv/scalelite/lib/tasks/poll.rake:14:in `block (2 levels) in <main>'
Sep 12 03:22:52 docker-scalite docker[3155]: /srv/scalelite/lib/tasks/poll.rake:12:in `loop'
Sep 12 03:22:52 docker-scalite docker[3155]: /srv/scalelite/lib/tasks/poll.rake:12:in `block in <main>'
Sep 12 03:22:52 docker-scalite docker[3155]: /srv/scalelite/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Sep 12 03:22:52 docker-scalite docker[3155]: /usr/bin/bundle:23:in `load'
Sep 12 03:22:52 docker-scalite docker[3155]: /usr/bin/bundle:23:in `<main>'
Sep 12 03:22:52 docker-scalite docker[3155]: Tasks: TOP => poll:all => poll:meetings
Sep 12 03:22:52 docker-scalite docker[3155]: (See full trace by running task with --trace)
Sep 12 03:22:53 docker-scalite systemd[1]: scalelite-poller.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 03:22:53 docker-scalite systemd[1]: scalelite-poller.service: Failed with result 'exit-code'.

I try to fix but I dont know what problem with docker?
