### ISSUE TITLE
PostgreSQL settings

### ISSUE THREAD

**Issue by erenilhan** [blindsidenetworks/scalelite#67]
Hi ,
I want ask something. Can i install scalelite server and postgresql in same server?
If is it true i got an error message.
 What is correct `DATABASE_URL` for env. ?
Here is errors screenshots
![Error Details](https://user-images.githubusercontent.com/5827342/76689421-c8c02180-6646-11ea-9897-5d0980652da7.jpeg)

**Comment by tomlp** [comment]
@erenilhan,
look into /etc/postgresql/10/main/ph_hba.conf.
there should be entrys like: 
```

host    scalelite       scalelite       172.18.0.2/32           trust
host    postgres        scalelite       172.18.0.2/32           trust
```
the IP-Address depends on you setting and comes from the Docker-Container !!! THIS connection is done over the "normal" Network (may be on the same maschine). So localhost or socket did't not work (except you redirect the socket into the container, but this would be to hard for my self).

To bring this into work, you have to bind Postgresql to your Interface (for easy setup all interfaces).
To do so, you look for the entry `listen_addresses = '*'` and remove the # on the beginning. Change the address from localhost to "*" and restart postgres.

hth - kr Tom

**Comment by tomlp** [comment]
@erenilhan 
i forgot the URL :)
`DATABASE_URL=postgresql://bbb-cluster.xxx-yyy.com:5432`
i used the FQDN, but the IP-Address should be enough too....
kr Tom

**Comment by erenilhan** [comment]
Hi @tomlp 
Thnaks for helping :) its working now. 
But i want ask something again. How can i call api scalelite loadbalancer ? 
Is it same bbb-api for create parameters?  what is endpoint?

**Comment by ffdixon** [comment]
There isn't any API for the scalelite load balancer itself (other than it's implementation of the BigBlueButton API calls).   

You use the `rake` commands in the docs to manage your servers.

**Comment by tomlp** [comment]
@erenilhan ,

to clearify (on of missing connections for me) : 
I had a Greenlight instance running for my single BBB-Server. After installing Scalelite:

On Greenlight give the BIGBLUEBUTTON_SECRET from your Scalelite-Secret (as explaint: `rake secret`) and the BIGBLUEBUTTON_ENDPOINT should have the URL from your new Scalelite-Web-Container-machine....
In Scalelite you have to add your servers (each with here URL and secrets - as explaint in the original documentation)
Scalelite orchestra afterwards the right BBB-Server (with the lowest load) and give the right room-id´s to the participant.

HTH & kr Tom
PS: is it wrong if i call Scalelite as an API-Proxy for BBB ?

**Comment by erenilhan** [comment]
Hi again,
I did fix this issue. we did setup 4 different bbb server and 1 load balancer server (redis and postgresql in same server). It's working perfectly.

**Comment by erenilhan** [comment]
@ffdixon is this scalelite-loadbalancer only about the number of participants and the class?
Or can the processor look at some features like cpu?
If i create one big server and 3 small server, can i make different scenario?

**Comment by tomlp** [comment]
@erenilhan ,
i would recommend the settings in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` of your BBB-Server(s):
```
# Default maximum number of users a meeting can have.
# Current default is 0 (meeting doesn't have a user limit).
defaultMaxUsers=80
```
you must set it **on every** server and you should set the parameter to a value that this specific server can serve.
Hopefully the Scalelite will respect the server parameter  :) 
I set it in this way and for now it runs as expected.
kr Tom

**Comment by ffdixon** [comment]
We would *not* recommend setting a value for `defaultMaxUsers`.  We would recommend keeping it at 0

~~~
defaultMaxUsers=0
~~~

We kinda regret implementing this as it's a hard stop -- the actual join request will return an error that many front-ends don't know what to do with.

You can use it (put it at some large number), but the experience for end users is not great.  Basically, you want to provision your Scalelite pool so you can handle the load of users (and not show them error messages).

We may improve this in the future.

**Comment by farhatahmad** [comment]
@erenilhan 

At the moment, Scalelite only looks at the number of meetings on each server and equally balances the load across them.

**Comment by tomlp** [comment]
@ffdixon ,
ok - got it. in our case (the reason for my decision) whose a invitation from our directors to our employees regarding Corona-19.....
The BBB-Server had a load average of 500.00 and 300 Sessions. We must kill the server in a hard way and it was not the best decision i hurt :(
I asked for a other solution and the only option is that the moderator grants the entry for every single person in the beginning... Not a easy Job for 100 People :)
i monitor the healthy and count usage of rooms - will see if we upper the values ot to set it back to 0 if enough servers are up (currently 3) so all sessions could be served.
kr Tom

PS: i nominated BBB for the best Corona-19 preventer !!! :)

**Comment by farhatahmad** [comment]
@tomlp Thank you for the kind words. Let us know if you run into any other issues with Scalelite
