### ISSUE TITLE
Rails Error

### ISSUE THREAD

**Issue by mortazan** [blindsidenetworks/scalelite#673]
Rails Error: Unable to access log file. Please ensure that /srv/scalelite/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /srv/scalelite/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.

**Comment by jfederico** [comment]
https://en.wikipedia.org/wiki/Chmod

**Comment by mortazan** [comment]
error again ....

root@localhost:~# chmod 0664 /srv/scalelite/log/production.log

root@localhost:~# docker exec -i scalelite-api bundle exec rake servers
Rails Error: Unable to access log file. Please ensure that /srv/scalelite/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /srv/scalelite/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.

**Comment by samuelpetrosyan** [comment]
I have the same error

**Comment by samuelpetrosyan** [comment]
@jfederico what can we do to fix this error? Thanks in advance.

**Comment by JeanPluzo** [comment]
Hi,
having same error. Using latest release. Just wanted to make a +1.
@jfederico could you please help us? Is there a workaround?
I tried entering the scalelite-api container, unfortunately there's no bash shell included.
Gracias de antemano!

**Comment by claudiohormazabal** [comment]
Hello here is the solution - Hola, Acá la solución (notar la equivalencia de los directorios entre el host y docker):
root@srv-bbblb:/home/bbb/scalelite-run# cat docker-compose.yml | grep srv
      - ./log/scalelite-api/:/srv/scalelite/log/
root@srv-bbblb-pro:/home/bbb/scalelite-run# cd log/scalelite-api/
root@srv-bbblb-pro:/home/bbb/scalelite-run/log/scalelite-api# chmod 777 production.log
root@srv-bbblb-pro:/home/bbb/scalelite-run/log/scalelite-api# docker exec -i scalelite-api bundle exec rake status
    HOSTNAME     STATE   STATUS  MEETINGS  USERS  LARGEST MEETI  VIDEOS
                                                        NG
 bbb1.domian.cl  enabled  online  0         0      0              0
