### ISSUE TITLE
View records bbb 2.3 - 404 with playback 2.3

### ISSUE THREAD

**Issue by aguerson** [blindsidenetworks/scalelite#677]
Hi guys,
When I try to view my record with the playback link 

https://host.domain/playback/presentation/2.3/$id

I get a 404 ?

It is the same with scalelite or in direct.

I saw some issue with a trick to re-use playback 2.0.

Is it normal ?

Is there a way to use the playback 2.3 without the 404 ?
Regards,
Aurélien

**Comment by rabser** [comment]
Which scalelite release are you using ? You should have an up-to-date release os scalelite (eg. 1.1.8) to support BBB v2.3, or the new playback tool will be missing in scalelite, that's why you get 404 errors.

**Comment by aguerson** [comment]
I use 1.1.8 :'(

**Comment by aguerson** [comment]
the tool is installed
```
ls -al /var/bigbluebutton/playback/presentation/
total 24
drwxr-xr-x 6 bigbluebutton23 bigbluebutton23 4096 Aug 13 16:43 .
drwxr-xr-x 3 bigbluebutton23 bigbluebutton23 4096 Sep  6 16:59 ..
drwxr-xr-x 5 bigbluebutton23 bigbluebutton23 4096 Aug 13 16:43 0.81
drwxr-xr-x 5 bigbluebutton23 bigbluebutton23 4096 Aug 13 16:43 0.9.0
drwxr-xr-x 5 bigbluebutton23 bigbluebutton23 4096 Sep 22 16:50 2.0
drwxr-xr-x 4 bigbluebutton23 bigbluebutton23 4096 Sep 22 17:43 2.3
```

**Comment by aguerson** [comment]
c'est quoi "polls.json" ?

**Comment by aguerson** [comment]
I try to understand what is the problem..

**Comment by rabser** [comment]
I run also SL1.1.8 and the 2.3 presentation runs fine. You should check what's happening in the docker log for your scalelite-nginx container. Also start checking the "hot" files about presentation that are stored in /etc/bigbluebutton/nginx

**Comment by aguerson** [comment]
OK 404 comes from 
`/var/bigbluebutton/playback/presentation/2.3/static/js/main.a25a0a90.chunk.js`
But I don't know why

**Comment by aguerson** [comment]
there are many URL inside
like 
`PUBLIC_URL:"/playback/presentation/2.3"`

**Comment by aguerson** [comment]
In nginx log file I can read this
```
"/var/bigbluebutton/published/presentation/$id/notes.html" failed (2: No such file or directory),...
"/var/bigbluebutton/published/presentation/$id/polls.json" failed (2: No such file or directory),
"/var/bigbluebutton/published/presentation/$id/external_videos.json" failed (2: No such file or directory)
```

**Comment by rabser** [comment]
But $id was changed by you or it's the effective log text ?
In my logs I can view:
/var/bigbluebutton/published/presentation/aa2f474514145b44a07af3eb4441644d4d84e204-1615446061457/notes.html
and the $id url part is effective (in this post I changed some numbers for security).

**Comment by aguerson** [comment]
I changed the uid by $id ( security )

**Comment by aguerson** [comment]
In fact, I don't undurstand why on a fresh BBB 2.3.14, I can't read the records with playback 2.3.

...
Is there anay problem to read them from the BBB instance ?
On scalelite, it doesn't work, but it should work and the BBB instance ?

**Comment by aguerson** [comment]
I read many issue to by-pass playback 2.3 to re-use 2.0.

Is playback 2.3 is OK for now ? Or there is still some problem to use it ?

**Comment by rabser** [comment]
In my experience in the last three weeks, playback 2.3 works fine. no needs to revert back to 2.0.
Getting back to 404, inspecting from inside the nginx container, the directory /var/bigbluebutton/published/presentation/$id/ exists and it's readable by the nginx process ? maybe you have wrong permissions on the SCALELITE_RECORDING_DIR ?

**Comment by aguerson** [comment]
```
bbb-x published$ls -al
total 24
drwxr-xr-x  6 bigbluebutton bigbluebutton 4096 Sep  9 14:41 .
drwxr-xr-x 16 bigbluebutton bigbluebutton 4096 Sep 23 16:06 ..
drwxr-xr-x  2 bigbluebutton bigbluebutton 4096 Sep  9 14:41 notes
drwxr-xr-x  2 bigbluebutton bigbluebutton 4096 Sep 23 13:08 podcast
drwxr-xr-x  3 bigbluebutton bigbluebutton 4096 Sep 23 13:22 presentation
drwxr-xr-x  2 bigbluebutton bigbluebutton 4096 Sep  9 14:41 screenshare
bbb-x published$cd presentation/
bbb-x presentation$ls -al
total 12
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Sep 23 13:22 .
drwxr-xr-x 6 bigbluebutton bigbluebutton 4096 Sep  9 14:41 ..
drwxr-xr-x 4 bigbluebutton bigbluebutton 4096 Sep 23 13:22 5aae0b057c53c3a73bbe6f0a3c446f4732f9e6d3-1632395962412
bbb-x presentation$cd 5aae0b057c53c3a73bbe6f0a3c446f4732f9e6d3-1632395962412/
bbb-x 5aae0b057c53c3a73bbe6f0a3c446f4732f9e6d3-1632395962412$ls -al
total 80
drwxr-xr-x 4 bigbluebutton bigbluebutton  4096 Sep 23 13:22 .
drwxr-xr-x 3 bigbluebutton bigbluebutton  4096 Sep 23 13:22 ..
-rw-r--r-x 1 bigbluebutton bigbluebutton     2 Sep 23 13:22 captions.json
-rw-r--r-x 1 bigbluebutton bigbluebutton 21654 Sep 23 13:22 cursor.xml
-rw-r--r-x 1 bigbluebutton bigbluebutton    57 Sep 23 13:22 deskshare.xml
-rw-r--r-x 1 bigbluebutton bigbluebutton  1966 Sep 23 13:22 metadata.xml
-rw-r--r-x 1 bigbluebutton bigbluebutton   150 Sep 23 13:22 panzooms.xml
drwxr-xr-x 3 bigbluebutton bigbluebutton  4096 Sep 23 13:22 presentation
-rw-r--r-x 1 bigbluebutton bigbluebutton   234 Sep 23 13:22 presentation_text.json
-rw-r--r-x 1 bigbluebutton bigbluebutton 14508 Sep 23 13:22 shapes.svg
-rw-r--r-x 1 bigbluebutton bigbluebutton    33 Sep 23 13:22 slides_new.xml
drwxr-xr-x 2 bigbluebutton bigbluebutton  4096 Sep 23 13:22 video
bbb-x 5aae0b057c53c3a73bbe6f0a3c446f4732f9e6d3-1632395962412$ls -al presentation
total 16
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Sep 23 13:22 .
drwxr-xr-x 4 bigbluebutton bigbluebutton 4096 Sep 23 13:22 ..
drwxr-xr-x 4 bigbluebutton bigbluebutton 4096 Sep 23 13:22 d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1632395963412
-rw-r--r-x 1 bigbluebutton bigbluebutton 3993 Sep 23 13:22 logo.png
bbb-x 5aae0b057c53c3a73bbe6f0a3c446f4732f9e6d3-1632395962412$ls -al presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1632395963412/
total 196
drwxr-xr-x 4 bigbluebutton bigbluebutton  4096 Sep 23 13:22 .
drwxr-xr-x 3 bigbluebutton bigbluebutton  4096 Sep 23 13:22 ..
-rw-r--r-x 1 bigbluebutton bigbluebutton 10530 Sep 23 13:22 slide-10.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 10530 Sep 23 13:22 slide-11.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 10530 Sep 23 13:22 slide-12.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 10530 Sep 23 13:22 slide-13.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 14828 Sep 23 13:22 slide-1.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 14980 Sep 23 13:22 slide-2.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 14830 Sep 23 13:22 slide-3.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 14947 Sep 23 13:22 slide-4.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 14830 Sep 23 13:22 slide-5.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 14947 Sep 23 13:22 slide-6.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 10530 Sep 23 13:22 slide-7.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 10530 Sep 23 13:22 slide-8.png
-rw-r--r-x 1 bigbluebutton bigbluebutton 10530 Sep 23 13:22 slide-9.png
drwxr-xr-x 2 bigbluebutton bigbluebutton  4096 Sep 23 13:22 textfiles
drwxr-xr-x 2 bigbluebutton bigbluebutton  4096 Sep 23 13:22 thumbnails
bbb-x 5aae0b057c53c3a73bbe6f0a3c446f4732f9e6d3-1632395962412$
```

**Comment by aguerson** [comment]
@rabser rights is good... I don't understand...

It seems to be a js 404 error.

I use Firefox-ESR

What did you use ?

**Comment by rabser** [comment]
Firefox 92 on windows or linuxes.
But the "ls- al" where fired from inside or outside the scalelite-nginx container  ? I see an unusual prompt for scalelite docker container: for me the sh prompt is "<currentpath> #", not "hostname <currentdir>".
You should check from inside the container the file readability.

**Comment by aguerson** [comment]
I have the same issue inside my scalelite and the bbb 2.3.13 host
The same error 404
the error is printed by
`/var/bigbluebutton/playback/presentation/2.3/static/js/main.a25a0a90.chunk.js`

Why ?

**Comment by aguerson** [comment]
Is there a condition that is not respected ?
Which one ?
I am not a js expert :'(

**Comment by rabser** [comment]
I give up, but think that bbb servers and scalelite do not share the same playback code, each of them has their own copy, so if you have the same error, I would suggest to check elsewhere.

**Comment by aguerson** [comment]
@rabser thansk again.
I found my problem
https://github.com/bigbluebutton/bigbluebutton/issues/13275

...

**Comment by amalrails** [comment]
thanks @rabser
