### ISSUE TITLE
Have a more than 200 users in the Bigbluebutton based on scalelite

### ISSUE THREAD

**Issue by harika1258** [blindsidenetworks/scalelite#680]
Hi
@jfederico , @ffdixon ,@kepstin 
I have 4 bbb-servers which are handling with Scalelite.
everything is OK. 
I'd like to have 600 users as a webinar in the one session. is it possible?

**Comment by ffdixon** [comment]
While Scalelite can load balance sessions by placing each session on the least loaded BigBlueButton server, once a session starts, it runs on that placed server.  Scalelite helps with load balancing the creation of a meeting, not the joining of a meeting.

We recommend each BigBlueButton session hold [150 users](https://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support) (or less).

Therefore, you can't have 600 users in a single session (using scalelite or not).
