### ISSUE TITLE
The videos are not displayed on the platform - redis

### ISSUE THREAD

**Issue by WinterJV** [blindsidenetworks/scalelite#681]
Hello, good morning:) 

If you could help me, I would appreciate them a lot, what happens is that where I had redis the server stopped working, the Postgresql DB made it in the same scalelite therefore it is intact.

If I change redis to another server, the videos are not shown on the platform, the ones that were being stored in the BD.

There is a way to restart the redis so that it recognizes everything from the postgressql or in this case it would need to be done :( I have investigated but I can not find anything

**Comment by amalrails** [comment]
@WinterJV i m sorry, i cannot understand your query clearly. Could you be more specific and provide more details about your problem, the way you have deployed ?

**Comment by WinterJV** [comment]
Sure, I managed to get the "dump.rdb" file from the inactive server, but passing it to the new server does not show the thumbnail videos on its proper platform.

first stop the redis process, Systemctl stop redis

then I replaced the dump.rdb of my server to put the one I had before.

then turn redis back on so it would get that new dump.rdb file

but the videos are not shown on the platform :( I would have to restart redis to get the data from the postgresql, is there any way ?

**Comment by WinterJV** [comment]
In greenlight it says that "This room has no recordings" but actually it does, I have the postgresql DB intact.

It is only redis that as it stored certain information in memory cache it could show them, but since I no longer have that server but I managed to rescue "dump.rdb" to be able to use it on the new server.

Or will there be a way to get the data back so that redis will recognize it from the postgresql Database and can display it now if :( ?


![Captura](https://user-images.githubusercontent.com/76982267/134985620-7b1b242c-6176-48e1-a76d-c3703b81eb15.JPG)

**Comment by WinterJV** [comment]
oh, look at something strange, I see that it rewrites the data of the dump.rdb to how it was the previous

Will I have to remove redis from 0 to make it clean and add the backup "dump.rbd" without it being overwritten?

I will delete those that are left over later, but from what I see it overwrites it and that is why it does not show me the videos, right? since it does not have the previous backup (the one I need) but it still has the new one.


![redis](https://user-images.githubusercontent.com/76982267/135003691-90188043-d1d7-4efd-abff-c45e46a7e0ab.JPG)

**Comment by rabser** [comment]
AFAIK, redis is not involved in recordings playback, so I believe you're looking at the wrong side.

**Comment by WinterJV** [comment]
Not to reproduce the recordings, but to be able to see them on the platform that can show them since the message it shows says "This room has no recordings", or am I wrong:( ?

I still haven't been able to find a solution :(, I'll see that it doesn't overwrite the data in the new backup of the dump.rdb

**Comment by rabser** [comment]
Listing all the keys on the redis connected to my SL installation, I saw only runtime data for SL management (eg. rooms/servers) nothing about recordings. I'm using SL 1.1.7.1
