### ISSUE TITLE
Poller fails due to old Amazon-Linux Certificates

### ISSUE THREAD

**Issue by michaelsergio** [blindsidenetworks/scalelite#688]
I noticed my scalelite-poller was failing to connect to my living BBB instances.

I tried to curl the BBB instances and noticed I was receiving certificate expiration failures.
When I switched from an amazon-linux image to an alpine based image, the poller was able to see my BBB instances and the curl requests worked.

I believe the issue I encountered has to do with the recently expired Let's Encrypt root certificate.
It appears that Amazon Linux is using old root CA data.
https://github.com/amazonlinux/container-images/issues/51

The above issue should be monitored and when the base images are updated, the Dockerfiles in this project should also be updated.

**Comment by alizamanir** [comment]
as a fast solution, you can change the containers from amazon-linux

edit the /etc/default/scalelite and comment the SCALELITE_TAG and use a version with no "-bionic230-amazonlinux" on its end

it will be some think like this:

SCALELITE_TAG=v1.1
#SCALELITE_TAG=v1.2-alpha-bionic230-amazonlinux
#SCALELITE_TAG=v1.1-bionic230-amazonlinux

then restart the scalelite using:
systemctl restart scalelite.target

and the BBB servers will back online.

**Comment by jfederico** [comment]
Thanks @michaelsergio. I was not aware that amazonlinux images were using the old root CA certificate. They will need to be updated as soon as there is a fix for that. We'll be monitoring.

Thanks @alizamanir, your suggestions seems to be the only workaround for now.

**Comment by alsammak1981** [comment]
Hello there
Still there is no update about this issue?
I am facing issue with redis also .. is that related to the certification issue ?

**Comment by jfederico** [comment]
@alsammak1981 there was nothing to do until 7 hours ago. See https://github.com/amazonlinux/container-images/issues/51

Although, you can use the alpine image instead of the amazonlinux one. 

If you still have an issue, then it is a different problem, please open a new issue with all the information required because this one is about the amazon linux alternate image not working properly
