### ISSUE TITLE
BBBs disconnected from Scalelite

### ISSUE THREAD

**Issue by alsammak1981** [blindsidenetworks/scalelite#691]
Hello There

Ubuntu 18.4 aws linux
Scalelite V1.2
Redis server v=4.0.9

I am facing an issue on Scalelite as it keep disconnecting the BBBs and I have to register and enable again and again.

I found the following error in the redis-server.log

1322:M 05 Oct 13:41:29.053 * 1 changes in 900 seconds. Saving...
1322:M 05 Oct 13:41:29.054 * Background saving started by pid 8022
8022:C 05 Oct 13:41:29.054 # Failed opening the RDB file crontab (in server root dir /etc) for saving: Read-only file system
1322:M 05 Oct 13:41:29.154 # Background saving error
1322:M 05 Oct 13:41:33.450 # Failed opening the RDB file backup.db (in server root dir /etc) for saving: Read-only file system
1322:M 05 Oct 13:41:33.900 # Failed opening the RDB file backup.db (in server root dir /etc) for saving: Read-only file system
1322:M 05 Oct 13:41:35.060 * 1 changes in 900 seconds. Saving...
1322:M 05 Oct 13:41:35.061 * Background saving started by pid 8024
8024:C 05 Oct 13:41:35.061 # Failed opening the RDB file backup.db (in server root dir /var/spool/cron) for saving: Read-only file system
1322:M 05 Oct 13:41:35.161 # Background saving error
1322:M 05 Oct 13:41:35.472 # Failed opening the RDB file root (in server root dir /var/spool/cron) for saving: Read-only file system
1322:M 05 Oct 13:41:35.924 # Failed opening the RDB file root (in server root dir /var/spool/cron) for saving: Read-only file system

I accessed redis-cli and set the dir and dbfilename as it should be from redis.conf but after sometime again the process will start to write /etc and /var/spool/cron

Inoticed that the BBBs will be disconnected once it is trying to opening  /var/spool/cron 
Failed opening the RDB file crontab (in server root dir /etc) for saving: Read-only file system

while when it is trying to open from /etc or the original path from the redis.conf the BBBs are connected.

also in the status redis.service i got the following error
redis-server.service: Can't open PID file /var/run/redis/redis-server.pid (yet?) after start: No such file or directory

**Comment by rabser** [comment]
Take a look at the answers here: https://stackoverflow.com/questions/44814351/failed-opening-the-rdb-file-read-only-file-system
It's not enough to change the redis.conf if you don't circumvent the security measures in systemd.

**Comment by alsammak1981** [comment]
Dear rabser

Thank you for your reply I already did the suggestion in the article but it did not work.

would you please explain maybe i am missing something; i checked all the directories under the systemd and found only the root user.

"if you don't circumvent the security measures in systemd"

Thank you in advance.

**Comment by rabser** [comment]
You should change the redis.service according to the directories where you would like that the redis daemon will write to the persistence data. If the redis daemon do not save their data periodically, it forgets them and your BBB servers disappear.
After changing the redis.service your should do a systemctl daemon-reload  and a systemctl restart redis to get your changes effective.

**Comment by alsammak1981** [comment]
I did reload the daemon and restart the redis but it keep changing !

I did fresh install and still the same issue 

the strange thing thing that it will get disconnected only when trying to open the file in /var/spool/cron while when trying to open the file in /etc the BBBs still connected..

and I can not any place in the configuration that listing any of there directories ..
