### ISSUE TITLE
CORS Error on custom frontend

### ISSUE THREAD

**Issue by mayank-kohbee** [blindsidenetworks/scalelite#694]
Creating a scalable BBB platform. 
Load Balancer and the BBB servers are configured and validated using  https://mconf.github.io/api-mate/
It is working as expected.

The problem is arising when we try to incorporate the same apis to self developed UI.
NOTE: The self developed UI is working perfectly fine with standalone BBB servers.

But when we replace it with a load balancer server and its respective LOADBALANCER_SECRET, the first hit of the API itself is throwing CORS error.

<img width="299" alt="Screenshot 2021-10-06 at 7 21 24 PM" src="https://user-images.githubusercontent.com/91543521/136216227-77839170-c16e-4a30-8ca6-3c76acf0a3a6.png">

scalelite version: v1.1-bionic230-amazonlinux
loadbalancer & BBB servers: AWS EC2

**Comment by mayank-kohbee** [comment]
Deployment:
 1: systemd deployment
 2: Versions:
<img width="790" alt="Screenshot 2021-10-08 at 11 00 12 AM" src="https://user-images.githubusercontent.com/91543521/136504090-f581e51f-2344-4539-bcee-8850d5c2cbeb.png">

3: Tools Used: 
        -   Google Chrome Version 94.0.4606.71
        -   Flutter for web application (Custom UI). (Mobile application is working as expected)

Steps to reproduce: 

1. Make 2 BBB servers (AWS EC2 instance with c5.2xlarge configuration)
    - bbb1.xxxx.com
    - bbb2.xxxx.com
   

2. Make 1 Load Balancer server and add both the BBB servers like ./bin/rake servers:add[bbb1.xxxx.com/bigbluebutton/api,SECRET_KEY]
    - loadbalance.xxxx.com

3. Custom Front-end hosting (hosted in GCP)
    - classes.xxxx.com

4. Connect the front-end with loadbalancer details like "loadbalance.xxx.com/bigbluebutton/api" & LOADBALANCER_SECRET.
5. Try accessing the loadbalancer through classes.xxxx.com.
6. It should redirect to loadbalance.xxxx.com first then direct to any of BBB server.. But it is giving CORS error.
7. It is actually generating meeting id using create api when we face the issue.'


By the time will try to incorporate Moodle.

**Comment by amalrails** [comment]
@mayank-kohbee did the moodle integration work for you? I m guessing it has something to do with the custom UI integration.

**Comment by mayank-kohbee** [comment]
Any help you can provide for the same?
