### ISSUE TITLE
recordings are not deleted from disk

### ISSUE THREAD

**Issue by geraldh** [blindsidenetworks/scalelite#70]
**Problem**:
When you delete a recording from the greenlight (connected to scalelite) webgui, the files are not deleted from the disk on the scalelite server.

**Solution**:
mount $SCALELITE_RECORDING_DIR in systemd `scalelite-api.service`
```
ExecStart=/usr/bin/docker run --name scalelite-api --env-file /etc/default/scalelite --network scalelite --mount type=bind,source=${SCALELITE_RECORDING_DIR},target=/var/bigbluebutton blindsidenetwks/scalelite:${SCALELITE_TAG}-api

**Comment by farhatahmad** [comment]
Hi @geraldh,

Good catch, thanks for reporting. Making the fix now

**Comment by farhatahmad** [comment]
Documentation fixed now. Thanks again for the report
