### ISSUE TITLE
Not importing new recordings and 404 not found error on browser

### ISSUE THREAD

**Issue by orksworld** [blindsidenetworks/scalelite#702]
Hi,

We are running scalelite v1. New recording are not imported. We get 404 error message when we try to view recording from browser. 

`docker logs scalelite-recording-importer  | grep -v INFO | grep -v DEBUG
E, [2021-10-12T08:39:53.666482 #7] ERROR -- : Failed to import recording: unknown attribute 'protected' for Recording.`

`ls /mnt/scalelite-recordings/var/bigbluebutton/spool |wc -l 977`

we already runned: docker exec -t scalelite-api bundle exec rake db:migrate

Can you please help us with our problem.

Thanks,

**Comment by MrCapitalist** [comment]
> @orksworld can you check your recording_importer logs and verify if the errors are similar to the one posted [here](https://github.com/blindsidenetworks/scalelite/issues/700#issue-1021712877) if yes then you can fix it by following [link](https://github.com/blindsidenetworks/scalelite/issues/700#issuecomment-941057691)

Excuse me, please check my closed topic again. Thanks.
