### ISSUE TITLE
Code 1130: Broken Iframe Screensharing

### ISSUE THREAD

**Issue by wilkis3** [blindsidenetworks/scalelite#730]
**Deployment (required):**
1. Deployment: docker-compose (Deployed with the following [Ansible role](https://github.com/ebbba-org/ansible-role-scalelite))
2. Versions: Ubuntu 20.04, Scalelite 1.0 - 1.3, BBB 2.10 - 2.14, 
3. Tools used for reproducing the issue: Chromium: 94.0, Firefox 94.0, api-mate

**Describe the problem (required):**
Screensharing in an iframe is broken and I get a 1130 errror code
![Code-1130](https://user-images.githubusercontent.com/36081959/141275377-1d79d020-4bd5-4069-b1a0-8179fc337f04.png)
We Implement the following iframe:
`<iframe src="https://scalelite-01.example.com/bigbluebutton/api/join?fullName=John+Smith&amp;meetingID=xxxx-xxxx-xxxx-xxxxxxxx&amp;password=xxxxx&amp;userdata-bbb_mirror_own_webcam=true&amp;checksum=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" allow="display-capture; geolocation; microphone *; camera *; fullscreen *;" width="100%" height="100%" style="display: block;"></iframe>`
And if I tried to share my screen, I get the 1130 error code from bigbluebutton.

**To Reproduce (optional):**
At first I checked the screensharing feature in scalelite with api-mate and it's works.

Then I include the BigBlueButton server directly info the iframe and the screensharing works.

We implement the following iframe:
`<iframe src="https://bbb33.example.com/bigbluebutton/api/join?fullName=John+Smith&amp;meetingID=xxxx-xx-xxxx-xxxxxxxx&amp;password=xxxxx&amp;userdata-bbb_mirror_own_webcam=true&amp;checksum=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" allow="display-capture; geolocation; microphone *; camera *; fullscreen *;" width="100%" height="100%" style="display: block;"></iframe>`

**Other references (optional):***

**Logs (may be required):**
no relevant logs entries found

Is there something wrong with my iframe or HTTP headers? Is this a scalelite bug or not?

**Comment by jfederico** [comment]
This issue is not relevant to Scalelite. You should open an issue on BBB itself.
