### ISSUE TITLE
Post publish script /usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb/scalelite_post_publish failed

### ISSUE THREAD

**Issue by dannyplace** [blindsidenetworks/scalelite#731]
**Describe the bug**

**To Reproduce**
Record a meeting within BBB. End record and see output with bbb-record --watch.
Error output can also be seen with: 

sudo journalctl -f -u bbb-rap-resque-worker.service

***Deployment:***
1. Deployment: docker-compose (scalelite), BBB is implemented with installer script on dedicated server.
2. Versions: 

BigBlueButton Server 2.3.15 (2482)
Scalelite 2.0 (master)

After a record has been ended, BBB should process it automatically with post_publish script.

Error:

![error_publish](https://user-images.githubusercontent.com/66772984/141866629-b49f2d31-770b-44d9-bd7f-50188893d038.png)

Manual Good:

![good](https://user-images.githubusercontent.com/66772984/141867077-b4a70fff-158f-4e61-863e-0a61d28f8594.png)

**Comment by rabser** [comment]
This is normally due to filesystem permission, if the post_publish task does not work, but run from root does it works, probably you have the wrong permissions on source files or the destination directory, or both.

**Comment by dannyplace** [comment]
Hi there,

Thank you.. Indeed it was a problem with permissions. I have set new permissions on the var/bigbluebutton folder and now everything is working fine.

**Comment by ffdixon** [comment]
Yay!

**Comment by samuelpetrosyan** [comment]
> Hi there,
> 
> Thank you.. Indeed it was a problem with permissions. I have set new permissions on the var/bigbluebutton folder and now everything is working fine.

@dannyplace please can you describe what permission should be there? Thanks in advance.

**Comment by dannyplace** [comment]
@samuelpetrosyan Hi there,

I changed the permissions on  var/bigbluebutton on every BBB Node.   

**Find userID with:**  

`id -u username`

_2000 = scalelite-spool group you created earlier by setting up the shared volume._

**Set permissions:**

`chown -R 1000:2000 var/bigbluebutton`

Although i checked my configuration and it seems that with the new version of BBB everything changed back to normal and is still working as it should be.

**Comment by mustafaaats** [comment]
Hello everyone, I have the same problem. The manual script is good working but automatic running doesn't work.

BigBlueButton version 2.4.2
Scalelite version 1.2

 My permissions 
`chown -R 997:2000 /var/bigbluebutton` 

_997 = bigbluebutton
2000 = scalelite-spool_

 and if a new record is created, it has bigbluebutton:bigbluebutton permissions.

**Comment by dannyplace** [comment]
> Hello everyone, I have the same problem. The manual script is good working but automatic running doesn't work.
> 
> BigBlueButton version 2.4.2
> Scalelite version 1.2
> 
>  My permissions 
> `chown -R 997:2000 /var/bigbluebutton` 
> 
> _997 = bigbluebutton
> 2000 = scalelite-spool_
> 
>  and if a new record is created, it has bigbluebutton:bigbluebutton permissions.
> 

Hi there, did you install BBB as root?

**Comment by dannyplace** [comment]
> > > Hello everyone, I have the same problem. The manual script is good working but automatic running doesn't work.
> > > BigBlueButton version 2.4.2
> > > Scalelite version 1.2
> > > My permissions
> > > `chown -R 997:2000 /var/bigbluebutton`
> > > _997 = bigbluebutton
> > > 2000 = scalelite-spool_
> > > and if a new record is created, it has bigbluebutton:bigbluebutton permissions.
> > 
> > Hi there, did you install BBB as root?
> 
> Yes, first switch user root after run bbb-install.sh script.

You should run bbb-install as root not switch to root after install. Also you can try to change userrights on folder to local user which you created with installation of OS.

**Comment by mustafaaats** [comment]
> > > > Hello everyone, I have the same problem. The manual script is good working but automatic running doesn't work.
> > > > BigBlueButton version 2.4.2
> > > > Scalelite version 1.2
> > > > My permissions
> > > > `chown -R 997:2000 /var/bigbluebutton`
> > > > _997 = bigbluebutton
> > > > 2000 = scalelite-spool_
> > > > and if a new record is created, it has bigbluebutton:bigbluebutton permissions.
> > > 
> > > Hi there, did you install BBB as root?
> > 
> > Yes, first switch user root after run bbb-install.sh script.
> 
> You should run bbb-install as root not switch to root after install. Also you can try to change userrights on folder to local user which you created with installation of OS.

No, you misunderstood me.  What I want to say is that I ran the bbb-install command directly with root user without sudo.  Also, I didn't quite understand what the other said.

**Comment by mustafaaats** [comment]
> Thanks @dannyplace, I've also found a solution on my side. @mustafaaats Can you show your `/usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb` script?

Thanks for reply, I was just going to write that the problem is solved right now. I upgraded BBB servers from 2.2.28 to 2.4.2 and was using old configurations. I changed

`/usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb`  `/usr/local/bigbluebutton/core/scripts/scalelite_batch_import.sh` 

now works well. Thanks again @dannyplace and @samuelpetrosyan
