### ISSUE TITLE
"Protected Recordings" cannot be disabled

### ISSUE THREAD

**Issue by mk-hs** [blindsidenetworks/scalelite#735]
I've updated to Scalelite 1.3 recently and was surprised that the option "Protected" was showing up on our recordings, even though I didn't explicitly enable this feature. 

According to [this documentation](https://github.com/blindsidenetworks/scalelite/blob/master/protectedrecordings_README.md) the protected recordings feature is enabled by default when using Scalelite 1.2 onwards. The protected_recordings_enabled flag only dictates whether the recordings should have the protected status upon import, so the flag's name is a bit misleading.

[Greenlight 2.10.0](https://github.com/bigbluebutton/greenlight/releases/tag/release-2.10.0) mentions that the protected recordings feature will only show up when it's enabled in Scalelite, but it seems that there's no proper way to disable it.

Is staying on Scalelite 1.1 the only viable way to disable protected recordings?

**Comment by jfederico** [comment]
Yeah, I think the wording in the description is misleading.
```
PROTECTED_RECORDINGS_ENABLED: Applies to the recording import process. If set to "true", then newly imported recordings will have protected links enabled. Default is "false".
```

The implementation however seems to be working as expected. The intention is that, when `PROTECTED_RECORDINGS_ENABLED=true`, the feature is enabled (would it be more clear if we say `PROTECTED_RECORDINGS_FEATURE_ENABLED`?)

When enabled, the recordings can be (or not) protected. But also when enabled, all the newly imported recordings are set as protected. The existent ones should have to be enabled manually.

So, for disabling the feature you should only need either to remove the variable, or to set it to false. Does any of those options works for you?

**Comment by jfederico** [comment]
Never mind, it is a bug. Either there is a regression or the feature was never implemented correctly

**Comment by mk-hs** [comment]
Thanks a lot!
