### ISSUE TITLE
servers:sync task wants explicit mode argument

### ISSUE THREAD

**Issue by crosscodr** [blindsidenetworks/scalelite#738]
**Describe the bug**
The rake task servers:sync (@defnull great feature by the way!) does not work without specifying a mode of synchronization (second parameter). 

**To Reproduce**
`docker exec -it scalelite-api bin/rake servers:sync[<valid-path>]`

***Deployment:***
1. Deployment: docker-compose
2. Versions: 1.3
3. Tools used for reproducing the issue: bash, docker, rake

***Steps to reproduce the behavior:***
1. `docker exec -it scalelite-api bin/rake servers:sync[<valid-path>]`
4. See error: "ERROR: Unknown sync mode '' (choose: keep cordon force)"

**Expected behavior**
I would expect `docker exec -it scalelite-api bin/rake servers:sync[<valid-path>]` to work with the default mode ('cordon'), as described in README.md.

**Comment by defnull** [comment]
Missing `args.with_defaults` in `severs.rake`? I guess I misinterpreted how ruby/rake handles default parameters.
