### ISSUE TITLE
scalelite-nginx 404 error

### ISSUE THREAD

**Issue by jgribonvald** [blindsidenetworks/scalelite#745]
**Deployment (required):**
With docker systemd on a local server.

**Describe the problem (required):**
When installing `bbb-playback-notes bbb-playback-podcast bbb-playback-screenshare` package on BBB, greenlight detect it and provide link to get them, but scalelite-nginx doesn't deploy required conf for access from these modules.

If we watch on https://github.com/blindsidenetworks/scalelite/blob/master/dockerfiles/v1/xenial220-alpine#L16 these modules are existing but anymore on https://github.com/blindsidenetworks/scalelite/blob/master/dockerfiles/v1/bionic230-alpine#L20. Is there any reason ? and could we add again these module to provide nginx conf ?

**Other references (optional):***

**Logs (may be required):**

*NOTE: Request that do not provide the minimal information required won't be taken in consideration and will be immediately closed.*

**Comment by jgribonvald** [comment]
To apply again such nginx conf the change to apply can be found here: https://github.com/GIP-RECIA/scalelite/commit/16f9ad409965edc4b0e91aa6e28c12250d3e1436 let me know if you are interested

**Comment by jfederico** [comment]
Thanks @jgribonvald I think the actual solution is to build the image out of 2.4. That would result in a bionic240 instead.
