### ISSUE TITLE
nginx starting problem

### ISSUE THREAD

**Issue by samuelpetrosyan** [blindsidenetworks/scalelite#746]
**Deployment (required):**
1. Deployment: docker-compose
2. Versions: v1
3. Tools used for reproducing the issue: docker images, such as **blindsidenetworks/scalelite**, **jfederico/scalelite-run**

**Describe the problem (required):**
When I start docker images scalelite-nginx does not starting correctly, as it says:
```
scalelite-nginx                 | nginx: [emerg] cannot load certificate "/etc/nginx/ssl/live/ncs2.asnet.am/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/live/ncs2.asnet.am/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
Please help me to cope!!
Thanks in advance.

**Comment by jfederico** [comment]
Those scripts have not been reviewed in a while, but did you run the steps in this document? https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6
