### ISSUE TITLE
Recording in Moolde

### ISSUE THREAD

**Issue by bbbmm** [blindsidenetworks/scalelite#76]
Hello,

First of all, thank you so much for this great solution specially with the current situation as it is so much in needs.

We have implemented the solution just today and everything worked perfectly and the high load is getting distributed.

One small issue we are facing, as we are using BBB with Moodle, we are not able to find the recording links once it process and published in Moodle, however we can see them on the server.

Could you please help us on this.

Many thanks again.

Best wishes,

**Comment by farhatahmad** [comment]
Hi @bbbmm,

Can you try doing a getRecordings call using [API Mate](https://mconf.github.io/api-mate/)?

Fill in your Scalelite server url and secret, and then click "getRecordings" on the right hand side. 

Do you see the recordings you generated?

**Comment by bbbmm** [comment]
Hi,

No, I am getting “SUCCESS noRecordings There are not recordings for the meetings”

**Comment by bbbmm** [comment]
Below is the details of what was done:

1. EFS created and successfully mounted on bbb servers and scalelite host server under /mnt
2.	Directory structure and permissions has been setup as mentioned on the documentation for bbb servers and scalelite server
uid=998(bigbluebutton) gid=998(bigbluebutton) groups=998(bigbluebutton),2000(scalelite-spool)
3.	Recording transfer scripts, https://github.com/blindsidenetworks/scalelite/tree/master/bigbluebutton, placed on the bbb servers as following

/usr/local/bigbluebutton/core/scripts/scalelite_batch_import.sh
/usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb
/usr/local/bigbluebutton/core/scripts/scalelite.yml 
(Configuration Modified)
        work_dir: /var/bigbluebutton/recording/scalelite
spool_dir: /mnt/scalelite-recordings/var/bigbluebutton/spool
                
Above three scripts permission changed to make executable.

4.	After that we run the scalelite_batch_import.sh, below is sample output

 
![1](https://user-images.githubusercontent.com/62310003/76999152-42b61a80-6967-11ea-9f2b-19506519df27.png)


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 
![2](https://user-images.githubusercontent.com/62310003/76999171-477ace80-6967-11ea-9350-fcf0aeab3f32.jpg)


•	What is the main purpose of moving the recording to shared volume? Is it only to archive published recording and free up space from the bbb node servers?
•	Do we run the scalelite_batch_import.sh manually or using cron and what is the recommended running interval? Can we set it up to run every 1-hour?

•	How to view the recorded meetings from Moodle.. We tested and no recording are shown? Any additional setup or configuration required?

![3](https://user-images.githubusercontent.com/62310003/76999182-4b0e5580-6967-11ea-8d30-87b101332bf0.jpg)

**Comment by farhatahmad** [comment]
One more step I forgot to include.

When you add the server url and secret, click the clear inputs button at the top first, then click the getRecordings link. Does it return the same response?

**Comment by bbbmm** [comment]
> One more step I forgot to include.
> 
> When you add the server url and secret, click the clear inputs button at the top first, then click the getRecordings link. Does it return the same response?
> 
>
Yes, i already did that

**Comment by bbbmm** [comment]
one more thing, When we run bbb-record --watch on the bbb server we do see it as published "presentation"

**Comment by bbbmm** [comment]
We successfully managed to make it work.

The issue was with the database permission.
few ips had to be added in the pg_hba.conf file

Thank you so much for this project.
Once again we are so happy and exited in implementing it! hopefully we will not face BBB heavy load disconnections issues anymore.

Best Wishes
