### ISSUE TITLE
letsencrypte update

### ISSUE THREAD

**Issue by kueppersf** [blindsidenetworks/scalelite#767]
Hello!

I installed Scalelite with docker compose and now I have problems updating the Letsencrypt certificate.

I would be very grateful for a tip.

Many greetings
Friedhelm

**Comment by JeanPluzo** [comment]
Hi,
it would be much easier for the community to know exactly what/which errors you have.
Have you looked at the logs?
Can you describe the error in more detail?

Regards,
J.

**Comment by kueppersf** [comment]
Hi,
thanks for the feedback! I was able to solve the problem by stopping docker-compose. Then Letsencrypt could be updated. Then I just had to start docker-compose again. 

Regards
Friedhelm
