### ISSUE TITLE
Add support for dial-in numbers

### ISSUE THREAD

**Issue by jfederico** [blindsidenetworks/scalelite#769]
**Problem to solve:**
If for any reason the voice bridge fails in BBB, users can fall-back to Dial In phone number. This requires the use of a FreeSwitch server to handle the calls and a bridge between those calls and BBB.

The issue raises when clustering BBB servers behind SL. The conference numbers though need to be stored somehow in SL and linked to the `BBB Server / Meeting`

**Purposed solution:**
Extend SL to support static conference number and assign them to meetings.

**Considered alternatives:**

**Additional context:**

**Comment by kepstin** [comment]
Things needed in scalelite:

* Design and implement allocation & storage of conference numbers in scalelite in redis
* Implement freeswitch dialplan (fsapi) endpoint which prompt for pin and redirect to meeting.

**Comment by relecand** [comment]
See:

- https://github.com/MBcom/bbb-clustersip
- https://github.com/bigbluebutton/greenlight/issues/1645#issuecomment-632013396
