### ISSUE TITLE
scalelite deployment

### ISSUE THREAD

**Issue by mhdcshel** [blindsidenetworks/scalelite#775]
**Deployment (required):**
1. Deployment: 
2. Versions: 
3. Tools used for reproducing the issue: 

**Describe the problem (required):**

We used the steps on this link: https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md#web-frontend-scalelite-api-and-scalelite-nginx
But when we try to execute the following command: systemctl status scalelite-api.service scalelite-nginx.service
We are getting this errors:

    ● scalelite-api.service - Scalelite Nginx
       Loaded: loaded (/etc/systemd/system/scalelite-api.service; enabled; vendor preset: enabled)
       Active: failed (Result: exit-code) since Mon 2022-04-18 15:00:54 UTC; 10s ago
      Process: 2477 ExecStartPost=/usr/bin/docker image prune -f (code=exited, status=0/SUCCESS)
      Process: 2476 ExecStart=/usr/bin/docker run --log-opt max-size=10m --log-opt max-file=5 --name scalelite-nginx --env-fi
      Process: 2459 ExecStartPre=/usr/bin/docker pull blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx (code=exited, status=0
      Process: 2450 ExecStartPre=/usr/bin/docker rm scalelite-nginx (code=exited, status=1/FAILURE)
      Process: 2423 ExecStartPre=/usr/bin/docker kill scalelite-nginx (code=exited, status=1/FAILURE)
     Main PID: 2476 (code=exited, status=125)
    
    Apr 18 15:00:54 scaletloadbalancer docker[2459]: v1.1-nginx: Pulling from blindsidenetwks/scalelite
    Apr 18 15:00:54 scaletloadbalancer docker[2459]: Digest: sha256:5e7671dd08e9ce58e5087eaba1001804066fa58de78314b3751fd5884
    Apr 18 15:00:54 scaletloadbalancer docker[2459]: Status: Image is up to date for blindsidenetwks/scalelite:v1.1-nginx
    Apr 18 15:00:54 scaletloadbalancer docker[2459]: docker.io/blindsidenetwks/scalelite:v1.1-nginx
    Apr 18 15:00:54 scaletloadbalancer docker[2476]: docker: Error response from daemon: invalid mount config for type "bind"
    Apr 18 15:00:54 scaletloadbalancer docker[2476]: See 'docker run --help'.
    Apr 18 15:00:54 scaletloadbalancer systemd[1]: scalelite-api.service: Main process exited, code=exited, status=125/n/a
    Apr 18 15:00:54 scaletloadbalancer docker[2477]: Total reclaimed space: 0B
    Apr 18 15:00:54 scaletloadbalancer systemd[1]: scalelite-api.service: Failed with result 'exit-code'.
    Apr 18 15:00:54 scaletloadbalancer systemd[1]: Failed to start Scalelite Nginx.

Do we have to follow this same steps, and if the ssl is requiered?
I noticed also that this step also is required to load the db schema in the Postgresql server : docker exec -it scalelite-api bin/rake db:setup
However it was not mentioned that we need to pull any containers so do we need to pull  scalelite-api container from docek hub before running this command?

**To Reproduce (optional):**

**Other references (optional):***

**Logs (may be required):**

*NOTE: Request that do not provide the minimal information required won't be taken in consideration and will be immediately closed.*

**Comment by JeanPluzo** [comment]
Hi,
it seems that you have a setup problem. The issues around here have to do with bugs or requests. I suggest you ask for help in the google groups. 
Regards,
J.
