### ISSUE TITLE
Migrate Scalelite

### ISSUE THREAD

**Issue by nidhin215** [blindsidenetworks/scalelite#778]
We are running the Scalelite setup on Ubuntu 16 and needs to migrate to Ubuntu 18. Can we do a direct upgrade or should we setup a new server and migrate.

Can you please provide us any documentation?

**Comment by JeanPluzo** [comment]
Hi,

you're not really specifying what exactly you need to upgrade (Ubuntu 16 to 18? Direct upgrade of what, ubuntu or SL? New server and migrate what, ubuntu or SL?)
Besides, I would advice you to ask this question in the google groups (bigbluebutton-dev, bigbluebutton-setup).

Regards,

J.

**Comment by jfederico** [comment]
Thanks @JeanPluzo that is correct. The issues open here should be development related. We normally don't provide support on deployments of any kind, unless it is specifically related to a potential bug, feature request or improvement.

@nidhin215 if you are talking about the box where Scalelite lives, it also depends of what procedure you followed to deploy it.

The systemd deployment can be applied on 16.04, 18.04, 20.04 and so on. The hassle is that you need to do all manually. If I were you I would use something simpler such as a docker-compose deployment
