### ISSUE TITLE
Scalelite server is loosing it connection with BBB servers

### ISSUE THREAD

**Issue by bbbmm** [blindsidenetworks/scalelite#78]
Hello,

One more issue we are facing is, the scalelite server is loosing it connection with BBB servers between time to time

![4](https://user-images.githubusercontent.com/62310003/77000700-d983d680-6969-11ea-9a0c-d8724c6f8f08.jpg)

and then we go back and add them all manually.

Could you please help us on why this is happening and what do we need to check and change?

Thank you so much, it is much appreciated!

Best Wishes,

**Comment by slacker82** [comment]
Hello,

I have same issue.

Regards,

**Comment by bbbmm** [comment]
Four hours ago we did changes and we still did not face any disconnections.
We are hoping we did fixed it.

The change was increased the number of MaximumClient in redies.conf file and try to tune redies. As well checking your redies logs will be a good place to start from.

Hope it help!!

Best wishes,

**Comment by farhatahmad** [comment]
You'll also want to enable persistence on your Redis Instance to prevent this problem from happening

**Comment by bbbmm** [comment]
We did that as well :)

Let me tell you, today we went live with our installation and it did worked perfectly. No lost at all.

Thank you so much for this.
Much valued.

Best wishes,
