### ISSUE TITLE
v1.3.4-beta.1.1 Can not give OVERRIDE_CREATE_PARAMS  parameter value with "=" sign in it

### ISSUE THREAD

**Issue by pielonet** [blindsidenetworks/scalelite#788]
**Describe the bug**
The new configuration parameter OVERRIDE_CREATE_PARAMS expects a value in the form "param1=value1,param2=value2..."

The problem is it does not accept a value containing the "=" sign like for example :

`OVERRIDE_CREATE_PARAMS=meta_analytics-callback-url=https://domain.com/bbb-analytics/api/v1/post_events?tag=mytag`

It produces the following error in the logs : 
```
[9] ! Unable to load application: ArgumentError: wrong array length at 0 (expected 2, was 3)
```
Please provide a way to enter value with ANY sign in it !

A possible solution would be to await parameter values to be url-encoded.

Kind regards,
Thierry

**Comment by farhatahmad** [comment]
Does encoding your URL not work?

**Comment by pielonet** [comment]
No, because it gets re-encoded one more time by the script.
The solution would be that the script expects encoded urls and does not re-encode them.

**Comment by pielonet** [comment]
Hi @farhatahmad ,

I can't start Scalelite with this beta release : here is what docker-compose complains of :
```
Jun 10 15:00:07 arawa-test-bbb-scalelite systemd[1]: Starting Scalelite...
Jun 10 15:00:09 arawa-test-bbb-scalelite docker-compose[2386]: Pulling scalelite-api (blindsidenetwks/scalelite:v1.3.4-beta.1.2)...
Jun 10 15:00:15 arawa-test-bbb-scalelite docker-compose[2386]: manifest for blindsidenetwks/scalelite:v1.3.4-beta.1.2 not found: manifest unknown: manifest unknown
Jun 10 15:00:15 arawa-test-bbb-scalelite systemd[1]: scalelite.service: Main process exited, code=exited, status=1/FAILURE
Jun 10 15:00:15 arawa-test-bbb-scalelite systemd[1]: scalelite.service: Failed with result 'exit-code'.
Jun 10 15:00:15 arawa-test-bbb-scalelite systemd[1]: Failed to start Scalelite.
```

**Comment by pielonet** [comment]
Hi,
setting parameter `defaultKeepEvents` to `true` in `/etc/bigbluebutton/bbb-web.properties` fixed it (see https://github.com/bigbluebutton/bigbluebutton/issues/15224#issuecomment-1163351552)
@farhatahmad you can release this new version of Scalelite. Please do it ASAP !
Kind regards,
Thierry

**Comment by farhatahmad** [comment]
Thanks for you help on this Thierry. https://github.com/blindsidenetworks/scalelite/releases/tag/v1.3.4 has been released (images are in the process of building). Should be ready for use in the next 20 mins or so
