### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by alfredonodo** [blindsidenetworks/scalelite#794]
Hi,
since BBB 2.5 uses mediasoup. What is the current maximum number of users per room? Is the limit still [150](https://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support)? Moreover, the link on README of scalelite refers to version 2.2.
Thank you

**Comment by ffdixon** [comment]
> What is the current maximum number of users per room? Is the limit still 150?

It's not a hard-coded limit; rather, more of guidelines.  We know users have put more than 150 users in a single room, but we are conservative and want to ensure you have a good experience.
