### ISSUE TITLE
Failed to get server id

### ISSUE THREAD

**Issue by freehussain** [blindsidenetworks/scalelite#81]
hello,

i have an issue with scalelite, all steps done successfully but at the end an error comes

~ $ ./bin/rake poll:all
D, [2020-03-20T01:26:02.453208 #30] DEBUG -- : Polling meetings
D, [2020-03-20T01:26:02.453323 #30] DEBUG -- : Polling servers
D, [2020-03-20T01:26:02.461178 #30] DEBUG -- : Polling Server id=120c3947-bc1d-4bfa-9371-adad60bd1793
W, [2020-03-20T01:26:02.482622 #30]  WARN -- : Failed to get server id=120c3947-bc1d-4bfa-9371-adad60bd1793 status: internalError: Response did not include returncode
I, [2020-03-20T01:26:02.482770 #30]  INFO -- : Server id=120c3947-bc1d-4bfa-9371-adad60bd1793 offline load: unavailable
D, [2020-03-20T01:26:02.482805 #30] DEBUG -- : Polling Server id=cfa158e1-3b15-4abe-ab1d-cbc2cc1c5fda
W, [2020-03-20T01:26:02.522022 #30]  WARN -- : Failed to get server id=cfa158e1-3b15-4abe-ab1d-cbc2cc1c5fda status: internalError: Response did not include returncode
I, [2020-03-20T01:26:02.522187 #30]  INFO -- : Server id=cfa158e1-3b15-4abe-ab1d-cbc2cc1c5fda offline load: unavailable

any help with this?

**Comment by farhatahmad** [comment]
Hi @freehussain,

Your BigBlueButton server is not responding. Can you check to see what the issue with it is?

**Comment by freehussain** [comment]
hello,

sorry my mistake, i didn;t include 'api' at the end

thank you for help @farhatahmad
