### ISSUE TITLE
Add support for SHA512

### ISSUE THREAD

**Issue by jfederico** [blindsidenetworks/scalelite#811]
**Problem to solve:**
Since [v1.3.1](https://github.com/blindsidenetworks/scalelite/releases/tag/v1.3.1), SL supports SHA256. The issue is that the implementation #697 allows the use of SHA1 and SHA256 together.

But there are cases where the organization requires the strict use of only SHA384+. 

This issue is linked to #810 but blocked until it is implemented by BBB (perhaps 2.6)

**Purposed solution:**
Implement support for SHA512

**Comment by defnull** [comment]
I'd like to see the reasoning behind this. I do not know of any government body or certification that discourages the use of SHA256 for this use-case. If a security adviser would complain about using SHA256 here, and not mention the other way more severe issues with this API security model, I'd go look for a different advisor.
