### ISSUE TITLE
Set server as hot spare.

### ISSUE THREAD

**Issue by Commifreak** [blindsidenetworks/scalelite#816]
**Problem to solve:**
I dont remember if I already asked that - Id like to see a feature, to tell scaleLite to add a hotspare server which is only used, if the primary server is not ready at all. If its ready, the hotspare never gets used.

**Purposed solution:**
declare server x as hotspare, scalelite only uses it, if the main server(s) are not able to handle the conference (or smth like that)

**Considered alternatives:**
-

**Additional context:**
Our setup contains two servers: one physical one which handles all load (not as big to need two) and one VM which acts as a spare, if wee maintenance the first one. An automated switch to the VM in case the first is being maintenanced would be nice.

**Comment by farhatahmad** [comment]
This is something you can achieve pretty easily with a simple script. Scalelite already makes this possible through the `enabled` flag. You could also try something clever with the loadMultiplier values instead
