### ISSUE TITLE
Postgres-DB not initialized automatically!?

### ISSUE THREAD

**Issue by einhirn** [blindsidenetworks/scalelite#82]
Hi, for some reason the "scalelight-api"-Container didn't automatically check whether the DB was available and primed - at least in my case.
I needed to do a
`./bin/rake db:reset`
to create it  - that wasn't in the documentation...

I shared the PostgreSQL-Server with greenlight - it uses docker-compose to automatically pull a postgres v9.5 container. So my DATABASE_URL is:

DATABASE_URL=postgresql://postgres:<here_goes_my_password>@db:5432

and "db" is the Service name in a Docker-Compose.yml file for Scalelite and greenlight on one host...

**Comment by farhatahmad** [comment]
Did you miss this step in the docs?

https://github.com/blindsidenetworks/scalelite/blob/master/docker-README.md#initialize-the-scalelite-api-database

**Comment by einhirn** [comment]
Obviously. Sorry, my bad. I seem to have assumed that it would work automagically like with greenlight.

**Comment by einhirn** [comment]
... but an example for the DATABASE-URL would still be nice in the docs...

**Comment by farhatahmad** [comment]
Agreed. I'll see if I can put something in later today
