### ISSUE TITLE
Question about infraestructure

### ISSUE THREAD

**Issue by villalvilla** [blindsidenetworks/scalelite#84]
Good morning.

Sorry to write here, but I don't have very clear where to post doubts. 
What I wanted to know is: Is it possible to have the scalalite server connected to a farm of servers with a VPN, and that the only server with a public IP and Public access could be the scalalite server? Or on the contrary, Scalalite server redirects BBB api clients to the available server and all the BBB servers in the farm need to have public access?

Sorry for the silly question, but it is very important for us to know this aspect. Thank you very much and this project is really awesome!!

**Comment by farhatahmad** [comment]
Hi @villalvilla,

The BigBlueButton servers need to be publicly accessible. Scalelite only does the job of deciding which server to redirect the user too. If the server is not publicly accessible then the user will not be  able to access any BigBlueButton feature

No worries, all questions are welcome :)
