### ISSUE TITLE
NGINX_SSL=true doesn't redirect http sessions to https.

### ISSUE THREAD

**Issue by einhirn** [blindsidenetworks/scalelite#87]
I'd expect http sessions redirected to https on an SSL-enabled web server. 

My suggestion is to just change the HTTP server block in `/etc/nginx/conf.d/scalelite-ssl.template` to redirect clients to the SSL server...

If you think the server should also be available on HTTP, please at least make it configurable for those of us that think otherwise.

**Comment by farhatahmad** [comment]
Hi @einhirn,

Sorry for the late response. Yes, you're correct. Scalelite should be able to be configured for both HTTP and HTTPS.

HTTP for when multiple instances of Scalelite are deployed in a high-availability deployment and HTTPS when only a single Scalelite is deployed
