### ISSUE TITLE
remove server before panic

### ISSUE THREAD

**Issue by mahdidev70** [blindsidenetworks/scalelite#887]
I had a BBB server that hosts 4 meetings but because of hard crashes, it goes offline.  
unfortunately, I disable and remove it without panic. 
now those 4 classes not working. maybe because scalelite considers it as a running meeting on the removed server.
what should I do to end those meetings?

**Comment by JeanPluzo** [comment]
Hi,
have you tried to remove that server completely from SL and add it again as brand new?
Also, restart that BBB Server. All running meetings will be ended
Regards,
J.

**Comment by mahdidev70** [comment]
@JeanPluzo 

hi
I can't restart the BBB server because the hardware is damaged!
I don't have any access to the server.

how can I add the BBB server that is not online?
even if it is possible I guess the server will get a new id and SL recognize it as a different server. so it's not an effective option.

**Comment by JeanPluzo** [comment]
Hi,
if you want to add a Server that is not online to SL, you have to user the `...rake servers:add[URL,bbb_secret]` command.
This will add the Server to SL but not enable it.
I really don't understand what you're trying to accomplish. Re-add the crashed server? Restore the classes/courses in moodle (I assume it's moodle)?
Regards,
J.

**Comment by mahdidev70** [comment]
@JeanPluzo 
I did what you said but doesn't solve the problem.
I try to re-add the BBB server with the same URL. but I don't remember the secret, so I use the fake secret.
BBB server was added but the problem doesn't solve.

this is normal [**class URL** ](https://croom.ir/b/mah-k6w-2q9)

this is a class that was online on the crashed server and now not working
[**class link**](https://croom.ir/b/yfe-h6v-24o-9r8)

as you see SL considers it as running but has no access to the server!

**Comment by JeanPluzo** [comment]
Hi,
- what frontend are you using (Greenlight, something else)?
- is your class/course in moodle?
- BBB version
- SL version
If you added a BBB server to SL with a "fake" secret... well that server won't be recognized by SL.
I still don't understand what you're trying to achieve. 
Regards,
J.

**Comment by mahdidev70** [comment]
@JeanPluzo 
your solution was not useful.
just do these steps to reproduce:
Must have BBB server, Scalelite and greenlight
start a session on bigbluebutton
turn off the BBB server
try to end the session that was running on the offline BBB server

**Comment by JeanPluzo** [comment]
Hi,
if you "end the session that was running on the offline BBB server"... well, I don't see how that would be possible.
When you turn off a BBB server the meeting ends, immediately. You can't "end again" a session that was ended by shutting down a BBB server.
Sorry, can't help you any further. I just don't understand what you're trying to do. 
Good luck by finding a solution, and if you do, please post it here.
Regards,
J.

**Comment by farhatahmad** [comment]
You can run the meetings:list rake task to get a list of meetings that are still running and then use the meetings:end rake task to remove the problematic meetings from Scalelite's db

**Comment by mahdidev70** [comment]
thank you @farhatahmad 
I didn't find meetings:list command. but i was trying poll:meetings and the result was like this:
`D, [2023-06-13T22:53:13.304605 #11129] DEBUG -- : Polling meetings
W, [2023-06-13T22:53:13.361793 #11129]  WARN -- : Failed to check meeting id=uqgiaynbecnmqwpivwhi7r1ifcp3ebq3ptnfzgpm status: Couldn't find Server with id=9e570eb9-9b01-40cb-a6fe-3aaf51aee816
W, [2023-06-13T22:53:13.370944 #11129]  WARN -- : Failed to check meeting id=3pqh7sj70czbpfu7mvxgaazb55oavoirmukx80pd status: Couldn't find Server with id=9bfe1650-4198-49a1-9d87-75c73ba5d351
W, [2023-06-13T22:53:13.373200 #11129]  WARN -- : Failed to check meeting id=otwk25q8dvhfywiytt0b4jdnjo1fgr65uoqxx5kj status: Couldn't find Server with id=9bfe1650-4198-49a1-9d87-75c73ba5d351
D, [2023-06-13T22:53:13.366856 #11129] DEBUG -- : Polling Meeting id=4537b02df1fb3e1600f282aa25f486ebdf71f8d8 on Server id=1f5a6c17-0831-42ac-8cd0-6889d5461b18
D, [2023-06-13T22:53:13.364736 #11129] DEBUG -- : Polling Meeting id=6MPxsvbOOI8VlwsKx0YzHtha4iU2NPYY4meKAsjB on Server id=1f5a6c17-0831-42ac-8cd0-6889d5461b18
D, [2023-06-13T22:53:13.369193 #11129] DEBUG -- : Polling Meeting id=DxYzgmvMZDyQZWTU7Ie6ozngCB4Y8Z3oUb8ivsRK on Server id=1f5a6c17-0831-42ac-8cd0-6889d5461b18
D, [2023-06-13T22:53:13.376113 #11129] DEBUG -- : Polling Meeting id=VlnKkS6IswCHDxhnIavjFCSOm9gDkdGSqzsb9uBe on Server id=1f5a6c17-0831-42ac-8cd0-6889d5461b18
W, [2023-06-13T22:53:18.378737 #11129]  WARN -- : Failed to check meeting id=4537b02df1fb3e1600f282aa25f486ebdf71f8d8 status: execution expired
W, [2023-06-13T22:53:18.380170 #11129]  WARN -- : Failed to check meeting id=lnyrkho53enu66igtijprti3vhbhqgcr9kypy429 status: Couldn't find Server with id=9bfe1650-4198-49a1-9d87-75c73ba5d351
W, [2023-06-13T22:53:18.381074 #11129]  WARN -- : Failed to check meeting id=wnviwizkby6lqu5dtiaq2omyqoymme57706shq4h status: Couldn't find Server with id=77b2e7ce-7ae9-4e28-a05e-d206bc8dddfd
W, [2023-06-13T22:53:18.382155 #11129]  WARN -- : Failed to check meeting id=6MPxsvbOOI8VlwsKx0YzHtha4iU2NPYY4meKAsjB status: execution expired
D, [2023-06-13T22:53:18.382881 #11129] DEBUG -- : Polling Meeting id=WJHOhiGAVCIy0TByhL5pBZlqCfKI71X9KzJ5Ii4c on Server id=1f5a6c17-0831-42ac-8cd0-6889d5461b18
W, [2023-06-13T22:53:18.383894 #11129]  WARN -- : Failed to check meeting id=rvqspgahvxu1l3gwzhsgoefpkvcy5cvz3bqkp8hu status: Couldn't find Server with id=9bfe1650-4198-49a1-9d87-75c73ba5d351
W, [2023-06-13T22:53:18.404134 #11129]  WARN -- : Failed to check meeting id=VlnKkS6IswCHDxhnIavjFCSOm9gDkdGSqzsb9uBe status: execution expired
W, [2023-06-13T22:53:18.403516 #11129]  WARN -- : Failed to check meeting id=DxYzgmvMZDyQZWTU7Ie6ozngCB4Y8Z3oUb8ivsRK status: execution expired
W, [2023-06-13T22:53:23.405226 #11129]  WARN -- : Failed to check meeting id=WJHOhiGAVCIy0TByhL5pBZlqCfKI71X9KzJ5Ii4c status: execution expired
`

**Comment by JeanPluzo** [comment]
That's where you should have started.
`meetings:list` will most likely not be in SL 1.2
Update to the latest (1.5.1) to get all available rake commands.

Regards,
J.
