### ISSUE TITLE
Annotations on the presentation/whiteboard are not included in recordings.

### ISSUE THREAD

**Issue by dirk-hl** [blindsidenetworks/scalelite#895]
**Describe the bug**

Added annotations on the presentation/whiteboard are not included in recordings with Bigbluebutton 2.6.0-RC.8

**To Reproduce**

1. Start a recording with Bigbluebutton 2.6.0 RC.8. 
2. Add annotations to the presentation/whiteboard.
3. Play this recording, then the annotations are missing.

***Deployment:***

1. Deployment:  default systemd deployment
2. Versions: Scalelite 1.4, Bigbluebutton 2.6.0-RC8, Greenlight 2.14.6 or 3.0.1

**Expected behavior**

Annotations display fine in recordings, like connecting Greenlight directly to Bigbluebotton without Scalelight loadbalancer.

**Screenshots**

With Scalelight, annotations are missing
![Screenshot with Scalelight](https://user-images.githubusercontent.com/64575524/225835977-b506ea8b-0f7f-473f-8b08-dd2abd7e10e3.png)

Without Scalelight, with annotations
![Screenshot without Scalelight](https://user-images.githubusercontent.com/64575524/225836073-a57d22eb-d5eb-4b3c-907e-b67b8c7f5adb.png)

**Additional context**

First discussions about the bug at [Bigbluebutton](https://github.com/bigbluebutton/bigbluebutton/issues/17013)

**Comment by schorschroch** [comment]
Scalelite V1.4 still uses BBB V2.4 ("https://ubuntu.bigbluebutton.org/bionic-240 bigbluebutton-bionic main") for the presentation player (see File Dockerfile Line 15/16).

This might be the reason, why the new whiteboard (tldraw) recording from BBB V2.6 isn't replayed correctly.

Let's hope that the dev team will adjust Scalelite to the new main BBB Version 2.6.

Best,
Bernhard

**Comment by ffdixon** [comment]
Thanks for reporting this issue -- there's been a big focus to get BigBlueButton 2.6 released (which we did) and GreenLight 3.0 (which we did as well).  

The theory about the recording format is out-of-date is likely the cause.  We're turning our attention to ScaleLite and will be taking a closer look at this issue.

**Comment by jfederico** [comment]
@dirk-hl et all, we just put out a new beta release. The issue should be gone with these changes. Can you please double check.
tag is [v1.4.1-beta.1](https://github.com/blindsidenetworks/scalelite/releases/tag/v1.4.1-beta.1)

Can you please validate the new image? And please report what deployment you have (systemd, docker-compose, k8s, custom)

**Comment by dirk-hl** [comment]
I was unfortunately offline for a few days and could not test sooner. With Scalelite 1.4.1 the annotations are now available in the recordings. Thanks for the great job.
