### ISSUE TITLE
scalelite-recording-importer not working

### ISSUE THREAD

**Issue by cod3r0k** [blindsidenetworks/scalelite#899]
**Describe the bug**
`scalelite-recording-importer` is not working. Every media was transferred from BBB to `nfs` but they are stay in `spool` directory

 `docker ps`  also don't have any logs about the incoming requests. (https://img.onl/LywpJw)

**Comment by cod3r0k** [comment]
It was resolved when I change the owner and mod of each dir to `nobody:nogroup` and `777`.  Is it OK or it is not secure or ... ?

**Comment by dirk-hl** [comment]
You should set the permissions as described in the instructions: https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md

**Comment by cod3r0k** [comment]
> You should set the permissions as described in the instructions: https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md

Thank you @dirk-hl . I have a different version of BBB (some of them was installed last year) and their bigbluebutton userid in each bigbluebutton is different (e.g. 995, 996,998, 1001 or etc.). Therefore the guideline which noted at that link which adds `usermod -a -G scalelite-spool bigbluebutton` to scalelite-spool and `chown 1000:2000 ` is not valid for them.

Do you have any option?  ( As I said, I set  `nobody:nogroup` and `777` to deal with this issue)
