### ISSUE TITLE
New BBB 2.6 "video" format playback in Scalelite fails with 404 error

### ISSUE THREAD

**Issue by pielonet** [blindsidenetworks/scalelite#901]
**Describe the bug**
Hi,

When trying to play the new "video" format introduced in BBB 2.6, Scalelite fails to read the file with a 404 error.

**To Reproduce**
- With API-mate connect to Scalelite and create a room with "record" enabled
- Connect to the room as moderator
- Record the session for a few seconds
- Close the session
- After a while, choose "getRecordings" in api-mate
- Api-mate shows xml containing two formats : video and presentation
- Presentation url in the form "/playback/presentation/2.3/[recording-id]" plays well
- Video url in the form "/playback/video/[recording-id]" fails with 404

**Additional context**
`error.log` logs for docker container "scalelite-recordings" based on Docker image "bigbluebutton/bbb-playback-proxy:bionic-240-alpine" (deployment of Scalelite based on jfederico/sclalelite-run)
```
2023/04/06 17:07:49 [error] 12#12: *129 "/var/lib/nginx/html/playback/video/xxxxxxxxxxxxxxxxxxxxxx/index.html" is not found (2: No such file or directory), client: 172.20.0.9, server: , request: "GET /playback/video/xxxxxxxxxxxxxxxxxxxxx/ HTTP/1.1", host: "xxxxxxxxxxxxxxxxxxxx"

**Comment by ffdixon** [comment]
Thanks for reporting this -- we're looking into the issues with playback of 2.6 recordings in ScaleLite.

**Comment by jfederico** [comment]
@pielonet we just put out a new beta release. The issue should be gone with these changes. Can you please double check.
tag is `v1.4.1-beta.1`
