### ISSUE TITLE
Could not find any available servers.

### ISSUE THREAD

**Issue by JGallot** [blindsidenetworks/scalelite#92]
hello,

When i try to create a metting on my scalelie, i've got this message :
Could not find any available servers.
This is returned by the API.

When i look my servers, all is allright, the command **bin/rake status** returns :
Running via Spring preloader in process 8561
        HOSTNAME         STATE   STATUS  MEETINGS  USERS  LARGEST MEETING  VIDEOS 
 server1   enabled  online         0      0                0       0 
 server2  enabled  online         0      0                0       0 

What can i can check ?

**Comment by JGallot** [comment]
Some more information :
Redis server seems to be empty :
**KEYS *** returns _(empty list or set)_
Client dockers can connect redis.
No password error is found in logs

**Comment by farhatahmad** [comment]
Whats the no password error that you found in the logs? Can you send a snippet of it?

**Comment by ngthienlinh** [comment]
I think we have common problem. In the document: "The Docker image defaults to production. Rails defaults to development" => this lead to incompatible redis namespace.
The solution is to set RAIL_ENV variable in /etc/default/scalelite.

**Comment by JGallot** [comment]
hello, i'Ve made some cheks and reinstallations.

redis is now "populated".

RAIL_ENV=production is now in the file /etc/default/scalelite
restart have be done

But the problem is always here , very strange.
No message in logs (no errors nor infor only the url used)

**Comment by JGallot** [comment]
in redis-client, i've got keys :
```
1) "scalelite_development:server_load"
2) "scalelite_development:server_enabled"
3) "scalelite_development:servers"
4) "scalelite_development:server:b223bb3e-961c-4cbf-ba29-d656797b7657"
5) "scalelite_development:server:e409d22f-5aa5-451b-9485-1d7c37e4e3fd"
```
I see __development_, shouldn't I  see __production_ instead ?

**Comment by ngthienlinh** [comment]
I think so.
I set RAIL_ENV=development, and it is working.
if you set RAIL_ENV=production, you may also need to set REDIS_NAMESPACE=<custom_namespace>.

**Comment by JGallot** [comment]
I've made this but it doesn't work.
./bin/rake servers:add[https://kbbb3-calc.unicaen.fr/bigbluebutton/api,XXXXX] RAIL_ENV=production REDIS_NAMESPACE=scalelite_production
also populate scalelite_development

**Comment by JGallot** [comment]
ok shame on me ... env vars must before the tasks...

**Comment by JGallot** [comment]
Ok it works for me now 
thanks
