### ISSUE TITLE
Scalelite and insertDocument API calls

### ISSUE THREAD

**Issue by thifranc** [blindsidenetworks/scalelite#941]
**Problem to solve:**
Hi,

First, thanks all a lot for all the work and tools you're giving us ! We've been working with bbb for over a year and improvements are just awesome.

I've been developing a bridge between a frontend for french national education. The goal is to plug their BBB frontend to nextcloud, so that teachers will be able to select which files will be sent to a meeting at start.

Code is ready to run and they're starting to deploy it, the code works like this :

1. on the 'create' BBB API call, our frontend will choose only the file deemed as 'default', and we will join ONLY this file to the BBB meeting creation ( the file is associated with xml data on the /create POST api request ).

2. our frontend will then push jobs in a celery job queue. Jobs are files that are not the default but that have been chosen to be associated to the BBB meeting. Our frontend will then make call to the BBB API /insertDocument. The problem is that I fear Scalelite, as of now, is not capable to handle that kind of call to BBB remote servers.

Is this feature something you're actually looking to release ? That's a big problem for deploying the feature to servers as our architecture relies heavily on Scalelite use. Our custom frontend is working when plugged directly to a BBB, but we can't scale up and plug it to a scalelite, as scalelite has not yet the ability to know and keep updated "who's who" ( which meeting is run on which BBB server ).

I'd be glad to be of help and maybe even try a push a patch for that, but I'm not familiar with Ruby at all so I think I'll take maybe too much time, that's why I first wanted to address the issue, to know if work regarding this had already been done or if someone else had trouble with that.

**Purposed solution:**
Maybe scalelite could implement a way of allowing a frontend to communicate with a meeting.
For example as long as scalelite proxy-back the response of a meeting creation, the fronted can have and keep the MEETING-ID. A frontend could then make api call direclty to the meeting using its ID as parameter. If we want to be clear of collateral 'meetingIds', we could have scalelite returning custom data on meeting creation ( bbb-id + meeting-id ), then the frontend could make requests to scalelite by using both data to speciify which meeting to address ( bbb-id + meeting-id ), but I fear that would be a breaking change :(

**Considered alternatives:**
I could try and go for a custom scalelite fork, but I fear it would take me too much time as of now. Or redo from scratch a basic scalelite, but I rather contribute to open-source code

If anything is unclear or lacks precision and details, don't hesitate to ping me back, as english is not my mother tongue previous message may contain errors, sorry in advance for that.

**Comment by defnull** [comment]
I think there is some confusion here. Scalelite implements (most of) the [BBB API](https://docs.bigbluebutton.org/development/api/) and acts as a single large virtual BBB server, but actually distributes meetings across multiple BBB nodes. For this to work, it keeps track of running meetings and recordings and of cause knows on which BBB node each meeting is currently running. No need to keep track of this at the front-end.

The only problem here is that Scalelite seems to not implement the `insertDocument` API yet. That's your actual feature request. No breaking change, just add a missing API endpoint to Scalelite.

This does not look too difficult to implement, actually. The API would just need to forward the POST payload to the correct BBB node and return the response.

**Comment by ffdixon** [comment]
> The only problem here is that Scalelite seems to not implement the insertDocument API yet. 

We want to support [insertDocument](https://docs.bigbluebutton.org./development/api#insertdocument) API call in ScaleLite as it's part of the official.

**Comment by farhatahmad** [comment]
`insertDocument` was implemented in release 1.5.1
