### ISSUE TITLE
Question: can we set the weight for each server?

### ISSUE THREAD

**Issue by slacker82** [blindsidenetworks/scalelite#95]
Hello,

Is it possible to set the weight for each server in the pool,  for now, Scalelite determine the current server load by the number of connected users then send the request to the least loaded server in the pool, what if I have one server can handle more requests than the others?

Thanks and appreciate your feedback.

**Comment by farhatahmad** [comment]
Hi @slacker82 

Not at the moment. The first pass for Scalelite was meant to just equally distribute the load across multiple servers.

**Comment by slacker82** [comment]
Salam @farhatahmad,

Thanks for your reply.
