### ISSUE TITLE
Warnings in scalelite-api (docker) when querying the status of the servers

### ISSUE THREAD

**Issue by mstruminski** [blindsidenetworks/scalelite#955]
**Describe the bug**

**To Reproduce**

***Deployment:***
1. Deployment: docker-compose
2. Versions: 1.5.0
3. Tools used for reproducing the issue: jump into the scalelite-api container

***Steps to reproduce the behavior:***

1. docker exec -it scalelite-api bash
2. rake status

**Expected behavior**
A status-report without warnings, that spamms our e-mail account.

**Screenshots**
![Bildschirmfoto 2023-05-31 um 10 27 26](https://github.com/blindsidenetworks/scalelite/assets/100774169/ee591211-2d29-4ad3-a971-d5552870ff6a)

**Comment by farhatahmad** [comment]
Duplicate https://github.com/blindsidenetworks/scalelite/issues/939
