### ISSUE TITLE
Scalelite main domain API blocked when multi-tenancy enabled

### ISSUE THREAD

**Issue by pielonet** [blindsidenetworks/scalelite#968]
Hi,

It looks like enabling multi-tenancy in Scalelite disables API for the main domain.

**To Reproduce**
- Enable multi-tenancy in `.env` file
- Try to create a room from the main domain (scalelite.example.com), using "LOADBALANCER_SECRET" from `.env` file to compute checksum
- Scalelite replies with Error "Checksum error"

Creating rooms for a tenant from domain mytenant.scalelite.example.com using a tenant's secret works perfectly well.

**What I expect**
- Creating rooms for the main domain should still be possible even if multi-tenancy is enabled

Is disabling room creation on main domain the desired behaviour ?

Kind regards,
Thierry

Scalelite version : 1.5.1
Deployment : scalelite-run

**Comment by farhatahmad** [comment]
Hi Thierry - This is expected. Once multitenant mode is enabled, all meetings must be created under a tenant. Any request to the main domain using the original credentials will fail
