### ISSUE TITLE
Link to multitenancy documentation leads nowhere

### ISSUE THREAD

**Issue by dmtrhfr** [blindsidenetworks/scalelite#969]
The link in the release notes regarding the multitenancy leads nowhere.
Could not find any documentation regarding multitenancy when i went through the repo, except the updates in the api.
Can you please provide documentation to the multitenancy feature.

All the Best

**Comment by ffdixon** [comment]
Thanks.  Updated the release notes to have the correct link.
 
  https://github.com/blindsidenetworks/scalelite/blob/v1.5-stable/docs/rake-README.md#multitenancy
