### ISSUE TITLE
Scalelite + Sakai

### ISSUE THREAD

**Issue by eemirtekin** [blindsidenetworks/scalelite#97]
Hello All,

I had been used Sakai (12.5) with single BigBlueButton in our University for a long time.

After Scalelite v1.0 released, I changed my env single BBB server to scalelite with 9 BBB servers.

Scalelite and BBB servers running successfully. There are no error.

After I changed my env, I edited in sakai.properties

from
bbb.url=https://single-bigbluebutton.xxxxxx.edu.tr/bigbluebutton/
bbb.salt=****

to
bbb.url=https://scalelite.xxxxx.edu.tr/bigbluebutton/
bbb.salt=****

Today, I realized that in some of the courses offered in Sakai, students can access the records on all servers. And any lecturer can delete these records. In fact, instructor only needs to view the records in his/her course.

This occurred only in 39 of the 1880 lessons opened on Sakai.

Is this problem related to Scalellite or Sakai's BBB tool?

Do you have any suggestions?
Thanks in advance.

**Comment by eemirtekin** [comment]
I just realied When meetingID parameter  is empty (meetingID=""), Scalelite API return all recordings.

**Comment by farhatahmad** [comment]
Hi @eemirtekin 

I believe this is a bug in the Sakai integration that causes it to send getRecordings calls with no meetingID specified. 

From Scalelite's point of view, this is expected behaviour
