### ISSUE TITLE
undefined local variable or method `request' for RecordingReadyNotifierService:Class

### ISSUE THREAD

**Issue by Tecumtha** [blindsidenetworks/scalelite#979]
After the Rreport from Issue: #971, i updated to Version 1.5.1.1.

blindsidenetwks/scalelite:v1.5.1.1-recording-importer
blindsidenetwks/scalelite:v1.5.1.1-poller                                      
blindsidenetwks/scalelite:v1.5.1.1-api 

The rest of the configuration is the same as in the previous Issue in #971.

Now I have a new error:

I, [2023-06-29T09:02:47.578108 #6]  INFO -- : Recording Ready Notify for [8h7eqb5l8tdpvsiow1dysirnpvjeegabaakcz8op] starts
I, [2023-06-29T09:02:47.578483 #6]  INFO -- : Making callback for recording ready notification
I, [2023-06-29T09:02:47.578834 #6]  INFO -- : Rescued
I, [2023-06-29T09:02:47.581832 #6]  INFO -- : undefined local variable or method `request' for RecordingReadyNotifierService:Class
    request.host.split(".").first
    ^^^^^^^
Did you mean?  require

**Comment by pielonet** [comment]
Hello,
I had the same problem when testing today !

**Comment by farhatahmad** [comment]
Sorry about that - there was a use case that I missed while testing

**Comment by farhatahmad** [comment]
Can you try out the latest image (https://github.com/blindsidenetworks/scalelite/releases/tag/v1.5.1.2) and let me know how that goes?

**Comment by Tecumtha** [comment]
I've tested this a bit now and it works as expected, thanks
