### ISSUE TITLE
video-recording

### ISSUE THREAD

**Issue by secretreal26** [blindsidenetworks/scalelite#98]
Hi,

Everything works perfect exept recordings :)

I setup 3 bbb server and try to use cifs..
Recordings stay in raw folder in bbb. How can I debug it for finding wrong config..

Thanks in Advance

**Comment by rabser** [comment]
I'm debugging recordings too and the best entry point is
docker logs scalelite-recording-importer 
to see what's happening...

**Comment by paul1278** [comment]
Can your servers write to the mounted spool-directory?

**Comment by secretreal26** [comment]
I can write from bbb to mounted spool directory..
Bu I do not understand : work_dir: /var/bigbluebutton/recording/scalelite
this is empty to.. these are local directory before transfer to mounted point..

**Comment by paul1278** [comment]
Ok then this should work.
the work_dir should be a directory on the local system where also BBB can write to, it works on my servers, the directory permissions are set to:
owner: bigbluebutton - group: bigbluebutton - permissions: 755

**Comment by secretreal26** [comment]
drwxr-xr-x  2 bigbluebutton bigbluebutton 4096 Mar 25 15:28 scalelite

**Comment by paul1278** [comment]
Looks good to me, and you placed the ruby-file https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/scalelite_post_publish.rb into `/usr/local/bigbluebutton/core/scripts/post_publish`
as mentioned [here](https://github.com/blindsidenetworks/scalelite/blob/master/bigbluebutton/README.md#installation)?

**Comment by secretreal26** [comment]
root@bbb-1:/usr/local/bigbluebutton/core/scripts/post_publish# ls -la
total 20
drwxr-xr-x  2 root root 4096 Mar 24 17:47 .
drwxr-xr-x 12 root root 4096 Mar 24 18:07 ..
-rw-r--r--  1 root root 1437 Mar  6 21:08 post_publish.rb.example
-rw-r--r--  1 root root 3675 Mar  6 21:08 post_publish_recording_ready_callback.rb
-rw-r--r--  1 root root 2415 Mar 24 17:47 scalelite_post_publish.rb

-rwxr-xr-x  1 root root  808 Mar 24 17:42 scalelite.yml

root@bbb-1:/usr/local/bigbluebutton/core/scripts# cat scalelite.yml 
# Directory for temporary storage of working files
work_dir: /var/bigbluebutton/recording/scalelite
#
# Directory to place recording files for scalelite to import
# If you are using a shared filesystem, this should be the local mountpoint on the BigBlueButton server.
spool_dir: /mnt/scalelite-recordings/var/bigbluebutton/spool
# If you are using rsync over ssh, this should be of the form [USER@]HOST:DEST
#spool_dir: scalelite-spool@scalelite-import.example.com:/var/bigbluebutton/spool
# If you are using an rsync daemon, this should be of the form [USER@]HOST::DEST or rsync://[USER@]HOST/DEST
#spool_dir: rsync://scalelite-spool@scalelite-import.example.com/spool
#
# Extra rsync command-line options
# You can use this to set up unusual configurations, like rsync daemon over ssh
extra_rsync_opts: []

**Comment by paul1278** [comment]
Well these look good, then you really need to look into the logs if there is something going on.

**Comment by secretreal26** [comment]
docker logs scalelite-recording-importer  this does not show anything  any other log  may I look..

by the way thanks for your help Paul

**Comment by secretreal26** [comment]
root@bbb-1:/var/bigbluebutton/recording/raw# ls
8e4afc4bcbb8325a9c861ef8b495cd674c80c468-1585336911636  8e4afc4bcbb8325a9c861ef8b495cd674c80c468-1585337322837

These records stay in raw folder and nothing happened.. :S

**Comment by paul1278** [comment]
No problem! Sorry for the late response, can you show the files in the folders `/var/bigbluebutton/recording/status/published` & `/var/bigbluebutton/recording/status/processed`

**Comment by secretreal26** [comment]
hi,
I just setup new bbb and use nfs.. Beginning of this post I tried with cifs.. But with nfs recording is ok.. :)
thanks for your help
