### ISSUE TITLE
Multitenancy is enabled although MULTITENANCY_ENABLED=false

### ISSUE THREAD

**Issue by Ithanil** [blindsidenetworks/scalelite#995]
**Describe the bug**

If you set MULTITENANCY_ENABLED=false in the environment file, Multitenancy will be enabled. Only if it not set at all, Multitenancy will be disabled.

**To Reproduce**

Set MULTITENANCY_ENABLED=false and check rake tenants. Observe that the output is "Total number of tenants: 0" instead of "Multitenancy is disabled, task can not be completed" 

**Expected behavior**

Multitenancy should be disabled unless MULTITENANCY_ENABLED=true is set.

**Additional context**

This leads to Checksum Error on every API request, because the variable LOADBALANCER_SECRET(S) is not used. Probably the cause of issue https://github.com/blindsidenetworks/scalelite/issues/985 (after he has changed to false), which was unfortunately closed.

This has also almost cost me my sanity.

**Comment by ffdixon** [comment]
Thanks Jan for pointing this out (and for keeping your sanity :-)

**Comment by Ithanil** [comment]
@ffdixon It was close. I was setting up a new "Dev" Scalelite and banged my head against the wall for hours, because every API request was failing with Checksum Error. The possibility that MT was actually not disabled didn't come to my mind for a long time.

**Comment by SamuelWei** [comment]
I would suggest to adjust the config option like for the other app settings

```
    # Multitenancy values
    config.x.multitenancy_enabled = ENV.fetch('MULTITENANCY_ENABLED', 'false').casecmp?('true')
```

https://github.com/blindsidenetworks/scalelite/blob/master/config/application.rb#L109C1-L110C75
