### ISSUE TITLE
`servers:add` accepts arguments which won't work

### ISSUE THREAD

**Issue by debuglevel** [blindsidenetworks/scalelite#996]
It's possible to `servers:add` a URL without a protocol:
`docker exec -i scalelite_scalelite-api bundle exec rake servers:add[bbb5.myhost.de,SECRET]`

It might be a good idea to at least check for the protocol part being contained: `http://bbb5.myhost.de` / `https://bbb5.myhost.de`

**Comment by scouillard** [comment]
Hi @debuglevel ,
Thank you for the report.
A guard clause has been added to `servers:add`
